### ISSUE TITLE
Memory allocation problems when cloning repository with LFS objects largen than available RAM

### ISSUE THREAD

**Issue by tmaczukin** [git-lfs/git-lfs#3524] opened 2019-02-14 22:24 UTC
Hey!

At GitLab [we're investigating an issue](https://gitlab.com/gitlab-org/gitlab-runner/issues/3366) discovered by users of our CI system: when cloning a git repository with LFS object fails, when the object is greater than memory available on the target machine.

In short:

1. Let's create a simple git repository with one 768MB file commited there as an LFS object. For purpose of my tests I've created https://gitlab.com/tmaczukin-test-projects/git-lfs-objects/.

1. Let's use a machine that has only 512MB of RAM. For my tests I've created a cloud VM with 1CPU and 512MB of RAM

1. Let's try to clone the repository:

    ```bash
    $ git clone https://gitlab.com/tmaczukin-test-projects/git-lfs-objects.git
    Cloning into 'git-lfs-objects'...
    remote: Enumerating objects: 5, done.
    remote: Counting objects: 100% (5/5), done.
    remote: Compressing objects: 100% (4/4), done.
    remote: Total 5 (delta 0), reused 0 (delta 0)
    Unpacking objects: 100% (5/5), done.
    Downloading urandom.data (805 MB)
    fatal: Out of memory, realloc failed
    warning: Clone succeeded, but checkout failed.
    You can inspect what was checked out with 'git status'
    and retry the checkout with 'git checkout -f HEAD'
    ```

The operation fails with a `fatal: Out of memory, realloc failed` error. The repository is cloned, however it's not checked out. At this moment the working directory is in a messed state, where files are not present and `git checkout -f HEAD` is failing.

During the discussion we've been pointed to #2840. While the issue is about slightly different problem, where it was the git-lfs that was failing, in this comment https://github.com/git-lfs/git-lfs/issues/2840#issuecomment-384881088 we've found a suggestion that `git lfs clone` should resolve the problem.

And indeed, after using the `git lfs clone` command with the same repository and on the same machine, it worked:

```bash
$ git lfs clone https://gitlab.com/tmaczukin-test-projects/git-lfs-objects.git
Cloning into 'git-lfs-objects'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (5/5), done.
Downloading LFS objects: 100% (1/1), 805 MB | 20 MB/s
```

Happy that we've found a solution we've decided to do few more tests to confirm that it works in all cases that we're supporting... and then we've found that `git lfs clone` command is deprecated. Currently it's marked as deprecated when git >= 2.15.0 is used, but from the discussion in PR that introduced the deprecation (#2526) it follows, that this decision should not be reverted and in some future version of git-lfs the `git lfs clone` command should be removed.

The discussion however focuses on a speed problem of `git clone` operation from before 2.15.0. It's even stated in the warning message:

```
WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'

'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
```

Well, in our case we don't have problem with the speed of the operation. We have problem with memory consumption that is not a problem at all, when `git lfs clone` is used. For some reason the regular `git clone` operation with all LFS filters installed is not handling the checkout operation properly.

For now, to not relay on a deprecated feature that may disappear in the future, we're trying to [manually replicate the behavior of `git lfs clone`](https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/1200) in our git cloning script, but it's more an ugly hack rather than a solution.

While we're trying to prepare a workaround because the problem is biting users of our CI system, the source of the issue seems to be in git-lfs and/or git. From the documentation and discussion about the `git lfs clone` deprecation I assume, that the user should simply use `git clone` in any case, and if the repository contains any LFS objects they should be properly handled. This however doesn't work in a case that we've found: where one of the objects is bigger than memory available on the target environment. This seems to be a bug.

Looking on how `git lfs clone` works, I see that it disables LFS integration for the `git clone` command and then it does additional `git lfs pull` (or `git lfs fetch` if the clone was disabling the `checkout` step). So if the clone operation works when LFS support is disabled and fails in other case, then one of these tools or the integration between them seems to be buggy :)

At this moment I see three solutions:

1. Since `git lfs clone` works in such cases, then it should be un-deprecated, since speed is not the only problem that plain `git clone` has with LFS repositories.

1. Either git or git-lfs should be fixed since one of them is allocating too much memory during clone operation.

1. I'm wrong and the problem is in other place. But since I don't have much experience with LFS I don't see it and would ask for any suggestions.

When googling around this problem I found few discussions about a similar issue when LFS is used with Windows based git. There I found suggestions to adjust git settings so it will differently handle memory allocation. But none of these settings was working for me, so either they are already removed or it's Windows specific.

Anyway, forgetting for a moment that I'm a software developer and I know how to dig into details and find workarounds: as a simple git user I'd expect that `git clone` is everything that I need to do to get my repository. I don't need to check how many memory I have and how to adjust settings or change my operation to 10 different commands to get the same result. I'm doing `git clone` on a 128GB machine and it clones the repository, the same should happen on a 128MB machine. Especially that it's exactly what I get when using the deprecated `git lfs clone`. It just works :)

If someone is interested in more details of the tests and assumptions that I've made already, then they are documented at https://gitlab.com/gitlab-org/gitlab-runner/issues/3366.

I'd appreciate help in resolving this issue. For now it looks like a git-lfs or git problem, so I'm moving the discussion here, where are people with bigger LFS experience than me. If any other information/tests would be needed to track where the problem is, please ask. I'll do my best to gave any needed update :)

**Comment by ttaylorr** [comment] 2019-02-15 01:21
Thanks for opening such a detailed issue, and sorry that you're having trouble. I believe that the crux of the issue is as follows:

1. `git clone` is (recently) fast, but currently buffers incoming data from the filter in memory in order to write it into the working copy, leading to memory exhaustion, and,

2. `git lfs clone` is similarly fast, and does not suffer from the same memory issues since it writes data directly, avoiding similar memory exhaustion issues.

I think that we are interested in deprecating `git lfs clone` since it's less things to maintain, and we'd like to encourage people to use something more widely accepted in the general case. But, that doesn't solve your problem.

One thing that you _can_ do is to disable smudging (e.g., `GIT_LFS_SKIP_SMUDGE=1 git clone <remote>`) and _then_ perform the checkout with `git lfs checkout`. `git lfs checkout` similarly writes directly to disk, and won't suffer from these sorts of memory exhaustion problems.

In the longer-term, I would be interested in teaching Git how to write directly from the filter into the working copy, to avoid these sorts of memory exhaustion issues. But I think that this is a good stop-gap which (1) solves the immediate problem, (2) allows us to still deprecate 'git lfs clone', and (3) buys us some time to think about ways to improve upstream Git.

Since I'm pretty sure that this will solve the problem at hand, I'm going to close this issue for now, but please don't hesitate to comment here again if you run into anything else in the future, and we'd be happy to dive in. Thanks!

**Closed by ttaylorr** 2019-02-15 01:21 UTC

**Comment by tmaczukin** [comment] 2019-02-15 08:56
@ttaylorr Thank you very much for your response! It pointed me to a way better solution than I was trying to use :smiley: 

However, `git lfs checkout` in your answer should be replaced by `git lfs pull`. The checkout command is failing with:

```bash
$ GIT_LFS_SKIP_SMUDGE=1 git clone https://gitlab.com/tmaczukin-test-projects/git-lfs-objects.git
Cloning into 'git-lfs-objects'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (5/5), done.

$ cd git-lfs-objects/

$ du -m *
1       urandom.data

$ git lfs checkout
Skipped checkout for "urandom.data", content not local. Use fetch to download.                                                                                                                                    

Errors logged to /tmp/git-lfs-objects/.git/lfs/logs/20190215T081959.519411557.log
Use `git lfs logs last` to view the log.

$ du -m *
1       urandom.data

$ git lfs pull
Downloading LFS objects: 100% (1/1), 805 MB | 20 MB/s

$ du -m *
769     urandom.data
```

The content of the log:

```bash
git-lfs/2.6.1 (GitHub; linux amd64; go 1.11.2; git dc072c3e)
git version 2.11.0

$ git-lfs checkout
Skipped checkout for "urandom.data", content not local. Use fetch to download.

stat /tmp/git-lfs-objects/.git/lfs/objects/e6/9a/e69a3a78c07db08f52a2ec5c9cee66fe1a4aebb9d35b520e7802a9b6cf79cdce: no such file or directory
smudge
github.com/git-lfs/git-lfs/errors.newWrappedError
        /Users/bk2204/checkouts/git-lfs/errors/types.go:184
github.com/git-lfs/git-lfs/errors.NewDownloadDeclinedError
        /Users/bk2204/checkouts/git-lfs/errors/types.go:335
github.com/git-lfs/git-lfs/lfs.(*GitFilter).Smudge
        /Users/bk2204/checkouts/git-lfs/lfs/gitfilter_smudge.go:73
github.com/git-lfs/git-lfs/lfs.(*GitFilter).SmudgeToFile
        /Users/bk2204/checkouts/git-lfs/lfs/gitfilter_smudge.go:36
github.com/git-lfs/git-lfs/commands.(*singleCheckout).RunToPath
        /Users/bk2204/checkouts/git-lfs/commands/pull.go:105
github.com/git-lfs/git-lfs/commands.(*singleCheckout).Run
        /Users/bk2204/checkouts/git-lfs/commands/pull.go:85
github.com/git-lfs/git-lfs/commands.checkoutCommand
        /Users/bk2204/checkouts/git-lfs/commands/command_checkout.go:76
github.com/spf13/cobra.(*Command).execute
        /Users/bk2204/checkouts/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:477
github.com/spf13/cobra.(*Command).Execute
        /Users/bk2204/checkouts/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:551
github.com/git-lfs/git-lfs/commands.Run
        /Users/bk2204/checkouts/git-lfs/commands/run.go:77
main.main
        /Users/bk2204/checkouts/git-lfs/git-lfs.go:35
runtime.main
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/proc.go:201
runtime.goexit
        /usr/local/Cellar/go/1.11.2/libexec/src/runtime/asm_amd64.s:1333

Current time in UTC: 
2019-02-15 08:19:59

ENV:
LocalWorkingDir=/tmp/git-lfs-objects
LocalGitDir=/tmp/git-lfs-objects/.git
LocalGitStorageDir=/tmp/git-lfs-objects/.git
LocalMediaDir=/tmp/git-lfs-objects/.git/lfs/objects
LocalReferenceDirs=
TempDir=/tmp/git-lfs-objects/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/tmp/git-lfs-objects/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic

Client IP addresses:
209.97.141.45 10.16.0.5 fe80::5cd4:7dff:fe0c:82d4
172.17.0.1 fe80::42:7eff:feca:d7c6
fe80::acf2:97ff:fec9:c396
```

The error seems to be obvious - content of LFS was not fetched from the remote, so it can't be checked out. Doing `git lfs pull` handles both steps. Adding `git lfs fetch` before `git lfs checkout` should also work according to the error message. I suppose that you know all of this, I'm just leaving this note for others that may find this issue :wink:

In my example above I've also described the simplest way to replicate the error. Our cloning strategy (with GitLab Runner) is however a little more complex. We're using `git clone --no-checkout` command, which changes a little how the workaround should be implemented.

Our existing strategy was:

1. Do a `git clone --no-checkout [URL] [local_path] --template [path_to_config_template_directory]`.
1. Do a `git checkout -f -q [reference_for_the_CI_job]`.

Adding `GIT_LFS_SKIP_SMUDGE=1` to the `git clone` command helps, but the `git checkout` command still fails afterwards. And adding `GIT_LFS_SKIP_SMUDGE=1` to the `git checkout` command doesn't help.

But thanks to your hint, I've found the `--skip-smudge` option of the `git lfs install` command that now resolves my problem. The cloning strategy was changed to:

1. Change the LFS installation command from `git lfs install` to `git lfs install --skip-smudge --skip-repo`.
1. Do a `git clone --no-checkout [URL] [local_path] --template [path_to_config_template_directory]` (so without changes).
1. Do a `git checkout -f -q [reference_for_the_CI_job]` (so still without changes).
1. Do an additional `git lfs pull` afterwards.

I still need to do some tests and adjust the solution for all sources downloading/updating strategies that we're supporting. But it's very promising.

However.

This is still a workaround. As I've mentioned above, from regular user perspective such additional work should be not needed. `git clone` should just work properly from the very beginning. And I assume you agree with this, basing on your statement that `longer-term, I would be interested in teaching Git how to write directly from the filter into the working copy, to avoid these sorts of memory exhaustion issues`.

Could we then leave the issue opened for now?

I understand that _teaching Git how to work_ may be not the biggest priority, highly depends on git maintainers and their will to handle the problem and that this may not happen in a long time. But I'd like to have this issue opened from a pragmatic reason: when it will finally happen, I (and probably not only I) would like to remove the hacky workaround and get back to a simple `git clone && git checkout` operation.

If the issue will be closed when the problem will be resolved with git, then anyone that will turn on notification on this issue will get an information that it happened. Otherwise we'd need to constantly check git-lfs and git release notes and try to figure out if the problem was resolved or not .

This is the only reason. The workaround works for me for now and makes the problem to not hurt so much :smiley:

**Comment by tmaczukin** [comment] 2019-02-15 09:16
Update: I was wrong (must done something wrong when testing) and `GIT_LFS_SKIP_SMUDGE=1 git checkout` also works. This again simplifies the workaround and makes it to be:

1. Export `GIT_LFS_SKIP_SMUDGE=1` variable (don't need to touch the git configuration file anymore).
1. Do a git clone --no-checkout [URL] [local_path] --template [path_to_config_template_directory] (so without changes).
1. Do a git checkout -f -q [reference_for_the_CI_job] (so still without changes).
1. Do an additional git lfs pull afterwards.

The rest of my above comment: the part about using `git lfs fetch && git lfs checkout` or `git lfs pull` and the question to re-open this issue still stays valid :)

**Comment by bk2204** [comment] 2019-02-15 18:38
I should point out that I believe that the issue you're seeing with `git clone` is in fact a Git issue upstream. As far as I can tell, Git reads the entire output of the filter process into memory, which is why you're seeing objects larger than memory fail. Part of this is because the filter process can technically abort at any time and say, "Oops, just kidding, I messed up," and Git should abort that checkout.

We've [covered this upstream recently](https://public-inbox.org/git/20190124003948.GS423984@genre.crustytoothpaste.net/) and the consensus is that this design can be improved by writing to a temporary file and then renaming into place, as @ttaylorr mentioned. I encourage you to reach out to upstream Git to see if this can be fixed there, which will probably be the easiest way to get this addressed.

**Comment by tmaczukin** [comment] 2019-02-15 18:43
@bk2204 Thank's for the information :)
