### ISSUE TITLE
Adding large files exhausts memory

### ISSUE THREAD

**Issue by johnepinterest** [git-lfs/git-lfs#1851] opened 2017-01-11 23:12 UTC
[This line](https://github.com/git-lfs/git-lfs/blob/39cbf99ede45dec4d241d423a64dd5b8211a20ba/lfs/pointer_clean.go#L81) in the `lfs/pointer_clean.go` `copyToTemp` function causes the entire file to be read in to memory:

```
by, rerr := ioutil.ReadAll(buf)
```

For large files this can cause the process to consume an enormous amount of memory.  In fact, on my particular system (Mac OS X), adding half a dozen 4-6 GB files caused it to run out of memory because it couldn't add more swap space because it had filled up the disk (the disk was quite full already).

I ended up having to `git add` files one at a time.  It seems like adding multiple files at once compounds the problem.

This really needs to be re-written so that it doesn't require the entire file to be in memory.  From my simple reading of the code, I can't see any reason why it needs to do this, and if it truly does, `mmap()`ing the file is probably a much better idea.

**Comment by ttaylorr** [comment] 2017-01-11 23:25
Hi @johnepinterest, thanks for opening this. What you're pointing out is my fault, and definitely a regression. Sorry about that.

The reason that we read from the buffer is to check if the contents of the file is already an LFS pointer, which we should [write back to Git directly][1] if asking to be cleaned during a check-in. Prior to LFS v1.5.4, the amount of data that was buffered was limited at `blobSizeCutoff`, which is 512 bytes (see: [lfs/pointer.go][1] at v1.5.3).

Behavior was added in v1.5.4 to enable LFS to stream the entire contents of a malformed pointer during checkouts. However, it looks like I forgot to cap the amount of data read from the `buf`, as you pointed out in the line above. Luckily, this only has measurable impact against _large_ malformed pointers. Going forward, I think the following patch can safely be applied, and should be released as v1.5.5.

```diff
diff --git a/lfs/pointer_clean.go b/lfs/pointer_clean.go
index 83cc725e..4928c444 100644
--- a/lfs/pointer_clean.go
+++ b/lfs/pointer_clean.go
@@ -5,7 +5,6 @@ import (
 	"crypto/sha256"
 	"encoding/hex"
 	"io"
-	"io/ioutil"
 	"os"
 
 	"github.com/git-lfs/git-lfs/config"
@@ -79,7 +78,11 @@ func copyToTemp(reader io.Reader, fileSize int64, cb progress.CopyCallback) (oid
 	}
 
 	ptr, buf, err := DecodeFrom(reader)
-	by, rerr := ioutil.ReadAll(buf)
+
+	by := make([]byte, blobSizeCutoff)
+	n, rerr := buf.Read(by)
+	by = by[:n]
+
 	if rerr != nil || (err == nil && len(by) < 512) {
 		err = errors.NewCleanPointerError(ptr, by)
 		return
```

[1]: https://github.com/git-lfs/git-lfs/blob/39cbf99ede45dec4d241d423a64dd5b8211a20ba/commands/command_clean.go#L50-L57
[2]: https://github.com/git-lfs/git-lfs/blob/v1.5.3/lfs/pointer.go#L113

**Comment by ttaylorr** [comment] 2017-01-12 00:24
I went ahead and applied the above patch in https://github.com/git-lfs/git-lfs/pull/1852, which is open for review.

**Comment by ttaylorr** [comment] 2017-01-12 21:32
Git LFS v1.5.5 has been [released][1] which resolves this issue. Thanks again!

[1]: https://github.com/git-lfs/git-lfs/releases/tag/v1.5.5

**Closed by ttaylorr** 2017-01-12 21:32 UTC
