### ISSUE TITLE
Submodule update does not update git-lfs files

### ISSUE THREAD

**Issue by lacombar** [git-lfs/git-lfs#1976] opened 2017-02-23 19:22 UTC
Actual behavior:
```
% git config --global lfs.fetchinclude 'external/linux/*64*'
% git submodule update --init
% [downloading packages matching 'external/linux/*64*']
% git config --global lfs.fetchinclude 'external/linux/*32*'
% git submodule update --init
[nothing happened]
```

Expected behavior
```
% git config --global lfs.fetchinclude 'external/linux/*64*'
% git submodule update --init
[downloading packages matching 'external/linux/*64*']
% git config --global lfs.fetchinclude 'external/linux/*32*'
% git submodule update --init
[downloading packages matching 'external/linux/*32]
```

**Comment by technoweenie** [comment] 2017-02-23 22:25
Thanks for the report. I've marked it as a bug. My hunch is that since the submodule didn't change, `git submodule update --init` doesn't do anything, bypassing the git smudge filter.

**Comment by ttaylorr** [comment] 2018-04-10 03:46
I think that:

```ShellSession
$ git submodule update --init --force
# ...
```

should work as intended.

**Closed by ttaylorr** 2018-04-10 03:46 UTC
Labels: bug

**Comment by basnijholt** [comment] 2020-03-06 15:11
@ttaylorr, that actually also doesn't work, unfortunately.
