### ISSUE TITLE
ssh remote URL must include "git@" prefix

### ISSUE THREAD

**Issue by boblaublaw** [git-lfs/git-lfs#798] opened 2015-10-28 00:29 UTC
I'm noticing that when my remote is set to either:

"github.com:/Team-Name/Repo-Name"  OR
"ssh://github.com:/Team-Name/Repo-Name"

i get unsupported scheme errors despite being able to confirm ssh authentication using command line ssh to verify.  This is because my .ssh/config file specifies my username as "git".

I believe this is because git is correctly detecting the ssh repo specification, but not using the username "git" when talking to the LFS HTTP API.  

This may well be intended behavior, but if so, I think it is important to call out the requirement to use "git@..."

**Comment by technoweenie** [comment] 2015-10-28 00:36
It's not _intended_, but the shortcuts and alternatives haven't been implemented yet. There's a really old issue tracking this, but haven't found anyone interested in working on them yet: #278 #295 

I'll add them to the list for v1.1 if we have time for it: #755

**Comment by ttaylorr** [comment] 2018-04-05 19:00
Duplicate of: https://github.com/git-lfs/git-lfs/issues/278.

**Closed by ttaylorr** 2018-04-05 19:00 UTC
