### ISSUE TITLE
git lfs refuse to install on windows 64

### ISSUE THREAD

**Issue by runiArnsbjornson** [git-lfs/git-lfs#3206] opened 2018-08-29 10:05 UTC
hello,

i just downloaded the client for git lfs and tried to follow the procedure for installation but cannot manage to make it works :

first i got an error saying that git lfs was not a valid git command. 
After some research i found that i had to had the git lfs path to my system env. 

done that, 
and now i have this issue : 

`` git lfs install
fatal: 'lfs' semble être une commande git, mais elle n'a pas pu
être exécutée. Peut-être git-lfs est-elle cassée ? ``

(means 'lfs' seems to be a git command, but could not be executed. may be it is broken ?) (yeah sorry i'm french) 

couldn't find anymore informations about what to do next

**Comment by ttaylorr** [comment] 2018-08-30 21:42
Hi, Runi! Sorry that you're having trouble. Let's see what we can do:

> first i got an error saying that git lfs was not a valid git command.
>
> After some research i found that i had to had the git lfs path to my
> system env.

Precisely. The "git" tool allows for extensions to be run as "git foo",
provided that there is a binary named "git-foo" present somewhere within
your "$PATH".

So, for example, in order to run "git lfs", Git will first look for a
file named "git-lfs" by searching through the list of directories in
your "$PATH".

> done that,
> and now i have this issue :
>
> [ ... ]
>
> couldn't find anymore informations about what to do next

From what I can gather, I think that this is a "failed to execute"
issue, which usually means that you have a different git-lfs binary than
was intended.

You can find the matching git-lfs executable for your operating system
and architecture (e.g., I run macOS on a recent machine, so my operating
system/architecture combination is "Darwin," and "amd64") on our
releases page: https://github.com/git-lfs/git-lfs/releases, or on our
website at: https://git-lfs.github.com.

Can you make sure that you have the right version installed and
available on your "$PATH"?

Since I'm reasonably sure that this is what's going on, I'm going to
close this issue for now. But, if we're off-base, or something else
comes up in the future, please do not hesitate to ping me here or
elsewhere on the repository.

Thanks!

**Closed** 2018-08-30 21:42 UTC
