### ISSUE TITLE
How to force replace a file in git lfs?

### ISSUE THREAD

**Issue by booker-dragon** [git-lfs/git-lfs#3528] opened 2019-02-17 05:15 UTC
I suspect one of the file is corrupted in my master branch

The md5 sum is same as the functional one but it just could not work properly.

Any way to force updating this file in git lfs?

I am using Github as my repository

Thanks!

**Comment by ttaylorr** [comment] 2019-02-19 02:29
Hi @booker-dragon, thanks for opening this issue and I'm sorry that you're having trouble. Can you clarify what you mean by "force updating this file"? If you want to replace the contents of a particular file, you can simply update it, and run `git add /path/to/file`, and commit your changes. So long as Git LFS is installed correctly, this should all work out.

As an aside, if a signature of your file is the same as the functional version that you describe, it is likely that the files are in fact the same, and that the problem might be elsewhere.

**Comment by booker-dragon** [comment] 2019-02-19 02:57
Hi @ttaylorr ,

Thanks for your reply.

I am having issue that I suspect one of the file on LFS is corrupted and it has the same size and md5 sum as the working one.

Even I replace the file, there is no modification to the file and thus I cannot add a new commit.

I don't know if there is any GUI or command to get the history of the large file so that I can revert it.

If it is not revert-able, is there any way to force replacing the file?

**Comment by ttaylorr** [comment] 2019-02-19 03:07
You can force Git to overwrite such changes by first running `git update-index --no-assume-unchanged`.

**Comment by booker-dragon** [comment] 2019-02-19 03:22
I tried running `git update-index --no-assume-unchanged` first and then replace the file

But there is no changes found

**Comment by bk2204** [comment] 2020-08-14 18:06
Hey,

Since this hasn't seen any activity in over a year, I'm going to close it.  If you can provide reproduction steps to demonstrate what you're seeing, we'll be happy to reopen and look further.

**Closed by bk2204** 2020-08-14 18:06 UTC
Labels: question

**Comment by stevecj** [comment] 2023-10-31 21:14
I have run into the same issue. I tried `git update-index --no-assume-unchanged` per above. I also tried adding a commit to remove the file followed by another commit to add it again. The new commit still pushes instantly, so has obviously not uploaded the 201M file.
