### ISSUE TITLE
Deleted file fails git push --tags

### ISSUE THREAD

**Issue by dogboydog** [git-lfs/git-lfs#3033] opened 2018-05-28 23:58 UTC
Hi, 

I am trying to set up a project using Git LFS in Jenkins and add a tag to my master branch after a successful build. I'm able to check out and build my project fine, but if I try to push it complains about a file which has been moved/ deleted. I have read a bunch of other issues on this topic but haven't determined how to fix it yet. I have updated Git LFS  on my Jenkins machine and my dev workstation and tried  some workarounds like ` git config lfs.allowincompletepush 1` just before my push.

`git push --tags` fails with a message like this:
```
open C:\Program Files (x86)\Jenkins\workspace\...\my\deleted\file.png: The system cannot find the path specified.

```
I moved this file into a different folder many commits ago but for some reason it's failing my push : ( I also tried adding `git lfs fetch --all` right before the `git push --tags` but encountered various issues with that like not being able to set my credentials (I have these commands in a withCredentials block where I can use $USERNAME or $PASSWORD to get the Jenkins GitHub user credentials)

The Jenkins machine is Windows 10. 

```
$ git lfs fsck
Git LFS fsck OK
```
Anything else to try? 

Thanks

**Comment by dogboydog** [comment] 2018-05-29 00:43
Hi,

Here are a few of the issues I was looking at, but maybe they're different issues

https://github.com/git-lfs/git-lfs/issues/1013

https://github.com/git-lfs/git-lfs/issues/1113

I ran again with GIT_TRACE=1 

```
trace git-lfs: run_command: 'git' version

trace git-lfs: run_command: 'git' config -l

trace git-lfs: tq: running as batched queue, batch size of 100

trace git-lfs: HTTP: POST https://****:****@github.com/****/******/info/lfs/locks/verify

trace git-lfs: HTTP: 200

trace git-lfs: HTTP: {"ours":[],"theirs":[],"next_cursor":""}


Locking support detected on remote "https://****:****@github.com/****/****". Consider enabling it with:

  $ git config 'lfs.https://****:****@github.com/****/*****.git/info/lfs.locksverify' true

trace git-lfs: pre-push: refs/tags/b139 42bec6988d1133baaa6ee36da32bb63869924b08 refs/tags/b139 0000000000000000000000000000000000000000

trace git-lfs: run_command: git rev-list --objects 42bec6988d1133baaa6ee36da32bb63869924b08 --not --remotes=https://****:****@github.com/****/****t --

trace git-lfs: run_command: git cat-file --batch-check

trace git-lfs: run_command: git cat-file --batch

trace git-lfs: tq: sending batch of size 100

trace git-lfs: api: batch 100 files

trace git-lfs: HTTP: POST https://****:****@github.com/****/****.git/info/lfs/objects/batch

trace git-lfs: HTTP: 200

trace git-lfs: HTTP: {"objects":
```

However I just realized that in this instance I can add `--no-verify` to my push command to bypass the error. So until  I need to make any real changes to code or assets in my Jenkins pipeline I guess I've found a workaround

**Comment by ttaylorr** [comment] 2018-05-29 01:15
@dogboydog is your repository bare?

**Comment by dogboydog** [comment] 2018-05-29 01:28
Yeah --no-verify bypasses the issue for me so it's all good. However I have pushed the move of the file to GitHub master already from my workstation -- the file doesn't exist on the master branch. So it kind of seems unexpected that LFS would complain about this file being missing.  But I should be all good for now unless I ever add build steps that modify LFS files

**Comment by lavinia8** [comment] 2018-10-25 06:40
Hi, 

I'm facing the same error in a big repository. Jenkins cannot push a merge commit (`branch` has been merged into `master`) because of `The system cannot find the ...` error. 
Some LFS files have been updated and renamed on `master`(e.g. `fileA`, which is tracked with LFS, has been modified and moved to `folder\fileA` on `master`) since `branch` was created. 
I'm trying now to reproduce the problem, I have the big repository locally, I'm merging `branch` into `master` and pushing the merge commit to GitHub, but I get no errors :weary:
On a second try, I want to reproduce this error in a fresh new repository to understand the root cause and to test if `--no-verify` is a workaround for my big repository.
@dogboydog - Could you please help with the steps to reproduce `The system cannot find the ...` error?

**Comment by dogboydog** [comment] 2018-10-25 13:03
Unfortunately I don't have the repo with the problem anymore. Sorry

**Comment by jokram** [comment] 2018-10-26 12:41
@ttaylorr: We could find the root cause of the problem.

### Summary
Precondition:
- On the local repository there is a commit having a new Git LFS objects (e.g. a new version of a Git LFS tracked file) which is not yet on GitHub
- The new Git LFS object is not availalbe in the local .git/lfs/objects folder (e.g. deleted)

When pushing now then you'll get the error message:
```bash
LFS upload failed:
  (missing) binfile.docx (27d358f52043f63f5ab06e03c1dcd008c0ad583cbbee7ae93360ea1f71380138)
Uploading LFS objects:  50% (1/2), 12 KB | 0 B/s, done
error: failed to push some refs to 'git@myserver:lfs-test/missing_path_test.git'
```
In the working directory delete the Git LFS tracked file (e.g. binfile.docx) and create another commit.
Now when pushing you'll get a different error message (the one which is mentioned in the issue):
```bash
open D:\casdev\_test\LFS_missing_path\Manual_test\binfile.docx: The system cannot find the file specified.
error: failed to push some refs to 'git@myserver:lfs-test/missing_path_test.git'
```

### Root Cause
The root cause is missing Git LFS objects in the folder `.git/lfs/objects`.
How this could happen?
When fetching from GitHub this will not download Git LFS objects.
Only when checkout is called it will download the LFS objects mentioned in the checked out commit (but not in previous commits!).

### Use Cases where objects might be missing
- Fetch from remote A and push to remote B, because fetch will not include Git LFS objects
- Someone deletes the objects in `.git/lfs/objects` (that's not really a use case)

### Workaround
- After fetching commits call `git lfs fetch --all` to download all LFS objects from all commits existing in the local repository (this might take some time).

### Detailed steps to reproduce the error
Create a repository with *.docx tracked by Git LFS:
```bash
$ git init
Initialized empty Git repository in d:/casdev/_test/LFS_missing_path/Manual_test/.git/

$ git lfs track *.docx
Tracking "binfile.docx"
```
Add  and commit a file binfile.docx:
```bash
$ git add .

$ git commit -m "Added binfile.docx"
[master (root-commit) 6fe3b83] Added binfile.docx
 2 files changed, 4 insertions(+)
 create mode 100644 .gitattributes
 create mode 100644 binfile.docx
```
Delete the file binfile.docx from the working directory and commit the changes:
```bash
$ git add .

$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        deleted:    binfile.docx

$ git commit -m "Deleted binfile.docx"
[master 7f3aab0] Deleted binfile.docx
 1 file changed, 3 deletions(-)
 delete mode 100644 binfile.docx
```
Delete the Git LFS object from the folder `.git/lfs/objects`.
Then push that repository to an empty GitHub project:
```bash
$ git remote add origin git@myserver:lfs-test/missing_path_test.git

$ git push origin master
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.https://myserver/lfs-test/missing_path_test.git/info/lfs.locksverify true
open D:\casdev\_test\LFS_missing_path\Manual_test\binfile.docx: The system cannot find the file specified.
error: failed to push some refs to 'git@myserver:lfs-test/missing_path_test.git'
```

/cc @lavinia8

**Comment by mathstuf** [comment] 2018-10-31 19:59
I think this is very similar to #1113 (which has a reproducer script in it)

**Comment by mathstuf** [comment] 2019-03-13 12:23
Coming back to this, #1113 was closed by #3398 which improves the error message. I opened #3557 to track a proper fix.

**Comment by mathstuf** [comment] 2019-10-25 00:22
Is this still an issue (I don't know)? The other related issues have been resolved and the fixes there may have affected this issue as well.

**Comment by mathstuf** [comment] 2019-10-25 12:26
Having read the description, I agree that there's not much to be done about this (the real offender is the deletion of the object from the local store before mirroring it anywhere else). The improved error message may still be worth it.

**Comment by bk2204** [comment] 2019-10-25 14:04
Okay, I'm going to close this, since we have an improved error message and we don't require objects which are already on the server to be pushed.  I think that's the best we can do in this case.

**Closed by bk2204** 2019-10-25 14:04 UTC
