### ISSUE TITLE
git-lfs prune panic

### ISSUE THREAD

**Issue by zakharovvi** [git-lfs/git-lfs#2694] opened 2017-10-26 22:27 UTC
Hello!

I can't execute `git-lfs prune` on our large repository. I tried on different working copies on multiple machines with macOS.

```
$ git version
git version 2.14.3
$ git-lfs version
git-lfs/2.3.4 (GitHub; darwin amd64; go 1.9.1; git d2f6752f)
```

GIT_TRACE=1 git-lfs prune --no-verify-remote --verbose
```
03:18:10.256002 trace git-lfs: run_command: 'git' version
03:18:10.266237 trace git-lfs: run_command: 'git' config -l
03:18:10.271565 trace git-lfs: run_command: 'git' -c filter.lfs.smudge= -c filter.lfs.clean= -c filter.lfs.process= -c filter.lfs.required=false rev-parse 18de1152df8868e6c69fbb3130515f45ee4675f9 --symbolic-full-name 18de1152df8868e6c69fbb3130515f45ee4675f9
03:18:10.273089 trace git-lfs: run_command: 'git' -c filter.lfs.smudge= -c filter.lfs.clean= -c filter.lfs.process= -c filter.lfs.required=false rev-parse HEAD --symbolic-full-name HEAD
03:18:10.278266 trace git-lfs: run_command: 'git' -c filter.lfs.smudge= -c filter.lfs.clean= -c filter.lfs.process= -c filter.lfs.required=false rev-parse HEAD --symbolic-full-name HEAD
\ 7 local objects, 0 retained                                                                                                                                                                               03:18:10.281034 trace git-lfs: PRUNE: Retaining non-HEAD refs within 10 (7+3) days
/ 13 local objects, 0 retained                                                                                                                                                                              03:18:10.283584 trace git-lfs: run_command: git rev-list --objects --no-walk 18de1152df8868e6c69fbb3130515f45ee4675f9 --
/ 17 local objects, 0 retained                                                                                                                                                                              03:18:10.286130 trace git-lfs: RECENT: Getting refs >= 2017-10-17 03:18:10.281057 +0500 +05
| 56 local objects, 0 retained                                                                                                                                                                              03:18:10.291041 trace git-lfs: run_command: git cat-file --batch
/ 109 local objects, 0 retained                                                                                                                                                                             03:18:10.300481 trace git-lfs: RECENT: origin/master (2017-10-26 05:26:18 +0000 +0000)

REMOVED_70_ROWS_WITH_BRANCH_NAMES

03:18:10.302344 trace git-lfs: run_command: git rev-list --objects --no-walk 0069dcd0755b79ea32b8a3b307e78533e1de7336 --
03:18:10.302354 trace git-lfs: run_command: git rev-list --objects --no-walk 787635dd1ad6755e35e48d4ca3bbbfa4c651025a --
03:18:10.302383 trace git-lfs: run_command: git rev-list --objects --no-walk 76d635d490ace49ca0852c00396f6f7e3be2a4f2 --
03:18:10.305118 trace git-lfs: run_command: git rev-list --objects --no-walk 920b08661bc6ccb54cebd9b474c4cff6ec45766e --
03:18:10.305139 trace git-lfs: run_command: git rev-list --objects --no-walk 6461afcf5691eeefc34f996e9ebcb6be90fd8b32 --
03:18:10.308065 trace git-lfs: run_command: git rev-list --objects --no-walk 1287c768bc97593f82dd3d9b507d750163ebaeb5 --
03:18:10.311556 trace git-lfs: run_command: git rev-list --objects --no-walk 3e16eda6264845dc2838589e22f3239521cdfa6d --
03:18:10.311656 trace git-lfs: run_command: git rev-list --objects --no-walk 3658d5cbde2fbcbf9cc37cd98148a8a2576f6063 --
03:18:10.311675 trace git-lfs: run_command: git rev-list --objects --no-walk 88e7502b5227c91c5509f613d22815c5e415b2b9 --
03:18:10.305092 trace git-lfs: run_command: git rev-list --objects --no-walk 6fd71b6b97c4f602a66e20d210e0058f6c141d6a --
\ 111 local objects, 0 retained                                                                                                                                                                             03:18:10.315189 trace git-lfs: run_command: git rev-list --objects --no-walk b3b8b016fcfefd067299439f31c703fc1fa1b8e9 --
03:18:10.315189 trace git-lfs: run_command: git rev-list --objects --no-walk fce489a9f22e169a6c047d6be6b7d2933af79ce9 --
03:18:10.315234 trace git-lfs: run_command: git rev-list --objects --no-walk b9363183b9e9fed4070dfad9841ea43c83f9af9e --
03:18:10.315371 trace git-lfs: run_command: git rev-list --objects --no-walk 73f69758bcbe1592c27ec1bfc18d2d4ea525a9f1 --
03:18:10.315384 trace git-lfs: run_command: git rev-list --objects --no-walk aa4b5bc2800f9a6cc35ab718244c09256eef94e1 --
| 112 local objects, 0 retained                                                                                                                                                                             03:18:10.318298 trace git-lfs: run_command: git rev-list --objects --no-walk da32c1f199d29b74ac0e25f9f1fa66102966814b --
03:18:10.318523 trace git-lfs: run_command: git rev-list --objects --no-walk 294e700b735b6bede398373fac1de62e28e34865 --
03:18:10.322581 trace git-lfs: run_command: git rev-list --objects --no-walk 83fa52919dfbdc72ccc7aac5af3a66a6b072a99a --
03:18:10.323494 trace git-lfs: run_command: git rev-list --objects --no-walk 9b50b26981abc9813f7ed97bd8a15a6b41399dbc --
03:18:10.323914 trace git-lfs: run_command: git rev-list --objects --no-walk 03ee20e1c982d887ae054d03a770d26e7642a66c --
03:18:10.324602 trace git-lfs: run_command: git rev-list --objects --no-walk 3879bd1de7690cfdc6c0f99a8e96cf8d732d8b6d --
/ 113 local objects, 0 retained                                                                                                                                                                             03:18:10.324949 trace git-lfs: run_command: git rev-list --objects --no-walk db8eef31d684d2c634eab02fdbc971c859a9d6fb --
03:18:10.325119 trace git-lfs: run_command: git rev-list --objects --no-walk 12f558de634ee61efd340e0659242926dcc63de5 --
03:18:10.325119 trace git-lfs: run_command: git rev-list --objects --no-walk 61569eeeff64f05c518f2f2011b63c3f59723e3a --
03:18:10.327682 trace git-lfs: run_command: git rev-list --objects --no-walk 7aadf61a886ddc87c633b14f25512cea38295450 --
- 114 local objects, 0 retained                                                                                                                                                                             03:18:10.327988 trace git-lfs: run_command: git rev-list --objects --no-walk d6fc89e70296fc35d8947dcb5dff637ab3738f3e --
03:18:10.328052 trace git-lfs: run_command: git rev-list --objects --no-walk aff180cd5d5fb95c6567d7b4713476bbcf0c8a00 --
03:18:10.328066 trace git-lfs: run_command: git rev-list --objects --no-walk b7aff8b96efd08b745985cf324dfed74256ed09b --
\ 115 local objects, 0 retained                                                                                                                                                                             03:18:10.331927 trace git-lfs: run_command: git rev-list --objects --no-walk c759480201bbae39d0e09f104b972aa6ed60eb1f --
03:18:10.332193 trace git-lfs: run_command: git rev-list --objects --no-walk c9e13ab66467a2baa6fcb7da8f9b1a2f5d0568a1 --
03:18:10.332437 trace git-lfs: run_command: git rev-list --objects --no-walk 46f3c1166e9a08006f49701521cfce72b778b254 --
03:18:10.332637 trace git-lfs: run_command: git rev-list --objects --no-walk a58a3efc784cea097943edbbc6f8021541fb76da --
03:18:10.332671 trace git-lfs: run_command: git rev-list --objects --no-walk 80a0973dd6a2cef489bc5c01cde4af8ffcfb214f --
03:18:10.332896 trace git-lfs: run_command: git rev-list --objects --no-walk d4c669856af625a4ad0093e15dea43844f1d276a --
03:18:10.333117 trace git-lfs: run_command: git rev-list --objects --no-walk cb63dd9d55f000e07f9b51a3b5533f5fdf3e3cde --
03:18:10.333121 trace git-lfs: run_command: git rev-list --objects --no-walk 2776daa179a5ab9387ca9c4e7d9241f58c9bd6a7 --
| 116 local objects, 0 retained                                                                                                                                                                             03:18:10.341017 trace git-lfs: run_command: git rev-list --objects --no-walk b45dbf3a1218a938fa7f2e6bd350dac83858e197 --
03:18:10.341597 trace git-lfs: run_command: git rev-list --objects --no-walk fcf46fad4a57f5a9cd17ad8cf1ea874080224ad8 --
03:18:10.341793 trace git-lfs: run_command: git rev-list --objects --no-walk c459f86d641ac426ac45b27844b073ebb5bf59a4 --
03:18:10.341799 trace git-lfs: run_command: git rev-list --objects --no-walk 51115c2b47e59f75c08cd01fdf0ab983df399996 --
- 118 local objects, 0 retained                                                                                                                                                                             03:18:10.348369 trace git-lfs: run_command: git rev-list --objects --no-walk c39b4f1c9e062f8f3c28701d81858a641bb22d3b --
03:18:10.349669 trace git-lfs: run_command: git rev-list --objects --no-walk ae71ae939159cc1e2f288272b881a5783f579ad6 --
03:18:10.353291 trace git-lfs: run_command: git rev-list --objects --no-walk 4edc2ae947c444a90fcace420c995c45967a4d5f --
03:18:10.353716 trace git-lfs: RETAIN: d09beba11484d622caed933b1d9d126c81d83bf1ab8928461834a316528c9362 unpushed
03:18:10.353736 trace git-lfs: RETAIN: 7b483eac43c43b7be8faa52912b06fa9bd5f646b3f3140654338597caa688e01 unpushed
- 120 local objects, 2 retained                                                                                                                                                                             03:18:10.362068 trace git-lfs: run_command: git rev-list --objects --no-walk ec545a54f0538296bfd1153ab9371e577a0fd01f --
03:18:10.362100 trace git-lfs: RETAIN: ef9e2e79492c8ed88ad3a7d1214cb7ab167a94f8be3c5070a8ad1d32628fc4e2 unpushed
\ 120 local objects, 3 retained                                                                                                                                                                             03:18:10.362301 trace git-lfs: run_command: git rev-list --objects --no-walk ac8d84803a205dbe7329ca01b5d199dfe9acbeee --
/ 122 local objects, 3 retained                                                                                                                                                                             03:18:10.366174 trace git-lfs: run_command: git rev-list --objects --no-walk 9cf207030836820c5c0857b18895c43d89e806d5 --
03:18:10.369645 trace git-lfs: run_command: git rev-list --objects --no-walk 35322d9f2c59e15048827406df85b726805c0dd8 --
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x132e852]

goroutine 25 [running]:
github.com/git-lfs/git-lfs/lfs.(*PointerScanner).Close(0x0, 0x173afe0, 0xc4202f4580)
	/Users/rick/go/src/github.com/git-lfs/git-lfs/lfs/gitscanner_catfilebatch.go:116 +0x22
github.com/git-lfs/git-lfs/lfs.runCatFileBatch(0xc420132a20, 0xc420132a80, 0xc420350000, 0xc42013e020, 0xc420132ae0, 0xc420055db8, 0x13318c4)
	/Users/rick/go/src/github.com/git-lfs/git-lfs/lfs/gitscanner_catfilebatch.go:22 +0x48
github.com/git-lfs/git-lfs/lfs.catFileBatch(0xc42013e020, 0xc420350000, 0x1511558, 0xc42023c660, 0x0, 0x0)
	/Users/rick/go/src/github.com/git-lfs/git-lfs/lfs/scanner.go:52 +0xbb
github.com/git-lfs/git-lfs/lfs.scanRefsToChan(0xc42013ba00, 0xc420055f78, 0xc4203d4106, 0x28, 0x0, 0x0, 0xc42025a190, 0x0, 0x13d8f96)
	/Users/rick/go/src/github.com/git-lfs/git-lfs/lfs/gitscanner_refs.go:66 +0x1ec
github.com/git-lfs/git-lfs/lfs.(*GitScanner).ScanRef(0xc42013ba00, 0xc4203d4106, 0x28, 0xc4201a6778, 0x0, 0x0)
	/Users/rick/go/src/github.com/git-lfs/git-lfs/lfs/gitscanner.go:124 +0x107
github.com/git-lfs/git-lfs/commands.pruneTaskGetRetainedAtRef(0xc42013ba00, 0xc4203d4106, 0x28, 0xc420063d40, 0xc420063ce0, 0xc420015620)
	/Users/rick/go/src/github.com/git-lfs/git-lfs/commands/command_prune.go:312 +0xdd
created by github.com/git-lfs/git-lfs/commands.pruneTaskGetRetainedCurrentAndRecentRefs
	/Users/rick/go/src/github.com/git-lfs/git-lfs/commands/command_prune.go:378 +0x823
```

**Comment by technoweenie** [comment] 2017-10-27 20:29
Doh, turned out to be an easy fix: #2699. This code has gone through a lot of changes since it was introduced, so it's possible there was a reason to try to close that scanner.

Now I'm really interested in what your actual error was :) Is this repeatable? I can provide a custom build if you want to see what error triggered this panic.

**Comment by zakharovvi** [comment] 2017-10-31 10:29
Hi @technoweenie!

I missed the notification. Sorry for this.

I built git-lfs binary via `script/bootstrap` from d039e37. I have the following errors with new binary:

$ git-lfs prune
```
- 485 local objects, 11353 retained                                                                                                                                                                                                                                             Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.430556579.log
Use `git lfs logs last` to view the log.
Prune error: open /dev/null: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.434493623.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.436711575.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.438845096.log
Use `git lfs logs last` to view the log.
Prune error: open /dev/null: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.440767543.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.442870539.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.444810517.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.446547773.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.448285742.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.450033285.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.451842717.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.453773168.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.455622771.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.457317289.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.458939982.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.460675216.log
Use `git lfs logs last` to view the log.
Prune error: open /dev/null: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.462417617.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.464210208.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.484811722.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.557326809.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.573062548.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.610534318.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.648637403.log
Use `git lfs logs last` to view the log.
Prune error: open stderr: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.685608641.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.721431812.log
Use `git lfs logs last` to view the log.
Prune error: open stdout: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.758884801.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.797139964.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.833935156.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.87637298.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.9139054.log
Use `git lfs logs last` to view the log.
Prune error: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.957412512.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151505.994146728.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: bad file descriptor

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151506.037422875.log
Use `git lfs logs last` to view the log.
Prune error: open stdin: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151506.074978415.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151506.111296864.log
Use `git lfs logs last` to view the log.
Prune error: open stderr: pipe: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151506.160281107.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151506.19776192.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151506.248619932.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151506.29072429.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: too many open files

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151506.331698156.log
Use `git lfs logs last` to view the log.
Prune error: fork/exec /usr/local/bin/git: bad file descriptor

Errors logged to PATH_TO_REPOSITORY/.git/lfs/logs/20171031T151506.374911259.log
Use `git lfs logs last` to view the log.
Prune sub-tasks failed, cannot continue
```

All log files content is almost same:

```
git-lfs/2.3.4 (GitHub; darwin amd64; go 1.9.2; git d039e379)
git version 2.14.3

$ git-lfs prune
- 485 local objects, 11353 retained                                                                                                                                                                                                                                             Prune error: pipe: too many open files
Prune error: open /dev/null: too many open files
Prune error: pipe: too many open files
Prune error: pipe: too many open files
Prune error: open /dev/null: too many open files
Prune error: pipe: too many open files
Prune error: pipe: too many open files
Prune error: pipe: too many open files
Prune error: pipe: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: pipe: too many open files
Prune error: pipe: too many open files
Prune error: pipe: too many open files
Prune error: pipe: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: open /dev/null: too many open files
Prune error: pipe: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: pipe: too many open files
Prune error: pipe: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: open stderr: pipe: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: open stdout: pipe: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: pipe: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: pipe: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: fork/exec /usr/local/bin/git: bad file descriptor
Prune error: open stdin: pipe: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: open stderr: pipe: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: fork/exec /usr/local/bin/git: too many open files
Prune error: fork/exec /usr/local/bin/git: bad file descriptor

fork/exec /usr/local/bin/git: bad file descriptor

Current time in UTC:
2017-10-31 10:15:06

ENV:
LocalWorkingDir=PATH_TO_REPOSITORY
LocalGitDir=PATH_TO_REPOSITORY/.git
LocalGitStorageDir=PATH_TO_REPOSITORY/.git
LocalMediaDir=PATH_TO_REPOSITORY/.git/lfs/objects
LocalReferenceDir=
TempDir=PATH_TO_REPOSITORY/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=PATH_TO_REPOSITORY/.git/lfs
AccessDownload=none
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic

```

**Comment by zakharovvi** [comment] 2017-10-31 10:42
macOS has an insufficient limit of open files by default:

```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited
```

After increasing the limit (`ulimit -n 4096`), errors a gone:

```
$ git-lfs prune
✔ 13069 local objects, 11442 retained
Pruning 1746 files, (3.7 GB)
✔ Deleted 1746 files
```

**Comment by technoweenie** [comment] 2017-10-31 16:47
Thanks for the report. I'll make another pass to see if there's an fd leak in there or something.

**Comment by ttaylorr** [comment] 2017-12-19 23:08
@zakharovvi Are any of the LFS objects in your repository using the extensions feature ([source](https://github.com/git-lfs/git-lfs/blob/master/docs/extensions.md))? I have a hunch that the issue is related to opening pipes into the stdout/stdin/stderr of subprocesses that are created and run by Git LFS, and the extensions code looks susceptible to me.

**Comment by zakharovvi** [comment] 2017-12-20 11:49
@ttaylorr We don't use extensions

**Comment by bk2204** [comment] 2018-10-16 16:44
I think this issue has been fixed.  In `master`, we're no longer invoking `git` in this case, so we shouldn't have a problem with forking and execing it due to too few file descriptors.  I'm going to close this, but if you see it again, please let us know, and we'll reopen it and take a look at fixing this.

**Closed by bk2204** 2018-10-16 16:44 UTC
Labels: bug

**Comment by SheldonWangRJT** [comment] 2019-09-18 00:18
this helps me a lot!
