### ISSUE TITLE
`git lfs pull` Too many open file

### ISSUE THREAD

**Issue by Socolin** [git-lfs/git-lfs#3446] opened 2018-12-24 19:26 UTC
When I'm trying to run `git lfs pull` in a big repository (40G and 30 000 files) I got these errors

```
$ git lfs pull
[...]
open /home/[...]/.git/lfs/incomplete/cdbc1....42047b.tmp: too many open files
open /home/[...]/.git/lfs/incomplete/34071....4ee084.tmp: too many open files
open /home/[...]/.git/lfs/incomplete/364a2....7ac3f1.tmp: too many open files
[...] # Lots more lines
open /home/[...]/.git/lfs/incomplete/4d9a3....a95460.tmp: too many open files
open /home/[...]/.git/lfs/incomplete/e5e91....aec7c8.tmp: too many open files
open /home/[...]/.git/lfs/incomplete/da698....acdf05.tmp: too many open files
open /home/[...]/.git/lfs/incomplete/dd1f9....159fc8.tmp: too many open files
```

```
$ git lfs version
git-lfs/2.6.1 (GitHub; linux amd64; go 1.11.1)
```

When git-lfs is spamming error, I get the following `lsof` output

```
git-lfs 11267 13144 root  mem       REG    0,0                       959188 /usr/bin/git-lfs (path dev=0,2, inode=4503599628329684)
git-lfs 11267 13144 root  mem       REG    0,0                       256014 /lib/x86_64-linux-gnu/libc-2.27.so (path dev=0,2, inode=844424930387982)
git-lfs 11267 13144 root  mem       REG    0,0                       255827 /lib/x86_64-linux-gnu/libpthread-2.27.so (path dev=0,2, inode=10414574138550099)
git-lfs 11267 13144 root  mem       REG    0,0                       255893 /lib/x86_64-linux-gnu/ld-2.27.so (path dev=0,2, inode=1125899907098517)
git-lfs 11267 13144 root    0u      CHR    4,1             2814749767486208 /dev/tty1
git-lfs 11267 13144 root    1u      CHR    4,1             2814749767486208 /dev/tty1
git-lfs 11267 13144 root    2u      CHR    4,1             2814749767486208 /dev/tty1
git-lfs 11267 13144 root    4u  unknown                                     /unknown (stat: Operation not permitted)
git-lfs 11267 13144 root    8u     sock    0,0                       112677 can't identify protocol
git-lfs 11267 13144 root   14u     sock    0,0                       112697 can't identify protocol
git-lfs 11267 13144 root   16u     sock    0,0                       112698 can't identify protocol
git-lfs 11267 13144 root   17u     sock    0,0                       112699 can't identify protocol
git-lfs 11267 13144 root   19u     sock    0,0                       112702 can't identify protocol
git-lfs 11267 13144 root   22u     sock    0,0                       112705 can't identify protocol
git-lfs 11267 13144 root   23u     sock    0,0                       112706 can't identify protocol
git-lfs 11267 13144 root   24u     sock    0,0                       112707 can't identify protocol
git-lfs 11267 13144 root   34u     sock    0,0                       112767 can't identify protocol
git-lfs 11267 13144 root   35u     sock    0,0                       112768 can't identify protocol
git-lfs 11267 13144 root   36u     sock    0,0                       112769 can't identify protocol
git-lfs 11267 13144 root   27u     sock    0,0                       112772 can't identify protocol
git-lfs 11267 13144 root   39u     sock    0,0                       112792 can't identify protocol
git-lfs 11267 13144 root   20u     sock    0,0                       112802 can't identify protocol
git-lfs 11267 13144 root   41u     sock    0,0                       112805 can't identify protocol
git-lfs 11267 13144 root   38u     sock    0,0                       112806 can't identify protocol
git-lfs 11267 13144 root   18u     sock    0,0                       112816 can't identify protocol
git-lfs 11267 13144 root   42u     sock    0,0                       112819 can't identify protocol
git-lfs 11267 13144 root   45u     sock    0,0                       112820 can't identify protocol
git-lfs 11267 13144 root   46u     sock    0,0                       112821 can't identify protocol
git-lfs 11267 13144 root   15u     sock    0,0                       112824 can't identify protocol
git-lfs 11267 13144 root   40u     sock    0,0                       112834 can't identify protocol
git-lfs 11267 13144 root   44u     sock    0,0                       112835 can't identify protocol
git-lfs 11267 13144 root   47u     sock    0,0                       112836 can't identify protocol
git-lfs 11267 13144 root   48u     sock    0,0                       112839 can't identify protocol
git-lfs 11267 13144 root   49u     sock    0,0                       112842 can't identify protocol
git-lfs 11267 13144 root   50u     sock    0,0                       112845 can't identify protocol
git-lfs 11267 13144 root   43u     sock    0,0                       112848 can't identify protocol
git-lfs 11267 13144 root   21u     sock    0,0                       112858 can't identify protocol
git-lfs 11267 13144 root   32u     sock    0,0                       112859 can't identify protocol
git-lfs 11267 13144 root   54u     sock    0,0                       112860 can't identify protocol
git-lfs 11267 13144 root   55u     sock    0,0                       112861 can't identify protocol
git-lfs 11267 13144 root   56u     sock    0,0                       112864 can't identify protocol
git-lfs 11267 13144 root   51u     sock    0,0                       112868 can't identify protocol
git-lfs 11267 13144 root   53u     sock    0,0                       112869 can't identify protocol
git-lfs 11267 13144 root   58u     sock    0,0                       112872 can't identify protocol
git-lfs 11267 13144 root   60u     sock    0,0                       112873 can't identify protocol
git-lfs 11267 13144 root   61u     sock    0,0                       112879 can't identify protocol
git-lfs 11267 13144 root   65u     sock    0,0                       112880 can't identify protocol
git-lfs 11267 13144 root   57u     sock    0,0                       112890 can't identify protocol
git-lfs 11267 13144 root   59u     sock    0,0                       112891 can't identify protocol
git-lfs 11267 13144 root   62u     sock    0,0                       112892 can't identify protocol
git-lfs 11267 13144 root   64u     sock    0,0                       112893 can't identify protocol
git-lfs 11267 13144 root   66u     sock    0,0                       112894 can't identify protocol
git-lfs 11267 13144 root   67u     sock    0,0                       112895 can't identify protocol
git-lfs 11267 13144 root   70u     sock    0,0                       112901 can't identify protocol
git-lfs 11267 13144 root   13u     sock    0,0                       112906 can't identify protocol
git-lfs 11267 13144 root   73u     sock    0,0                       112908 can't identify protocol
git-lfs 11267 13144 root   74u     sock    0,0                       112909 can't identify protocol
git-lfs 11267 13144 root   75u     sock    0,0                       112910 can't identify protocol
git-lfs 11267 13144 root   68u     sock    0,0                       112913 can't identify protocol
git-lfs 11267 13144 root   72u     sock    0,0                       112916 can't identify protocol
git-lfs 11267 13144 root   28u     sock    0,0                       112919 can't identify protocol
git-lfs 11267 13144 root   77u     sock    0,0                       112922 can't identify protocol
git-lfs 11267 13144 root   71u     sock    0,0                       112925 can't identify protocol
git-lfs 11267 13144 root   76u     sock    0,0                       112928 can't identify protocol
git-lfs 11267 13144 root   52u     sock    0,0                       112931 can't identify protocol
git-lfs 11267 13144 root   80u     sock    0,0                       112932 can't identify protocol
git-lfs 11267 13144 root   78u     sock    0,0                       112935 can't identify protocol
git-lfs 11267 13144 root   81u     sock    0,0                       112936 can't identify protocol
git-lfs 11267 13144 root   83u     sock    0,0                       112939 can't identify protocol
git-lfs 11267 13144 root   84u     sock    0,0                       112949 can't identify protocol
git-lfs 11267 13144 root   85u     sock    0,0                       112952 can't identify protocol
git-lfs 11267 13144 root   87u     sock    0,0                       112955 can't identify protocol
git-lfs 11267 13144 root   10u     sock    0,0                       112958 can't identify protocol
git-lfs 11267 13144 root   86u     sock    0,0                       112961 can't identify protocol
git-lfs 11267 13144 root   82u     sock    0,0                       112966 can't identify protocol
git-lfs 11267 13144 root   88u     sock    0,0                       112971 can't identify protocol
git-lfs 11267 13144 root   12u     sock    0,0                       112976 can't identify protocol
git-lfs 11267 13144 root   29u     sock    0,0                       112977 can't identify protocol
git-lfs 11267 13144 root   94u     sock    0,0                       112980 can't identify protocol
git-lfs 11267 13144 root   92u     sock    0,0                       112983 can't identify protocol
git-lfs 11267 13144 root   93u     sock    0,0                       112986 can't identify protocol
git-lfs 11267 13144 root   95u     sock    0,0                       112989 can't identify protocol
git-lfs 11267 13144 root   96u     sock    0,0                       112992 can't identify protocol
git-lfs 11267 13144 root   97u     sock    0,0                       112995 can't identify protocol
git-lfs 11267 13144 root   31u     sock    0,0                       112998 can't identify protocol
git-lfs 11267 13144 root   98u     sock    0,0                       113001 can't identify protocol
git-lfs 11267 13144 root  100u     sock    0,0                       113008 can't identify protocol
git-lfs 11267 13144 root   30u     sock    0,0                       113011 can't identify protocol
git-lfs 11267 13144 root  104u     sock    0,0                       113024 can't identify protocol
git-lfs 11267 13144 root  105u     sock    0,0                       113025 can't identify protocol
git-lfs 11267 13144 root  106u     sock    0,0                       113026 can't identify protocol
git-lfs 11267 13144 root  107u     sock    0,0                       113027 can't identify protocol
git-lfs 11267 13144 root  108u     sock    0,0                       113030 can't identify protocol
git-lfs 11267 13144 root   69u     sock    0,0                       113033 can't identify protocol
git-lfs 11267 13144 root  110u     sock    0,0                       113034 can't identify protocol
git-lfs 11267 13144 root   26u     sock    0,0                       113039 can't identify protocol
git-lfs 11267 13144 root   91u     sock    0,0                       113040 can't identify protocol
git-lfs 11267 13144 root  112u     sock    0,0                       113045 can't identify protocol
git-lfs 11267 13144 root  113u     sock    0,0                       113052 can't identify protocol
git-lfs 11267 13144 root  118u     sock    0,0                       113053 can't identify protocol
git-lfs 11267 13144 root  116u     sock    0,0                       113058 can't identify protocol
git-lfs 11267 13144 root   90u     sock    0,0                       113059 can't identify protocol
git-lfs 11267 13144 root   25u     sock    0,0                       113062 can't identify protocol
git-lfs 11267 13144 root   99u     sock    0,0                       113063 can't identify protocol
git-lfs 11267 13144 root   89u     sock    0,0                       113066 can't identify protocol
git-lfs 11267 13144 root  115u     sock    0,0                       113069 can't identify protocol
git-lfs 11267 13144 root  119u     sock    0,0                       113070 can't identify protocol
git-lfs 11267 13144 root  101u     sock    0,0                       113073 can't identify protocol
git-lfs 11267 13144 root   11u     sock    0,0                       113084 can't identify protocol
git-lfs 11267 13144 root  122u     sock    0,0                       113099 can't identify protocol
git-lfs 11267 13144 root  123u     sock    0,0                       113100 can't identify protocol
git-lfs 11267 13144 root  124u     sock    0,0                       113101 can't identify protocol
git-lfs 11267 13144 root  125u     sock    0,0                       113102 can't identify protocol
git-lfs 11267 13144 root  126u     sock    0,0                       113105 can't identify protocol
git-lfs 11267 13144 root  127u     sock    0,0                       113106 can't identify protocol
git-lfs 11267 13144 root  128u     sock    0,0                       113107 can't identify protocol
git-lfs 11267 13144 root  134u     sock    0,0                       113161 can't identify protocol
git-lfs 11267 13144 root  137u     sock    0,0                       113192 can't identify protocol
git-lfs 11267 13144 root  138u     sock    0,0                       113195 can't identify protocol
git-lfs 11267 13144 root  139u     sock    0,0                       113198 can't identify protocol
git-lfs 11267 13144 root  140u     sock    0,0                       113208 can't identify protocol
git-lfs 11267 13144 root  141u     sock    0,0                       113214 can't identify protocol
git-lfs 11267 13144 root  120u     sock    0,0                       113221 can't identify protocol
git-lfs 11267 13144 root  135u     sock    0,0                       113227 can't identify protocol
git-lfs 11267 13144 root   63u     sock    0,0                       113244 can't identify protocol
git-lfs 11267 13144 root  145u     sock    0,0                       113254 can't identify protocol
git-lfs 11267 13144 root  146u     sock    0,0                       113257 can't identify protocol
git-lfs 11267 13144 root  147u     sock    0,0                       113260 can't identify protocol
git-lfs 11267 13144 root  148u     sock    0,0                       113274 can't identify protocol
git-lfs 11267 13144 root  149u     sock    0,0                       113277 can't identify protocol
git-lfs 11267 13144 root  150u     sock    0,0                       113283 can't identify protocol
git-lfs 11267 13144 root  117u     sock    0,0                       113314 can't identify protocol
git-lfs 11267 13144 root  131u     sock    0,0                       113315 can't identify protocol
git-lfs 11267 13144 root  136u     sock    0,0                       113316 can't identify protocol
git-lfs 11267 13144 root  143u     sock    0,0                       113317 can't identify protocol
git-lfs 11267 13144 root  144u     sock    0,0                       113318 can't identify protocol
git-lfs 11267 13144 root  151u     sock    0,0                       113319 can't identify protocol
git-lfs 11267 13144 root  154u     sock    0,0                       113322 can't identify protocol
git-lfs 11267 13144 root  158u     sock    0,0                       113338 can't identify protocol
git-lfs 11267 13144 root  152u     sock    0,0                       113358 can't identify protocol
git-lfs 11267 13144 root  160u     sock    0,0                       113368 can't identify protocol
git-lfs 11267 13144 root  159u     sock    0,0                       113371 can't identify protocol
git-lfs 11267 13144 root  153u     sock    0,0                       113374 can't identify protocol
git-lfs 11267 13144 root  111u     sock    0,0                       113377 can't identify protocol
git-lfs 11267 13144 root  156u     sock    0,0                       113378 can't identify protocol
git-lfs 11267 13144 root    9u     sock    0,0                       113388 can't identify protocol
git-lfs 11267 13144 root  161u     sock    0,0                       113389 can't identify protocol
git-lfs 11267 13144 root  103u     sock    0,0                       113392 can't identify protocol
git-lfs 11267 13144 root  142u     sock    0,0                       113393 can't identify protocol
git-lfs 11267 13144 root  165u     sock    0,0                       113396 can't identify protocol
git-lfs 11267 13144 root  166u     sock    0,0                       113397 can't identify protocol
git-lfs 11267 13144 root  167u     sock    0,0                       113400 can't identify protocol
git-lfs 11267 13144 root  168u     sock    0,0                       113403 can't identify protocol
git-lfs 11267 13144 root  169u     sock    0,0                       113406 can't identify protocol
git-lfs 11267 13144 root  170u     sock    0,0                       113407 can't identify protocol
git-lfs 11267 13144 root  171u     sock    0,0                       113408 can't identify protocol
git-lfs 11267 13144 root  109u     sock    0,0                       113415 can't identify protocol
git-lfs 11267 13144 root  162u     sock    0,0                       113416 can't identify protocol
git-lfs 11267 13144 root  172u     sock    0,0                       113417 can't identify protocol
git-lfs 11267 13144 root  173u     sock    0,0                       113418 can't identify protocol
git-lfs 11267 13144 root  174u     sock    0,0                       113419 can't identify protocol
git-lfs 11267 13144 root  175u     sock    0,0                       113425 can't identify protocol
git-lfs 11267 13144 root  176u     sock    0,0                       113426 can't identify protocol
git-lfs 11267 13144 root  177u     sock    0,0                       113431 can't identify protocol
git-lfs 11267 13144 root  181u     sock    0,0                       113435 can't identify protocol
git-lfs 11267 13144 root  179u     sock    0,0                       113436 can't identify protocol
git-lfs 11267 13144 root  180u     sock    0,0                       113439 can't identify protocol
git-lfs 11267 13144 root  182u     sock    0,0                       113442 can't identify protocol
git-lfs 11267 13144 root  183u     sock    0,0                       113443 can't identify protocol
git-lfs 11267 13144 root  185u     sock    0,0                       113446 can't identify protocol
git-lfs 11267 13144 root  186u     sock    0,0                       113447 can't identify protocol
git-lfs 11267 13144 root  187u     sock    0,0                       113448 can't identify protocol
git-lfs 11267 13144 root  129u     sock    0,0                       113451 can't identify protocol
git-lfs 11267 13144 root  189u     sock    0,0                       113454 can't identify protocol
git-lfs 11267 13144 root  121u     sock    0,0                       113457 can't identify protocol
git-lfs 11267 13144 root  188u     sock    0,0                       113460 can't identify protocol
git-lfs 11267 13144 root  192u     sock    0,0                       113461 can't identify protocol
git-lfs 11267 13144 root  155u     sock    0,0                       113464 can't identify protocol
git-lfs 11267 13144 root  190u     sock    0,0                       113467 can't identify protocol
git-lfs 11267 13144 root  193u     sock    0,0                       113470 can't identify protocol
git-lfs 11267 13144 root  102u     sock    0,0                       113473 can't identify protocol
git-lfs 11267 13144 root  157u     sock    0,0                       113474 can't identify protocol
git-lfs 11267 13144 root  194u     sock    0,0                       113477 can't identify protocol
git-lfs 11267 13144 root  199u     sock    0,0                       113483 can't identify protocol
git-lfs 11267 13144 root  197u     sock    0,0                       113484 can't identify protocol
git-lfs 11267 13144 root  200u     sock    0,0                       113490 can't identify protocol
git-lfs 11267 13144 root  114u     sock    0,0                       113497 can't identify protocol
git-lfs 11267 13144 root  202u     sock    0,0                       113500 can't identify protocol
git-lfs 11267 13144 root  178u     sock    0,0                       113503 can't identify protocol
git-lfs 11267 13144 root  203u     sock    0,0                       113506 can't identify protocol
git-lfs 11267 13144 root  184u     sock    0,0                       113509 can't identify protocol
git-lfs 11267 13144 root  205u     sock    0,0                       113514 can't identify protocol
git-lfs 11267 13144 root  206u     sock    0,0                       113515 can't identify protocol
git-lfs 11267 13144 root  207u     sock    0,0                       113516 can't identify protocol
git-lfs 11267 13144 root  209u     sock    0,0                       113517 can't identify protocol
git-lfs 11267 13144 root  196u     sock    0,0                       113521 can't identify protocol
git-lfs 11267 13144 root  208u     sock    0,0                       113522 can't identify protocol
git-lfs 11267 13144 root  211u     sock    0,0                       113525 can't identify protocol
git-lfs 11267 13144 root  212u     sock    0,0                       113531 can't identify protocol
git-lfs 11267 13144 root  213u     sock    0,0                       113534 can't identify protocol
git-lfs 11267 13144 root  214u     sock    0,0                       113535 can't identify protocol
git-lfs 11267 13144 root  216u     sock    0,0                       113538 can't identify protocol
git-lfs 11267 13144 root  215u     sock    0,0                       113541 can't identify protocol
git-lfs 11267 13144 root  217u     sock    0,0                       113544 can't identify protocol
git-lfs 11267 13144 root  191u     sock    0,0                       113547 can't identify protocol
git-lfs 11267 13144 root  195u     sock    0,0                       113550 can't identify protocol
git-lfs 11267 13144 root  219u     sock    0,0                       113553 can't identify protocol
git-lfs 11267 13144 root  221u     sock    0,0                       113559 can't identify protocol
git-lfs 11267 13144 root  130u     sock    0,0                       113569 can't identify protocol
git-lfs 11267 13144 root  201u     sock    0,0                       113579 can't identify protocol
git-lfs 11267 13144 root  218u     sock    0,0                       113580 can't identify protocol
git-lfs 11267 13144 root  224u     sock    0,0                       113581 can't identify protocol
git-lfs 11267 13144 root  225u     sock    0,0                       113582 can't identify protocol
git-lfs 11267 13144 root  226u     sock    0,0                       113583 can't identify protocol
git-lfs 11267 13144 root  227u     sock    0,0                       113584 can't identify protocol
git-lfs 11267 13144 root  228u     sock    0,0                       113585 can't identify protocol
git-lfs 11267 13144 root  236u     sock    0,0                       113606 can't identify protocol
git-lfs 11267 13144 root  237u     sock    0,0                       113616 can't identify protocol
git-lfs 11267 13144 root  238u     sock    0,0                       113630 can't identify protocol
git-lfs 11267 13144 root  239u     sock    0,0                       113631 can't identify protocol
git-lfs 11267 13144 root  235u     sock    0,0                       113637 can't identify protocol
git-lfs 11267 13144 root  241u     sock    0,0                       113638 can't identify protocol
git-lfs 11267 13144 root  234u     sock    0,0                       113662 can't identify protocol
git-lfs 11267 13144 root  240u     sock    0,0                       113665 can't identify protocol
git-lfs 11267 13144 root  132u     sock    0,0                       113672 can't identify protocol
git-lfs 11267 13144 root  242u     sock    0,0                       113673 can't identify protocol
git-lfs 11267 13144 root  244u     sock    0,0                       113676 can't identify protocol
git-lfs 11267 13144 root  243u     sock    0,0                       113692 can't identify protocol
git-lfs 11267 13144 root  245u     sock    0,0                       113695 can't identify protocol
git-lfs 11267 13144 root  247u     sock    0,0                       113696 can't identify protocol
git-lfs 11267 13144 root  248u     sock    0,0                       113703 can't identify protocol
git-lfs 11267 13144 root  249u     sock    0,0                       113713 can't identify protocol
git-lfs 11267 13144 root  250u     sock    0,0                       113716 can't identify protocol
git-lfs 11267 13144 root  251u     sock    0,0                       113719 can't identify protocol
git-lfs 11267 13144 root  253u     sock    0,0                       113725 can't identify protocol
git-lfs 11267 13144 root  254u     sock    0,0                       113728 can't identify protocol
git-lfs 11267 13144 root  255u     sock    0,0                       113729 can't identify protocol
git-lfs 11267 13144 root  223u     sock    0,0                       113765 can't identify protocol
git-lfs 11267 13144 root  133u     sock    0,0                       113772 can't identify protocol
git-lfs 11267 13144 root  198u     sock    0,0                       113773 can't identify protocol
git-lfs 11267 13144 root  230u     sock    0,0                       113790 can't identify protocol
git-lfs 11267 13144 root  252u     sock    0,0                       113793 can't identify protocol
git-lfs 11267 13144 root   37u     sock    0,0                       113885 can't identify protocol
git-lfs 11267 13144 root   79u     sock    0,0                       113886 can't identify protocol
git-lfs 11267 13144 root  164u     sock    0,0                       113887 can't identify protocol
git-lfs 11267 13144 root  210u     sock    0,0                       113888 can't identify protocol
git-lfs 11267 13144 root  204u     sock    0,0                       113897 can't identify protocol
git-lfs 11267 13144 root  232u     sock    0,0                       113993 can't identify protocol
git-lfs 11267 13144 root  233u     sock    0,0                       113994 can't identify protocol
git-lfs 11267 13144 root  231u     sock    0,0                       114016 can't identify protocol
git-lfs 11267 13144 root  220u     sock    0,0                       114071 can't identify protocol
git-lfs 11267 13144 root  222u     sock    0,0                       114107 can't identify protocol
git-lfs 11267 13144 root  163u     sock    0,0                       114163 can't identify protocol
git-lfs 11267 13144 root  246u     sock    0,0                       114199 can't identify protocol
git-lfs 11267 13144 root  229u     sock    0,0                       117790 can't identify protocol
git-lfs 11267 13144 root    3u     sock    0,0                       118122 can't identify protocol
git-lfs 11267 13144 root    6u     sock    0,0                       120583 can't identify protocol
git-lfs 11267 13144 root    5u     sock    0,0                       120653 can't identify protocol
git-lfs 11267 13144 root    7u     sock    0,0                       122695 can't identify protocol
```

OS: `Ubuntu 18.04 (Linux subsystem on Windows 10)`

The "too many open files" don't seem to be caused by a missing close, since I can see some `close` for opened sockets in `strace` output.
It looks like there is no limit on the maximum files that are being downloaded at the same time.

**Comment by bk2204** [comment] 2019-01-03 15:08
Hey, sorry to hear you've having a problem.

We should theoretically limit batch sizes to 100 by default, which should avoid this problem. Can you include the output of `git lfs env` and `ulimit -a`, so we can see if Git LFS is configured properly for the number of open files on your system?

**Comment by Socolin** [comment] 2019-01-04 01:57
`git lfs env`

```
git-lfs/2.6.1 (GitHub; linux amd64; go 1.11.1)
git version 2.17.1

Endpoint=https://git.mediacliphub.com/librairies/shindigz.git/info/lfs (auth=none)
  SSH=git@git.mediacliphub.com:librairies/shindigz.git
LocalWorkingDir=/mnt/d/some-path
LocalGitDir=/mnt/d/some-path/.git
LocalGitStorageDir=/mnt/d/some-path/.git
LocalMediaDir=/mnt/d/some-path/.git/lfs/objects
LocalReferenceDirs=
TempDir=/mnt/d/some-path/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/mnt/d/some-path/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

`ulimit -a` Even with `ulimit -n 8192` its still failing at some points

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7823
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7823
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by snichols** [comment] 2019-01-14 06:22
@bk2204 I'm seeing a similar issue on Windows and OS X as well.  Different repository than @Socolin.  Around 29k files in LFS.

On Windows `git lfs pull` pulls around 16k files before failing repeatedly with this message:
```
batch response: Post https://git.someurl.com/project.git/info/lfs/objects/batch: dial tcp xxx.xxx.xxx.xxx:443: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
```
That message is caused when the OS has no more buffer space for new sockets.

On OS X, `too many open files` occurs when the number of LFS files downloaded exceeds the `ulimit -n` setting.  Have verified this with values of 256 and 8192.

The workaround for this is to invoke `git lfs pull` multiple times as it picks up from where it left off.

I've not looked at the git-lfs code yet but it sure sounds like it's leaking sockets.  Will have a look and let you know what I find.

**Comment by bk2204** [comment] 2019-01-14 19:39
I'm definitely interested to see if you can find a socket leak. We've had some discussion about this in the past, but I don't think we've been able to definitively find a leak.

**Comment by snichols** [comment] 2019-01-15 17:45
@bk2204 @PastelMobileSuit Alrighty, I've given this a bit more time this morning.  The root issue looks to be how request redirect is handled.  We're using GitLab for our LFS server with the blobs backed by S3.  Each `lfs/object` request gets redirected to S3 for the actual download.

This is the offending code in `lfshttpclient/client.go`:
```go
httpClient := &http.Client{
	Transport: tr,
	CheckRedirect: func(*http.Request, []*http.Request) error {
		return http.ErrUseLastResponse
	},
}
```
There's no comment on the use of `CheckRedirect` here but I surmise that it's being used to enable custom redirect processing in `DoWithRedirect` in `lfshttp/client.go`.  In any case, removing that `CheckRedirect` assignment resolved the problem.  All files were downloaded properly.

The comment for `CheckRedirect` in `http/client.go` sheds some light on why this is a problem:
```go
// CheckRedirect specifies the policy for handling redirects.
// If CheckRedirect is not nil, the client calls it before
// following an HTTP redirect. The arguments req and via are
// the upcoming request and the requests made already, oldest
// first. If CheckRedirect returns an error, the Client's Get
// method returns both the previous Response (with its Body
// closed) and CheckRedirect's error (wrapped in a url.Error)
// instead of issuing the Request req.
// As a special case, if CheckRedirect returns ErrUseLastResponse,
// then the most recent response is returned with its body
// unclosed, along with a nil error.
//
// If CheckRedirect is nil, the Client uses its default policy,
// which is to stop after 10 consecutive requests.
CheckRedirect func(req *Request, via []*Request) error
```
The critical piece here is that returning `ErrUseLastResponse` from `CheckRedirect` causes the original `3XX` response body to remain unread and opened.  The transport requires the body of a http/1 response to be fully read and closed in order to be deemed idle.  So, in essence, this code is causing a socket leak for each redirect hop.

I assume that `DoWithRedirect` is supposed to be handling the leaking response body in some way but I've not investigated that code yet.  My intuition tells me that this custom redirect handling is probably unnecessary and removal should be considered.  However, I will investigate that code to understand the author's intent and report back my findings.

**Comment by bk2204** [comment] 2019-01-15 18:31
Thanks, this is really great investigative work.

Just so you know, the code in question was moved from `lfsapi/client.go`, where it was implemented originally, so we've had it for a long time. Blaming that file shows that it came in with 85f172389, which seems to imply that it was intended to handle 307 redirections. It's indeed possible that with newer versions of Go, that those are handled correctly and we can remove that code.

**Comment by bk2204** [comment] 2019-01-15 18:50
Also, I have what might be a smaller fix in a branch on my remote called `close-body-redirect`. If that works for you, I'm happy to submit it (with a better commit message, of course).

**Comment by snichols** [comment] 2019-01-15 19:40
You're welcome!  I didn't dig too deeply on the blame... that extra context is great.

I'll apply your change in `close-body-redirect` and verify it works.

**Comment by snichols** [comment] 2019-01-15 19:49
And, yeah, that's an old change.  Looks like we've found a long-standing bug.  Woot!

**Comment by snichols** [comment] 2019-01-15 19:58
It looks like your change resolves the problem as well.  It feels a bit dirty to me... but only because the lifetime of the various responses immediately obvious to me when reading the code.  I'm particularly nervous when I see returns that may bypass the close call.  Regardless, it's an improvement over running out of file handles.  :shipit:

As I've read through other parts of the code some further improvements come to mind.  I'll see about capturing those in separate issues.  I definitely think reenabling http/2 could allow for more parallel download requests and overall higher throughput... but I'll need to do testing to prove that out.

Thanks for the fast turnaround!

**Closed** 2019-01-22 17:32 UTC
