### ISSUE TITLE
Windows installer issues

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#1120] opened 2016-04-03 20:28 UTC
- When `c:\Program Files\Git LFS` (or anything not in the `$PATH`), either warn or add it to the `$PATH`.
- Mention when `git lfs install` fails to run, especially due to a `$PATH` issue.
- Rename uninst filename to something like `git-uninstall.exe`.

**Comment by strich** [comment] 2016-04-03 20:45
The installer does already add `C:\Program Files\Git LFS` to `$PATH`. There is however no error reporting or recovery, so if there is something going wrong we won't know about it. I'll look into ensuring that all steps are confirmed and errors caught and either dealt with or reported to the user.

**Comment by technoweenie** [comment] 2016-04-03 20:50
I wonder if there's something that needs to be refreshed between when it adds to the `$PATH` and when `git lfs install` runs? I restarted Git Bash, and now `/c/Program Files/Git LFS:/bin` is in there. Installing and uninstalling works fine with that. 

I'm pretty sure the installer added it to `$PATH` because I have no idea how to change it on Windows :)

**Comment by dg9ngf** [comment] 2016-04-03 20:51
Why does this extension to Git even need its own installation directory? Can't the git-lfs.exe binary just be placed somewhere git.exe will find it like every other Git command, too? %PATH% is growing and growing...

**Comment by strich** [comment] 2016-04-03 21:03
@technoweenie a console window does need to be refreshed after `$PATH` changes. However we use a new console session to perform the `git lfs install` so that cannot be the problem.

However this discussion has led me to think there might be an issue with the setup not performing the steps in the order I expected them to. This could be the root cause. I'll check it out in a day or so and report back.

@dg9ngf the reason we chose to give Git LFS its own installation directory is because there can be many forms of Git in windows with their own ways of installing themselves, and it is really difficult to figure out where to put git-lfs.exe. Furthermore, it created a dependency on another project - If, for example, Git for Windows changed the way it installs itself it could instantly break the Git LFS installer. It just seemed cleaner to give Git LFS its own installation directory, and there are no drawbacks to doing so.

**Comment by sinbad** [comment] 2016-04-04 11:13
> and there are no drawbacks to doing so

Unfortunately there are: primarily the limited `PATH` length on Windows. Anything over 2047 characters gets a bit dodgy, Win 7 can extend that to 4095 but requires a restart before it works (after you go over the old limit). The results of exceeding this length are randomly failing to find things on the PATH all of a sudden; in SourceTree for Windows we deliberately keep PATH additions to a minimum because of this, some developers have a lot of stuff on their PATH especially if they work in a lot of environments or forget to clean up.

**Comment by strich** [comment] 2016-04-04 12:00
Ah. I was not aware of that. In either case I do feel that the issue of trying to ensure `git-lfs.exe` is installed to the correct location is more difficult and serious to deal with than the `PATH` character limit edge-case.

I could add some error reporting to the installer in the case of `PATH` being >2047 and leave it to the user to deal with in that case, as presumably they will be a poweruser to have a `PATH` so long.

**Comment by dg9ngf** [comment] 2016-04-04 13:00
Git LFS could be integrated into Git directly, as many other Git-related software is doing the same (for example GitLab comes with LFS by default). That would make things a lot easier to set up and integrate.

**Comment by strich** [comment] 2016-04-04 13:20
It makes sense for software like GitLab or SourceTree to package git and git LFS as one because they have full control over that package. In this case we do not, so I have to disagree.

**Comment by strich** [comment] 2016-04-19 18:02
I think this can be closed now? @technoweenie

**Comment by technoweenie** [comment] 2016-04-19 19:45
I think it's good, but I'd like verification from @dg9ngf

**Comment by javabrett** [comment] 2016-04-24 08:26
Should add label `installation`?

**Comment by dg9ngf** [comment] 2016-04-24 15:11
Yes, version 1.2.0 works fine for me now. `git config -l` shows the added filter items directly after running the installer. Thank you.

**Comment by sschuberth** [comment] 2016-12-23 09:51
Closing this as @ygoe (aka @dg9ngf) verified the fix.

**Closed by sschuberth** 2016-12-23 09:51 UTC
