### ISSUE TITLE
Error running 'git rev-parse': error converting ".git" to absolute: Access is denied.

### ISSUE THREAD

**Issue by 4nti-7rust** [git-lfs/git-lfs#4178] opened 2020-07-03 09:05 UTC
**Describe the bug**
A colleague of mine had some trouble pushing its branch to the remote (see trace below), so I got a copy of the git project and tried it on my side too, with the same error. It probably mean that the project is somewhat corrupted, but I cannot figure out what is wrong and what the error mean.

**To Reproduce**
I could not reproduce the error on a dummy repo, and sadly I cannot share the project (proprietary informations).

Here is the output of the command that I want to run and fail :

```
GIT_TRACE=1 git push --set-upstream origin fix/defect_073
10:03:23.178283 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
10:03:23.197282 git.c:442               trace: built-in: git push --set-upstream origin fix/defect_073
10:03:23.213283 run-command.c:663       trace: run_command: git remote-https origin https://*******
10:03:23.313806 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:03:23.328805 git.c:702               trace: exec: git-remote-https origin https://*******
10:03:23.328805 run-command.c:663       trace: run_command: git-remote-https origin https://*******
10:03:23.442817 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:03:24.024826 run-command.c:663       trace: run_command: 'git credential-manager get'
10:03:24.235806 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:03:24.250810 git.c:702               trace: exec: git-credential-manager get
10:03:24.250810 run-command.c:663       trace: run_command: git-credential-manager get
10:03:24.995806 run-command.c:663       trace: run_command: 'git credential-manager store'
10:03:25.174841 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:03:25.191806 git.c:702               trace: exec: git-credential-manager store
10:03:25.191806 run-command.c:663       trace: run_command: git-credential-manager store
10:03:25.619809 run-command.c:663       trace: run_command: .git/hooks/pre-push origin https://*******
10:03:25.852807 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:03:25.866810 git.c:702               trace: exec: git-lfs pre-push origin https://*******
10:03:25.867817 run-command.c:663       trace: run_command: git-lfs pre-push origin https://*******
10:03:26.073804 trace git-lfs: exec: git 'version'
10:03:26.391806 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
10:03:27.001809 trace git-lfs: Error running 'git rev-parse': error converting ".git" to absolute: Access is denied.
Error: error converting ".git" to absolute: Access is denied.
10:03:27.001809 trace git-lfs: exec: git 'config' '-l'
10:03:27.089808 trace git-lfs: pre-push: refs/heads/fix/defect_073 14d67673b11480541510ab24d6015107268b3fd0 refs/heads/fix/defect_073 0000000000000000000000000000000000000000
10:03:29.332821 trace git-lfs: creds: git credential fill ("https", "*******", "")
10:03:29.393807 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:03:29.410810 git.c:442               trace: built-in: git credential fill
10:03:29.419810 run-command.c:663       trace: run_command: 'git credential-manager get'
10:03:29.578812 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:03:29.591810 git.c:702               trace: exec: git-credential-manager get
10:03:29.591810 run-command.c:663       trace: run_command: git-credential-manager get
10:03:30.089806 trace git-lfs: Filled credentials for https://*******
10:03:30.089806 trace git-lfs: HTTP: POST https://*******.git/info/lfs/locks/verify
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://*******.git/info/lfs.locksverify false
Post "https://*******.git/info/lfs/locks/verify": Bad Gateway
error: failed to push some refs to 'https://*******'
```

**Expected behavior**
The push operation should work.

**System environment**
Using :
- Windows 10 professional version 1809 / 17763.1283
- git version 2.27.0.windows.1
- git-lfs/2.11.0 (GitHub; windows amd64; go 1.14.2; git 48b28d97)

**Output of `git lfs env`**
```
git-lfs/2.11.0 (GitHub; windows amd64; go 1.14.2; git 48b28d97)
git version 2.27.0.windows.1

Error: Access is denied.
Endpoint=https://****.git/info/lfs (auth=basic)
LocalWorkingDir=
LocalGitDir=D:\****\.git
LocalGitStorageDir=D:\****\.git
LocalMediaDir=D:\****\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\****\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\****\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
- Other projects can be pushed with no error
- Problem can be reproduce on other machines by copying the local git repo

**Comment by chrisd8088** [comment] 2020-07-04 06:50
Hey, I'm sorry you're having trouble.

Reading through the [relevant code](https://github.com/git-lfs/git-lfs/blob/43a83115f3d5b13e8432ccb9d7ac0d1880ff6d46/git/git.go#L724-L733) it appears that Git LFS is having a problem converting the `.git` directory as returned by `git rev-parse --git-dir --show-toplevel` into an absolute path with all symlinks resolved.  To do this, it calls the Go language [`filepath.Abs()`](https://golang.org/pkg/path/filepath/#Abs) and [filepath.EvalSymLinks()`](https://golang.org/pkg/path/filepath/#EvalSymlinks) routines, in that order.  One of those seems like it must be returning the error you're seeing.

If I had to guess, I might suspect the symlink-resolution code is more likely to be the source of problems, since you say you can reproduce the problem just by copying the Git repository.  And the `Access is denied` problem is coming from Windows itself, obviously, as Go tries to execute one of these two routines.  So I would look closely at the `.git` entry in your repo, and determine where there's an restrictive access control setting on it, one of its ancestors, or a symlink target that it or its ancestors points to.

(You could also try running `git rev-parse --absolute-git-dir --git-dir --git-common-dir --show-toplevel` just to see what Git outputs, and report that back here, if it seems useful.)


FWIW, if you're also having problems with the subsequent `Post "https://.../info/lfs/locks/verify": Bad Gateway` error, and you don't need Git LFS locking, you might want to experiment with disabling it by setting the Git configuration `lfs.<url>.locksverify` to `false`.  But it doesn't sound like that's your main problem at the moment.

**Comment by 4nti-7rust** [comment] 2020-07-09 12:29
Here is the result of command :
```
git rev-parse --git-dir --show-toplevel
.git
C:/VirtPart/Drive.D/devt/****
```

I have the same pattern everywhere. I also noticed that in the corrupted project, there was two folders lfs and hooks at the root of the project (like [here](https://github.com/git-lfs/git-lfs/issues/3898)). But this particular bug should have been fixed in 2.9.2 and I am now in 2.11.0. I am a bit lost... Thanks a lot for you help, do you think I should start another ticket for the folder "bug" ?

**Comment by chrisd8088** [comment] 2020-07-10 21:22
As for the `lfs` and `hooks` folders being in the wrong place, per #3898, you can probably just delete those, or make a fresh clone without them.  They won't be cleaned up just by upgrading Git LFS; you'd have to do that manually.  No need for a separate bug report on that, though.

But as for this bug report, I would focus on whether you've resolved the permissions or symlink issues which were causing Windows to report the `Access is denied` message.  If that's resolved for you, then by all means please close this ticket.

**Comment by chrisd8088** [comment] 2020-07-28 20:17
I'm going to close this as being due to an underlying Windows access issue and not specific to LFS, but please re-open it if that's not the case and have some further details on where there might be a bug in LFS.

**Closed by chrisd8088** 2020-07-28 20:17 UTC
