### ISSUE TITLE
Pushing with Windows built-in OpenSSH hangs

### ISSUE THREAD

**Issue by Sairony** [git-lfs/git-lfs#3779] opened 2019-08-16 12:38 UTC
Ran `git config —global credential.helper wincred` & `git config —global credential.helper cache` as advised for Windows successfully beforehand, did nothing. Here's the output with trace on:

```D:\Projects\Test>git push
14:28:25.029963 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
14:28:25.033034 git.c:439               trace: built-in: git push
14:28:25.035239 run-command.c:663       trace: run_command: unset GIT_PREFIX; ''\''C:\Windows\System32\OpenSSH\ssh.exe'\''' git@192.168.1.7 'git-receive-pack '\''MountainKing'\'''
14:28:26.011025 run-command.c:663       trace: run_command: .git/hooks/pre-push origin git@192.168.1.7:MountainKing
14:28:26.129602 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
14:28:26.133618 git.c:704               trace: exec: git-lfs pre-push origin git@192.168.1.7:MountainKing
14:28:26.133618 run-command.c:663       trace: run_command: git-lfs pre-push origin git@192.168.1.7:MountainKing
14:28:26.166504 trace git-lfs: exec: git 'version'
14:28:26.209536 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
14:28:26.308399 trace git-lfs: exec: git 'config' '-l'
14:28:26.335384 trace git-lfs: pre-push: refs/heads/master 3bd6761de5ed6b8220ed521d3af34fa6a43af61d refs/heads/master 34ab8d3f3c305b20a298b1befc6fd379863d627a
14:28:27.496607 trace git-lfs: run_command: C:\Windows\System32\OpenSSH\ssh.exe -- git@192.168.1.7 git-lfs-authenticate MountainKing upload
```

Everything worked dandy before git-lfs, tried both from git bash & ordinary cmd with the same results. Logging in via ssh from the same console works without any problems.

**Comment by bk2204** [comment] 2019-08-16 14:24
Hey,

When you run `C:\Windows\System32\OpenSSH\ssh.exe -- git@192.168.1.7 git-lfs-authenticate MountainKing upload` by hand, does this command prompt for a password or any type of credentials?

**Comment by Sairony** [comment] 2019-08-19 12:12
If I run it by hand I get command not found. Investigating some more it seems ssh isn't really supported out of the box ( #1044 )? On the other hand [this](https://github.com/ksurent/git-lfs-authenticate) also shows up, if that project works though it's kind of confusing why it's not already a part of git-lfs since it's a rather old project. It's all rather confusing.

**Comment by bk2204** [comment] 2019-08-19 14:04
It's completely possible to use SSH remotes with Git LFS. The authentication happens over SSH and the actual data exchange happens over HTTPS. #1044 is tracking the protocol where the data exchange also goes over the same SSH connection.

My question was intended to see if your problem is #1843. Are you trying to run that command from Git Bash or CMD? If you're running it from Git Bash, you probably need to write the path in the Unix style used by Git Bash. Does that path really exist? Are you using an environment variable or a config setting to set the SSH command, and if so, which one?

**Comment by Sairony** [comment] 2019-08-19 14:40
I'm setting `GIT_SSH` to use the OpenSSH that ships with Windows 10. I've tried over both the git bash which comes with git for windows, and CMD ( as well as powershell ). If I run `git-lfs-authenticate` on the server I also get command not found, I assume my problem is that I need to setup this command on the server with for example this [project](https://github.com/ksurent/git-lfs-authenticate)? However I haven't seen that project mentioned anywhere else, and it almost seems as if some version of `git-lfs-authenticate` should be present? The server is running a vanilla Ubuntu 18.04.3 install which is up to date.

**Comment by memphis88** [comment] 2019-09-10 11:01
I'm also affected by this. Running the command manually yields what looks like a response with an access token. The interesting bit though is that via tracing I see the command being `sh -c C:/WINDOWS/System32/OpenSSH/ssh.exe -- git@github.com 'git-lfs-authenticate
 org/repo.git upload'` and when I run this manually, I'm getting this response
>usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-J [user@]host[:port]] [-L address] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port] [-Q query_option] [-R address]
           [-S ctl_path] [-W host:port] [-w local_tun[:remote_tun]]
           destination [command]

My guess is that this has to do with using the UNIX commands in powershell, ironically this used to work though.

**Comment by bk2204** [comment] 2019-09-10 14:51
If you're using the environment variable `GIT_SSH` and not `GIT_SSH_COMMAND` or `core.sshCommand`, then the argument will not be passed to the shell.  If you're invoking the command at the command line, you need to escape the command line so that the argument to `sh -c` is entirely one single argument, like so:

```sh
$ sh -c 'C:/WINDOWS/System32/OpenSSH/ssh.exe -- git@github.com '\''git-lfs-authenticate org/repo.git upload'\''
```

I am able to reproduce the hang with OpenSSH from Windows 10, but I'm also able to reproduce it when doing the following, which indicates that it's a problem with the Windows 10 OpenSSH:

```sh
$ C:/WINDOWS/System32/OpenSSH/ssh.exe -- git@github.com 'git-lfs-authenticate org/repo.git upload' </dev/null 2>/dev/null | cat
```

This operation shouldn't fail; redirecting stdin from `/dev/null` is a legitimate thing to do, and in fact it's what we do here.  This should be reported to them; when it's been fixed, things should work automatically (provided you don't require a passphrase for your key).

**Comment by rs22** [comment] 2019-09-30 18:06
As a workaround to the `/dev/null` issue, I've pointed `core.sshCommand` to this wrapper script:
```bash
#! /bin/bash

stdin_is_dev_null(){ perl -e 'exit((stat STDIN)[6]!=(stat "/dev/null")[6])'; }

if stdin_is_dev_null ; then
    echo "" | C:/Windows/System32/OpenSSH/ssh.exe "$@"
else
    C:/Windows/System32/OpenSSH/ssh.exe "$@"
fi
```

With this, I can now push and pull git lfs objects using the credentials provided by the Windows OpenSSH agent.

**Comment by bk2204** [comment] 2019-09-30 19:39
I've reported this issue to PowerShell/Win32-OpenSSH#1470, so hopefully this will get fixed sooner or later.

**Comment by GingerLoaf** [comment] 2019-12-01 09:32
> As a workaround to the `/dev/null` issue, I've pointed `core.sshCommand` to this wrapper script:
> 
> ```shell
> #! /bin/bash
> 
> stdin_is_dev_null(){ perl -e 'exit((stat STDIN)[6]!=(stat "/dev/null")[6])'; }
> 
> if stdin_is_dev_null ; then
>     echo "" | C:/Windows/System32/OpenSSH/ssh.exe "$@"
> else
>     C:/Windows/System32/OpenSSH/ssh.exe "$@"
> fi
> ```
> 
> With this, I can now push and pull git lfs objects using the credentials provided by the Windows OpenSSH agent.

I would like to say that, after a large amount of frustration, I gave this a try. It works!!! For the time in-between either a git patch or windows ssh patch, this is the best answer I found if you would like to continue using the windows ssh solution

**Comment by roelkok** [comment] 2020-06-09 09:18
Even though the problem may lie with Microsofts implementation of OpenSSH, would it be possible to detect this issue on the git-lfs side and throw an error (with a link to the MS issue) instead of hanging? Right now I'm also using the solution by @rs22 but it took me a very long time to identify the problem in the first place.

**Comment by bk2204** [comment] 2020-06-09 17:55
I don't think we have a way to detect this issue, unfortunately.  We're limited by the fact that the SSH command need not be OpenSSH at all; it could be Putty or a custom script, and so we can't query it for information.  The hang happens in Microsoft's OpenSSH implementation itself, not in Git LFS, so we can't detect this until it's already happened and we're waiting for a response.

**Comment by robmessick** [comment] 2020-07-12 03:58
Looks like this issue is resolved in newer versions of openssh-portable (`openssh v8.0.0.1` installed by chocolatey).

**Comment by GrantMoyer** [comment] 2020-11-10 21:54
Until windows OpenSSH is fixed, you can work around this with:

    git config --global core.sshCommand 'cat - | C:/Windows/System32/OpenSSH/ssh.exe'

or by setting the GIT_SSH_COMMAND environment variable to `cat - | C:/Windows/System32/OpenSSH/ssh.exe`.

In either casem GIT_SSH should be unset. And GIT_SSH_COMMAND shouls be unset if you use the git config.

**Comment by jcowles** [comment] 2021-05-03 22:20
`choco install openssh` also fixed me up

**Comment by jmlee2k** [comment] 2021-05-05 14:22
> git config --global core.sshCommand 'cat - | C:/Windows/System32/OpenSSH/ssh.exe'

This workaround indeed fixes the issue, but it also causes git to hang on some (or perhaps all) SSH errors.  

For example, here's what happens when running `git fetch` if the remote host x.y.z can't be resolved.

With the workaround (process hangs forever):
```
ssh: Could not resolve hostname x.y.z: No such host is known.
```

Without the workaround (process returns as expected)
```
ssh: Could not resolve hostname x.y.z: No such host is known.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by jmlee2k** [comment] 2021-05-05 17:50
OpenSSH 8.1p1 is included in windows update KB5001391, and it appears to work properly without a workaround.

**Comment by bk2204** [comment] 2021-05-05 18:07
That's great to hear.  I'll try to upgrade my VM and verify this, and assuming it works, I'll close this issue.

**Comment by tblong** [comment] 2021-05-06 20:09
The note from @jmlee2k to install the preview KB5001391 patch fixed the lfs hang for us with none of the git workarounds in this thread.  This was the setup prior to installing KB5001391:
```
Windows 10 20H2 (OS Build 19042.928)
git version 2.31.1.windows.1
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```

Post update, OpenSSH is now at:
```
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
```

**Comment by bk2204** [comment] 2021-05-06 21:23
Great.  I haven't had time to verify this myself, but if multiple people are reporting success, then I think it's probably fixed, so I'm going to close this.

**Closed by bk2204** 2021-05-06 21:23 UTC
Labels: windows

**Comment by rs22** [comment] 2021-07-30 17:05
- [ ] W ärwx pa. Oftdyw h fwf veqxfh in gut g
