### ISSUE TITLE
git-lfs track very slow on Windows

### ISSUE THREAD

**Issue by nfgferreira** [git-lfs/git-lfs#5421] opened 2023-07-12 16:10 UTC
**Describe the bug**

In Windows, `git lfs track` takes 20+ seconds to execute. I have experienced this issue for some time now. Some few months ago everything was good and I do not know what happened for the problem to show up (I use a corporate computer I do not have full control of). I guess the issue depends on my machine configuration and most likely not everybody can reproduce it.

This delay is very annoying because the HMI I use (Sourcetree) runs the command any time I stage a file.

See https://github.com/git-lfs/git-lfs/discussions/5254

Using export GIT_TRACE=1, I get:

```
$ git lfs track
11:35:51.001836 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
11:35:51.001836 git.c:725               trace: exec: git-lfs track
11:35:51.001836 run-command.c:655       trace: run_command: git-lfs track
11:35:51.032212 trace git-lfs: exec: git 'version'
11:35:51.144849 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
11:35:51.220515 trace git-lfs: exec: uname
11:35:51.300364 trace git-lfs: exec: git 'config' '--includes' '--local' 'lfs.repositoryformatversion'
11:35:51.375237 trace git-lfs: exec: git 'config' '--includes' '-l'
11:35:51.440847 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
11:35:51.515246 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' ':.lfsconfig'
11:35:51.581437 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' 'HEAD:.lfsconfig'
11:35:51.647150 trace git-lfs: Install hook: pre-push, force=false, path=C:\my_repo\.git\hooks\pre-push, upgrading...
11:35:51.657459 trace git-lfs: Install hook: post-checkout, force=false, path=C:\my_repo\.git\hooks\post-checkout, upgrading...
11:35:51.666852 trace git-lfs: Install hook: post-commit, force=false, path=C:\my_repo\.git\hooks\post-commit, upgrading...
11:35:51.675851 trace git-lfs: Install hook: post-merge, force=false, path=C:\my_repo\.git\hooks\post-merge, upgrading...
11:36:14.267778 trace git-lfs: NewLsFiles: running in C:\my_repo git ls-files -z --cached --sparse --exclude-standard --others
11:36:14.267778 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'ls-files' '-z' '--cached' '--sparse' '--exclude-standard' '--others'
11:36:14.343443 trace git-lfs: findAttributeFiles: located .gitattributes
Listing tracked patterns

... there follows a correct list of patterns ...

Listing excluded patterns
11:36:14.353523 trace git-lfs: filepathfilter: creating pattern ".git" of type gitignore
11:36:14.353523 trace git-lfs: filepathfilter: creating pattern "**/.git" of type gitignore
11:36:14.353523 trace git-lfs: filepathfilter: accepting "tmp"
11:36:14.582394 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
11:36:14.590787 git.c:439               trace: built-in: git config --bool core.sparseCheckout
```

As you see, there is a 23 sec interval between the pos-merge hook installation and the NewLsFiles trace.

**To Reproduce**

Simply type `git lfs track` when inside a repository.

**Expected behavior**

The command should finish nearly immediately.

**System environment**

Windows 10.0.19045 Build 19045
git version 2.40.0.windows.1
git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)

**Output of `git lfs env`**

```
$ git lfs env
git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)
git version 2.40.0.windows.1

Endpoint=https://xxx.com/git/yyy/lfs (auth=basic)
LocalWorkingDir=C:\my_repo
LocalGitDir=C:\my_repo\.git
LocalGitStorageDir=C:\my_repo\.git
LocalMediaDir=C:\my_repo\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\my_repo\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\my_repo\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_TRACE=0
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

```

**Comment by bk2204** [comment] 2023-07-13 18:31
Hey,

Thanks for the report.  I'm unable to reproduce this on my Windows 10 test VM.  It looks like simply reading a few files here is very expensive, and it shouldn't be.

Can you mention if you're using an antivirus or firewall other than the Windows default (Windows Defender and Windows Firewall), or any sort of monitoring software?  In addition, can you try these commands in the Windows Subsystem for Linux and see if the same performance problem happens there (you can download up-to-date binaries from the release page if your distro doesn't have them)?

**Comment by nfgferreira** [comment] 2023-07-16 14:44
Thanks for the response. I am not using anything other than Windows Security from the OS. Installing WSL (Ubuntu), I do not have the issue.
The fit-lfs version I have in WSL/Ubuntu is:
git-lfs/3.0.2 (GitHub; linux amd64; go 1.18.1).

**Comment by bk2204** [comment] 2023-07-17 14:46
Hey,

About how many patterns do you have in `.gitattributes` and related files?  Does running `GIT_TRACE=1 PREFIX=C:/Program Files/Git/mingw64 git lfs track` in Git Bash show any performance difference?  Does this trigger with the latest version of Git for Windows, which is some version of 2.41?  Are you using a network drive, a repository using a cloud-syncing service, or any other sort of non-local drive?

I'm trying to see if we can figure out what the relevant difference is between your environment and mine.

**Comment by nfgferreira** [comment] 2023-07-18 17:26
I tested this issue a little longer and found that the delay is due to the call `u, err := user.Current()` in `currentUser func() (*user.User, error)` in `filetools.go`. I did not investigate the user package implementation, though.

I simply removed the call, any reference to err, and defined `u` so it can be used to be returned by the function. After that, the command takes much shorter to execute.

I do not understand why the software calls `user.Current()` if the only thing it needs is `HomeDir`, which is calculated by `os.Getenv("HOME")` anyway (and that is fast on my PC).

During my tests I also found:
1. If I run the original software twice in a short interval, the second call is faster.
2. The problem happens even in a just initialized repository.
3. The time it takes for the command to execute is also much shorter (about 4 secs rather than 20+ secs) if the PC is in airplane mode, indicating that the delay has to do at least partially with some communication somewhere.

**Comment by bk2204** [comment] 2023-07-20 13:43
Ah, thanks, that's very useful to know.  The likely problem is that you're on a corporate machine with an extremely slow LDAP or Active Directory server, which is why this operation results in a big delay.  My Windows VM is standalone, so that explains the difference between our two systems.

I think we can try to improve this by removing the need to call `user.Current`, but it's not likely that it will be in place in time for v3.4.0, which will happen next week.  I'll try to get it in shortly thereafter, though.

**Comment by nfgferreira** [comment] 2023-07-20 13:52
I can create a PR, hopefully today.

**Comment by bk2204** [comment] 2023-07-20 14:03
Fantastic, that would be very welcome.

**Closed** 2023-07-20 17:24 UTC
