### ISSUE TITLE
git-lfs crashes

### ISSUE THREAD

**Issue by neslekkim** [git-lfs/git-lfs#1872] opened 2017-01-17 12:08 UTC
(related to previous issue)

Trying to setup everything clean on another machine to clone/pull our repository, and I'm getting this:

```
Updating ca1746d0..77b35829
fatal: Doc/NPK - Beregningsregler 20161116.pdf: smudge filter lfs failed
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x7a6c60, 0xc04200c0a0)
        C:/Go/src/runtime/panic.go:500 +0x1af
github.com/git-lfs/git-lfs/git.(*FilterProcessScanner).readRequest(0xc04206d220, 0xc0420768f0, 0x0, 0xc0420c19e0)
        C:/Go/src/github.com/git-lfs/git-lfs/git/filter_process_scanner.go:181 +0x22b
github.com/git-lfs/git-lfs/git.(*FilterProcessScanner).Scan(0xc04206d220, 0x807d76)
        C:/Go/src/github.com/git-lfs/git-lfs/git/filter_process_scanner.go:143 +0x57
github.com/git-lfs/git-lfs/commands.filterCommand(0xc042103040, 0x9ff368, 0x0, 0x0)
        C:/Go/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:76 +0x200
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0xc042103040, 0x9ff368, 0x0, 0x0, 0xc042103040, 0x9ff368)
        C:/Go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0x177
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0421021a0, 0xc0420c1eb0, 0x1)
        C:/Go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x364
github.com/git-lfs/git-lfs/commands.Run()
        C:/Go/src/github.com/git-lfs/git-lfs/commands/run.go:66 +0x19d
main.main()
        C:/Go/src/github.com/git-lfs/git-lfs/git-lfs.go:33 +0x118
```

Still, this is an windows based machine, we also use norwegian characters i filenames+paths, which obviously should not be ap rpbolem.
(git-lfs 1.5.3, git 2.11.0.windows.1)

**Comment by neslekkim** [comment] 2017-01-17 13:08
We have multiple repositories on bitbucket, have tested two others, and no problem at all on those, with lfs files checked in.

But our main repo is having these problems, have tried git-lfs 1.5.3, 1.5.4 and 1.5.5, on the two last revisions of git-lfs it hangs.

But, we didn't enable LFS in bitbucket until late, on folders that we have already checked in stuff, can that give problems?
On one repository I have this in .gitattributes:
*.pdb filter=lfs diff=lfs merge=lfs -text
*.dll filter=lfs diff=lfs merge=lfs -text

And on another one we have this settings:
Libraries/**/* filter=lfs diff=lfs merge=lfs -text

In the one that we have problems with, we have same type config as the last one, but we have lots of files already under versioncontrol on that path, but we thought that should not be a problem, since it's documented that only new files after turning git-lfs would be lfs handled.

**Comment by technoweenie** [comment] 2017-01-17 17:36
Hey @neslekkim, looks like the crash is coming from https://github.com/git-lfs/git-lfs/blob/f09e5d41ee2a1be5980efeae4ab829482a60739b/git/filter_process_scanner.go#L179-L182. 

Can you try rerunning the command with `GIT_TRACE_PACKET=1` so we can see exactly what Git is sending to Git LFS?

**Comment by neslekkim** [comment] 2017-01-17 19:54
where do I put that flag?, I asked in another issue about this also, but not sure where to put what.

But why does it work on two repositories, but not this one?, and I started clone to an clean folder to make sure there was no local rubbish.

**Comment by technoweenie** [comment] 2017-01-17 21:08
Put it in front of the command that triggered the output of the original issue. For example:

    $ GIT_TRACE_PACKET=1 git pull ...

> But why does it work on two repositories, but not this one?, and I started clone to an clean folder to make sure there was no local rubbish.

It looks like either Git is sending a bad packet to LFS, or LFS is [parsing it incorrectly](https://github.com/git-lfs/git-lfs/blob/f09e5d41ee2a1be5980efeae4ab829482a60739b/git/filter_process_scanner.go#L179-L182). Having a full packet trace will let us determine the cause.

If the packet trace is too sensitive for an OSS issue, you can send it to https://github.com/contact, where it will be routed to me.

**Comment by ttaylorr** [comment] 2017-01-18 17:40
I agree with @technoweenie's analysis. What could also be happening is that Git is sending us a malformed packet earlier up the line (or there is a bug parsing some packets), which causes our index to be in the wrong place when we try and read these packet headers.

Seeing what packets are actually sent (with the `GIT_TRACE_PACKET=1` flag) will be helpful in continuing to debug this 👍 .

**Comment by neslekkim** [comment] 2017-01-18 18:35
will try to see if we can reproduce again, we lost one full day of work due to this, so we finally managed to turn off lfs and delete the lfs files, and add them directly.. 
But our repsitory is eaten by these files, so we need to do something soon.. but the problem was that other test repostitories did not have the problem..
Looks like Bitbucket does not support copying of lfs based repositories, so I'll have to figure out a way.

**Comment by ttaylorr** [comment] 2018-04-10 03:15
Hi @neslekkim, I am going to close this issue as well since it has been a long time without any activity. In the last year, I have fixed a number of process filter bugs and and expect that this is no longer an issue. If that's not the case, please do not hesitate to let me know, and I'd be happy to figure out what's going on.

**Closed by ttaylorr** 2018-04-10 03:15 UTC
