### ISSUE TITLE
git lfs sets ignored files to read-only when file type is marked as lockable

### ISSUE THREAD

**Issue by Kitzibua** [git-lfs/git-lfs#3390] opened 2018-11-23 12:25 UTC
### Setup:
```
git version
git version 2.19.2.windows.1

git lfs version
git-lfs/2.6.0 (GitHub; windows amd64; go 1.11.1; git 93702d75)
```

- Git LFS is used for locking some binary files with the extention _.vw7_, so `.gitattributes` is set to `*.vw7 lockable`
- The project contains several .vw7 files which we lock when we need to change them and unlock after push
- In the project folder there is a folder named __output_ which is generated in the build process, it also contains _.vw7_ files
- This folder is ignored in git, `.gitignore` contains `_output`

### Problem:
For example when I run a `git checkout` of any file in the repository, all the _.vw7_ files in the __output_ folder are marked as read-only.
This causes any following build process to fail, as the build can't modify the _.vw7_ files in the __output_ folder. The files have to be manually set to writable to make it work again.

### Expected behaviour:
Files marked as lockable that are in an ignored folder should not be set to read-only

**Comment by bk2204** [comment] 2018-11-26 15:06
Hey, thanks for reporting this issue.

I can confirm that this code path seems to affect all files and directories, including ignored ones.  I hope to have a little bit of time over the next few days to look into this and see about fixing it.

**Comment by Kitzibua** [comment] 2018-11-27 07:14
By the way, I did play around a little and the action I came accross triggering this is reverting uncommitted file changes using TortoiseGit. In the background this probably executes a `git checkout some.file`.
Interestingly a `git checkout somebranch` doesn't change any access-modifiers. Is this behaviour intended?

**Comment by bk2204** [comment] 2018-11-27 15:06
> Interestingly a `git checkout somebranch` doesn't change any access-modifiers. Is this behaviour intended?

Yes, this behavior is intended.  It's an optimization to make checkouts significantly faster: we only modify files that have changed between branches.

**Comment by bk2204** [comment] 2018-11-29 17:30
Looking at this a little more, it looks like the current behavior is intentional. Commit a727fea2a introduced this behavior with the goal of making `git lfs lock` and `git lfs unlock` work properly for files that are no longer in the repository.  This behavior was requested in #3183 and implemented in #3190.

So since this behavior is intentional, I'm going to leave the code as it is, and close this issue.

**Comment by Kitzibua** [comment] 2018-11-30 08:49
Thanks for digging into this.
I understand the intention of #3190. However, the side effect of setting every file in the working directory that maches the lockable-pattern to read-only, even if the file is not in the git repository, makes it practically impossible for us to use Git LFS. And I can imagine that there are more examples where a build process creates or modifies binary files of the same type as the files in the repository one wishes to lock, where this creates problems.

For now we will downgrade to V2.5.2, but this is not a permanent solution. Maybe there could be an option of switching this new behaviour off or any other way of excluding certain files or folders from the permission handling.

**Comment by bk2204** [comment] 2018-11-30 14:45
What may also work for you is specifying `somedir/*.vw7 -lockable` if you want the files in `somedir` to not be lockable.  I don't know how achievable that would be in your scenario.

I'll reopen this to register that you'd like an option for this.

**Closed** 2019-01-25 15:46 UTC

**Comment by DheerajSingh1107** [comment] 2021-05-28 10:58
I am using git with segger when I tried to edit code from segger it seem all files are read only how I want to edit them with so text editor externally
