### ISSUE TITLE
'bufio.Scanner: token too long' when running 'git-lfs migrate import'

### ISSUE THREAD

**Issue by woopla** [git-lfs/git-lfs#4005] opened 2020-01-28 21:12 UTC
**Describe the bug**
As part of a CVS-to-Git migration of a CVS repo with 25 years and close to 300k commits, I'm trying to move some binary files (think PDF and Word) into LFS using `git lfs migrate import`.
The _Sorting commits_ stage works fine, it's during _Rewriting commits_ that the failure occurs. Here's the unhelpful transcript:
```bash
> git lfs migrate import --include-ref=refs/heads/master --exclude=path/to/dir --include '*.docx'
migrate: Sorting commits: ..., done.
bufio.Scanner: token too long
```

I've tried with `GIT_TRACE=1` and I'm not getting helpful information (a bunch of `filepathfilter: rejecting` messages, but nothing related to the failure). I actually have a longer list of file extensions to import besides `*.docx`, I tried a couple of other extensions in isolation with the same result. I also tried running it with `delve`, but there's no stack to be found after the process exits (I did rebuild git-lfs from source)...

**System environment**
OS is CentOS 7.2

**Output of `git lfs env`**
```bash
git-lfs/2.10.0 (GitHub; linux amd64; go 1.13.7)
git version 2.20.1

Endpoint=file:///path/to/repo-origin/.git (auth=none)
LocalWorkingDir=/path/to/repo
LocalGitDir=/path/to/repo/.git
LocalGitStorageDir=/path/to/repo/.git
LocalMediaDir=/path/to/repo/.git/lfs/objects
LocalReferenceDirs=
TempDir=/path/to/repo/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/path/to/repo/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment] 2020-01-28 21:38
Hey,

Thanks for writing in.  We haven't seen this before, and looking at the code path I believe it's taking, it looks like this should be handling just object IDs, so we shouldn't get an overly long line.

Since you're already compiling the code, would you be willing to instrument the `git.RevListScanner.scan` function (which I believe is the source of this) and find out what it's choking on?  You can dump each line it produces successfully, and then when it returns an error, you'll be able to run the same rev-list command (which will be in the `GIT_TRACE=1` output) and find out what line it's choking on.  The buffer size is supposed to be 64 KiB, so we shouldn't be exhausting it.

**Comment by woopla** [comment] 2020-01-29 01:53
Hey @bk2204 it's not coming from there, it's from later in the code. It looks like some of the OIDs in `Rewriter.Rewriter()` are not correct. I'm going through the code from that function (and potentially `commitsToMigrate()`, I'll let you know when I get stuck or find the root cause.

**Comment by woopla** [comment] 2020-01-30 18:16
The issue is coming from a bogus CVS commit, in which the intended commit message was repeated a gazillion times, causing a 927,003 characters long commit message :fearful: That CVS commit message was translated fine into Git.

The root of the limitation in the Go code is not in `git-lfs`, but in `gitobj` - the `Commit.Decode()` func, specifically.

I'm going to fix that commit message on our end, not sure `gitobj` should deal with this corner case. What do you think?

**Comment by bk2204** [comment] 2020-01-30 19:52
How interesting.  I think it's reasonable to expect gitobj to deal with commit messages up to 1 MiB in size, so I'll open a PR to get that fixed.  I think that would be a reasonable upper limit to a human-readable commit message.

Thanks for troubleshooting this and tracking down where the problem is.

**Closed** 2020-02-03 16:59 UTC

**Comment by hiroponz** [comment] 2020-07-08 15:15
This issue has not been fixed in latest version (git-lfs 2.11.0).

When will you release a version with a fix for this issue?

**Comment by bk2204** [comment] 2020-07-08 15:36
We're planning to do a release sometime in July which will include a new version of gitobj.

**Comment by ptarjan** [comment] 2020-07-30 18:26
Bump on this issue as I ran into the same error message in a completely unrelated (nothing to do with CVS) context on 2.11.0
