### ISSUE TITLE
Failure to canonicalize path using ASCII apostrophe on Windows

### ISSUE THREAD

**Issue by awe21001** [git-lfs/git-lfs#4829] opened 2022-01-20 15:50 UTC
**Describe the bug**
git lfs install won't work. I have desktop successfully installed. I have git successfully installed. I have LFS successfully installed. I have a brand new repository and successfully cloned it to the desktop. I go to command prompt and type in git lfs install, and insteaad of working I get: " Error: The system cannot find the path specified.
fatal: could not canonicalize current working directory: The system cannot find the path specified."

**To Reproduce**
1. Literally don't know why this is happening. I uninstalled and reinstalled git desktop and LFS three times now. I have tried it on my main drive (which is pretty full), I have tried it on my added drive (which has 1T available). I put both on the same drive, I've tried just installing LFS to my original C drive..........

**Expected behavior**
I should simply type git lfs install and it says initiated, so I can continue with the rest of the simple LFS instructions. 

**System environment**
Windsx64. Perfect internet connection. Solid beefy computer that is a few years old.

**Additional context**
For shits and giggles I opened Git and typed git lfs install - and it said initiated, but I can't do anything else and it still fails in desktop.

**Comment by bk2204** [comment] 2022-01-20 20:41
Hey,

Sorry to hear you're having trouble.  This sounds like an issue which we might have fixed in a previous release, or possibly a Windows shortcoming.  Can you provide the version from `git lfs --version` and the name of the directory in which you're running the command?  Also, which version of Windows are you running (10, 11, or something older)?

Is the directory any special type of directory, like one managed by a cloud syncing service or a network drive?  Does it work if you use a directory other than one on the desktop, like one in your home directory (e.g., under `C:\Users`)?  The reason I ask is that in some cases Windows restricts access to directories on the desktop or in special locations such that programs have to have special permissions, and it will just totally break any other programs that try to run in those directories.

Hopefully we can figure out what's going on here and get you on your way.

**Comment by awe21001** [comment] 2022-01-20 21:30
Hello,

Thank you for getting back to me so quickly!
* Git lfs v3.0.2 is what I’m downloading
* I would open up GitHub desktop, go to repository settings and open
command prompt from there, then type in my commands.
* If it helps, the command prompt opens with: “H:\Alden’s\Alden_Repository>
(Which is the drive, my folder, and then the repository folder)
* Windows version: 10 pro

I’m not real familiar with all of this, I’m new to GitHub. The directory is
not special, not cloud or network drive, just on my computer on the same
hard-drive. Not seeing any change using home directory.

I uninstalled and reinstalled desktop and lfs, but didn’t touch git, should
I try reinstalling git as well?

**Comment by bk2204** [comment] 2022-01-20 21:59
Hey,

I don't think reinstalling things is going to help here.  Let's see if we can do some more troubleshooting to figure out what the problem is.  It's good that you have the latest release, since we should have fixed all the known issues so far.

I noticed your directory contains a Unicode apostrophe.  I know of no reason why that shouldn't work, but could you try creating a repository in a directory that doesn't have any special characters like that?  It could be that for some reason that's not working and we have a bug there.

Can you also, in both your existing repository and in the new one you create, run `git rev-parse --show-toplevel --absolute-git-dir` and provide the output here?  That will help us see what Git thinks the proper behavior is here, which will help me track down the right behavior.

**Comment by awe21001** [comment] 2022-01-21 05:51
Holy crap it was the Unicode apostrophe from the folder on my drive I had selected to store the cloned repository...

Made a new repository called TestRep with the same settings (private, add a README file, add .gitignore set to Unity).
Cloned to desktop. I tried two ways and discovered you were right. 
Attempt 1: I put it in my "Alden's" folder and had the same errors as before. When I typed in the command you provided I got what you see below:
H:\Alden's\TestRep>git rev-parse --show-toplevel --absolute-git-dir
H:/Alden's/TestRep
H:/Alden's/TestRep/.git

ATTEMPT 2: I cloned my repository not to "Alden's" but directly to my H: drive instead. I ran "git lfs install" and it worked! This confirms my naming convention (which admittingly was an odd folder name I had used to distinguish between Users on my desktop) was the culprit.

Thank you for the suggestion, I will keep this in mind for my classmates in case they run into a similar issue!

**Comment by bk2204** [comment] 2022-01-21 13:38
I'm glad we figured out what the problem is.  Thanks for helping us troubleshoot.

We should be able to handle a Unicode apostrophe just fine, so I'll try to get this fixed, since we want people to be able to use arbitrary Unicode in filenames.  After all, people speak many different languages.

**Comment by bk2204** [comment] 2022-03-03 21:02
Hey,

I'm looking into this, and I'm not able to reproduce the problem.  A clone and pull with the latest version work for me.  Is it possible that you're using some sort of cloud syncing service (e.g., Dropbox or OneDrive) on the folder with the problem?  That's a common situation that we might see the error you're seeing in.

**Comment by Iurii132** [comment] 2022-04-20 10:11
I am having this fatal error when trying to set up Git on a Virtual Desktop Infrastructure (VDI) machine, with probably only a network drive available, Are there plans to provided such support in near future?

C:\Git\ABC>git checkout master
Error: The system cannot find the path specified.
fatal: could not canonicalize current working directory: The system cannot find the path specified.
fatal: the remote end hung up unexpectedly

C:\Git\ABC>git rev-parse --show-toplevel --absolute-git-dir
C:/SnapVolumesTemp/MountPoints/{8e399ec3-0000-0000-0000-100000000000}/SVROOT/Git/ABC
C:/SnapVolumesTemp/MountPoints/{8e399ec3-0000-0000-0000-100000000000}/SVROOT/Git/ABC/.git

**Comment by bk2204** [comment] 2022-04-20 12:43
Hey,

Basically, we need something for which `GetFinalPathNameByHandle` will work.  It's possible that it does work for that drive and we just have a bug in our code, in which case, we'll happily accept a patch.  If it doesn't work, then we won't be able to support that drive.  Unfortunately, we don't have such a configuration, so we'd need to rely on other folks to submit a patch which works on their machine.

**Comment by KiranPranay** [comment] 2022-07-11 06:25
# I got the error and resolved .

Definitely, it was the Unicode apostrophe.

## When Project Path = "D:\ROM's\hemlo"

we get the following error,

```bash
Error: The system cannot find the path specified.
Could not canonicalize current working directory: The system cannot find the path specified.
```

## When Project Path = "D:\test"

```python
Git LFS initialized.
```
Changing/Renaming path would help here .

## git lfs version
```
git-lfs/3.1.4 (GitHub; windows amd64; go 1.17.8)
```
## git --version
```
git version 2.36.0.windows.1
```

**Comment by bk2204** [comment] 2022-07-11 13:20
Hey,

I attempted to reproduce this problem and was not able to do so on my Windows 10 VM.  Can you provide a script for Bash that creates an affected repository?  Also, what file system is on your D drive, and what OS created it?

**Comment by KiranPranay** [comment] 2022-07-11 17:51
> Hey,
> 
> I attempted to reproduce this problem and was not able to do so on my Windows 10 VM. Can you provide a script for Bash that creates an affected repository? Also, what file system is on your D drive, and what OS created it?

- OS : `Windows 11`
- File System : `NTFS`

## Bash Script

```bash
#!/bin/bash
mkdir repo's
cd repo's
git init
git lfs install
```

## Result
```
Error: The system cannot find the file specified.
Could not canonicalize current working directory: The system cannot find the file specified. 
```

**Comment by bk2204** [comment] 2022-07-11 18:31
Hey,

I don't think that script works like you think it does.  You have an ASCII apostrophe in that script, not a Unicode apostrophe, and so what you end up creating is a directory called `repos\ncd repos` (where `\n` is a newline).  That does indeed work for me in Git Bash, but it may or may not in PowerShell.  The reason I ask for a script here is that if I replace the ASCII quotation mark with a U+2019, I don't see a problem running the script.

Of course, I don't have any external drives here, since this is a VM: I only have the C drive.  Does this happen for you on C, or only on other drives?

**Closed** 2022-09-08 16:02 UTC
Labels: bug, windows
