### ISSUE TITLE
Why Git LFS add is so slow?

### ISSUE THREAD

**Issue by Tiny-Snow** [git-lfs/git-lfs#5074] opened 2022-07-10 11:26 UTC
**Describe the issue**

I am trying to add some very small **binary** model files to my repository. Each file size does not exceed 20MB, and it only takes 10s to upload 50 files using git.

However, `git add` becomes very slow after using git LFS. For a 800KB file, `git add` takes 5 minutes to complete, and for a 7MB file `git add` never completes.

There are no problems with the network, and `git push` with LFS is just as fast.

**System environment**

I used the latest LFS 3.2.0, tried both git Bush and Github Desktop. 

```
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
```

**Output of `git lfs env`**

```
git-lfs/3.2.0 (GitHub; windows amd64; go 1.18.2)
git version 2.37.0.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by Tiny-Snow** [comment] 2022-07-11 14:40
> Hey,
> 
> This definitely sounds like it's some sort of monitoring software. Git LFS is written in Go, and Go programs tend to have an unusual structure which such software often flags. Do you see the same performance problems if you try it under WSL?

I'm sorry, but WSL doesn't work on this computer.

Confusingly, I just transferred a 7MB file using Git LFS, `git add` is almost instantaneous.  But then I transmit 10 × 7MB files, there are 10 parallel LFS threads, one of them is transferring the first file, but the thread seems to be stuck ...

I haven't read the Git LFS source code yet, but if Git LFS is transferred over the network in `git add`, there may be network considerations (VPN is used, and git works).

What's more interesting is,  after uninstalling LFS from my computer, I can still use git LFS commad, which is quite confusing to me...

**Comment by bk2204** [comment] 2022-07-11 15:40
Hey,

Git LFS doesn't do anything over the network in `git add`.  That's a purely local operation and nothing is transferred until you run `git push` or `git lfs push`.  The only reason you'd see any sort of network activity is if you're using a network drive (which could certainly explain the poor performance).  Is that the case?

I can definitely say that we don't see this kind of performance on our systems, even in my extremely underpowered Windows test VM.  We have seen various situations where various kinds of antivirus or monitoring software cause problems with Go's goroutines, and if you're seeing deadlocks and slow performance, that's very likely, especially on Windows.  That's the reason I asked you to try WSL, since usually that software doesn't affect WSL and things tend to work.

Can you reproduce this on a fresh Windows install, another computer that does have WSL, or a Linux VM?

**Comment by bk2204** [comment] 2023-04-25 19:42
Hey, since there's been no response to the request to reproduce this elsewhere, I'm going to close this issue.  If you can provide the information requested, we can reopen.

**Closed by bk2204** 2023-04-25 19:42 UTC
Labels: waiting

**Comment by manuelstein** [comment] 2024-10-10 16:14
I'm running into the same problem. Running on a Ubuntu VM, `git add` is crazy slow
