### ISSUE TITLE
git lfs instructions without github leads to misconfigured repos

### ISSUE THREAD

**Issue by perumaal** [git-lfs/git-lfs#4137] opened 2020-05-16 11:52 UTC
Copying from https://github.com/git-lfs/git-lfs/issues/2416#issuecomment-629336101
Hi,
I searched for git lfs, followed the doc (on a safe machine that is backed up - but with tons of PSDs/PNGs). https://git-lfs.github.com/ ->

Here is the "That's it'" Step 3:

"There is no step three. Just commit and push to GitHub as you normally would."

There was no documentation or warning that you need github server to run this.
There were no step 4 to say 'oh btw, if you messed this up, here is how to rewind'.

What follows is one obscure issue after another where people are complaining about disable/uninstall git lfs.

In general, good software must come with:

 * proper doc/support to rewind back stuff it does
 * consistent usage of 'install' and 'uninstall' that mirror such usage
 * and not be deceptive: It says open source and blah. But it does not provide a non-github server.  * does not have any pointer on how to remove nonsensensical 1KB stuff left over.
 * and have good spec'ed protocol. An obscure .git hook that secretely hooks up to some saintly side-loaded software is antithesis to everything about git: This is not software. it's a bunch of wires held by duct tape. [Note that I realized that this was happening on a remote git pull'ed device not on a local client]
Please put a huge warning in the doc saying 'this is not for production use' and 'only use if you have github account' and please fix these inane problems in your broken software.

I was of the impression that 'oh its those github folks, I can trust them when they say 'there is no step 3, that's it' and happily tried this on a giant repo.' You have lost my trust so terribly that i will never buy whatever you are trying to sell.

-------------------------------------------

PSA: The proven way out of git lfs is:

git lfs migrate export --everything --include="*.psd"
git lfs migrate export --everything --include="*.png"
git lfs migrate export --everything --include="*.jpg"
 etc..
 and until git lfs ls-files does not list anything.

Note that it is even more infuriating that on Windows:
```
git lfs migrate export --everything --include="*.*"
prints out an amazing "EOF" and dies.

```
:(

**Comment by perumaal** [comment] 2020-05-16 12:04
Actually that's not it... after git lfs migrate export you can no longer push to a non-github origin

"error: failed to push some refs to 'file://blah'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details."

so you either have to branch out or do some other surgery

**Comment by bk2204** [comment] 2020-05-18 18:14
Hey,

If you run `git lfs migrate export`, that rewrites your history, so you do need to do a force push.

I'm sorry you seem to have had a bad experience here, but I think I've responded to the other points elsewhere: there are multiple non-GitHub implementations; there is documentation, built into the binary, in the man pages, and on the website, even if it's not where you expected it; and Git LFS does the best it can provided the limitations that Git provides.

If there are concrete places you'd have looked for the documentation that I haven't mentioned above, we'd be happy to try to add pointers or improve the documentation.  If there are other concrete improvements you'd like to see, we can try to work on those things as well.  However, absent concrete and actionable problems that we can work on, I don't think there's anything else we can do here.

**Comment by bk2204** [comment] 2020-05-18 18:23
As a note, it's nearly impossible for us to figure out what's going on if you don't use the issue template to fill out the steps you took to cause the problem and the actual output you saw.  Presumably there was a problem, but without knowing what the problem was or the output you saw, we can't figure out what happened or how to make it better.

**Comment by bk2204** [comment] 2020-08-14 17:53
Hey,

Since we lack actual reproduction steps here, I'm going to close this issue.  We'll consider reopening it if you can provide the information requested in the issue template, including a set of reproduction steps.

**Closed by bk2204** 2020-08-14 17:53 UTC
