### ISSUE TITLE
Install on Windows fails due to "unexpected" git executable

### ISSUE THREAD

**Issue by jovball** [git-lfs/git-lfs#5679] opened 2024-03-11 20:16 UTC
Starting with 3.20, the chocolatey package install is failing and I'm seeing the same behavior when I attempt a silent install from the command line using the exe file. 

This just fails without any indication of what happened unless I add the switch to create a log file
`.\git-lfs-windows-v3.2.0.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /LOG`

The log shows that a Warning message was suppressed and defaulted to No which cancelled the install process.

```
Warning: Found Git in unexpected location: "c:\program files\git\cmd\git.EXE"
Defaulting to No for suppressed message box (Yes/No):

An executable Git program was found in an unexpected location outside of Program Files:
     "c:\program files\git\cmd\git.EXE"
If this looks dubious, Git LFS should not be registered using it.

Do you want to register Git LFS using this Git program?

Refusing to use Git found at: "c:\program files\git\cmd\git.EXE"
```
Depending on the exact configuration of the PC, the error message might say c:\program files\git\bin\git.exe. I can't understand why git-lfs thinks that location is "outside of Program Files." If I run the installer manually without the /SILENT switch and choose Yes then it installs as expected but this breaks any scripted install.

**Comment by bk2204** [comment] 2024-03-12 19:14
Hey,

Thanks for the report.  It's intentional that your install has to be under one of the program files directories and that it will fail if that's not possible, since we need to invoke Git during the installation.  That change came in #4925 and is because the installer might run privileged but `PATH` might be unprivileged, so that's a security hardening approach.

It's unclear to me why this is failing, because that path should in fact be correct.  My guess is that the entry in `PATH` perhaps differs in case from the actual value we've looked up.  If you change `PATH` such that it contains `C:\Program Files\Git\cmd` instead of `c:\program files\git\cmd`, does that fix the problem?

While I agree it would be nice to improve the output here, none of the core team members use Windows and the Windows installer is very much a best effort approach, so patches are welcome.  If the problem is the difference in case, I think we can provide a fix nonetheless if you'd be willing to test it.

**Comment by jovball** [comment] 2024-03-12 21:33
You have it right exactly and I'm embarrassed that I didn't think of the case difference. I would be happy to test a patch if you can change that to be case-insensitive.

**Comment by chrisd8088** [comment] 2024-03-13 03:32
As @bk2204 said, I suspect the problem is the case-sensitivity of the Pascal `Pos()` [function](https://jrsoftware.org/ishelp/index.php?topic=isxfunc_pos) which we use to [compare](https://github.com/git-lfs/git-lfs/blob/eda4fd704cf5c17e2c061fb4d435a41e0bc2f83b/script/windows-installer/inno-setup-git-lfs-installer.iss#L189) executable paths against the canonical location for program files.

**Comment by bk2204** [comment] 2024-03-14 13:27
I'm pretty sure that setting `C:\Program Files` to be case sensitive is going to break lots of native Win32 and Win64 programs that live there, so I'm certain that isn't going to be a problem.

I do have #5680, which should fix this.  The Actions tab is at https://github.com/git-lfs/git-lfs/actions/runs/8265604754 and you can download the `windows-latest` assets and extract the installer.  That should have the fix, but do note that it's not signed.

**Comment by jovball** [comment] 2024-03-15 15:23
I tested this build several time with both a silent install from the command line and using the installer GUI. I also put several different variations of casing in PATH including all lowercase (the original situation for this issue) and mixed case such as "c:\Program files." Each of the tests were successful. Do you need me to comment on #5680 or is this enough here?

Thanks for your attention to this. It was obviously an edge case and I could've worked around it but it's nicer this way.

**Comment by bk2204** [comment] 2024-03-15 17:20
No, this is quite sufficient.  Many thanks for your assistance in testing this.  I've opened #5680 for review and it will likely be merged on Monday or Tuesday, in which case, this will automatically close.

**Closed** 2024-03-21 12:57 UTC
Labels: installation, windows

**Comment by asesidaa** [comment] 2024-11-30 07:04
Hi, there are actually more cases to consider. 
For example, on my machine, my path variable is compressed using the [short path](https://en.wikipedia.org/wiki/8.3_filename) format and `C:\Program Files` becomes `C:\PROGRA~1`. 
And this format is not recognized by the installer even though git is on the default location.
Before string comparison maybe the path needs to be expanded to its full form
![image](https://github.com/user-attachments/assets/745bd633-99bb-42d6-9309-30d24831984d)

**Comment by chrisd8088** [comment] 2024-12-04 15:47
Thanks, @asesidaa, that's a good point.  I'll see if we can use a function in the Windows installer to expand short paths before testing against the system paths for program files.

Until then, you're of course OK to just acknowledge the warning and proceed to install.
