### ISSUE TITLE
git lfs not working with git subtree ?

### ISSUE THREAD

**Issue by prudhomm** [git-lfs/git-lfs#854] opened 2015-11-21 20:26 UTC
Hi

I am trying to use git lfs in a repository A which is then used as a subtree into several other repo B,C and D.
the lfs handled files are ok in A but in B C and D I get these messages:

```
git pull
Updating 7260202..eb6db19
Downloading _posts/images/a09.png (557 B)
Error accessing media: _posts/images/a09.png (e1cde171e0c2a17b59874d54351cc9da7f218f1018c8a7d9984e7fd495cb9b12)

Errors logged to .git/lfs/objects/logs/20151121T211224.774211385.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge %f failed 2
error: external filter git-lfs smudge %f failed
fatal: _posts/images/a09.png: smudge filter lfs failed
```

basically I share some images using repo A between several other git repo. 
am i missing something ?
is it supposed to work or not work ?

thanks in advance

**Comment by technoweenie** [comment] 2015-11-23 17:20
Git LFS works by storing files outside of the repository. So standard repository tools like subtree won't work out of the box, since it only references the Git data, and not the Git LFS data. I think it'll work if you do something like this:

```bash
# in repo A
$ git remote add B git-server.com/prudhomm/b
$ git remote add C git-server.com/prudhomm/c
$ git remote add D git-server.com/prudhomm/d
$ git lfs push B master --all
$ git lfs push C master --all
$ git lfs push D master --all
```

This pushes all of the LFS objects in A to the LFS endpoints for B, C, and D. It's not the most efficient option though. There may be a better way to support subtrees, but I don't know enough about the underlying command to know what it would be right now.

**Comment by xpol** [comment] 2016-05-24 10:39
My subtree module does not contains any files that store in lfs.
But git subtree push still failed.

**Comment by technoweenie** [comment] 2016-05-24 13:51
Hi @xpol, I don't see anything in your output that indicates this is a problem with the git lfs client. Is there something I'm missing?

**Comment by xpol** [comment] 2016-05-25 02:40
Hi @technoweenie, I can confirm that it is relate to lfs.

Here is my steps (all steps are in directory of repo **W**):

1. create a repo **W** without lfs enabled.
2. add repo **A** as subtree in repo **W**, (repo **A** is alose without lfs)
3. `git subtree pull` and `git subtree push` works at this point.
4. Enable lfs in repo W by add tracking extensions, and some files in repo **W** has now managed by lfs.
5. Commit and Push in repo **W** works and the LFS push binary files.
6. `git subtree pull` still works, but `git subtree push` got error just like my [comment above](https://github.com/github/git-lfs/issues/854#issuecomment-221231510).

**Comment by xpol** [comment] 2016-05-25 03:28
I'm currently consider disable lfs.
How can I convert a repo with lfs enabled back to normal git repo?

**Comment by xpol** [comment] 2016-05-25 03:47
I think the error `Invalid remote name "https://gitlab.local/team/A.git"` is related to #1069.

**Comment by technoweenie** [comment] 2016-05-25 13:17
The only way to disable lfs is to use [`git filter-branch`](https://git-scm.com/docs/git-filter-branch) to rewrite the lfs pointers back to normal git blobs.

And yes, that "invalid remote name" issue looks like the right bug.

**Comment by flowlo** [comment] 2016-06-14 12:22
I just ran into the same, or a similar issue.

I am using [`pass`](https://www.passwordstore.org) and now want to share some of my passwords with a coworker. We set up a Git repository for the shared passwords and want to use it by means of a Git subtree, e.g. `.password-store/foo` will point at some different remote.

Furthermore I am using Git LFS to store my `*.gpg` files since they are not text-based.

Now I added a new file `.password-store/foo/bar.gpg` that contains a password and is tracked by Git LFS. This works fine with my original repo, but as soon as I attempt to push my changes to the  other remote, I am faced with the following:

```
$ git remote -v
...
secrets	git@shared-git.invalid:foo/secrets.git (fetch)
secrets	git@shared-git.invalid:foo/secrets.git (push)
$ GIT_TRACE=1 git subtree push --prefix=.password-store/foo secrets master                             
14:12:20.449764 git.c:558               trace: exec: 'git-subtree' 'push' '--prefix=.password-store/foo' 'secrets' 'master'
14:12:20.449792 run-command.c:335       trace: run_command: 'git-subtree' 'push' '--prefix=.password-store/foo' 'secrets' 'master'
14:12:20.452679 git.c:348               trace: built-in: git 'rev-parse' '--parseopt' '--' 'push' '--prefix=.password-store/foo' 'secrets' 'master'
14:12:20.458976 git.c:348               trace: built-in: git 'rev-parse' '--git-dir'
14:12:20.460130 git.c:348               trace: built-in: git 'rev-parse' '--show-cdup'
14:12:20.461887 git.c:348               trace: built-in: git 'rev-parse' '--git-path' 'objects'
14:12:20.467470 git.c:348               trace: built-in: git 'check-ref-format' 'refs/heads/master'
git push using:  secrets master
14:12:20.468584 git.c:558               trace: exec: 'git-subtree' 'split' '--prefix=.password-store/foo'
14:12:20.468607 run-command.c:335       trace: run_command: 'git-subtree' 'split' '--prefix=.password-store/foo'
14:12:20.470851 git.c:348               trace: built-in: git 'rev-parse' '--parseopt' '--' 'split' '--prefix=.password-store/foo'
14:12:20.476662 git.c:348               trace: built-in: git 'rev-parse' '--git-dir'
14:12:20.478042 git.c:348               trace: built-in: git 'rev-parse' '--show-cdup'
14:12:20.479865 git.c:348               trace: built-in: git 'rev-parse' '--git-path' 'objects'
14:12:20.483926 git.c:348               trace: built-in: git 'rev-parse' '--default' 'HEAD' '--revs-only'
14:12:20.485090 git.c:348               trace: built-in: git 'rev-parse' '--no-revs' '--no-flags'
14:12:20.490833 git.c:348               trace: built-in: git 'log' '--grep=^git-subtree-dir: .password-store/foo/*$' '--pretty=format:START %H%n%s%n%n%b%nEND%n' '98eaadf4eaa547f9543506ebe4bb685a4acf5c7e'
14:12:20.495291 git.c:348               trace: built-in: git 'rev-list' '--topo-order' '--reverse' '--parents' '98eaadf4eaa547f9543506ebe4bb685a4acf5c7e' '^279ef8e96e480e5d949431274a219e2eb09a8263^'
14:12:20.497212 git.c:348               trace: built-in: git 'rev-list' '--topo-order' '--reverse' '--parents' '98eaadf4eaa547f9543506ebe4bb685a4acf5c7e' '^279ef8e96e480e5d949431274a219e2eb09a8263^'
14:12:20.501152 git.c:348               trace: built-in: git 'ls-tree' '3c8e946ad9afbe812b7fa0dea6e10c03b282ce95' '--' '.password-store/foo'
14:12:20.503893 git.c:348               trace: built-in: git 'log' '-1' '--pretty=format:%T' 'c30d757fe728daac7bced6e655cf64aa76df2256' '--'
14:12:20.505538 git.c:348               trace: built-in: git 'log' '-1' '--pretty=format:%T' 'c30d757fe728daac7bced6e655cf64aa76df2256' '--'
14:12:20.508646 git.c:348               trace: built-in: git 'ls-tree' '80dd2dbd440da47edcf0297643e01baa6a61e508' '--' '.password-store/foo'
14:12:20.511404 git.c:348               trace: built-in: git 'log' '-1' '--pretty=format:%T' 'c30d757fe728daac7bced6e655cf64aa76df2256' '--'
14:12:20.513090 git.c:348               trace: built-in: git 'log' '-1' '--pretty=format:%an%n%ae%n%aD%n%cn%n%ce%n%cD%n%B' '80dd2dbd440da47edcf0297643e01baa6a61e508'
14:12:20.514569 git.c:348               trace: built-in: git 'commit-tree' 'dad5ce893b5ca976d0500941575bea9fab1ead71' '-p' 'c30d757fe728daac7bced6e655cf64aa76df2256'
14:12:20.517989 git.c:348               trace: built-in: git 'ls-tree' 'f46b830af1fc8a59d140365c2ed6c94a5ebfcb29' '--' '.password-store/foo'
14:12:20.520730 git.c:348               trace: built-in: git 'log' '-1' '--pretty=format:%T' '183cddb2277430f9a0b968a35906d2d2db9046fc' '--'
14:12:20.524070 git.c:348               trace: built-in: git 'ls-tree' '98eaadf4eaa547f9543506ebe4bb685a4acf5c7e' '--' '.password-store/foo'
14:12:20.526695 git.c:348               trace: built-in: git 'log' '-1' '--pretty=format:%T' '183cddb2277430f9a0b968a35906d2d2db9046fc' '--'
14:12:20.529929 git.c:348               trace: built-in: git 'push' 'secrets' '183cddb2277430f9a0b968a35906d2d2db9046fc:refs/heads/master'
14:12:20.530172 run-command.c:335       trace: run_command: 'ssh' 'git@shared-git.invalid' 'git-receive-pack '\''foo/secrets.git'\'''
14:12:27.452946 run-command.c:335       trace: run_command: '.git/hooks/pre-push' 'secrets' 'git@shared-git.invalid:foo/secrets.git'
14:12:27.455161 git.c:558               trace: exec: 'git-lfs' 'pre-push' 'secrets' 'git@shared-git.invalid:foo/secrets.git'
14:12:27.455185 run-command.c:335       trace: run_command: 'git-lfs' 'pre-push' 'secrets' 'git@shared-git.invalid:foo/secrets.git'
trace git-lfs: run_command: git rev-list --objects 183cddb2277430f9a0b968a35906d2d2db9046fc --not --remotes=secrets --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' config -l
trace git-lfs: tq: starting 3 transfer workers
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: tq: sending batch of size 1
trace git-lfs: ssh: git@shared-git.invalid git-lfs-authenticate foo/secrets.git upload 
trace git-lfs: ssh: upload attempted with git@shared-git.invalid.  Error: exit status 1
Git LFS: (0 of 1 files) 0 B / 626 B                                                                                                                                                                               
exit status 1
exit status 1
error: failed to push some refs to 'git@shared-git.invalid:foo/secrets.git'
```

The domain name obviously is redacted.

I am not sure what Git LFS is trying to do here, and why it fails. SSH authentication is fine.

**Comment by rBatt** [comment] 2016-07-14 03:54
[I'm trying to follow this procedure (both the highest voted and the Easy Way](http://stackoverflow.com/questions/359424/detachmove-subdirectory-into-separate-git-repository)

The subdirectory I want to turn into  its own repo has lfs files. So do other parts of the big repo.
`trawl` is the big repo. `trawlDiversity` is a subdirectory inside `trawl`. Here's one example of the procedures I've attempted:  
```{bash}
pushd trawl-local\ copy
git subtree split -P trawlDiversity -b tdSplit
git checkout tdSplit
popd

mkdir trawlDiversity-local
pushd trawlDiversity-local

git init
git lfs pull ../trawl-local\ copy tdSplit

git remote add origin https://github.com/rBatt/trawlDiversity.git
git push origin -u master
```

**Comment by ttaylorr** [comment] 2018-07-27 17:44
Hi, working trees are not officially supported in Git LFS, so some issues are to be expected when working with them. Since this issue hasn't been updated in more than two years, I am going to close it for now. That said, please do not hesitate to continue reporting these bugs, and hopefully someone will get a chance to take a look at them. Thanks!

**Closed by ttaylorr** 2018-07-27 17:44 UTC
