### ISSUE TITLE
New Git Filter Protocol cannot handle files with lots of `\0`?!

### ISSUE THREAD

**Issue by larsxschneider** [git-lfs/git-lfs#1667] opened 2016-11-16 16:54 UTC
### Setup

```
git-lfs/1.4.4 (GitHub; darwin amd64; go 1.6.1; git 5e48c70) --> latest master
git version 2.11.0.rc1 --> lastest master
macOS
```
### Steps to reproduce

``` bash
$ git init .
$ mkfile -n 2k test.dat
$ git-lfs track *.dat 
$ git add .

--> this will hang!
```

`mkfile` creates a file full of `\0` and this seems to be a problem 😨

**Comment by ttaylorr** [comment] 2016-11-16 17:21
Thanks for the report! Just tried to reproduce this, but wasn't able to. Here's what I was using:

```bash
~/D/foo (master) $ git lfs env                               
git-lfs/1.4.4 (GitHub; darwin amd64; go 1.7.3; git 5e48c70)  
git version 2.11.0.rc1                                       
                                                             
git config filter.lfs.process = "git-lfs filter-process"     
git config filter.lfs.smudge = "false"                       
git config filter.lfs.clean = "false"                        
```

and the steps I took to reproduce:

```
~/Desktop $ mkdir foo                                                      
~/Desktop $ cd foo                                                         
~/D/foo $ git init .                                                       
Initialized empty Git repository in /Users/ttaylorr/Desktop/foo/.git/      
~/D/foo $ mkfile -n 2k test.dat                                            
~/D/foo $ git lfs track "*.dat"                                            
Tracking *.dat                                                             
~/D/foo $ git add .                                                        
~/D/foo $ git commit -m "hello world"                                      
[master (root-commit) e3f28cd] hello world                                 
 2 files changed, 4 insertions(+)                                          
 create mode 100644 .gitattributes                                         
 create mode 100644 test.dat                                               
~/D/foo (master) $ git cat-file -p :test.dat                               
version https://git-lfs.github.com/spec/v1                                 
oid sha256:e5a00aa9991ac8a5ee3109844d84a55583bd20572ad3ffcd42792f3c36b183ad
size 2048                                                                  
~/D/foo (master) $                                                         
```

It looks like we're using different versions of Go, which might be what's going on.

**Comment by larsxschneider** [comment] 2016-11-16 17:21
It's not related to '\0'. All files larger than 1024 bytes hang:

```bash
$ mkfile -n 1024 test1.dat && GIT_TRACE=1 GIT_TRACE_PACKET=1 git add .
18:19:15.134003 git.c:371               trace: built-in: git 'add' '.'
18:19:15.135293 run-command.c:350       trace: run_command: 'git-lfs filter-process'
18:19:15.135785 run-command.c:209       trace: exec: '/bin/sh' '-c' 'git-lfs filter-process' 'git-lfs filter-process'
18:19:15.136080 pkt-line.c:80           packet:          git> git-filter-client
18:19:15.136104 pkt-line.c:80           packet:          git> version=2
18:19:15.136108 pkt-line.c:80           packet:          git> 0000
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: 'git' config -l
trace git-lfs: Initialize filter-process
18:19:15.161977 pkt-line.c:80           packet:          git< git-filter-server
18:19:15.161988 pkt-line.c:80           packet:          git< version=2
18:19:15.161991 pkt-line.c:80           packet:          git< 0000
18:19:15.161994 pkt-line.c:80           packet:          git> capability=clean
18:19:15.161999 pkt-line.c:80           packet:          git> capability=smudge
18:19:15.162002 pkt-line.c:80           packet:          git> 0000
trace git-lfs: Read filter-process request.
18:19:15.162027 pkt-line.c:80           packet:          git< capability=clean
18:19:15.162032 pkt-line.c:80           packet:          git< capability=smudge
18:19:15.162035 pkt-line.c:80           packet:          git< 0000
18:19:15.162041 pkt-line.c:80           packet:          git> command=clean
18:19:15.162046 pkt-line.c:80           packet:          git> pathname=test1.dat
18:19:15.162049 pkt-line.c:80           packet:          git> 0000
18:19:15.162161 pkt-line.c:80           packet:          git> \0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0
18:19:15.162327 pkt-line.c:80           packet:          git> 0000
18:19:15.162340 pkt-line.c:80           packet:          git< status=success
18:19:15.162348 pkt-line.c:80           packet:          git< 0000
trace git-lfs: Read filter-process request.
18:19:15.162630 pkt-line.c:80           packet:          git< version https://git-lfs.github.com/spec/v1oid sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6efsize 1024
18:19:15.162706 pkt-line.c:80           packet:          git< 0000
18:19:15.162710 pkt-line.c:80           packet:          git< status=success
18:19:15.162714 pkt-line.c:80           packet:          git< 0000
18:19:15.162969 run-command.c:42        trace: run_command: running exit handler for pid 18106

$ mkfile -n 1025 test1.dat && GIT_TRACE=1 GIT_TRACE_PACKET=1 git add .
18:19:18.470551 git.c:371               trace: built-in: git 'add' '.'
18:19:18.471739 run-command.c:350       trace: run_command: 'git-lfs filter-process'
18:19:18.472241 run-command.c:209       trace: exec: '/bin/sh' '-c' 'git-lfs filter-process' 'git-lfs filter-process'
18:19:18.472557 pkt-line.c:80           packet:          git> git-filter-client
18:19:18.472582 pkt-line.c:80           packet:          git> version=2
18:19:18.472586 pkt-line.c:80           packet:          git> 0000
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: 'git' config -l
trace git-lfs: Initialize filter-process
18:19:18.496576 pkt-line.c:80           packet:          git< git-filter-server
18:19:18.496586 pkt-line.c:80           packet:          git< version=2
18:19:18.496589 pkt-line.c:80           packet:          git< 0000
18:19:18.496593 pkt-line.c:80           packet:          git> capability=clean
18:19:18.496597 pkt-line.c:80           packet:          git> capability=smudge
18:19:18.496599 pkt-line.c:80           packet:          git> 0000
trace git-lfs: Read filter-process request.
18:19:18.496632 pkt-line.c:80           packet:          git< capability=clean
18:19:18.496641 pkt-line.c:80           packet:          git< capability=smudge
18:19:18.496644 pkt-line.c:80           packet:          git< 0000
18:19:18.496651 pkt-line.c:80           packet:          git> command=clean
18:19:18.496656 pkt-line.c:80           packet:          git> pathname=test1.dat
18:19:18.496659 pkt-line.c:80           packet:          git> 0000
18:19:18.496771 pkt-line.c:80           packet:          git> \0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0
18:19:18.496970 pkt-line.c:80           packet:          git> 0000
18:19:18.496979 pkt-line.c:80           packet:          git< status=success
18:19:18.496987 pkt-line.c:80           packet:          git< 0000
```

**Comment by larsxschneider** [comment] 2016-11-16 18:12
This bug seems to be related to `go 1.6.1`. Everything works fine with `go 1.7.3`!

**Comment by ttaylorr** [comment] 2016-11-16 20:30
> This bug seems to be related to go 1.6.1. Everything works fine with go 1.7.3!

Rad. We only support LFS on 1.7.3, so I think we should be fine here (that's the homebrew installation path, the version I compile Windows builds, and the version I pinned in Docker to build the `.deb` packages).

Without having looked too deep into this, I think the issue has to do with the implementation of `bufio.Writer` in Go 1.6.1. I want to look more into this before we release so I can be sure, though.

**Comment by ttaylorr** [comment] 2016-11-16 21:54
No significant changes in the implementation of that method. Going to close this for now, since we don't support Go 1.6.x anyway. 👍

**Closed by ttaylorr** 2016-11-16 21:54 UTC
Labels: bug
