### ISSUE TITLE
git lfs migrate import --everything ignores remote refs

### ISSUE THREAD

**Issue by GLaN1K** [git-lfs/git-lfs#5316] opened 2023-03-20 18:17 UTC
**Describe the bug**

`--everything` in `git lfs migrate import --everything` ignored all remote refs

**To Reproduce**

1. Clone repo which was prepared for the test:
```
git clone https://gitlab.com/nikita.savitsky1/lfs-migration-test
```

In it,  there are two branches `main` and `test_branch`:

```
glanik@Luna ~/lfs-migration-test:main 0> git show-ref
127eefa52cdb16bf4ad726aa1a83600f11ccf753 refs/heads/main
27db8eb4158f34493f0e238695274e6ea014cc51 refs/remotes/origin/HEAD
27db8eb4158f34493f0e238695274e6ea014cc51 refs/remotes/origin/main
27db8eb4158f34493f0e238695274e6ea014cc51 refs/remotes/origin/test_branch
```

2. Execute migration with `--everything`

```
 git lfs migrate import --everything --include="*.dat"
```

3. In output, only `main` was migrated, but `test_branch` was ignored:

```
migrate: Sorting commits: ..., done.
migrate: Rewriting commits: 100% (3/3), done.
  main  27db8eb4158f34493f0e238695274e6ea014cc51 -> 127eefa52cdb16bf4ad726aa1a83600f11ccf753
migrate: Updating refs: ..., done.
migrate: checkout: ..., done.
```

**Expected behavior**

All remote refs, including `test_branch` should have been migrated

**System environment**

M1 ARM CPU, MacOS "Ventura" Version 13.2.1 (22D68)

**Output of `git lfs env`**
```
glanik@Luna ~/lfs-migration-test:main 0> git lfs env
git-lfs/3.1.2 (GitHub; darwin arm64; go 1.17.6)
git version 2.30.1

Endpoint=https://gitlab.com/nikita.savitsky1/lfs-migration-test.git/info/lfs (auth=none)
  SSH=git@gitlab.com:nikita.savitsky1/lfs-migration-test.git
LocalWorkingDir=/Users/glanik/lfs-migration-test
LocalGitDir=/Users/glanik/lfs-migration-test/.git
LocalGitStorageDir=/Users/glanik/lfs-migration-test/.git
LocalMediaDir=/Users/glanik/lfs-migration-test/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/glanik/lfs-migration-test/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/glanik/lfs-migration-test/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/opt/homebrew/Cellar/git/2.30.1/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
N/A

**Comment by chrisd8088** [comment] 2023-03-22 07:01
Hey, sorry you're having trouble, and thanks for the demonstration case!

I think what's going on here is that the migration is intentionally only performed locally; that is, it doesn't automatically push any changes to your remote.  The reasoning behind this is explained in PR #2559, which specifically chose not to update non-local refs after migration because they would then be out-of-sync with the remote.

The `git lfs migrate import --everything` command does consider remote refs when looking for commits in history to modify.  But you would then need to update your refs to the rewritten history and push them if you want them to replace what is on your Git LFS hosting service.

Looking at your demonstration repository, there are three commits in history, and all refs have the same history:
```
$ git log --oneline
27db8eb (HEAD -> main, origin/test_branch, origin/main, origin/HEAD) Merge branch 'binary-without-lfs' into 'main'
9b21a7f Added binary blob without LFS
187dd5f Initial commit
```

The `git lfs migrate import --everything` command does walk through all the named refs (using `git for-each-ref --format'=%(objectname)%00%(refname)'`) and then feed all of those, including `origin/test_branch`, into the command which lists the commits to consider for rewriting (`git rev-list --reverse --topo-order --do-walk --stdin --`).  One can simulate this with:
```
$ git for-each-ref --format'=%(objectname)%00%(refname)' | git rev-list --reverse --topo-order --do-walk --stdin --
187dd5f5b7f3869cf881e689e60b2158da36414e
9b21a7ff3b1f571d9bf5869762ee15d95997e858
27db8eb4158f34493f0e238695274e6ea014cc51
```

So all possible commits are being considered for rewriting.  What you would need to do after the migration, if you want to update `test_branch` locally and remotely, might be something like the following, assuming `main` and `test_branch` are expected to be identical:
```
$ git checkout main
$ git checkout -b test_branch
$ git branch --set-upstream-to origin/test_branch
$ git push --force-with-lease origin test_branch
```

Alternatively, one can check out all the branches locally first, and that way they will all exist as local references and so will be migrated; then a force-push of all your branches will update the remote server (but only do this if you are happy with the migration, of course!)  This is probably the more useful approach in the general case.

**Comment by GLaN1K** [comment] 2023-03-28 22:00
Hello!

Thank you so much for such a detailed answer! 

I see, so tool was misused

But what do you think, is it reasonable to do some adjustments to the documentation?

https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-migrate.adoc

Because in it:

> Use the --everything option to specify that all refs should be examined, **_including all remote refs._** See [[_include_and_exclude_references]](https://github.com/git-lfs/git-lfs/issues/5316#_include_and_exclude_references) for details.

And even specifically suggest to use `push -f --all` in such cases:

> Note: This will require a force-push to any existing Git remotes. Using the --all option when force-pushing may be convenient if many refs were updated, e.g., after exporting from Git LFS with the --everything option.

Apparently, im not the only one who was confused:

https://stackoverflow.com/questions/72205544/git-lfs-migrate-with-everything-is-not-migrating-all-the-remote-branches

**Comment by chrisd8088** [comment] 2023-03-31 21:48
I've updated the `git-lfs-migrate(1)` manual [page](https://github.com/git-lfs/git-lfs/blob/1c16945d926de791e9104460caab3b4abfa722cb/docs/man/git-lfs-migrate.adoc) in PR #5327 to explain more fully and correctly how local and remote references are treated during migration, and also documented an example in https://github.com/git-lfs/git-lfs/pull/5327#issuecomment-1492644043 for future reference, so I'm going to close this issue.

Thanks again for the reproduction case and suggestions!

**Closed by chrisd8088** 2023-03-31 21:48 UTC
