### ISSUE TITLE
zlib: invalid header 

### ISSUE THREAD

**Issue by huamingduo** [git-lfs/git-lfs#5115] opened 2022-09-15 04:04 UTC
**Describe the issue**
When I am trying to use git-lfs following https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage, it outputs the `zlib: invalid header` error when I run `git push`

git and git-lfs versions:
git-lfs/3.2.0 (GitHub; linux amd64; go 1.18.2)
git version 2.25.1

Does anyone has any comments on this? Thanks in advance.

**Comment by chrisd8088** [comment] 2022-09-15 22:24
Hey, I'm sorry you're having trouble.  Would you be able to provide some more details by filling out the full issue template, such as the output of `git lfs env`?

I we'll also need the full output of the `git push` command, and ideally a small reproduction test case if you can share it with us.

**Comment by bk2204** [comment] 2023-04-25 19:43
Hey, since we're still waiting on information here and it hasn't been forthcoming, I'm going to close this.  If you can provide the requested information, we can reopen.

**Closed by bk2204** 2023-04-25 19:43 UTC
