### ISSUE TITLE
I've modified the pre-push commit hook to deal with path issues when running in a cron job. This okay?

### ISSUE THREAD

**Issue by michaelgwelch** [git-lfs/git-lfs#4319] opened 2020-11-24 16:00 UTC
**Describe the issue**
I'm attempting to use a cron job to  "backup" my local repo on a periodic basis. I'm just pushing to a bare repo on the same machine as my local repo (but it's in a onedrive folder that will be synced to OneDrive.)

Basically I just want the command `git push onedrive --all` to be run from my local repo. I can run this manually without issue, but I have trouble if I set up the following cron entry:

```bash
0 * * 1-5 cd $HOME/repos/project && ./backup 
```

where `myrepo` is the local repo I want backed up and `backup` is the script that does `git push onedrive --all`. 

The pre-push hook fails because it doesn't detect `git-lfs` in the path. 

```
This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.
```

This is a little odd because `git-lfs` and `git` are in the exact same location on my machine.

```bash
> which git
/usr/local/bin/git
> which git-lfs
/usr/local/bin/git-lfs
> command -v git-lfs
/usr/local/bin/git-lfs
```

I've resolved the issue by modifying the pre-push hook to include a modified path:

```bash
#!/bin/sh
PATH=/usr/local/bin:$PATH command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
PATH=/usr/local/bin:$PATH git lfs pre-push "$@"
```

Would there be any issues with using a modified pre-push hook?

**System environment**
OS: macOS Catalina (10.15.7)
git: 2.28.0
git-lfs: 2:11.0

**Output of `git lfs env`**

(project and user names changed, the onedrive remote is the one being used for backups)

```bash
git lfs env
git-lfs/2.11.0 (GitHub; darwin amd64; go 1.14.2)
git version 2.28.0

Endpoint (onedrive)=file:///Users/michaelgwelch/onedrive/bare-repos-for-backup/project.git (auth=none)
Endpoint (origin)=https://github.com/michaelgwelch/project.git/info/lfs (auth=basic)
LocalWorkingDir=/Users/michaelgwelch/repos/project
LocalGitDir=/Users/michaelgwelch/repos/project/.git
LocalGitStorageDir=/Users/michaelgwelch/repos/project/.git
LocalMediaDir=/Users/michaelgwelch/repos/project/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/michaelgwelch/repos/project/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/michaelgwelch/repos/project/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/local/Cellar/git/2.28.0/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
```

**Comment by bk2204** [comment] 2020-11-24 20:02
Hey,

There shouldn't be any problem with changing the `PATH` like this.  Users can certainly change the hooks as appropriate to set things or to add additional functionality.

To provide some context about what I think is going on here, which may or may not be helpful here, I suspect you're using bash or zsh with `/usr/local/bin` added to your `PATH` in your shell configuration.  However, the hook is using `/bin/sh`, and even if that's a link to bash, your `.bashrc` won't be read because that file is only read for interactive shells (and SSH).

As for the idea of pushing to a repository on a OneDrive folder, I strongly recommend against that, whether you're using Git LFS or not.  It's known that cloud file syncing services can cause corruption of the repository.  You'd be better off creating an uncompressed tar archive of the repository and putting that in OneDrive instead, but only when the repository is guaranteed to be idle (that is, no processes, not even `git gc` running in it).

Hopefully this is helpful.

**Comment by michaelgwelch** [comment] 2020-11-25 19:21
> To provide some context about what I think is going on here, which may or may not be helpful here, I suspect you're using bash or zsh with /usr/local/bin added to your PATH in your shell configuration. However, the hook is using /bin/sh, and even if that's a link to bash, your .bashrc won't be read because that file is only read for interactive shells (and SSH).

Thanks, that's the hint I needed. That seems logical. I see that macOS has a version of `git` in `/usr/bin` so that would explain why `git` is found but not `git-lfs`.

Yeah I've heard rumors about the issue with one drive. This repo I'm pushing to is a "write-only" bare repo with only one process every writing to it. I thought the issues were a result of trying to use a one drive repo as a source for multiple people/processes (all reading/writing to it).

**Comment by bk2204** [comment] 2020-11-30 22:57
> Yeah I've heard rumors about the issue with one drive. This repo I'm pushing to is a "write-only" bare repo with only one process every writing to it. I thought the issues were a result of trying to use a one drive repo as a source for multiple people/processes (all reading/writing to it).

I think the problem is that these types of services can cause files to disappear or reappear as part of the syncing process, which can cause the working tree or repository contents to be broken.  That's the kind of thing folks have seen in the past, although I don't personally use these services so I can't speak from experience.

Anyway, your changes to the hooks should be fine, so I'm going to close this.  Glad things are working for you now.

**Closed by bk2204** 2020-11-30 22:57 UTC
Labels: question
