### ISSUE TITLE
git-lfs-migrate doesn't fully migrate some tags

### ISSUE THREAD

**Issue by westerlund** [git-lfs/git-lfs#3467] opened 2019-01-10 09:25 UTC
Hi!

I haven't had very much luck when running `git lfs migrate [import|info]`. For some reason, when not specifying `include/exclude-ref` I got `fatal: bad revision` on all the tags, I was able to bypass this error by setting the flag `--everything`.

Anyway, the real issue is that the migration tool doesn't seem to be fully working with tags. I have one tag that just don't want to be migrated. The output looks alright:
```bash
❯ git lfs migrate import --include="*.a" --include-ref=refs/tags/my-tag
migrate: Sorting commits: ..., done                                                                                                                                                
migrate: Rewriting commits: 100% (11507/11507), done                                                                                                                               
migrate: Updating refs: ..., done                                                                                                                                                  
migrate: checkout: ..., done  
```

but when I try to push that tag using `git push origin tag my-tag` I eventually get an error.
```bash
Counting objects: 107496, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (29763/29763), done.
Writing objects: 100% (107496/107496), 371.90 MiB | 454.00 KiB/s, done.
Total 107496 (delta 73509), reused 95483 (delta 71932)
remote: Resolving deltas: 100% (73509/73509), done.
remote: Checking connectivity: 107496, done.
remote: warning: File path/to/big.file is 58.11 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File path/to/big.file is 58.11 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File path/to/big.file is 58.09 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 5d774b6e610bedc0fdbb013b25861977
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File path/to/big.file is 109.28 MB; this exceeds GitHub's file size limit of 100.00 MB
To github.com:example/repo.git
 ! [remote rejected]       my-tag -> my-tag (pre-receive hook declined)
error: failed to push some refs to 'git@github.com:example/repo.git
```

As you can see from my log, the tag clearly hasn't been updated and Github is rejecting the push.

Am I missing something, a flag or any limitations or is this a bug in the migration tool?

This is my setup:
```bash
❯ git lfs version
git-lfs/2.6.1 (GitHub; darwin amd64; go 1.11.2)
❯ git --version
git version 2.17.2 (Apple Git-113)
```

Thanks!

**Comment by bk2204** [comment] 2019-01-10 14:21
Hey, sorry to hear you're having trouble with this.

Does `path/to/big.file` match `*.a`? If not, you may need to expand the wildcard match to include that file as well.

**Comment by westerlund** [comment] 2019-01-10 14:33
@bk2204 oh, yes it does, I had to remove the paths. But yes, the rules are correct since a `git lfs migrate info --include="*.a" --include-ref=refs/tags/my-tag` lists all the files that would be affected.

**Comment by bk2204** [comment] 2019-01-10 15:17
We currently have #3238 open for this issue and we're waiting on a testcase to reproduce it. We've seen reports, but lack the ability to fix it without reproduction steps.

I'm going to close this issue in favor of that one, but please do let us know if you have a situation in which it can be reproduced, because we would quite like to fix it.

**Closed by bk2204** 2019-01-10 15:17 UTC
