### ISSUE TITLE
`git lfs fsck` giving "should have been a pointer but was not"

### ISSUE THREAD

**Issue by baffles** [git-lfs/git-lfs#5145] opened 2022-10-19 19:52 UTC
**Describe the issue**

I have a `.gitattributes` at the base of my repository with:

```gitattributes
[attr]lfs filter=lfs diff=lfs merge=lfs -text
```

And in a subfolder whose contents I want to be stored in git-lfs in their entirety, I have a `.gitattributes` file with:

```gitattributes
* lfs
**/.git* !lfs
.git* !lfs
```

I have a CI script that runs `git fsck lfs` to verify that its cache of the repository is okay. Lately, this has started outputting "pointer: unexpectedGitObject: "path/to/folder/.gitignore" (treeish <hash>) should have been a pointer but was not"

This seems non-sensical to me. I have verified that this file does not show up in `git lfs ls-files` and also verified that the filter for that file is not set with `git check-attr -a path/to/folder/.gitignore`. Trying to do a `git add --renormalize` on that file also doesn't produce any changes.

Was there a recent change that may have caused this? At one point, that `.gitignore` file was stored in LFS erroneously, but that was corrected in 2018, and `git lfs fsck` has not reported any issues until recently.

**System environment**

I am able to see this in my local working copy on macOS as well as on my CI build environment. Standard operations (checkout/commit/etc) are not impacted by this, this only shows up when running an `lfs fsck`.

**Output of `git lfs env`**

```
$ git lfs env                                                                                                                                                                                        git:dev/v2022.10.x java:11
git-lfs/3.2.0 (GitHub; darwin amd64; go 1.18.2)
git version 2.37.0

Endpoint=<redacted>
LocalWorkingDir=<redacted>
LocalGitDir=<redacted>
LocalGitStorageDir=<redacted>
LocalMediaDir=<redacted>
LocalReferenceDirs=<redacted>
TempDir=<redacted>
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=<redacted>
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/local/Cellar/git/2.37.0/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by chrisd8088** [comment] 2022-10-20 15:29
Hey, I'm sorry you're having trouble, and thanks for the detailed notes.  I've been able to reproduce this as follows:
```
$ git init test
$ cd test
$ echo "[attr]lfs filter=lfs diff=lfs merge=lfs -text" >.gitattributes
$ mkdir images
$ cat <<EOF >images/.gitattributes
* lfs
**/.git* !lfs
.git* !lfs
EOF
$ echo "foo.txt" >images/.gitignore
$ git add .gitattributes images
$ git commit -m init

$ git lfs fsck
pointer: unexpectedGitObject: "images/.gitignore" (treeish 7460b1b18717e4a8b9a3e83a8b89233c06259a79) should have been a pointer but was not
```

We'll have to take a look and see what the cause is.

**Comment by chrisd8088** [comment] 2022-11-02 22:35
I think the problem here is that when processing macros in `.gitattributes` files we only take [account](https://github.com/git-lfs/git-lfs/blob/7cbab661c505d9a113625eb55682079da0b8af79/git/gitattr/macro.go#L36-L41) of the positive "set"/`true` case, and not either of the "unset"/`false`/`-` or unspecified/`!` cases.

**Comment by chrisd8088** [comment] 2022-11-03 05:07
A little more precisely, it appears that what the `gitattributes(5)` documentation [says](https://git-scm.com/docs/gitattributes#_using_macro_attributes):
> Note that macro attributes can only be "Set" ...
this is not strictly true, they can also be returned to an unspecified state with `!`, as done in the example here.  That's the specific case we don't handle yet.  But the unset case (`-`) does not apply to macro attributes.  Interesting.

**Comment by chrisd8088** [comment] 2022-11-04 08:09
I've encountered another problem, I think, with the current macro processing, this time in relation to how we handle `git lfs track` (and `git lfs untrack`, most likely).  Here's a demo, for my own reference, primarily:

```
$ git init test
$ cd test
$ echo "[attr]foo filter=foo" > .gitattributes
$ mkdir dir
$ cd dir
$ echo "*.bin foo" >.gitattributes
$ echo "*.dat filter=bar" >>.gitattributes

$ cat .gitattributes
*.bin foo
*.dat filter=bar

$ touch foo.bin
$ git check-attr -a foo.bin
foo.bin: foo: set
foo.bin: filter: foo

$ touch bar.dat
$ git check-attr -a bar.dat
bar.dat: filter: bar

$ git lfs track '*.bin'
Tracking "*.bin"

$ git lfs track '*.dat'
"*.dat" already supported

$ cat .gitattributes
*.bin filter=lfs diff=lfs merge=lfs -text
*.dat filter=bar
```

So although both `*.bin` and `*.dat` in the subdirectory have `filter=...` attributes defined and set, `git lfs track` refuses (correctly) to update the regular `*.dat` one but will overwrite the `*.bin` one because it's defined via a macro attribute.  The reason is that we [reverse](https://github.com/git-lfs/git-lfs/blob/7cbab661c505d9a113625eb55682079da0b8af79/git/attribs.go#L196-L200) the order of `.gitattributes` files so that we process the deepest ones first, but then when we [iterate](https://github.com/git-lfs/git-lfs/blob/7cbab661c505d9a113625eb55682079da0b8af79/git/attribs.go#L88-L90) over those calling `attrPathsFromFile()` which [calls](https://github.com/git-lfs/git-lfs/blob/7cbab661c505d9a113625eb55682079da0b8af79/git/attribs.go#L101) `AttrPathsFromReader()`, it means that we don't see macro definitions until we get through all the higher-precedence (i.e., deeper) `.gitattributes` files where they might be used.

We may need to look for macros only in `.gitattributes`, `$GIT_DIR/info/attributes`, etc. first (in the right higher-to-lower precedence order), then go back and process all the files from highest to lowest precedence.  Or, more efficiently, load everything into memory first that might be applicable by going from highest (deepest) to lowest, but without resolving macros, and then go back and expand all the macros in a second pass.

I'm also not sure that we're processing the global or system attributes files (`$XDG_CONFIG_HOME/git/attributes` and `$(prefix)/etc/gitattributes`) at all.  In fact, I'm pretty certain we aren't; this is on a macOS system in an existing repo:
```
$ sudo echo "*.foo filter=foo" >/usr/local/etc/gitattributes
$ touch abc.foo
$ git check-attr -a abc.foo
abc.foo: filter: foo

$ git lfs track '*.foo'
Tracking "*.foo"
$ grep foo .gitattributes
*.foo filter=lfs diff=lfs merge=lfs -text
```

So although Git looks at the system-wide and global attributes files, we don't, and proceed to allow tracking/untracking.  Arguably this is not a huge issue for these commands, but it does affect correct macro processing, since macros can be defined in those files, and so we need to read them to get the full potential set of macro definitions.

**Comment by baffles** [comment] 2022-11-07 19:33
Glad to hear you were able to reproduce and get a fix in so quickly. Thanks!

**Closed** 2022-11-08 18:23 UTC
Labels: bug
