### ISSUE TITLE
add ssh and local filesystem protocol support to git-lfs

### ISSUE THREAD

**Issue by laoshaw** [git-lfs/git-lfs#2565] opened 2017-09-08 15:21 UTC
Please add native ssh and local filesystem (i.e. copy) to git-lfs, so I can 'git lfs push' via ssh instead of http/https, and I can also 'git lfs push' to a local directory without using any network protocols. This is very essential to man user cases.

**Comment by ttaylorr** [comment] 2017-09-08 17:42
Hi @laoshaw, thanks for opening this. This is certainly something that I would like to add to Git LFS, but I am going to close this particular issue for now, since it is largely a duplicate of https://github.com/git-lfs/git-lfs/issues/1207.

**Closed by ttaylorr** 2017-09-08 17:42 UTC
