### ISSUE TITLE
git fetch remoteA branchA --> Invalid ref argument: [branchA]

### ISSUE THREAD

**Issue by nhatkhai** [git-lfs/git-lfs#4136] opened 2020-05-15 04:24 UTC
I found `git lfs fetch` did not treat `<ref>` as same as regular git command. So here are what happen:
* ERROR when run something like:
```
>git lfs fetch remoteA branchA
....
Invalid ref argument: [branchA]
```
* Work as expected when run something like:
```
>git lfs fetch remoteA remoteA/branchA
```

**Comment by nhatkhai** [comment] 2020-05-19 09:59
Same error if <ref> is tag name. In this case, I can't find the work around yet for tag,

**Comment by bk2204** [comment] 2020-05-19 13:42
Hey,

While this is a little confusing, I believe it's intentional.  `git lfs fetch` doesn't actually fetch refs from the remote server (or speak the Git protocol to the remote server at all), so it's not possible to know for certain what the remote server has.  It only fetches the LFS objects from the specified remote using the given local branch.

**Comment by nhatkhai** [comment] 2020-05-19 14:14
Ops.. I left of the "lfs" in the commands I stated in the problems. So I re-edit it. Sorry for wasting your time.
I basically looking for a one uniform work around so it can work for tag, branch, and comit-SHA1 if possible. Otherwise, I will would be struggle to write addition script for detect tag, branch, or commit then apply the write one. So far the work around status for `git lfs fetch origin <ref>` are:
```
git lfs fetch origin branchA # Not Work
git lfs fetch origin origin/branchA # Work

git lfs fetch origin tagA # Work
git lfs fetch origin origin/tagA # Not Work

git lfs fetch origin 5b8cbb890 # Work
git lfs fetch origin origin/5b8cbb890 # Not Work
```
So look to me the only one on my way is the `git lfs fetch origin origin/branchA` make it not unifirm as tag, and SHA1 version.

**Comment by nhatkhai** [comment] 2020-05-19 14:33
Actually if I use `git show-ref origin <ref>` to get the SHA1, then I had a word around to work for all cases using the commit SHA1 like mention above.

**Comment by bk2204** [comment] 2020-05-19 15:19
Yeah, the second argument needs to be something in your local repository.  So that can be an actual branch, a remote tracking branch, a tag, any other ref, or an object ID, but it has to be local.

I'm pretty sure that `git show-ref origin <ref>` doesn't actually fetch the ref from the remote server.  It instead lists the refs `origin` (i.e., `refs/heads/origin`) and `<ref>` on your local machine.  If you want to know what the remote side has, you can use `git ls-remote` instead, but of course that won't work with `git lfs fetch` if you don't actually have that commit locally.

**Comment by nhatkhai** [comment] 2020-05-20 12:57
Thank @bk2204, `git ls-remote` is the best solution for working around.

**Comment by bk2204** [comment] 2020-05-20 19:34
Great.  Since this is working as intended and you have a workaround, I'm going to close this issue.

**Closed by bk2204** 2020-05-20 19:34 UTC
