### ISSUE TITLE
API rate limit exceeded

### ISSUE THREAD

**Issue by martyngigg** [git-lfs/git-lfs#2134] opened 2017-04-06 15:20 UTC
In the past couple of days I have started receiving the message

```
{"message":"API rate limit exceeded for 172.16.40.28. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}Error downloading object: bin/TKPrimd.dll (52b9d734b5ef817c848c0afb97668e017893f791f334fd9959c2dd469b07ed50)
```

when git lfs attempts to download the binary objects. This never used to be a problem. Has the rate been lowered so that we are unlucky and hitting this more often?

Output of `git lfs env`:

```
git-lfs/2.0.2 (GitHub; linux amd64; go 1.8)
git version 2.7.4

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=
LocalReferenceDir=
TempDir=/tmp/git-lfs
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
__GIT_PROMPT_IGNORE_STASH=
__GIT_PROMPT_SHOW_UPSTREAM=
__GIT_PROMPT_SHOW_UNTRACKED_FILES=all
__GIT_PROMPT_SHOW_CHANGED_FILES_COUNT=1
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

Full git log with `GIT_CURL_VERBOSE=1` is in [this gist](https://gist.github.com/martyngigg/f372f7ba5da6b07c8d7ef3fb9e61273f).

**Comment by technoweenie** [comment] 2017-04-07 14:45
The rate limit hasn't been lowered, but I'll have to double check. One workaround is setting the `lfs.<url>.access` git config setting, forcing a login.

```sh
$ git config lfs.https://github.com/OWNER/REPO.git/info/lfs.access basic

# real example
~g/git-lfs-test git:(master) ✗$ git config -l
lfs.https://github.com/github/git-lfs-test.git/info/lfs.access=basic
```

If you're using GitHub Enterprise, can you let me know what version you're on? Otherwise I'm assuming you're using GitHub.com.

**Comment by martyngigg** [comment] 2017-04-09 07:12
@technoweenie I am using github.com. Thanks for the workaround, I'll try it out.

**Comment by jonasmalacofilho** [comment] 2017-05-01 17:23
@martyngigg [I had similar issues around the same time](https://gist.github.com/jonasmalacofilho/aacf8230ab0e88b764016c60c5cb749d), but that since seemed to improve by itself.

Note that the IP reported as rate limited was the same...

**Comment by technoweenie** [comment] 2017-05-01 17:32
Closing this out. API rate limit has not changed. Unauthenticated rate limits across all of GitHub's API have been fairly low historically. Configuring a password or turning `lfs.access` to basic as I demonstrated in https://github.com/git-lfs/git-lfs/issues/2134#issuecomment-292556483 will give you the higher, authenticated rate limit.

**Closed by technoweenie** 2017-05-01 17:32 UTC

**Comment by jonasmalacofilho** [comment] 2017-05-01 17:39
I think you meant to link to [#2133 (comment)](https://github.com/git-lfs/git-lfs/issues/2133#issuecomment-292583445).

**Comment by lbergelson** [comment] 2017-05-23 18:33
@jonasmalacofilho  We also saw this exact same problem at the same time you did with the same IP ( 172.16.40.2)  address reported in the error messages.  It brought all of our work to a halt and then resolved on its own.  172.16.* is an address block reserved for [private network routing](https://www.arin.net/knowledge/address_filters.html), so I believe this must was probably caused by an internal error at github or one of their providers rather than being due to an actual increase in api requests.

**Comment by jonasmalacofilho** [comment] 2017-05-23 23:46
@lbergelson, I din't know about that range, thanks for the info!
