### ISSUE TITLE
LFS modifies files then they will not discard

### ISSUE THREAD

**Issue by RagtagShawn** [git-lfs/git-lfs#902] opened 2015-12-17 22:55 UTC
The scenario is something like this:
- Repo is partially pulled due to some network error or timeout
- LFS auto-modifies the local files due to them being set at tracked by LFS, but these files are old versions before LFS existed and was being used in this repo
- User doesn't want those modifications and tries to discard them so they can pull again and get up to date, but LFS just keeps modifying them so the discard does not work and the user cannot pull

How do I get around this so that my not savvy at git remote team member can just pull the repo and get up to date?

**Comment by technoweenie** [comment] 2015-12-20 22:24
I've seen two cases where Git will show an LFS file as modified without deliberate user action (such as changing and running `git add` on a file):

1. The index was damaged. Common if there's a network issue while downloading.
2. A file is being converted from a regular Git blob to a Git LFS pointer.

In the first scenario, running `git add` on the file should clear it up.

In the second scenario, you just have to commit the file or remove the appropriate pattern from the `.gitattributes` file. I really want a future Git LFS update to show that this is happening in the `git lfs status` output.

**Comment by svermeulen** [comment] 2016-04-10 19:34
I'm seeing this occur quite often on Windows.  I'm not sure how it gets into this state but I often find that there are files (with extensions that are tracked by LFS) that are spontaneously marked as modified.  And running `git clean -xdf` and `git reset --hard` don't have any effect. The files remain marked as modified.  Is there a way to get rid of these modified files other than committing them?

**Comment by technoweenie** [comment] 2016-04-11 14:11
We could update LFS to stop using `.gitattributes`, but it would require you to manually track every edit to every file in LFS. That's not something we're planning on adding.

You have two options now. Your best bet is to do a full conversion of all the LFS files in the repository. If you don't want to do that for some reason, you can remove them from `.gitattributes`. If you're only storing some files, but not all, you can use more specific paths like `this-dir/*.bigfile` instead of just `*.bigfile`.

**Comment by juan-cardelino** [comment] 2018-01-22 17:51
I'm observing the same issue on mac as well. My repo has 12Gb and this happens daily on a very stable network connection. We are considering droping git-lfs, because it is making it completely unreliable.

**Comment by ttaylorr** [comment] 2018-01-31 22:53
> I'm observing the same issue on mac as well. My repo has 12Gb and this happens daily on a very stable network connection.

The issue being that LFS only completes a pull partially, or that the files appear as modified after a pull? If the issue is the later, it can be fixed by running `git lfs migrate` 😄.

**Comment by jasonnyan** [comment] 2018-05-10 07:46
Hallo Folks,

Faced the same issue, also tried the above mentioned methods and failed, but I managed to find a way to fix for myself without having to commit:

Repro-steps: Undefined, I get this problem @ 1/100 probability after a regular Pull, and it only happens to newly added files to lfs, which can be added by myself or my collaborators.
Suspect: Broken Index
Workaround: (1) Stage the problematic files, there's no need to commit! (2) Hard Reset to any arbitrary changeset that's not the current changeset (3) Now, Hard Reset back to the initial changeset again

I cannot explain the underlying principles, so if any insiders can explain, please share with us.

Hope it works for you too! ;)

**Comment by lidiamartinez** [comment] 2019-01-25 13:54
Hi there. I found another solucion. This is a bug, I suspect. I use submodules, and this is a 3rd level submodule:

- Go to lfs settings for the repo. Remove the file type this file has.
- You will see a change in a hidden properties file
- Perform a pull on the parent repository
- Go back and discard the change to that file

The file will not come up again.

**Comment by Polo3cat** [comment] 2019-06-06 12:58
> Hi there. I found another solucion. This is a bug, I suspect. I use submodules, and this is a 3rd level submodule:
> 
>     * Go to lfs settings for the repo. Remove the file type this file has.
> 
>     * You will see a change in a hidden properties file
> 
>     * Perform a pull on the parent repository
> 
>     * Go back and discard the change to that file
> 
> 
> The file will not come up again.

I had a large file staged for commit, stashed it and then couldn't pop anymore because of conflicts. The solution fixes the popping of the stash. Then I had to repeat the steps to remove it from the tree.

**Comment by jgod** [comment] 2020-11-10 19:55
> In the second scenario, you just have to commit the file or remove the appropriate pattern from the `.gitattributes` file.

This is the only thing that worked for me.

**Comment by bk2204** [comment] 2020-11-10 20:25
Hey,

This is because the file in question is marked as being an LFS file but has actually been committed as a large file in Git without Git LFS.  Usually this happens because a contributor to the project did not have Git LFS installed or had not run `git lfs install` when they committed it.  The proper way to fix this going forward is to make sure your working directory is otherwise clean, run `git add --renormalize .`, and then commit.

This isn't really avoidable with the way that Git works, so the only way to address it is to fix the files or rewrite the history so all the large files are properly turned into LFS objects.  Since there isn't a way we can fix this, I'm going to close this.

**Closed by bk2204** 2020-11-10 20:25 UTC

**Comment by reinerzer** [comment] 2025-10-30 10:41
> > In the second scenario, you just have to commit the file or remove the appropriate pattern from the `.gitattributes` file.
> 
> Thank you, nothing else worked. Didn't want to commit the lfs file, so removing from `.gitattributes`, resetting file to HEAD, and stash+drop `.gitattributes` was the only way for me to get back to clean.

Thank you! <3
