### ISSUE TITLE
Git lfs pull or fetch not executing 

### ISSUE THREAD

**Issue by VioletteM** [git-lfs/git-lfs#4360] opened 2021-01-07 20:07 UTC
Hi, i am quite new to using git and git lfs. i have been running git lfs pull//fetch on a cloned repo with the latest git lfs version, i can git lfs ls-files and see them all but the git lfs pull command runs for a while and eventually times out without executing (see below photo). Thank you...your help is appreciated!!

![lfspullissue](https://user-images.githubusercontent.com/67260599/103939065-ddb8f480-5133-11eb-91db-7948418de194.PNG)

i am running this on a ubuntu 18.04.5 lts server, with git version 2.30.0 and git lfs version 2.13.1

my output for git config -l 
![conf](https://user-images.githubusercontent.com/67260599/103939123-f6290f00-5133-11eb-9195-33514dbbf30b.PNG)

my output for git lfs env
![env](https://user-images.githubusercontent.com/67260599/103939158-080ab200-5134-11eb-8009-0f01bb1bbac7.PNG)

**Comment by bk2204** [comment] 2021-01-07 20:18
Hey, 

Sorry to hear you're having trouble.  Could you run the command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and either post or attach the output (as a text file) here?  That should tell us more about the problem that's occurring.

**Comment by VioletteM** [comment] 2021-01-07 22:10
This is the output i'm getting.

$ GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git lfs pull
00:06:49.441059 git.c:730               trace: exec: git-lfs pull
00:06:49.441112 run-command.c:664       trace: run_command: git-lfs pull
00:06:49.444494 trace git-lfs: exec: git 'version'
00:06:49.445841 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
00:06:49.447042 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
00:06:49.448152 trace git-lfs: exec: git 'config' '-l'
00:06:49.449140 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
00:06:49.450182 trace git-lfs: exec: git 'config' '-l' '--blob' ':.lfsconfig'
00:06:49.451303 trace git-lfs: exec: git 'config' '-l' '--blob' 'HEAD:.lfsconfig'
00:06:49.452440 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
Could not pull
00:06:49.453684 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
00:06:49.454844 trace git-lfs: Error loading current ref: Git can't resolve ref: "HEAD"
00:06:49.454918 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote'
00:06:49.455988 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote'

Errors logged to /home/vmahoro/.git/lfs/logs/20210108T000649.453497779.log
Use `git lfs logs last` to view the log.

**Comment by bk2204** [comment] 2021-01-07 22:22
Can you include that log file as well, please?

**Comment by VioletteM** [comment] 2021-01-08 14:00
Ran the command again before checking the logs and it produced this output. Please bear with me as it is a work project hence the use of asterisks on the file paths. Looks like am able to pull the files now. Am just wondering if everytime i have to update my branch i have to run the whole or just "git lfs pull".

$ GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git lfs pull
13:35:40.115156 git.c:730               trace: exec: git-lfs pull
13:35:40.115198 run-command.c:664       trace: run_command: git-lfs pull
13:35:40.118532 trace git-lfs: exec: git 'version'
13:35:40.121669 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
13:35:40.122814 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
13:35:40.123932 trace git-lfs: exec: git 'config' '-l'
13:35:40.124994 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
13:35:40.126067 trace git-lfs: exec: git 'config' '-l' '--blob' ':.lfsconfig'
13:35:40.127239 trace git-lfs: exec: git 'config' '-l' '--blob' 'HEAD:.lfsconfig'
13:35:40.128607 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
13:35:40.129812 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
13:35:40.131142 trace git-lfs: tq: running as batched queue, batch size of 100
13:35:40.131271 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'ls-tree' '-r' '-l' '-z' '--full-tree' '279fbee8f8dda669a8ba754de6ae6ffb2d786f02'
13:35:40.131477 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-common-dir'
13:35:40.132917 trace git-lfs: filepathfilter: accepting ".gitattributes"
13:35:40.133031 trace git-lfs: filepathfilter: accepting ".here"
13:35:40.133083 trace git-lfs: filepathfilter: accepting "*************************************.xlsx"
13:35:40.133122 trace git-lfs: filepathfilter: accepting "*************************************.csv"
13:35:40.133131 trace git-lfs: filepathfilter: accepting "*************************************.dta"
13:35:40.133168 trace git-lfs: filepathfilter: accepting "*************************************.csv"
13:35:40.133177 trace git-lfs: filepathfilter: accepting "*************************************.dta"
13:35:40.133184 trace git-lfs: filepathfilter: accepting "*************************************.dta"
13:35:40.133191 trace git-lfs: filepathfilter: accepting "*************************************.csv"
13:35:40.133234 trace git-lfs: filepathfilter: accepting "*************************************.dta"
13:35:40.133242 trace git-lfs: filepathfilter: accepting "*************************************.dta"
13:35:40.133249 trace git-lfs: filepathfilter: accepting "*************************************.dta"
13:35:40.133255 trace git-lfs: filepathfilter: accepting "*************************************.csv"
13:35:40.133262 trace git-lfs: filepathfilter: accepting "*************************************.csv"
13:35:40.133312 trace git-lfs: filepathfilter: accepting "*************************************.csv"
13:35:40.133320 trace git-lfs: filepathfilter: accepting "*************************************.csv"
13:35:40.133327 trace git-lfs: filepathfilter: accepting "*************************************.csv"
13:35:40.133341 trace git-lfs: filepathfilter: accepting "*************************************.csv"
13:35:40.133349 trace git-lfs: filepathfilter: accepting "*************************************.dta"
13:35:40.133356 trace git-lfs: filepathfilter: accepting "*************************************.dta"
13:35:40.133399 trace git-lfs: filepathfilter: accepting "*************************************.csv"
13:35:40.133407 trace git-lfs: filepathfilter: accepting "*************************************.csv"
13:35:40.133413 trace git-lfs: filepathfilter: accepting "*************************************.dta"
13:35:40.133420 trace git-lfs: filepathfilter: accepting "**********/.gitattributes"
13:35:40.133426 trace git-lfs: filepathfilter: accepting "*************************************csv"
13:35:40.133442 trace git-lfs: filepathfilter: accepting "*************************************.dta"
13:35:40.133487 trace git-lfs: filepathfilter: accepting "*************************************.csv"
13:35:40.133496 trace git-lfs: filepathfilter: accepting "*************************************.dta"
13:35:40.133503 trace git-lfs: filepathfilter: accepting "markdown/*****.md"
13:35:40.133510 trace git-lfs: filepathfilter: accepting "markdown/*****.md"
13:35:40.133562 trace git-lfs: filepathfilter: accepting "markdown/****.md"
13:35:40.133570 trace git-lfs: filepathfilter: accepting "markdown/****.md"
13:35:40.133579 trace git-lfs: filepathfilter: accepting "markdown/*****.md"
13:35:40.133586 trace git-lfs: filepathfilter: accepting "markdown/****.md"
13:35:40.133592 trace git-lfs: filepathfilter: accepting "markdown/*****.md"
13:35:40.133650 trace git-lfs: filepathfilter: accepting "markdown/*****.md"
13:35:40.133663 trace git-lfs: filepathfilter: accepting "rsconnect/*************************************.dcf"
13:35:40.133673 trace git-lfs: filepathfilter: accepting "rsconnect/*************************************.dcf"
13:35:40.133680 trace git-lfs: filepathfilter: accepting "rsconnect/*************************************.dcf"
13:35:40.133739 trace git-lfs: filepathfilter: accepting "shapefiles/rwa_adm2_2006_NISR_WGS1984_20181002.shx"
13:35:40.133503 trace git-lfs: fetch *************************************.xlsx [048bd1a9dc77d1805ded32fd5eecb2057ac29c95320300b72da8abc25387a537]
13:35:40.133944 trace git-lfs: fetch *************************************.csv [872e8fd27111a3458ccd44e1eb5e1ff4391990810a92580fc4335ecfddb5c9c9]
13:35:40.134053 trace git-lfs: fetch *************************************.dta [ed6de8a78b05c411c6ffb9d2cbcb4d16b0d230c94f235ed1d4eee2ef467fffa7]
13:35:40.134167 trace git-lfs: fetch *************************************.csv [7ec3b08319327265ee5d5bd2cf5b192b70f62d72e0538bb1e854ddf29c8a6cc0]
13:35:40.134259 trace git-lfs: fetch *************************************.dta [4019e6d9733a6fb3a29407d4a07fd593f046a9e082cbb190da0ca40ade38ca47]
13:35:40.134351 trace git-lfs: fetch *************************************.dta [dd1b6408f5a192f837ee08a1da1f2a33080dbbcff7453972a5595580691fde2c]
13:35:40.134449 trace git-lfs: fetch *************************************.csv [249774a11f0ec5e8dc07184d302a136d2484e319ed5ced25b6077b15c0125c1f]
13:35:40.134555 trace git-lfs: fetch *************************************.dta [41b844ef175523540beff36fa9162a4b14fb41e423e3c26ddbe4da9333357f62]
13:35:40.134661 trace git-lfs: fetch *************************************.dta [fd7d6a68aea5f6d92f948bfb92dafad1734b844cfef422966323bbf14a1b5fb0]
13:35:40.134790 trace git-lfs: fetch *************************************.dta [529f8f1972ecbe8e25557d44a607a18c0bb88e6d44b4504e06334a0aaee7d07c]
13:35:40.134881 trace git-lfs: fetch *************************************.csv [7761a893d18b20dd634db66570c81af85e736b9d96ecee95d124d13b635c9078]
13:35:40.134973 trace git-lfs: fetch *************************************.csv [9499d4b812b9ca51e75ba3eb90896c1d3d97ef943179edec3ae1d89a524468d9]
13:35:40.135058 trace git-lfs: fetch *************************************.csv [4e738d7208c3154ca90b6dc2879a911c62716fb08fbf5ea05e21a2ff6d46a42c]
13:35:40.135120 trace git-lfs: fetch *************************************.csv [d4976964aee9dc7d7ca4ef1e375beb6d44d8f3263d98a34fcfd16805ec078f46]
13:35:40.135439 trace git-lfs: fetch *************************************.csv [da31d1fafba2f481a07071709ff40cbce10e50e64cb18c81d9ebf6ee87338c1a]
13:35:40.135919 trace git-lfs: fetch *************************************.csv [87976221a19ab5b4b4d42a3c31d053bd5eb61a7dce3a87cd392141a762813a90]
13:35:40.136028 trace git-lfs: fetch *************************************.dta [91184ad3775ff792f014f4c3a2ae96752fd52d61481ced4e6cb6d8513fba166f]
13:35:40.136125 trace git-lfs: fetch *************************************.dta [1b84632bfa088cae7b5eb57de34718f1dfd3aa6101a87450202349dd37e22959]
13:35:40.136220 trace git-lfs: fetch *************************************.csv [c3590c27f25d3aa3517ec01f542fcf59ce6edb89ca9c380d39c0e2f01371c7e0]
13:35:40.136308 trace git-lfs: fetch *************************************.csv [fed2247044b640ff3389bfec567d4a3a0fd9d5a359e575ee34e4b8ef8132754c]
13:35:40.136400 trace git-lfs: fetch *************************************.dta [523985611765ea22a40717d1f2f863173a3c01761de0c66e6884ac76416f833c]
13:35:40.136498 trace git-lfs: fetch *************************************.csv [135b761d3a0437ca375e94e52d8fd31e78c01a14fcd75592d740ba30550d3a55]
13:35:40.136591 trace git-lfs: fetch *************************************.dta [70c4eb2502de388e9fcc83f3676d2cf1e087a8ac0a6e90989130f93182f010c2]
13:35:40.136683 trace git-lfs: fetch *************************************csv [998af8a445e2e17754f5679bd7958258a4e755c25588e51e955babf390fa1d8b]
13:35:40.136777 trace git-lfs: fetch *************************************.dta [78aadd5b6d602806532bcddc1caf29b2f2a65c5a62c1036da2a9e3ca02558c06]
13:35:40.136874 trace git-lfs: tq: sending batch of size 25
13:35:40.137336 trace git-lfs: api: batch 25 files
13:35:40.137523 trace git-lfs: creds: git credential fill ("https", "github.com", "")
13:35:40.138415 git.c:444               trace: built-in: git credential fill
13:35:40.138518 run-command.c:664       trace: run_command: 'git credential-wincred get'
13:35:40.139927 git.c:730               trace: exec: git-credential-wincred get
13:35:40.139960 run-command.c:664       trace: run_command: git-credential-wincred get
git: 'credential-wincred' is not a git command. See 'git --help'.
13:35:40.141937 run-command.c:664       trace: run_command: 'git credential-manager get'
13:35:40.143418 git.c:730               trace: exec: git-credential-manager get
13:35:40.143514 run-command.c:664       trace: run_command: git-credential-manager get
git: 'credential-manager' is not a git command. See 'git --help'.
Username for 'https://github.com': VioletteM
Password for 'https://VioletteM@github.com':

**Comment by bk2204** [comment] 2021-01-08 14:54
Hey,

This output just shows that it's determining what needs to be downloaded.  If you're seeing the hang when it's downloading files, the information I need is the information after the username and password prompt, since that's the data that shows what's being transferred and why it would be hanging.  There's probably enough of it that you'll want to attach a text file.

If you're seeing a crash of some sort, the logs are still helpful.

**Comment by VioletteM** [comment] 2021-01-08 17:06
This is the output after logging in. it's so long (runs for quite some time), i just copied the first few lines.

[output.txt](https://github.com/git-lfs/git-lfs/files/5788400/output.txt)

It runs but due to slow network it breaks but no crash of any sort. Also they were no logs to show when i ran the "git lfs logs last" command.

**Comment by bk2204** [comment] 2021-01-08 18:04
Okay, it looks like the problem is that we're waiting on the first thread to respond, which means that this could be some sort of problem connecting to the remote server.  Are you on a network with a proxy or some sort of filtering that prevents access to Amazon S3?

**Comment by VioletteM** [comment] 2021-01-08 19:15
There's no filtering set on this server. Also i was able to clone the repo and fetch the files just fine locally on my computer on the same network. Not sure what's preventing access but i access the internet while on the server just fine. Any suggestions on how i can have that resolved?

**Comment by bk2204** [comment] 2021-01-08 19:51
I'm not sure.  It seems like some sort of network problem, so I'd ask whomever is in charge of that network, or try standard network debugging attempts (ping, traceroute, etc.).  It doesn't seem like a problem with the Git LFS client itself, though.

**Comment by VioletteM** [comment] 2021-01-11 08:03
Alright, thank you very much for your assistance. Will have it resolved internally.

**Comment by bk2204** [comment] 2021-01-11 15:21
Sorry I couldn't be of more help, and hope you get things sorted out.

**Closed by bk2204** 2021-01-11 15:21 UTC
