### ISSUE TITLE
Git LFS fails to resolve pointers in --branch clones

### ISSUE THREAD

**Issue by RPGillespie6** [git-lfs/git-lfs#5447] opened 2023-08-02 16:26 UTC
**Describe the bug**
If I clone my repo with:

```
git clone --branch v2.3.1 git@bitbucket.org:myproject/myrepo.git
```

Then none of the LFS pointers are resolved unless I subsequently run `git lfs pull` from within the repo. If I do a full clone and then checkout `v2.3.1`, then all pointers are resolved. 

How to reproduce:

```
git clone --branch=v1.0 git@github.com:RPGillespie6/lfs-branch-bug.git
```

Note that `hello.txt` in cloned repo is still an LFS pointer

However, if you instead do :
```
git clone git@github.com:RPGillespie6/lfs-branch-bug.git
git checkout v1.0
```

Then the LFS pointer is resolved.

Link to repro repo: https://github.com/RPGillespie6/lfs-branch-bug

Other potentially important context: 
- Note that `.gitattributes` is missing on the `v1.0` ref yet the file is still tracked by LFS
- This situation arises when using [bfg-repo-cleaner](https://github.com/rtyley/bfg-repo-cleaner) to convert historical files to LFS

**Comment by bk2204** [comment] 2023-08-02 17:21
Hey,

I think this is working as designed.  A file is considered tracked by LFS if and only if `.gitattributes` has `filter=lfs` defined as a pattern for the file.  So in `v1.0`, the file isn't actually tracked by LFS, and it's not considered an LFS file.

The reason that Git invokes Git LFS to check files out is because the `filter=lfs` attribute is present, so without that configuration, Git can't know that the file is supposed to be an LFS file, and it doesn't even invoke Git LFS.  Thus, there's nothing we can do to change this situation, since Git LFS isn't even invoked by Git.

As such, I'm going to close this issue, since we can't change how it works.  If you need Git LFS invoked, the `.gitattributes` configuration is obligatory.

**Closed by bk2204** 2023-08-02 17:21 UTC

**Comment by RPGillespie6** [comment] 2023-08-02 17:32
Got it, so I have to explicitly run `git lfs pull` on historical commits that don't have `.gitattributes` in order to resolve the pointers?

How is it that cloning the repository and checking out `v1.0` results in the pointers being resolved without needing to run `git lfs pull`?

**Comment by bk2204** [comment] 2023-08-03 13:16
The `gitattributes(5)` documentation mentions this:

> When the `.gitattributes` file is missing from the work tree, the path in the index is used as a fall-back. During checkout process, `.gitattributes` in the index is used and then the file in the working tree is used as a fall-back.

So in that case, there's no `.gitattributes` file in the index, but there is one in the working tree, so that's used as a fallback.  If you checked out `v1.0` while on `v2.0` that also had no `.gitattributes` file, you'd also find that Git LFS was not invoked.
