### ISSUE TITLE
Git clone freezes indefinitely without errormessage

### ISSUE THREAD

**Issue by arndtp** [git-lfs/git-lfs#4480] opened 2021-04-14 10:20 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.28.0.windows.1
cpu: x86_64
built from commit 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

also tested on gitversion: 
2.24.1
2.26.1
2.27.0
2.29.0
2.31.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.19042.906]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

install-options.txt:
```
Editor Option: Notepad++
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```
system gitconfig:
```
[diff "astextplain"]
	textconv = astextplain
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[http]
	sslBackend = openssl
	sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
[core]
	autocrlf = false
	fscache = true
	symlinks = true
	editor = \"C:\\\\Program Files (x86)\\\\Notepad++\\\\notepad++.exe\" -multiInst -notabbar -nosession -noPlugin
[pull]
	rebase = false
[credential]
	helper = manager
```

global .gitconfig:
```
[http]
	sslVerify = false
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The repository is hosted on a self-hosted gitlab-server. We also tried copying it to the Azure DevOps-Cloud but it did not help the issue.
The repository contains 6397 LFS-files.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone git@git.pdv-software.de:pdv-software/entwicklung.net.git
```
 - What did you expect to occur after running these commands?

successful clone of the repository

 - What actually happened instead?

During the steps "updating files" or "filtering content" the process freezes without any errormessage. The freeze is indefinite. We let it run over night without any progress. The repository is missing most of the LFS-files when the freeze happens.
The freeze doesn't occur everytime and it's also not deterministic at which time/percentage it's freezing.
When we exit the console the git-lfs process does not exit properly, we need to terminate it via the task-manager.
If you need logs we can provide the ones you need. 

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It's a private repository, we cannot give you access to it.

---

We're using the included LFS-version of the git-for-windows installer.

**Output of `git lfs env`**
```
git-lfs/2.13.3 (GitHub; windows amd64; go 1.16.2; git a5e65851)
git version 2.31.1.windows.1
```
in working git-repository:  
[...]
```
Endpoint=https://git.pdv-software.de/pdv-software/entwicklung.net.git/info/lfs (auth=none)
  SSH=git@git.pdv-software.de:pdv-software/entwicklung.net.git
LocalWorkingDir=D:\Entwicklung\Entwicklung.Net
LocalGitDir=D:\Entwicklung\Entwicklung.Net\.git
LocalGitStorageDir=D:\Entwicklung\Entwicklung.Net\.git
LocalMediaDir=D:\git\lfs\objects
LocalReferenceDirs=
TempDir=D:\git\lfs\tmp
ConcurrentTransfers=4
TusTransfers=false
BasicTransfersOnly=true
SkipDownloadErrors=true
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:/git/lfs/
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

---

We already tried to log the `GIT_LFS_PROGRESS`, using the `Git CMD` instead of the `Git Bash` and tested some git-lfs config options according to suggestions made under the [Git-for-windows issue](https://github.com/git-for-windows/git/issues/3173) without any noticeable success.

**Comment by bk2204** [comment] 2021-04-14 15:07
Hey,

Can you run this command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and, once you've gotten it to hang, attach the trace from the hanging run here as a text file?

**Comment by bk2204** [comment] 2021-04-15 19:23
Hmmm, okay.  This isn't what I was expecting; here it looks like we're processing files to add to the queue and we just stop at some point.  We'd also expect to see "tq: sending batch of size 100" as soon as we have 100 items, but we don't, and I don't see any reason we shouldn't be seeing that, since we have well over 300 items.

Do you see this only on Windows?  Have you tried other operating systems, and if so, do they also experience the problem?  I'm trying to figure out if this is maybe related to something like an antivirus interfering with thread scheduling, or maybe a bug in the Go scheduler for Windows, versus a latent bug that we have that only seems to trigger on this repository (which is certainly possible), since we haven't seen any other reports of this type of thing.  For example, could you try this with the same version of Git LFS on a Linux system or under WSL 2 to see if this is a more general problem with this repository?

**Comment by arndtp** [comment] 2021-04-16 07:58
Here is the [log.txt](https://github.com/git-lfs/git-lfs/files/6323361/log.txt)-file of the run on a Linux system.  
The run stuck at 16%

**Comment by arndtp** [comment] 2021-04-16 08:04
Here is a screenshot of the console.

 ![Linux Git freeze](https://user-images.githubusercontent.com/82498658/114992133-b1cbae80-9e9a-11eb-8a32-7b2e4bb3908b.JPG)

**Comment by bk2204** [comment] 2021-04-16 13:45
Hey,

Can you include the output with `GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` as well as part of the log file from Linux?  The log itself doesn't seem to contain that information and it's very helpful to include that so we can see what's going on, since I think that's relevant to the problem.  If you're not sure how to capture it, you can do so with `script`, which will write a file called `typescript` in the current directory:

```
GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 \
  script -c 'git clone git@git.pdv-software.de:pdv-software/entwicklung.net.git'
```

**Comment by arndtp** [comment] 2021-04-19 14:22
Hey, 
sry for the delay. Here is the requested log-file.
[typescript](https://github.com/git-lfs/git-lfs/files/6336701/typescript.txt)

**Comment by bk2204** [comment] 2021-04-19 16:41
Hey,

The problem is that your DNS configuration is broken.  This message repeats in the log multiple times:

```
batch response: Post "https://git.pdv-software.de/pdv-software/entwicklung.net.git/info/lfs/objects/batch": dial tcp: lookup git.pdv-software.de on 192.168.65.5:53: read udp 172.17.0.2:44929->192.168.65.5:53: i/o timeout
```

That means that your DNS requests are timing out, which is preventing fetching the files.  You'd need to fix whatever is causing your DNS to be broken.

**Comment by arndtp** [comment] 2021-04-21 06:37
Hey,

As it turns out, the first linux machine didn't get the same error, it just asked for the git credentials again because there was no credential manager. We misinterpreted that as a freeze because there was no console output asking for said credentials. As for the provided logs, those came from an ubuntu docker container which caused the DNS Problems, that doesn't seem to be connected to the initial problem. 

We conclude that the Problem exclusively occurs on windows environments.

**Comment by bk2204** [comment] 2021-04-21 13:40
Okay.  Are you using an antivirus or firewall other than the system default (the defaults being Windows Defender and Windows Firewall) or other security monitoring software?  We do frequently see those as a cause of problems for Git and Git LFS.  If so, could you try completely uninstalling it and rebooting and then trying again?

**Comment by arndtp** [comment] 2021-04-23 07:06
We tested on some systems if stopping the antivirus fixes the problem - successfully. It seems like the antiviruses real-time monitoring of the cloned files randomly freezes the process.  
We will keep testing this symptom to find a way fixing it.

**Comment by bk2204** [comment] 2021-04-26 13:54
Great, it sounds like we've found the problem.  Since this is a problem with a misbehaving antivirus, I'm going to close this, but if you could, please mention which one it is so we know for future reference.

**Comment by arndtp** [comment] 2021-04-26 14:07
Thanks for the help!

**Closed** 2021-06-11 13:32 UTC
