### ISSUE TITLE
LFS Locks block rebase/cherry-pick of the locked files last version on another branch

### ISSUE THREAD

**Issue by Murazaki** [git-lfs/git-lfs#5573] opened 2023-11-16 15:01 UTC
**Describe the issue**
If you have a feature branch with locked files, you can't rebase it in the integration branches unless they are unlocked

**System environment**
OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631

**Output of `git lfs env`**
```
git-lfs/3.4.0 (GitHub; windows amd64; go 1.20.6; git d06d6e9e)
git version 2.42.0.windows.2

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=0
PruneVerifyRemoteAlways=true
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by chrisd8088** [comment] 2023-11-21 07:22
Hey, I'm sorry you're having trouble.

I suspect this may in part relate to which LFS hosting service you are using.  GitHub, for instance, has not implemented the optional "ref-aware" portions of the locking protocol, so all locks are identified strictly by file path, rather than path+ref.  (See PR #5538 for some recent discussion of this and the history behind it.)

Would you be able to provide a short reproduction example, for reference?

**Comment by chrisd8088** [comment] 2023-12-12 22:15
> You should get the blocking behavior there, while LFS behavior on rebase should have maintained the value of the file at the state of the lock

While I can't speak to GitLab's behaviour, I can perhaps clarify that Git LFS locks are [identified](https://github.com/git-lfs/git-lfs/blob/6c94277c6c725b1c72c211dc9f145e37c0e0bcad/docs/api/locking.md#create-lock) by path (plus an optional ref, _if_ the LFS hosting service has implemented that extension to the API), so I'm not sure that this will permit the use case you have in mind.

Once you take the lock, it's applied to the file's path, regardless of its contents.  (If the hosting service also provides ref-aware locks, the lock will also be scoped to the current ref in which it was taken, and as I said before, that might help with your scenario.)  But at least with GitHub, and perhaps GitLab as well, the lock is scoped just to the path, so it will apply regardless of the ref or the file contents.

I have a test repo set up on GitHub where another user has made changes to an LFS-managed file in a branch, committed and pushed that change, and has locked the file, e.g.:
```
# As user A, changing an existing LFS-managed file foo.bin
$ git checkout -b feature
$ echo foo2 >foo.bin
$ git add foo.bin
$ git commit -m foo2
$ git push origin feature
$ git lfs lock foo.bin
```

As another user, I've tried the following and they have all succeeded.

```
# As user B
$ git checkout main
$ git fetch
$ git lfs locks
foo.bin      <user-a> ID:...

$ git rebase origin/feature
Successfully rebased and updated refs/heads/main.

$ git reset --hard HEAD^

$ git merge origin/feature
Updating 2f05123..d5e276a
Fast-forward
 foo.bin  | ...
```

So I haven't been able to reproduce what you're seeing, but maybe I don't understand what you mean by "rebase and merge branch".

If you can provide an really explicit set of steps, and maybe the output of the "blocking" command when run with `GIT_TRACE=1`, that might help explain what you're encountering.

**Comment by bk2204** [comment] 2024-05-08 15:13
Hey,

Since we haven't been able to reproduce this and there's no additional information here, I'm going to close this.  If you can provide suitable reproduction steps, we can reopen this.

**Closed by bk2204** 2024-05-08 15:13 UTC
