### ISSUE TITLE
Powershell/CMD crash on push with GfW 2.14.2

### ISSUE THREAD

**Issue by csmager** [git-lfs/git-lfs#2631] opened 2017-09-29 08:29 UTC
I recently updated to Git for Windows 2.14.2 and have noticed that both PowerShell and CMD both quit after calling `git push` or after closing vim on doing an interactive rebase (e.g `git rebase -i HEAD^^`).

I can also replicate a quit by simply `git lfs push origin master`. And running `git lfs logs last` afterwards shows `No logs to show'.

I am seeing this issue on both Windows 10 and Windows 7.

I'm not sure where exactly the problem lies, but rolling back to GfW 2.14.1 or removing the git LFS hooks (`git lfs uninstall`) both seem to 'cure' the problem.

**Comment by technoweenie** [comment] 2017-10-02 21:10
Are there any detailed logs that you can pull up? I don't work on Windows, so I'll need some help figuring this out.

@sschuberth Do you have any thoughts?

**Comment by sschuberth** [comment] 2017-10-03 07:03
I just have it a quick try but was unable to reproduce it (GfW 2.14.2, Git LFS 2.3.0, Windows 10 64-bit).

**Comment by csmager** [comment] 2017-10-03 07:04
Do you know where I could look for logs that might help with this? As I said, there's nothing returned by `git lfs logs last`. I think I checked Event Viewer and saw nothing interesting either.

**Comment by sschuberth** [comment] 2017-10-03 07:41
Correction, I'm able to reproduce it now. In my first test I've simple forgotten to install the LFS hooks :-/ However, I don't have time to look into it right now.

**Comment by csmager** [comment] 2017-10-03 07:44
I've found a bug report in the GfW repo (https://github.com/git-for-windows/git/issues/1312) related to git subrepo - given two different reports, it's possible an issue in GfW rather than git lfs

**Comment by sschuberth** [comment] 2017-10-03 07:45
However, one thing I've realized is that the editor for interactive rebase is only populated with one commit, whereas it should be two commits for `HEAD^^` (at that's what it is for Git Bash).

**Comment by sschuberth** [comment] 2017-10-04 06:08
> whereas it should be two commits for `HEAD^^` (at that's what it is for Git Bash).

I just realized that's unrelated as `cmd`'s escape character is `^`, so for `HEAD^^` Git only sees `HEAD^`.

**Comment by dscho** [comment] 2017-10-04 23:58
I think I found the bug, it was something introduced into Cygwin v2.9.0 (and fixed in Cygwin's `master`), but as it had not made it into any Cygwin release, I did not yet notice. Please find more details as well as the progress at git-for-windows/git#1312.

**Comment by ttaylorr** [comment] 2017-12-19 17:14
It looks like this was fixed by @dscho in https://github.com/git-for-windows/MSYS2-packages/commit/e9d0a2be2720007c2a734866ebbb4c15e503003c, so I'm going to close this for now 😄 .

@dscho: Thanks!

**Closed by ttaylorr** 2017-12-19 17:14 UTC
