### ISSUE TITLE
After clone,it's stuck here, why is that?

### ISSUE THREAD

**Issue by moHen-github** [git-lfs/git-lfs#5602] opened 2023-12-29 16:14 UTC
Hello, I encountered some issues while using git lfs:

After re operating, I entered the command:
Git clone XXXXXX,
But it's stuck here, why is that：

<img width="605" alt="image" src="https://github.com/git-lfs/git-lfs/assets/142018482/b33037ad-a6a8-4443-abd0-7387243b39ff">

If you need the output of git lfs env to help determine, the following is:

<img width="397" alt="image" src="https://github.com/git-lfs/git-lfs/assets/142018482/4e3291ae-8596-4d38-87d1-a8d4d6bf324c">

Looking forward to your reply.

**Comment by chrisd8088** [comment] 2023-12-30 05:45
Hey, I'm sorry you're having trouble.  This sounds like a duplicate of #5600, but I don't know if you're still trying to use `gitclone.com` or if you're contacting GitHub and AWS S3 directly.

You can add `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` before your `git clone` command to get detailed logs which will show the HTTP requests being made; that might help identify if there is one which is slow or stuck.

I suspect this is just a network issue between your client and GitHub or AWS S3, and there's not much we can advice we can provide, as this project is just for the Git LFS client software.  You may need to contact GitHub Support if there's a particular repository you want to clone and it's not available in your region.

**Comment by bk2204** [comment] 2024-05-08 15:30
Hey,

Since I think this is a duplicate and it's already been answered, I'm going to close this.

**Closed by bk2204** 2024-05-08 15:30 UTC
