### ISSUE TITLE
Git-lfs installing more recent version did not overwrite "git lfs" command

### ISSUE THREAD

**Issue by Kryofenix** [git-lfs/git-lfs#2612] opened 2017-09-25 08:02 UTC
Observed problem: I have installed git-lfs 2.3 however running "git lfs version" returns the older version. The discrepancy is that using "git-lfs" correctly points to the new version, but not "git lfs". 

Seems related to or duplicate of https://github.com/git-lfs/git-lfs/issues/2587

See below:
$ git-lfs version
git-lfs/2.3.0 (GitHub; windows amd64; go 1.8.3; git 4dd2bf73)
$ git lfs version
git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f82)

Repro steps:
* On a clean windows, install git 2.14.1 (latest today), leave the LFS option on. This installs the bundled version of git lfs (2.2.1).
* Install git-lfs 2.3.0
* Observe the problem

**Comment by technoweenie** [comment] 2017-09-26 19:00
The LFS installer used install to `C:\Program Files\Git\mingw64\bin`, but it turned into a wild guessing game of where Git _could_ be installed. The installer was updated to install to `C:\Program Files\Git LFS`, and add itself to the PATH, which helped solve these PATH related issues.

It sounds like bundling LFS with the Git for Windows installer has brought it back. I think the fix is teaching the Git for Windows installer to set `GIT_LFS_PATH` in the environment after installation. The LFS installer will use that instead of the `C:\Program Files\Git LFS` default. As a workaround, you can probably set this yourself to `C:\Program Files\Git\mingw64\bin` (or wherever your original `git-lfs.exe` was installed), so future LFS updates know where to go.

**Comment by sschuberth** [comment] 2017-09-26 19:33
@technoweenie, that sounds about right, except that I cannot find any code in the existing Git LFS Inno Setup installer that would make it install to `GIT_LFS_PATH` if that variable is set.

**Comment by technoweenie** [comment] 2017-09-26 21:32
Ah you're right, it's just _setting_ that value.

**Comment by 92161898515** [comment] 2017-09-26 21:34
É isso mesmo
--
Enviado da aplicação Mail.Ru para Android terça-feira, 26 setembro 2017, 06:33da tarde -03:00 de risk danger olson  notifications@github.com :

**Comment by sschuberth** [comment] 2017-09-27 06:24
Also, I'm closing this as a duplicate of #2587 where we already started the discussion about possible solutions.

**Closed by sschuberth** 2017-09-27 06:24 UTC
