### ISSUE TITLE
Removing bad LFS object references from origin

### ISSUE THREAD

**Issue by ilienert** [git-lfs/git-lfs#3245] opened 2018-09-12 09:15 UTC
Hello,

My organization is running some nightly backups of our LFS-backed git repo which ping IT with a big fat "FAILED" message whenever an error is thrown in the process.

Currently, we have a missing LFS object on the server, which always causes problems whenever calling git lfs fetch --all in the backup. The error is: `[e70f2f6f92ac50774e87160ee70c163607f69f49518fde060731b28a38a88ca8] Object does not exist on the server: [404] Object does not exist on the server`.

In [this comment](https://github.com/git-lfs/git-lfs/issues/1935#issuecomment-419578704), you recommend two solutions: 1) Using 'git migrate export' and 2) 'git filter-
branch'.

Could you describe a little bit how to determine which commits need to be excised and how I would do this exactly using 'git migrate export'? I'm a little reticent to make destructive changes here.

Also, our versioning system relies on having a consistent rev-list. How will this change affect the rev-list?

Thanks

**Comment by ttaylorr** [comment] 2018-09-12 13:46
> In [this comment](https://github.com/git-lfs/git-lfs/issues/1935#issuecomment-419578704), you recommend two solutions: 1) Using 'git migrate export' and 2) 'git
> filter- branch'.

Right. The problem is roughly that when you run 'git lfs fetch --all'
you are asking Git LFS to get _all_ LFS objects instead of ones
reachable from the current checkout only, which is the default.

So, when you ask Git LFS for all objects and it finds them based on the
blobs in your repository's history, when the server responds with "I
don't have this one", your client will complain because there's
fundamentally no way to satisfy both ends.

> Could you describe a little bit how to determine which commits need to
> be excised and how I would do this exactly using 'git migrate export'?
> I'm a little reticent to make destructive changes here.

Sure. The idea behind using one of these (either 'filter branch' or 'lfs
migrate export') is that you would remove the LFS pointer blob from your
history referring to the one that doesn't exist on the server so that
'git lfs fetch --all' doesn't find them.

I actually think that 'git filter-branch' would be more appropriate,
since 'git lfs migrate export' tries to replace the LFS pointer blob
with the large object that it refers to, so I think that it would fail
in a similar way as described in the issue that you referred to earlier.

As for how to do that, you'll first need Git's SHA-1 assigned to the
blob that you're missing, which you can find by running:

  $ git rev-list --all --objects -- "<path/to/file>" \
    | cut -d' ' -f1 \
    | while read sha1; do
        if [ git cat-file -p "$sha1" | grep -q "<missing-oid>" ]; then
          echo "$sha1"
        fi \
      done

And then you can take the output of that command with:

  $ git filter-branch --index-filter='
      git ls-files -s \
      | grep -v "<missing-oid>" \
      | git update-index --index-info
    '

> Also, our versioning system relies on having a consistent rev-list.
> How will this change affect the rev-list?

It will change the history of your repository, and thus the rev-list. If
you don't _drop_ the blob, you'll retain the number of entries in any
rev-list invocation, but the SHA-1's will change.

**Closed** 2018-09-12 13:47 UTC

**Comment by everttrollip** [comment] 2020-03-31 00:08
Hi @ttaylorr, 

I have recently run into same issues as @ilienert, and I am getting 404 not found errors after trying to do a `git lfs fetch or fetch -all`. 

I am trying to follow your comment above, where you suggested the following: 

> As for how to do that, you'll first need Git's SHA-1 assigned to the
> blob that you're missing, which you can find by running:
> 
>   $ git rev-list --all --objects -- "<path/to/file>" \
>     | cut -d' ' -f1 \
>     | while read sha1; do
>         if [ git cat-file -p "$sha1" | grep -q "<missing-oid>" ]; then
>           echo "$sha1"
>         fi \
>       done

If the path to my file is, "src/_common/assets/logo.png", I did the following in my zsh mac terminal: 

```
git rev-list --all --objects -- "src/_common/assets/logo.png" \
    | cut -d' ' -f1 \
    | while read sha1; do
        if [ git cat-file -p "$sha1" | grep -q "<missing-oid>" ]; then
          echo "$sha1"
        fi \
      done
```

however, I get a parse error, `zsh: parse error near `done'`

I tried replacing the "<missing-oid>" placeholder with the oid, and I found it by looking at the contents of the file that is missing on the server: 

```
version https://git-lfs.github.com/spec/v1
oid **sha256:5dd4dcc5d399f28972c40739e1a25b532767bc996a1a56dfeca29bfa01322fa3**
size 1190
```

Pasting **sha256:5dd4dcc5d399f28972c40739e1a25b532767bc996a1a56dfeca29bfa01322fa3** in place of <missing-oid>, 

```
git rev-list --all --objects -- "src/_common/assets/logo.png" \ 
    | cut -d' ' -f1 \
    | while read sha1; do
        if [ git cat-file -p "$sha1" | grep -q "sha256:5dd4dcc5d399f28972c40739e1a25b532767bc996a1a56dfeca29bfa01322fa3" ]; then
          echo "$sha1"
        fi \
      done
```

but I still get the same parse error. What could I be doing wrong?

> And then you can take the output of that command with:
> 
>   $ git filter-branch --index-filter='
>       git ls-files -s \
>       | grep -v "<missing-oid>" \
>       | git update-index --index-info
>     '

Where do I use the output of the command? Again in the place of the "<missing-oid>" placeholder?

**Comment by bk2204** [comment] 2020-03-31 14:05
Hey,

I think there might be a typo in that command.  I've fixed it by running the following instead:

```
git rev-list --all --objects -- "<path/to/file>" \
    | cut -d' ' -f1 \
    | while read sha1; do
        if git cat-file -p "$sha1" | grep -q "<missing oid>"; then \
          echo "$sha1"; \
        fi; \
      done
```

That seems to work for me in zsh.
