### ISSUE TITLE
GIT LFS is not working with the CA certificate

### ISSUE THREAD

**Issue by AETTELA** [git-lfs/git-lfs#2036] opened 2017-03-16 07:27 UTC
Thanks for your response.

As per the below suggestions provided by you, we have tried this still we are facing same issue now.

==================================================================
This means that Stash/BitBucket does not correctly support TLS v1.2, and does not fallback to the TLS v1.1 handshake, as is given here.

One workaround you could try is to grab the root CA for your host and explicitly trust it by adding the following keys to your .git/config:

http.https://<host>/.sslKey: the SSL key
http.https://<host>/.sslCert: the SSL certificate
Let me know if that works :+1: .

===================================================================

When i added these below lines to the .git/config file and after saving it is showing the below error
http.https://Abcd-xyz.com/stash/.sslKey
http.https://Abcd-xyz.com/stash/.sslCert

error : fatal: bad config file line 5 in c:\users\xxxxx

please let me know if i have did any mistake in the above configuration.

And i tried with below mention commands in the git
git config --global http.https://Abcd-xyz.com/stash/.sslkey
git config --global http.https://Abcd-xyz.com/stash/.sslCert

and pushed the files to the remote and now it is not showing the handshake failure error but it is showing below error, and i can able to see the file in the repository.

$ git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Remote "origin" does not support the LFS locking API. Consider disabling it with:
$ git config 'lfs.https://aeaaa@Abcd-xyz.com/stash/scm/tes/gitlfs.git/info/lfs.locksverify' false
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 339 bytes | 0 bytes/s, done.
Total 4 (delta 0), reused 0 (delta 0)
To https://aeaaa@Abcd-xyz.com/stash/scm/tes/gitlfs.git
194b097..0f7ee70 master -> master

Thanks
AETTELA

**Comment by technoweenie** [comment] 2017-03-16 15:20
Closing, duplicate of #2034.

**Closed by technoweenie** 2017-03-16 15:20 UTC
