### ISSUE TITLE
git lfs uninstall does not work with windows

### ISSUE THREAD

**Issue by mrkita** [git-lfs/git-lfs#2416] opened 2017-07-13 12:47 UTC
Using the latest 2.13.2 git for windows with installed LFS, when I try to run "git lfs uninstall" from within a git bash window in windows 7, it claims to have completed successfully, but nothing changes when I call "git lfs env", the filters are still there.

Our install for git is under c:\tools\git, and when I go under that directory to the global .gitconfig and manually delete the filters there, git lfs install/uninstall correctly works, by adding and removing it from my user config.

**Comment by technoweenie** [comment] 2017-07-13 14:15
If you run `GIT_TRACE=1 git lfs uninstall`, you can see what it's doing to remove the config:

```sh
$ GIT_TRACE=1 git lfs uninstall
08:09:50.610936 git.c:600               trace: exec: 'git-lfs' 'uninstall'
08:09:50.611952 run-command.c:350       trace: run_command: 'git-lfs' 'uninstall'
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' version
trace git-lfs: run_command: 'git' config --global --remove-section filter.lfs
```

That only removes it from the global config by default. If you have the LFS filters installed for a specific repository, you can also run `git lfs uninstall --local` while inside that repository. If you have admin rights, and you ran `git lfs install --system`, you can also run `git lfs uninstall --system`.

LFS relies on a correctly configured git in your system PATH. If you have multiple git installs, it's very possible that LFS could miss some `.gitconfig` files.

**Comment by mrkita** [comment] 2017-07-14 08:36
Sorry, yes I was confusing global and system levels configs. I meant the system level.

Theoretically the user running the command has admin rights, but I may have run it from a cmd prompt that was not run with "as adminstrator". I will check that and post here.

**Comment by perumaal** [comment] 2020-05-15 10:34
This is an extremely fragile system. It's been frustrating trying to uninstall lfs. It doesn't work and it is simply an advertisement for github. 

IS there a way to completely remove this? 
IF I miss some intricate step, the entire thing blows away all my psd/png files with 1kb pointer with no way to revert. There must be an easy way to uninstall, this is unacceptable for a tool that is not claimed as beta/test-only.

**Comment by perumaal** [comment] 2020-05-15 10:45
The git lfs uninstall command does not work. Please fix this. It's ridiculous to ship stuff like this.
Just try on a normal machine with a single png and no server.

**Comment by bk2204** [comment] 2020-05-15 14:55
@perumaal Are you trying to remove your files from Git LFS and make them regular Git files?  If so, `git lfs uninstall` doesn't do that.  You need to use `git lfs migrate export` for that (see the documentation for details).  `git lfs uninstall` just removes the configuration and hooks from your repository and configuration, but doesn't rewrite objects to be non-Git LFS files.

If you're still having trouble, please open a new issue with a filled out issue template, including an example, and we'll look into it.

**Comment by perumaal** [comment] 2020-05-15 15:54
Hi,
I searched for git lfs, followed the doc (on a safe machine that is backed up - but with tons of PSDs/PNGs).   https://git-lfs.github.com/ -> 

Here is the "That's it'" Step 3:

"There is no step three. Just commit and push to GitHub as you normally would."

There was no documentation or warning that you need github server to run this.
There were no step 4 to say 'oh btw, if you messed this up, here is how to rewind'.

What follows is one obscure issue after another where people are complaining about disable/uninstall git lfs.

In general, good software must come with:
 - proper doc/support to rewind back stuff it does
 - consistent usage of 'install' and 'uninstall' that mirror such usage
 - and not be deceptive: It says open source and blah. But it does not provide a non-github server. does not have any pointer on how to remove nonsensensical 1KB stuff left over. 
 - and have good spec'ed protocol. An obscure .git hook that secretely hooks up to some saintly side-loaded software is antithesis to everything about git: This is not software. it's a bunch of wires held by duct tape.

Please put a huge warning in the doc saying 'this is not for production use' and 'only use if you have github account' and please fix these inane problems in your broken software.

I was of the impression that 'oh its those github folks, I can trust them when they say 'there is no step 3, that's it' and happily tried this on a giant repo.' You have lost my trust so terribly that i will never buy whatever you are trying to sell.

**Comment by perumaal** [comment] 2020-05-15 15:59
It's really poorly designed if you mess up my actual repo *files* by providing instructions that end with 'that's it, there is no step 3'.

Git hooks and other software that are not git lfs would at least have a way to *maintain* my source of truth with the raw data and instead manipulate the server-side data / .git happily. 

This is a pre-beta/internal-testonly level of software. Even the issues elsewhere have a pile of 'oh you are holding the phone wrong' with absolutely no cohesive 'oh we must actually fix this'. But instead series of inane steps by multiple people (which  presumably includes folks maintain this tool).

https://github.com/git-lfs/git-lfs/issues/316
https://github.com/git-lfs/git-lfs/issues/3026
and this issue here.

**Comment by bk2204** [comment] 2020-05-15 16:17
Hey, the original report reflects a different issue, which is that `git lfs uninstall` doesn't remove the system configuration that's shipped with Git for Windows.  That isn't the issue that you're reporting, which is that `git lfs uninstall` doesn't work in the way you expect.

If you'd like to report that issue, please open a new issue.  I'm sorry that you're unhappy, but we do indeed ship documentation with the software about how to operate it and use it.  It is necessarily complex because of the way Git works and the limitations of what we can do within Git's existing tooling, but we're open to hearing constructive ways to improve it.

The way Git LFS works is by replacing your files with pointer files and storing the large objects outside the main repository structure.  That is by design, since it prevents huge files from being in your repository and having to be cloned all the time.  If you want to undo that operation, you necessarily need to rewrite history, since the contents of your repository will have changed; that's just how Git works.

A GitHub server is not required; we provide an LFS test server in the github/lfs-test-server repo that some people use for production purposes, and other hosting platforms also provide implementations.  There are also other implementations listed on the wiki.

Again, if you're having trouble, please open a new issue, filling out the issue template and describing the expected and actual behavior.

**Comment by arcticoder** [comment] 2022-01-07 00:28
So this is still an issue @bk2204 as reported initially, it's unfortunate the subject was changed. I have a repo on a Windows Server installation that I'm trying to push to bitbucket, but because of https://community.atlassian.com/t5/Bitbucket-articles/Git-LFS-v3-0-1-includes-backwards-incompatible-changes-with/ba-p/1819819, I need to downgrade to lfs 2.13.3. 

I don't need it to be intuitive (that's why they pay us) but I do need it to work. Apologies for referencing the 3.0.1 issue, but issues like the one mentioned at the top of this ticket are compounded by issues like that. And also apologies for below, I clearly don't fully understand how git lfs works. But if it can't be uninstalled, that needs to be made clear so people aren't wasting their time.

PS> git lfs uninstall ⬛❕
Global Git LFS configuration has been removed.
⊩should have done this in $home\Sites\myapp-tomcat-home?
PS> iwr https://github.com/git-lfs/git-lfs/releases/download/v2.13.3/git-lfs-windows-v2.13.3.exe -o $home\Downloads\git-lfs-windows-v2.13.3.exe
PS> & "$home\Downloads\git-lfs-windows-v2.13.3.exe" ✅
PS> git lfs install
Git LFS initialized.

⊩ Copy latest changes from MyApp PROD ✅
PS> icm $myappProdSession -script {
  compress-archive -u "C:\Tomcat7\.git\*" $home\Downloads\tomcat-home.zip
}
PS> cpi "C:\Users\myuser\Downloads\tomcat-home.zip" -from $myAppProdSession -d "$home\Downloads\myapp-tomcat-home.zip"
PS> expand-archive -fo "$home\Downloads\myapp-tomcat-home.zip" -d "$home\Sites\myapp-tomcat-home\.git"

⊩ Remove unused/unneeded old myserver-c-tomcat7 folder
PS> ri -r -fo $home\Code\myserver-c-tomcat7
PS> sl $home\Sites\myapp-tomcat-home
PS> git lfs install
Updated git hooks.
Git LFS initialized.

PS> git push -u origin master ❌
...batch request: Bitbucket cannot execute 'git-lfs-authenticate /mas/myapp-tomcat-home.git upload'. The command is not supported as entered.
...
Ensure you are using a supported SCM, check the syntax and try again.: exit status 1
error: failed to push some refs to 'ssh://mybitbucketserver.ca:7999/myproject/myapp-tomcat-home.git'

⊩ https://mybitbucketserver.ca/projects/myproject/repos/myapp-tomcat-home/browse ❌
...You have an empty repository...

⊩ I didn't run `git lfs uninstall` in this other directory, trying a reinstall ❌
PS> git lfs uninstall
PS> git lfs install
PS> git push -u origin master ❌
⊩same error

PS C:\Users\myuser\Sites\myapp-tomcat-home> git lfs version
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
⊩it didn't actually downgrade

⊩ Try downgrade again ❌
PS> git lfs uninstall ⬛
PS> git lfs version
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
⊩didn't uninstall

PS> pushd $home
PS C:\Users\myuser> git lfs version
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
⊩nothing to do with the repository, it just didn't uninstall it

**Comment by arcticoder** [comment] 2022-01-07 00:35
Can I propose this issue be closed if it's not actually an issue? It's been open for 4 years so it feels like an unresolved issue, but perhaps it got forgotten about. If it's user error, please make that clear and those of us with some reading can do can better spend our time. 😊

**Comment by bk2204** [comment] 2022-01-07 13:50
Hey,

`git lfs uninstall` doesn't remove Git LFS from the system.  That's not what it's designed to do or documented to do.  Please see `git lfs uninstall --help` for the documentation on what it _does_ do.

If you've installed Git LFS as part of Git for Windows, we don't replace that, which is #4002 and marked `help-wanted` because we have nobody capable of fixing the problem.  If folks find this too confusing, we can always remove the installer and simply ship plain binaries instead unless someone is willing to fix it.

I am going to close this issue because this is working as designed, even if Git for Windows ships different settings.  If you have complaints about Git for Windows' settings, please direct them to their issue tracker in a helpful and productive way.

**Closed by bk2204** 2022-01-07 13:50 UTC
