### ISSUE TITLE
Very slow performance

### ISSUE THREAD

**Issue by herrbischoff** [git-lfs/git-lfs#4155] opened 2020-06-09 16:09 UTC
**Describe the issue**
When checking out a large 5.3 GB Git LFS repository on a local gigabit LAN from a Gitea installation, it takes upwards of 17 minutes to complete. Non-LFS repository checkouts are happening quickly. Here's the screen output:

```
$ time git clone git@172.16.0.100:website/uploads.git
Cloning into 'uploads'...
remote: Enumerating objects: 2655, done.
remote: Counting objects: 100% (2655/2655), done.
remote: Compressing objects: 100% (2636/2636), done.
remote: Total 2655 (delta 24), reused 2491 (delta 12), pack-reused 0
Receiving objects: 100% (2655/2655), 271.00 MiB | 16.51 MiB/s, done.
Resolving deltas: 100% (24/24), done.
Filtering content: 100% (2266/2266), 5.30 GiB | 5.21 MiB/s, done.

________________________________________________________
Executed in   17.70 mins   fish           external 
   usr time  115.65 secs  131.00 micros  115.65 secs 
   sys time  111.58 secs  806.00 micros  111.57 secs 
```

However, when using a regular Git repository of the same data, both server-side consumed storage is lower and checkout time is dramatically (~2.6x) shorter:

```
# time git clone git@172.16.0.100:website/uploads-non-lfs.git
Cloning into 'uploads-non-lfs'...
remote: Enumerating objects: 2285, done.
remote: Counting objects: 100% (2285/2285), done.
remote: Compressing objects: 100% (2221/2221), done.
remote: Total 2285 (delta 59), reused 2285 (delta 59), pack-reused 0
Receiving objects: 100% (2285/2285), 5.00 GiB | 15.69 MiB/s, done.
remote: 
Resolving deltas: 100% (59/59), done.
Updating files: 100% (2275/2275), done.

________________________________________________________
Executed in  416.20 secs   fish           external 
   usr time   69.87 secs  131.00 micros   69.87 secs 
   sys time   30.77 secs  735.00 micros   30.77 secs 
```

* Is this the expected performance?
* If so, what exactly is the benefit of using Git LFS?
* Does it show its strengths only with seriously large files (100M+) and dozens of gigabytes of binary data?

**System environment**

Client:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101


$ git lfs -v
git-lfs/2.11.0 (GitHub; darwin amd64; go 1.14.2)

$ fish -v
fish, version 3.1.2
```
Server:
```
$ uname -a
FreeBSD [REDACTED] 12.1-RELEASE-p5 FreeBSD 12.1-RELEASE-p5 GENERIC  amd64

$ gitea -v
Gitea version 1.11.6 built with GNU Make 4.3, go1.14.4 : pam, sqlite, sqlite_unlock_notify
```

**Output of `git lfs env`**
```
# git lfs env
git-lfs/2.11.0 (GitHub; darwin amd64; go 1.14.2)
git version 2.27.0

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/local/Cellar/git/2.27.0/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment] 2020-06-09 20:54
Hey,

I'm not sure why you're seeing such a difference in performance, but there are some possibilities:

* The data you're transferring over the Git protocol is compressed, and the data you're transferring over Git LFS is usually not.
* You're downloading a large number of objects, and Git LFS downloads objects via multiple HTTP requests instead of one.  If your server is not using TLS or is not capable of HTTP/2, the performance impact of the protocol overhead could be significant.
* Git LFS can't download data until Git passes the pointer file to us, so slow operation from Git (say, due to a limited number of items in flight at once) could be causing it.
* There's something that makes HTTP slower in your network (e.g., a proxy) than SSH.
* Git LFS isn't able to fully saturate the bandwidth of your connection, and raising `lfs.concurrenttransfer` above 8 may help.

You can try running the command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and seeing what's taking the bulk of the time.  If you want to include that output here, be aware that it contains credential information which you should sanitize.

One of the main benefits from Git LFS is that you're not downloading every large object every time you clone or fetch, and they don't all have to be stored on your computer, only the ones you're using right now.  Since many large objects are things like images which don't compress well, this means that you're avoiding the need to pack and repack uncompressible data, and you're also not storing a full copy of every large object.  If you run your own server, which it sounds like you do, you also gain all those packing benefits on the server side as well, especially since the deltification process (which is also used when serving data) performs pathologically on most compressed data.

Whether it's a good trade-off in your case depends on your data and how compressible it is, how large it's likely to grow, how frequently it changes, and a bunch of other factors.  If you think you're likely to have a lot of history, it can be a better choice to use Git LFS to avoid storing a copy of every large object in your history.

**Comment by herrbischoff** [comment] 2020-06-10 08:49
Thank you for the detailed reply. I've investigated the points you raised and reply my findings below.

> The data you're transferring over the Git protocol is compressed, and the data you're transferring over Git LFS is usually not.

Since both repositories contain the same data and the data is media like audio and image files. I cannot see any relevant reduction in data size resulting from the compression. Unless all files get compressed into a single download stream that is. In that case it would be one continuous download vs. thousands of separate connections. It strikes me that could be the case here.

> You're downloading a large number of objects, and Git LFS downloads objects via multiple HTTP requests instead of one. If your server is not using TLS or is not capable of HTTP/2, the performance impact of the protocol overhead could be significant.

The server uses both HTTP/2 and TLS, both are correctly set up and working for other web workloads.

> Git LFS can't download data until Git passes the pointer file to us, so slow operation from Git (say, due to a limited number of items in flight at once) could be causing it.

I've added `lfs.concurrenttransfer = 16` to my Git config and it sped up the initial repository download. As soon as the filtering process starts (and from what I gather the real HTTP download of the referenced files), download rates drop again.

> There's something that makes HTTP slower in your network (e.g., a proxy) than SSH.

The traffic passes through an unmanaged Gigabit switch. It's a simple home setup. However, I use Nginx as a reverse proxy so there might be an unforeseen bottleneck.

> Git LFS isn't able to fully saturate the bandwidth of your connection, and raising lfs.concurrenttransfer above 8 may help.

See above. Setting to `16` improves repository download but not HTTP download. Another clue that the reverse proxy may be at fault.

Regarding the benefits, thanks for clearing a couple of things up. I couldn't find any obvious information regarding how it works on the website. What I knew was that Git stores binary files as full objects on every change. If I understand correctly, the main difference of Git LFS is that while it also stores full binary copies, it does so on external storage and downloads happen via HTTP.

Therefore the use case appears to be repositories with lots of changes, especially with very large media files (say gigabytes). Given a 250 MB Photoshop file, it's the difference of having the repository grow by 250 MB every time a change is committed vs. having the repository size grow insignificantly and having a copy of the file stored via the LFS capable server. Conversely, if there are lots of media files, each just a couple of MB in size that change infrequently, it may well be better to stick to regular Git repositories due to compression.

**Comment by bk2204** [comment] 2020-08-14 17:44
Hey,

It's hard for us to look any more into this without suitable trace output, so I'm going to close this.  If you can provide suitable trace output or a reproducible test repository, we'll look more into this.

**Closed by bk2204** 2020-08-14 17:44 UTC

**Comment by herrbischoff** [comment] 2020-08-17 16:57
Thanks for the ping. For the time being I've given up on using Git LFS as I deduced that my file sizes are not necessarily within the range where it would make sense. Should I encounter issues in the future, I will open a new issue and reference this one.

Thanks again for the suggestions and of course your time to engage with me.
