### ISSUE TITLE
Error downloading objects when cloning private repository

### ISSUE THREAD

**Issue by jasjuang** [git-lfs/git-lfs#2039] opened 2017-03-16 18:17 UTC
I am on Windows 10. Git LFS 2.0.1 for windows.

I am getting error when I git clone a repository that contains lfs files, the error looks exactly like the error shown at #1865, however if I set the repository to be public like the one shown in #1865, I am able to clone it without a problem. If I save my git credentials with windows credential helper and clone the private repository, I am also able to clone the repository without a problem.  

I am on a shared computer so I don't want to save my credentials, when I clone the private repository it did ask me for my git credentials and after I input it it is able to download the non-lfs files but not the lfs files. I suspect that git lfs is not picking up the entered git credentials thus causing it to fail.

I reproduce the same scenario on another computer (no saved git credentials, and cloning a private repo with lfs files) and it still fails, please help.

**Comment by technoweenie** [comment] 2017-03-20 16:28
Closing as a dupe of #2040.

**Closed by technoweenie** 2017-03-20 16:28 UTC
