### ISSUE TITLE
LFS 2.7.1 doesn't include extra header from git config

### ISSUE THREAD

**Issue by mitesch** [git-lfs/git-lfs#3571] opened 2019-03-20 13:45 UTC
Steps to reproduce:
```
GIT_LFS_SKIP_SMUDGE=1 git clone https://account@dev.azure.com/account/Test/_git/mitesch-lfs mitesch-lfs
cd mitesch-lfs
git config http.https://account@dev.azure.com/account/Test/_git/mitesch-lfs.extraheader "AUTHORIZATION: bearer notvalid"
export GIT_CURL_VERBOSE=1
git lfs fetch
```

In 2.6.1, it includes the authorization header in the requests made by `git lfs fetch`.
In 2.7.1, the header is not included.

We (Azure DevOps) optionally set the bearer token in the config for users during builds so that later steps can perform authenticated git commands. Our upgrade to 2.7.1 on the build machines breaks this functionality for LFS. 

OS: Windows 10
Git: 2.20.1

**Comment by bk2204** [comment] 2019-03-21 23:38
Hey, thanks for writing in.

I think the proper way URL to use needs to include the `/info/lfs` portion. Does this work for you if you use `http.https://account@dev.azure.com/account/Test/_git/mitesch-lfs.git/info/lfs.extraheader` or `http.https://dev.azure.com/account/Test/_git/mitesch-lfs.git/info/lfs.extraheader`?

We have tests for that form, but we don't have tests for the other form (without the `info/lfs`). It may have happened to work in the past, but it doesn't seem that it was intentional. In general, we require the `/info/lfs` form for other HTTP settings as well so that users can use different settings for LFS and plain Git if necessary.

**Comment by mitesch** [comment] 2019-03-27 15:25
It doesn't seem to work with that setting either. I'm not sure why.
I set up an example in a public DevOps account. The builds all pass because it's a public account and authorization is obviously unneeded, but we can see via GIT_CURL_VERBOSE that the header isn't being included in new requests. They match the experience I see in private builds, except those fail because the header isn't included.

The "copy config" step creates the new entry and dumps the git config.
The "lfs fetch" step has GIT_CURL_VERBOSE enabled. 

lfs 2.6.1, passes bearer token with original config setting (checkout step sets the config setting)
`git config http.https://miteschpublic@dev.azure.com/miteschpublic/Public/_git/Public.extraheader "AUTHORIZATION: bearer ***"`
https://dev.azure.com/miteschpublic/Public/_build/results?buildId=4&_a=summary

lfs 2.7.1, doesn't use the header with original config setting (checkout step sets the config setting)
`git config http.https://miteschpublic@dev.azure.com/miteschpublic/Public/_git/Public.extraheader "AUTHORIZATION: bearer ***"`
https://dev.azure.com/miteschpublic/Public/_build/results?buildId=5&_a=summary

lfs 2.7.1 with `http.https://miteschpublic@dev.azure.com/miteschpublic/Public/_git/Public/info/lfs.extraheader` doesn't use the header
https://dev.azure.com/miteschpublic/Public/_build/results?buildId=6&_a=summary

lfs 2.7.1 with `http.https://miteschpublic@dev.azure.com/miteschpublic/Public/_git/Public.git/info/lfs.extraheader` doesn't use the header
https://dev.azure.com/miteschpublic/Public/_build/results?buildId=7&_a=summary

lfs 2.7.1 with 
`http.https://dev.azure.com/miteschpublic/Public/_git/Public.git/info/lfs.extraheader`
doesn't use the header
https://dev.azure.com/miteschpublic/Public/_build/results?buildId=8&_a=summary

Then one last one with all 4 config entries at once
https://dev.azure.com/miteschpublic/Public/_build/results?buildId=9&_a=summary

**Comment by bk2204** [comment] 2019-03-27 20:01
This is really interesting. I see in my testing, both with the plain `.git` URL and the `.git/info/lfs` URL in the file, that the header is being passed. I can see this both with a non-Authorization header (e.g. `X-Random: octocat`) and with something like `AUTHORIZATION: octocat` (which of course causes my request to fail):

```
[http "https://github.com/git-lfs/test-repo.git"]
	extraheader = AUTHORIZATION: octocat
```

```
> POST /git-lfs/test-repo.git/info/lfs/objects/batch HTTP/1.1
> Host: github.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: octocat
> Content-Length: 2338
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.7.1 (GitHub; darwin amd64; go 1.12.1; git 6b7fb6e3)
```

There must be some difference that's causing this to trigger for you and not me, but I can't figure out what it is. The only thought I have is that something is unhappy with the underscore, but that's a perfectly valid unreserved character in a URI. Does anyone on @git-lfs/core have any ideas about what might be going on here?

**Comment by bk2204** [comment] 2019-03-27 20:43
I've just tested with a repo on Azure DevOps, and I can say that creating a personal access token and then pushing from the command line on my Mac using an appropriate "Authorization: Basic" extraheader config entry does indeed work for me. It's definitely not an issue with the format of the URL. Perhaps something with the format of the token or the header being provided is the cause, but I'm not familiar with what format Azure DevOps uses for its OAuth tokens or the entries it writes into `.git/config`.

**Comment by PastelMobileSuit** [comment] 2019-03-27 22:38
@bk2204 Is it possible some quirk of Windows or Git for Windows could be causing this to fail in LFS 2.7.1?

**Comment by mitesch** [comment] 2019-03-28 01:48
Here are some more runs. I added a step to dump the raw config file as well. Doesn't seem to be Windows specific.

Ubuntu 16.04 w/LFS 2.6.1, old header entry, uses it in requests:
https://dev.azure.com/miteschpublic/Public/_build/results?buildId=20&_a=summary

Ubuntu 16.04 w/LFS 2.7.1, old header entry (not used in requests):
https://dev.azure.com/miteschpublic/Public/_build/results?buildId=17&_a=summary

Ubuntu 16.04 w/LFS 2.7.1, with the 4 urls with /info/lfs (not used in requests):
https://dev.azure.com/miteschpublic/Public/_build/results?buildId=18&_a=summary

Mac OS 10.13 with LFS 2.7.1, old header entry (not used in requests):
https://dev.azure.com/miteschpublic/Public/_build/results?buildId=19&_a=summary

Mac OS 10.13 with LFS 2.7.1, with the 4 urls with /info/lfs (not used in requests):
https://dev.azure.com/miteschpublic/Public/_build%2Fresults?buildId=21&_a=summary

And one on Windows w/LFS 2.7.1 with the config dump for good measure:
https://dev.azure.com/miteschpublic/Public/_build%2Fresults?buildId=22&_a=summary

**Comment by mitesch** [comment] 2019-03-28 02:50
I went ahead and added a yaml pipeline that runs the full matrix of builds across mac/windows/linux. Let me know if there's anything additional you'd like to see.

https://dev.azure.com/miteschpublic/_git/Public?path=%2Fazure-pipelines.yml&version=GBmaster
https://dev.azure.com/miteschpublic/Public/_build/results?buildId=34

**Comment by bk2204** [comment] 2019-03-28 15:17
Does this work for you from a standard command line environment? I ask because you and someone reporting this issue on #1500 are both using Azure Pipelines, but I'm seeing this work on my command-line environment. We also haven't seen any reports of this from users who aren't using Azure Pipelines, so I'm wondering if there's some relevant difference involved.

What I'd like to know is what format the OAuth bearer tokens are in. I'm thinking there's something about the format of the OAuth tokens or the config file that's making us misparse in this situation. Ideally I'd be able to see the output of `od -Ax -tx1` on the config file, but unless we know that those tokens are expired immediately after use, that would leak valid credentials, which obviously we should avoid.

**Comment by mitesch** [comment] 2019-03-28 16:45
Yes, the steps in the original post were run in Git bash on Windows on my dev box with both versions of LFS.
If I modify it to include the new headers like so:
```
GIT_LFS_SKIP_SMUDGE=1 git clone https://miteschpublic@dev.azure.com/miteschpublic/Public/_git/Public
cd Public
git config http.https://miteschpublic@dev.azure.com/miteschpublic/Public/_git/Public.extraheader "AUTHORIZATION: bearer notvalid"
git config http.https://dev.azure.com/miteschpublic/Public/_git/Public.git/info/lfs.extraheader "$(git config http.https://miteschpublic@dev.azure.com/miteschpublic/Public/_git/Public.extraheader)"
git config http.https://dev.azure.com/miteschpublic/Public/_git/Public/info/lfs.extraheader "$(git config http.https://miteschpublic@dev.azure.com/miteschpublic/Public/_git/Public.extraheader)"
git config http.https://miteschpublic@dev.azure.com/miteschpublic/Public/_git/Public.git/info/lfs.extraheader "$(git config http.https://miteschpublic@dev.azure.com/miteschpublic/Public/_git/Public.extraheader)"
git config http.https://miteschpublic@dev.azure.com/miteschpublic/Public/_git/Public/info/lfs.extraheader "$(git config http.https://miteschpublic@dev.azure.com/miteschpublic/Public/_git/Public.extraheader)"
GIT_CURL_VERBOSE=1 git lfs fetch
```
git lfs fetch does not pass up the header in 2.7.1. You should be able to run these verbatim since the project is public to see if it reproduces on your side.

```
> POST /miteschpublic/Public/_git/Public.git/info/lfs/objects/batch HTTP/1.1
> Host: dev.azure.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Content-Length: 3053
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
```

In 2.6.1, it passes up the header
```
> POST /miteschpublic/Public/_git/Public.git/info/lfs/objects/batch HTTP/1.1
> Host: dev.azure.com
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: bearer notvalid
> Content-Length: 3053
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.6.1 (GitHub; windows amd64; go 1.11.1; git dc072c3e)
```

No changes to my machine between runs besides running the LFS installer exe between runs and deleting the Public folder.

**Comment by mitesch** [comment] 2019-03-28 16:55
```
GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/mitesch/LfsTesting.git
cd LfsTesting
git config http.https://github.com/mitesch/LfsTesting.git.extraheader "AUTHORIZATION: bearer notvalid"
git config http.https://github.com/mitesch/LfsTesting.git/info/lfs.extraheader "$(git config http.https://github.com/mitesch/LfsTesting.git.extraheader)"
GIT_CURL_VERBOSE=1 git lfs fetch
```
This GitHub repo behaves the same as DevOps in 2.7.1 and 2.6.1. Meaning the header is included with LFS 2.6.1 and not included with LFS 2.7.1.

The exception is that GitHub is more strict with bad credentials on anonymous requests, so it 403's with LFS 2.6.1 since GitHub rejects the bogus header.

**Comment by bk2204** [comment] 2019-03-28 18:40
Okay, I can reproduce this now. This is specific to URLs with capital letters in them; my test repos don't have that, which is why I was unable to reproduce it originally. During the 2.7.0 cycle, @PastelMobileSuit was kind enough to help rewrite our URL handling so it uses the standard Git rules (in #3392), but one thing I didn't think about when looking at it was how we handled uppercase URLs.

Apparently there are several places where we force config keys to lowercase, and that's part of the problem that's happening here. We used to always force a direct lookup, pushing URLs into lowercase, but now we don't, and we get a mismatch of cases, preventing the lookup from returning anything.

I'll see if I can get a fix written up. Since this looks like a regression, we may do a 2.7.2 with the fix for this issue.

**Comment by ttaylorr** [comment] 2019-03-28 19:20
Thanks @bk2204 and @PastelMobileSuit, this is a great analysis.

> I'll see if I can get a fix written up. Since this looks like a
> regression, we may do a 2.7.2 with the fix for this issue.

I'd be happy to do a review when you are ready for one. I think that
v2.7.2 makes sense.

**Closed** 2019-04-04 13:23 UTC
Labels: bug
