### ISSUE TITLE
Can't finish the Uploading LFS Objects: 100%(759/762) 

### ISSUE THREAD

**Issue by jikks** [git-lfs/git-lfs#4541] opened 2021-07-03 18:37 UTC
Uploading can not finished.
Uploading LFS Objects: 100%(759/762) ,14GB | 0 B/s ,done.
Not Found
Not Found
Not Found

Window10 

git-lfs/2.13.3 (GitHub; windows amd64; go 1.16.2; git a5e65851)
git version 2.32.0.windows.1

Endpoint=http://jikks.synology.me:3000/jikks/MultiTopGame.git/info/lfs (auth=basic)
LocalWorkingDir=H:\GitRepository\MultiTopGame
LocalGitDir=H:\GitRepository\MultiTopGame\.git
LocalGitStorageDir=H:\GitRepository\MultiTopGame\.git
LocalMediaDir=H:\GitRepository\MultiTopGame\.git\lfs\objects
LocalReferenceDirs=
TempDir=H:\GitRepository\MultiTopGame\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=H:\GitRepository\MultiTopGame\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=G:/Tools/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by bk2204** [comment] 2021-07-05 20:20
Hey,

I'm not sure where the "Not Found" message you're seeing comes from.  Could you try running the command from Git Bash with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1`, save the exact output (copy and paste) into a text file, and attach that text file here, please?  I suspect that the output you're seeing is coming from something other than Git LFS and Git LFS is working properly here, but it's hard for me to confirm.

**Comment by jikks** [comment] 2021-07-12 02:54
sorry for late, the issue had resolved, but not actually down. I had uploaded these files part by part. I found if the files count too many, It will occur the error frequently.

**Comment by bk2204** [comment] 2021-07-12 12:42
Hey,

Could you please provide the relevant information we've asked for?  It's possible that the problem is in Git LFS, or it could be elsewhere (I have lots of interesting stories about Synology NASes).  We'd love to help fix the problem if it's on our end, but we can't do so or investigate further without the requested information.

If you can't reproduce this anymore, please close the issue.

**Comment by jikks** [comment] 2021-07-14 01:24
Hi, I've input the orders, but nothing happen.

**Comment by bk2204** [comment] 2021-07-14 12:38
Could you try updating to the latest Git for Windows?  It's likely that the problem is git-for-windows/git#3294 if you're not seeing any progress at all.

**Comment by jikks** [comment] 2021-07-21 05:57
$ git --version --build-option
git version 2.32.0.windows.1
cpu: x86_64
built from commit: 4c204998d0e156d13d81abe1d1963051b1418fc0
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

Microsoft Windows [Version 10.0.19042.1110]

**Comment by bk2204** [comment] 2021-07-21 12:40
The problem you're seeing is almost certainly git-for-windows/git#3294 and is resolved in the latest version of Git for Windows.  This is a Git for Windows issue and not an issue in Git LFS.

**Closed by bk2204** 2021-07-21 12:40 UTC
