### ISSUE TITLE
Problem with migration of a very big repository

### ISSUE THREAD

**Issue by windwalker78** [git-lfs/git-lfs#4100] opened 2020-04-16 15:16 UTC
Hello,

  Two weeks ago we were doing a test migration of a 140GB repository for the following file types:

`git lfs migrate import --everything --include="*.png,*.wav,*.avi,*.mov,*.m2v,*.db,*.FLI,*.dds,*.ttf,*.mpg,*.ogg,*.rar,*.bmp,*.264,*.mp4"
`
 These settings were needed because we were running out of RAM on our migration machine:

```
git config pack.threads 4
git config pack.deltaCacheSize 256m
git config core.packedGitWindowSize 16m
git config core.packedGitLimit 128m
git config pack.windowMemory 1024m

git reflog expire --expire=now --all && git reflog expire --expire-unreachable=now --all && git gc --prune=now --aggressive

```
And two weeks ago this went fine. 
We had like 170GB of LFS objects and 600MB git repository.

Yesterday we did another test migration, using the same steps and updated repo (contributors added like 5-10GB), but this time we had 184GB of LFS objects and **22GB git repo**

None of the commands returned any error on exit. We decided to check one of the migrated extensions i.e.  "*.264" and see that in the original repo there are 40 blob objects from this type.

After the migration in repository.git/objects/pack, we see all 40 of them migrated with new size of 132-133 bytes each (holding just the https link), but we also see 21 files with complete size part of the initial 40 set of "*.264" files. We don't know if this is a problem with "git lfs migrate" or "git gc" did not remove these objects from the git repo.

For both migrations, the following binaries were used:

git --version
git version 2.20.1
git lfs --version
git-lfs/2.10.0 (GitHub; linux amd64; go 1.13.4)

Please, give us a hand in this.

Kind regards,
Todor

**Comment by bk2204** [comment] 2020-04-16 17:56
Hey,

The thing I would use to check this operation is to do a `git push --mirror` to another (bare) repository on the same machine and then measure that.  That will tell you whether the issue is that you have any reachable objects in Git or whether you just have unimportant unreachable objects.

If you still have reachable objects, then what you may be seeing is #3238, which unfortunately we haven't been able to get any reproduction steps for.  We know it occurs in some instances but since we can't reproduce it, we can't fix it.

**Comment by windwalker78** [comment] 2020-04-21 14:11
Hi, Brian,

                   Thank you for your feedback! As our repository is rather
large, tests take some time. I already pushed the repository to a gitlab
server for the test and all git 22GB of repo object data got transferred.
Obviously git links many commits and tags to these blobs, instead of the
migrated ones.
                   I also pushed locally with --mirror as you suggested,
but this takes time and will finish probably tomorrow. We really don't want
to risk and go for a BFG migration, because we would like to use the
official tool and try to help you identify the bug for others. As you have
guessed we cannot give you original repository as it is proprietary. I
checked git fast-export --anonymize, but I don't think this will help at
all, as it scrambles completely the file tree structure+names and I have no
idea how you apply an "git lfs migrate --everyting --include" filter on it.
If you still think this might be useful, we can assist.

What we currently have for our repository is:
1. A successful migration 1 month ago with LFS objects and git data
2. A recent migration with same filter, where many LFS objects are not
correctly referenced by commits/tags and wrongly point to the initial blobs

We can run many times step 2 with verbose (debug if possible) and etc if
this helps somehow. This usually takes around 4-5 hours, but if we select a
smaller, filter probably things will be faster and scope reduced.

If you have any other idea, we will gladly assist. I have also cc'ed Kalin,
who is my colleague and line manager.

Regards,
Todor Ivanov
+359 887 38 36 00

**Comment by windwalker78** [comment] 2020-04-21 15:57
Hi, Brian,

I confirm git push --mirror did not produce any different result.

Kind regards,
Todor

**Comment by windwalker78** [comment] 2020-04-21 16:06
Hi, Brian,

I confirm git push --mirror did not produce any different result.

Kind regards,
Todor

**Comment by bk2204** [comment] 2020-04-21 17:47
We don't really have any debug information in this code path, so we'd need some sort of test repository that reproduces the problem, since running with `GIT_TRACE=1` isn't likely to produce any more elucidating information.

Since this appears a duplicate of #3238, I'd suggest that we track it there.  As mentioned, we're looking for a test repo we can use to trigger the problem so we can fix it.  If someone can provide such a repo, we'll do our best to get to it reasonably quickly.

**Closed by bk2204** 2020-04-21 17:47 UTC
