### ISSUE TITLE
'lfs' and 'hooks' folder is outside the .git folder

### ISSUE THREAD

**Issue by javurtez** [git-lfs/git-lfs#4050] opened 2020-03-01 13:51 UTC
The 'lfs' and 'hooks' folder seems to be inside the project instead in the .git folder. How can I solve it?

**Comment by chrisd8088** [comment] 2020-03-02 23:54
Hey, I'm sorry you're having trouble.

I think we'll need a bit more information before we can provide any assistance.  Would you be able to provide some more detail?  For instance, what does the structure of your project's top-level folder look like, and what do you see in `.git/`?

Can you provide the output of `git lfs env` and `git config -l` (with any personal information removed, of course!)

**Comment by javurtez** [comment] 2020-03-03 02:02
Well, I just copied the project to a new pc, and the 'lfs' and 'hooks' folder are suddenly outside of the .git folder, making these two folders to be in unstage files on sourcetree.

> git-lfs/2.9.2 (GitHub; windows amd64; go 1.12.7; git 0274d856)
> git version 2.25.0.windows.1
> 
> LocalWorkingDir=C:\Users\MyComp\Documents\Project Gedia 2018 LFS
> LocalGitDir=C:\Users\MyComp\Documents\Project Gedia 2018 LFS\.git
> LocalGitStorageDir=C:\Users\MyComp\Documents\Project Gedia 2018 LFS\.git
> LocalMediaDir=C:\Users\MyComp\Documents\Project Gedia 2018 LFS\.git\lfs\objects
> LocalReferenceDirs=
> TempDir=C:\Users\MyComp\Documents\Project Gedia 2018 LFS\.git\lfs\tmp
> ConcurrentTransfers=3
> TusTransfers=false
> BasicTransfersOnly=false
> SkipDownloadErrors=false
> FetchRecentAlways=false
> FetchRecentRefsDays=7
> FetchRecentCommitsDays=0
> FetchRecentRefsIncludeRemotes=true
> PruneOffsetDays=3
> PruneVerifyRemoteAlways=false
> PruneRemoteName=origin
> LfsStorageDir=C:\Users\MyComp\Documents\Project Gedia 2018 LFS\.git\lfs
> AccessDownload=none
> AccessUpload=none
> DownloadTransfers=basic,lfs-standalone-file
> UploadTransfers=basic,lfs-standalone-file
> GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
> GIT_LFS_PATH=C:\Program Files\Git LFS
> git config filter.lfs.process = "git-lfs filter-process"
> git config filter.lfs.smudge = "git-lfs smudge -- %f"
> git config filter.lfs.clean = "git-lfs clean -- %f"

> diff.astextplain.textconv=astextplain
> filter.lfs.clean=git-lfs clean -- %f
> filter.lfs.smudge=git-lfs smudge -- %f
> filter.lfs.process=git-lfs filter-process
> filter.lfs.required=true
> http.sslbackend=openssl
> http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
> core.autocrlf=true
> core.fscache=true
> core.symlinks=false
> credential.helper=manager
> filter.lfs.required=true
> filter.lfs.clean=git-lfs clean -- %f
> filter.lfs.smudge=git-lfs smudge --skip -- %f
> filter.lfs.process=git-lfs filter-process --skip
> credential.helperselector.selected=manager
> difftool.sourcetree.cmd='' "$LOCAL" "$REMOTE"
> mergetool.sourcetree.cmd=''
> mergetool.sourcetree.trustexitcode=true
> core.repositoryformatversion=0
> core.filemode=false
> core.bare=false
> core.logallrefupdates=true
> core.symlinks=false
> core.ignorecase=true
> remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
> branch.master.remote=origin
> branch.master.merge=refs/heads/master
> filter.lfs.process=git-lfs filter-process
> filter.lfs.required=true
> filter.lfs.clean=git-lfs clean -- %f
> filter.lfs.smudge=git-lfs smudge -- %f
> (END)

**Comment by chrisd8088** [comment] 2020-03-03 22:10
Hmm.  It looks as though Git LFS is having trouble detecting the `.git` folder; from your `git lfs env` output, this looks wrong to me:
```
LocalGitDir=C:\Users\MyComp\Documents\Project Gedia 2018 LFS.git
```
where I would expect:
```
LocalGitDir=C:\Users\MyComp\Documents\Project Gedia 2018 LFS\.git
```

Would you mind trying something like `git rev-parse --git-dir --absolute-git-dir --show-toplevel --is-inside-work-tree` from inside your project folder and reporting the results?

**Comment by javurtez** [comment] 2020-03-04 01:14
```
C:/Users/MyComp/Documents/Project Gedia 2018 LFS/.git
C:/Users/MyComp/Documents/Project Gedia 2018 LFS
true
```

**Comment by chrisd8088** [comment] 2020-03-06 21:07
Hi, sorry for not replying sooner -- I confess I have no good ideas here, in part because I'm not normally a Windows user.

I notice you're using Git LFS v2.9.2, and #3910 was included in v2.10 which fixes #3898 ("hooks and lfs folders are created on project root instead of inside .git folder when using git-lfs") due to the lack of the `cygpath` binary on some Windows systems.

If by chance you're moving to a new PC, and having yet installed Cygwin, perhaps that was the cause of the problem.  You might try upgrading to Git LFS v2.10.0, and/or installing Cygwin, and re-copying your project folder into a fresh location (leaving out the misplaced `hooks` and `lfs` directories, I mean).

**Comment by javurtez** [comment] 2020-03-07 01:10
Is it safe to delete the 'hooks' and 'lfs' folder outside the .git folder?

**Comment by chrisd8088** [comment] 2020-03-07 02:24
Well, the `lfs` folder in particular contains the Git LFS storage objects.  Personally, I would be inclined to create a fresh clone of the repo using Git LFS v2.10.0, and then copy over any local in-progress changes to the fresh clone, so I could be confident I wasn't altering the existing (broken) copy until I had a completely working new one.  But you might also be fine to just move those folders back under `.git/`.

**Comment by javurtez** [comment] 2020-03-08 15:04
Ok, thanks. I've updated the git-lfs to v2.10.0 and copied the 'hooks' and 'lfs' folder to .git folder.

**Comment by axelucho** [comment] 2020-04-08 03:57
Hi, I'm having similar issues..
Did a fresh clone with git 2.26.0.windows.1 and GitLFS 2.10.0
Folder structure was ok at first, but as soon as I started to commit files into lfs the folders in the root folder were created..

Folder structure
```
.git/
    hooks/
        pre-push
        post-checkout
        post-merge
        post-commit
    lfs/
        cache
        incomplete
        objects
        tmp
hooks/
    pre-push
    post-checkout
    post-merge
    post-commit
lfs/
    objects
    tmp
ourFilesAndStuff
```

Git lfs Env
```
LocalWorkingDir=C:\Users\Axel\Desktop\TacGalac
LocalGitDir=C:\Users\Axel\Desktop\TacGalac\.git
LocalGitStorageDir=C:\Users\Axel\Desktop\TacGalac\.git
LocalMediaDir=C:\Users\Axel\Desktop\TacGalac\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\Axel\Desktop\TacGalac\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\Axel\Desktop\TacGalac\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files (x86)/Git/mingw32/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

git config -l
```
pack.packsizelimit=2g
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager
user.name=axelucho
user.email=
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
difftool.sourcetree.cmd='' "$LOCAL" "$REMOTE"
mergetool.sourcetree.cmd=''
mergetool.sourcetree.trustexitcode=true
core.editor="C:\Users\Axel\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=<git url removed>
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.dev.remote=origin
branch.dev.merge=refs/heads/dev
lfs.<git url removed>/info/lfs.access=basic
```
Running git rev-parse --git-dir --absolute-git-dir --show-toplevel --is-inside-work-tree
```
C:/Users/Axel/Desktop/TacGalac/.git
C:/Users/Axel/Desktop/TacGalac
true
```

Any help is much appreciated, thanks in advance!

**Comment by bk2204** [comment] 2020-04-08 14:50
Hey,

We definitely have seen this before, but we're not sure why it occurs.  Can you perhaps tell us what steps you took before seeing this?  We'd love to be able to reproduce it so we can fix it.

**Comment by axelucho** [comment] 2020-04-14 01:25
I tried making a fresh repo to see if I could reproduce the problem but no luck... Thought SourceTree might have something to do as well, and that doesn't seem to be it either. I'll keep looking into it. I'll post if I find anything..

**Comment by gwenpasquarello** [comment] 2021-02-06 23:51
Hi all,
Sorry to necro this but I've found a way to repro on my system. For me if i setup a project with git-lfs and a .gitattributes on my C:/ drive everything works as expected. However, I have a separate disk drive mounted in windows as a sub-folder like this C:\_D\
If I run the same procedure anywhere under C:\_D\ git lfs breaks either with the above mentioned hooks and lfs folder issue or by simply refusing to run (see below)

Since it seems to depend on the location of the repo, I'm willing to bet the `cygpath` stuff is what's throwing lfs off.

Is there a way I can just force the variables in `git lfs env` to a particular value?
Obviously that's not a long-term solution, but I just need lfs to work for the moment.

### System Details
- Windows 10 Pro 1909 build 18363.1316
- git version 2.30.0.windows.2
- git-lfs/2.13.2 (GitHub; windows amd64; go 1.14.13; git fc664697)
- cmder or git bash (both will repro)
- cygpath version 3.1.7

### Steps to reproduce
1. on a drive mounted as a sub-folder
2. `mkdir test-repo`
3. `cd test-repo`
4. `git init`
5. `add a file to track. in this case test.jpg`
6. `git lfs track test.jpg`
git will fail with this error
```
Error: error converting ".git" to absolute: EvalSymlinks: too many links
Not in a git repository.
```
7. manually add a .gitattributes with a like this
```
test.jpg filter=lfs diff=lfs merge=lfs -text
```
8. `git add test.jpg`

Result: the lfs and hooks directories will be generated in the wrong place (as siblings of .git instead of children)

### git lfs env comparison
output in a correctly functioning directory:
```
λ git lfs env
git-lfs/2.13.2 (GitHub; windows amd64; go 1.14.13; git fc664697)
git version 2.30.0.windows.2

LocalWorkingDir=C:\Users\john\deletme
LocalGitDir=C:\Users\john\deletme\.git
LocalGitStorageDir=C:\Users\john\deletme\.git
LocalMediaDir=C:\Users\john\deletme\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\john\deletme\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\john\deletme\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/_D/Programs/Git/mingw64/libexec/git-core
GIT_INSTALL_ROOT=C:\_D\Programs\Git
GIT_VERSION_USER=2.30.0.windows.1
GIT_VERSION_VENDORED=2.28.0.windows.1
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

Output in an incorrectly functioning directory:
```
λ git lfs env
git-lfs/2.13.2 (GitHub; windows amd64; go 1.14.13; git fc664697)
git version 2.30.0.windows.2

Error: error converting ".git" to absolute: EvalSymlinks: too many links
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/_D/Programs/Git/mingw64/libexec/git-core
GIT_INSTALL_ROOT=C:\_D\Programs\Git
GIT_VERSION_USER=2.30.0.windows.1
GIT_VERSION_VENDORED=2.28.0.windows.1
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment] 2021-02-08 18:53
Thanks for the reproduction steps.  What you're reporting is #4012, which is known and is caused by a bug in Go that they refuse to fix.  There is no workaround at the moment other than avoiding those paths, although we _may_ be able to fix it upon the release of Git 2.31.0.

**Comment by dietergovaerts** [comment] 2021-02-17 13:02
Hi,
I can indeed confirm that it is caused by cloning a repo to a drive mounted as a sub-folder on Windows as reported by @gwenprime. I'm experiencing this now on a fresh installed system.

**Comment by dimitarcl** [comment] 2021-04-14 08:37
With the Git 2.31.0 release out, are there any news for this issue?

**Comment by bk2204** [comment] 2021-04-14 14:53
We have a fix in `main` for this issue.  It will be released when we release 3.0.0.

**Comment by dmitrymatveev** [comment] 2021-10-16 20:26
I can confirm similar outcome as @raphaelsetin 

I had a similar issue with VS2019... 
1. pull a clean repo with lfs items
2. open .sln file
At this moment, vs2019 would create `/hooks` and `/lfs` folder in the project root.

After updating my git to the latest version this does not happen anymore
```
 C:\Users\user> git lfs env
git-lfs/3.0.1 (GitHub; windows amd64; go 1.17.1)
git version 2.33.1.windows.1

```

**Comment by bk2204** [comment] 2021-10-18 12:26
Okay, since it sounds like this is fixed, I'm going to close this issue.  Thanks for confirming it's gone.

**Closed by bk2204** 2021-10-18 12:26 UTC
