### ISSUE TITLE
Git LFS fails to checkout when Git repo is used via symlink

### ISSUE THREAD

**Issue by dentuzhik** [git-lfs/git-lfs#866] opened 2015-11-26 12:26 UTC
I think this one is related to https://github.com/github/git-lfs/issues/591

The basic failure test-case is the following:
1. Clone fresh repo, with git-lfs configured
2. Create a symlink to this repo somewehere
3. `cd` into repo by symlink
4. `git lfs fetch; git lfs checkout` - fetch succedes, checkout fails with `error: git-lfs died of signal 13`

Doing absolutely the same thing without symlink works just fine.

Here's the output of `git lfs env`, when accessing repo by symlink, the top arrow is the real path, the bottom one is symlink path.
![2015-11-26 15-18-52 ssh](https://cloud.githubusercontent.com/assets/1346296/11422953/543458fc-9451-11e5-846c-bbf7193aaa8f.png)

More on that, `git lfs logs last` are empty in this case:
![2015-11-26 15-23-21 ssh](https://cloud.githubusercontent.com/assets/1346296/11422990/b15b6bec-9451-11e5-964c-f189782f05cf.png)

**Comment by dentuzhik** [comment] 2015-11-26 12:32
Probably related to
https://github.com/github/git-lfs/issues/811
https://github.com/github/git-lfs/pull/818

**Comment by dentuzhik** [comment] 2015-11-26 12:54
Tried with merged https://github.com/github/git-lfs/pull/816 patch. No luck.

**Comment by technoweenie** [comment] 2015-11-26 15:38
Cool, thanks for the report. Can you try running `GIT_TRACE=1 git lfs checkout` instead? I wonder what it's doing before it dies of signal 13.

**Comment by ttaylorr** [comment] 2018-04-16 22:38
If I am reading this issue correctly, I believe that it is a duplicate of https://github.com/git-lfs/git-lfs/issues/811, which was fixed in #818.

**Closed by ttaylorr** 2018-04-16 22:38 UTC
Labels: bug
