### ISSUE TITLE
git-lfs hangs on all lfs calls

### ISSUE THREAD

**Issue by papaver** [git-lfs/git-lfs#4663] opened 2021-10-01 04:18 UTC
**Describe the bug**
Any call to lfs hangs.

**To Reproduce**
Any action which triggers a hook with lfs hangs.
 - post-commit 
 - post-checkout
 - pre-push
 - post-merge

**Expected behavior**
LFS to work as expected.

**System environment**
MacOsx Catalina (10.15.7)
Running in bash

```filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.required=true
filter.lfs.process=git-lfs filter-process
http.sslversion=tlsv1.2
http.sslbackend=openssl
```

**Output of `git lfs env`**
This also hangs.

with following debug enabled:

```
     GIT_TRACE=1
     GIT_TRACE_PACKET=1
     GIT_TRACE_PERFORMANCE=1
     GIT_TRACE_SETUP=1
     GIT_CURL_VERBOSE=1
     GIT_TRANSFER_TRACE=1
```

this is output of a commit and then just hangs.

```
setup: git_dir: .git                     
setup: worktree: /Users/papaver/work/test
setup: cwd: /Users/papaver/work/test
setup: prefix: (null)         
trace: built-in: git 'commit' '-m' 'Update makefile.'
trace: run_command: '.git/hooks/post-commit'
trace: exec: 'git-lfs' 'post-commit'
trace: run_command: 'git-lfs' 'post-commit'
```

just started happening a bit ago unexpectedly.  no upgrade nothing.  very confused.  tried to upgrade to latest and same result.  even just running the version command hangs.

any help would be appreciated.

**Comment by bk2204** [comment] 2021-10-01 13:11
Hey,

This does sound unexpected.  Let's see if we can figure out what's going on here.

* What is the output `ulimit -a` on your system?
* Are you operating in a directory that's special to macOS, such as `Desktop` or `Documents`?
* Do you have some sort of security or monitoring software on your system, like an antivirus?
* Where did you get Git LFS from?  Homebrew?  Our official binaries?  Somewhere else?

**Comment by papaver** [comment] 2021-10-01 17:26
`ulimit -a`

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2784
virtual memory          (kbytes, -v) unlimited
```

- no special directory, a subdir under a /Users/papaver/work
- no antivirus or security software
- you official binaries

the only thing i can think of that i did that was a little out of norm was install a dongle driver for avid media composer.  not sure if its related at all but figured i'd mention it.

**Comment by bk2204** [comment] 2021-10-04 16:08
Hey,

I assume our binaries do work on most systems, but it's not clear to me what the relevant difference is.  Apparently Catalina has [some problems where at least some Go binaries hang](https://github.com/golang/go/issues/37885).

You could try some of the following:
* See if syspolicyd is using 100% of the CPU at that point and if so, kill it as mentioned in the issue I linked above.
* Try without the dongle driver, in case it's trying to intercept process start in some way.

**Comment by papaver** [comment] 2021-10-04 23:38
what is lfs doing that the dongle driver would be messing with it?  just curios?

removing the dongle driver isn't really an option.

**Comment by slonopotamus** [comment] 2021-10-05 09:41
> what is lfs doing that the dongle driver would be messing with it? just curios?

We'll tell as soon as we see dongle driver source code!

It is very likely that dongle driver is not the cause of the issue. @bk2204 suggested temporarily removing it as a way to at least somehow diagnose the issue.

**Comment by bk2204** [comment] 2021-10-05 16:52
I'm looking for relevant reasons why things might be failing.  It looks like for some reason the Git LFS processes are failing to spawn or run properly.  That means things in the kernel, like third-party drivers, are potentially interesting.  Also, things that implement any sort of security handling, such as antivirus or monitoring programs, are also interesting, especially since Go programs tend to have a different structure than most other binaries and are frequently flagged by these tools.

In your case, it sounds like you're using some sort of license or DRM dongle, and those are both going to provide third-party drivers and security handling, and therefore they're interesting.  syspolicyd is also interesting because it verifies binary signatures and therefore has security handling, and it's known to be somewhat broken on Go programs on Catalina.

Typically we tend to see this kind of failure on Windows and not macOS, because those two categories of problem cases are more common on Windows.  Of course, it could be something entirely different here, but it's hard for me to know without having access to the system myself.

**Comment by tangshi** [comment] 2021-10-13 08:53
@bk2204 It happened on my device as well after I upgrade git-lfs to the newest v3.0.1. 
I spent almost one day to figure out the reason.

@papaver I solved it by downgrade git-lfs to [v2.13.3](https://github.com/git-lfs/git-lfs/releases/tag/v2.13.3)

**Comment by tangshi** [comment] 2021-10-14 06:45
@bk2204 I'm sorry, but it's difficult for me to bisect the issue to a particular commit, I'm not familiar with golang and git-lfs development(just a git-lfs user). 

In fact I don't know how to reproduce the case, It just happened after I upgrade git-lfs to v3.0.1 by `brew upgrade` and it goes well after I downgrade to the previous release v2.13.3. 

I found it caused by git-lfs because of the git operation logs:
``` 
GIT_CURL_VERBOSE=1 GIT_TRACE=1 git switch any_branch
```

**Comment by bk2204** [comment] 2022-02-07 20:25
Hey,

Since the original issue has been reported to be outside of our project, I'm going to close this issue.  If folks continue to see similar behavior, please open a new issue, filling out the issue template, and we'll look into it.

**Closed by bk2204** 2022-02-07 20:25 UTC
