### ISSUE TITLE
HELP WITH LFS FOR A NOOB

### ISSUE THREAD

**Issue by Giri292002** [git-lfs/git-lfs#4092] opened 2020-04-06 11:00 UTC
I am a beginner with github and all my understanding and fixing problem with github is through documentations and forums. Here's the problem (or not a problem, just a little step I am missing maybe?) I'll tell everything I did that led to the problem I am having, which is basically my .uasset files and .umap files have been made to 1Kb and I can't see them in Unreal Engine and git bash is throwing errors that I don't understand.

**Background**
I am developing a game with UE4 and use github as version control.

**Problem**
I have no idea what's happening, I'll explain everything below.

It all started when a .umap file couldn't push because it was greater than 100 mb. I was confused, because I had LFS enabled. A little bit of snooping here and there confirmed that I had to add .umap and .uasset files to the git attributes.

So these are the lines I added in the git attributes

`*.uasset filter=lfs diff=lfs merge=lfs -text
*.umap filter=lfs diff=lfs merge=lfs -text`

Here's where everything started to crash. I come back to my project and I open up unreal and it said cant open .umap it is an asset file. I said alright open it anyways, and my level is gone, on further investigation I found that my main character asset file is also missing along with other asset files. I went back to the good old internet and started snooping around and everything pointed to one thing -

`git lfs pull`

So I do that and I get this error:

`git lfs pull
Checkout error: pointer parsing: Expected key oid, got <<<<<<<

Errors logged to C:\Users\Gkannan\.git\lfs\logs\20200406T035015.6174722.log
Use `git lfs logs last` to view the log.
Checkout error: pointer parsing: Expected key oid, got <<<<<<<`

I am attaching the log incase you are curious.
[20200406T035015.6254507.log](https://github.com/git-lfs/git-lfs/files/4437859/20200406T035015.6254507.log)

And there you go, that's everything that happened. I am stuck at this point my levels are gone and been replaced with 1Kb files which is apparently pointers and I have no idea how to bring back my original files back into unreal engine 4. I just want my UE4 project back to normal.. As I said before, I am very very new to this, Maybe I am missing something and this is a very easy problem to fix, please explain it to me step by step kindly.

Thank You so much for your time.

**Comment by chrisd8088** [comment] 2020-04-07 02:55
Hey, I'm sorry you're having trouble.

It sounds like your problem is similar to the ones discussed in #3531, where Git LFS expects to find valid pointer files (small files with OIDs in them) but is finding files with Git merge conflict markers (the `<<<<<<<` part), perhaps caused by actions similar to those documented in https://github.com/git-lfs/git-lfs/issues/3531#issuecomment-473170887.

Is it possible that after a regular Git merge operation, Git warned about some conflicts but you may not have resolved those before committing the merge?  If so, that could result in a "broken" pointer file which contains Git's `<<<<<<<` conflict marker as text, instead of valid pointer data.

Unfortunately, I don't have a quick suggestion for finding the problematic file.  I'm not a Windows expert, but you might try something like `findstr /s /c:"<<<<<<" *.*`, using the [`findstr`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/findstr) command.  If you can locate the broken pointer files, using `git log` on them may help you identify when you accidentally committed them while they contained a merge conflict marker.

---

Just as some background, a key concept behind Git LFS is that large files -- the `*.uasset` and `*.umap` ones you've configured in your `.gitattributes` file -- are replaced by pointer files in Git, but the actual full file content *should* be in place in your working tree, because Git LFS steps in and converts the pointer file to the corresponding full data when you pull or fetch, and converts the full data back to a pointer file when you push.

However, you mention that you are not seeing the expected full data files, but the pointer files.  That indicates more may have gone wrong beyond just a single bad merge, although I'm not sure about that.  Looking at your log file, the tail of it includes the output from the `git lfs env` command, and it seems like possibly you may not have Git LFS fully configured.

Would you mind running `git lfs env` and `git config -l` including the full output from both?

**Comment by Giri292002** [comment] 2020-04-07 09:35
Hey, This is what i got from `git lfs env`

git-lfs/2.10.0 (GitHub; windows amd64; go 1.12.7; git a526ba6b)
git version 2.25.1.windows.1

`Endpoint=https://github.com/Giri292002/UntitledFantasyAdventureGame.git/info/lfs (auth=basic)
LocalWorkingDir=C:\Users\Gkannan
LocalGitDir=C:\Users\Gkannan\.git
LocalGitStorageDir=C:\Users\Gkannan\.git
LocalMediaDir=C:\Users\Gkannan\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\Gkannan\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\Gkannan\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Users/Gkannan/AppData/Local/Programs/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Users\Gkannan\AppData\Local\Programs\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
`

And this is what i got from `git config -l`

`diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Users/Gkannan/AppData/Local/Programs/Git/mingw64/ssl/certs/ca-bundle.crt
http.postbuffer=4294967296
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager
user.name=Giri
user.email=pbgiridhara@gmail.com
http.postbuffer=209715200
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
http.postbuffer=209715200
remote.origin.url=https://github.com/Giri292002/UntitledFantasyAdventureGame
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
lfs.https://github.com/Giri292002/UntitledFantasyAdventureGame.git/info/lfs.access=basic
gui.wmstate=zoomed
gui.geometry=893x435+26+26 434 196
`

**Comment by chrisd8088** [comment] 2020-04-08 06:06
Thanks -- well, at least from a configuration perspective, things seem OK on a first glance.

Have you had any luck with `findstr /s /c:"<<<<<<" *.*`?  The idea is to locate any files which may have accidentally ended up including Git's merge conflict markers.

In your `master` branch, I think I see a few:
```
Content/Blueprints/Characters/Enemy02/BP_OxBaren.uasset
Content/World/Workshop.umap
Config/DefaultGame.ini
```

What I would suggest is using `git log` on these files, and any others you find, and then checking out a revision prior to the merge which caused the problem.  That is, if the most recent change is a merge commit, use the commit SHA from the previous commit and do a `git checkout` with that.  The file should at this point be restored to good binary data, which you can copy outside of your working tree.  Switch back to the head of your `master` branch, copy the good binary file back into place, and add and commit it.  That should replace the broken file with a recent, good copy.  So for example, in PowerShell:
```
> git checkout master
> git log .\Content\World\Workshop.umap
commit 71088939059b210f7f073e849a6b6d4ac874e06d
...
    Merge branch 'master' of https://github.com/Giri292002/UntitledFantasyAdventureGame

commit 4f94270c50f9d576e8ed7555e3d36678d5ec322a
...
    ws

> git checkout 4f94270c50f9d576e8ed7555e3d36678d5ec322a
> cp .\Content\World\Workshop.umap ..
> git checkout master
> cp ..\Workshop.umap .\Content\World\Workshop.umap
> git add .\Content\World\Workshop.umap
> git commit -m 'fixup message here'
> del ..\Workshop.umap
```

---

Now as for how things got into this state, these look like files where, when you ran a `git merge` at some point in the past, you would likely have seen a message such as:
```
Auto-merging Content/World/Workshop.umap
CONFLICT (content): Merge conflict in Content/World/Workshop.umap
Automatic merge failed; fix conflicts and then commit the result.
Encountered 1 file(s) that should have been pointers, but weren't:
	Content/World/Workshop.umap
```

By proceeding to commit the file without resolving the conflict, what you end up with are files which no longer have the binary data you're expecting, but instead have corrupted Git LFS pointer data.

Suppose you have file X in your `master` branch, and you create a new branch A.  In branch A, you commit a new version of file X.  Then in your `master` branch, you *also* commit a different, other new version of file X.  When you try to merge your branch A back into `master`, you'll see a conflict message like the one above.

At this point, rather than just moving forward with a `git commit` or `git add`, you need to decide which of the two versions of X you want, get that version in place, and add and commit it.  Personally, in this sort of situation, I would probably run `git merge --abort`, which will put everything back in a known good state, and then spend some time trying to figure out which of the two X's I want.

I hope that all makes some sense and helps a bit.

**Comment by Giri292002** [comment] 2020-04-08 06:11
Hey If I type in `git checkout master`, its giving me this

`=: =: command not found
fatal: the remote end hung up unexpectedly`

**Comment by Giri292002** [comment] 2020-04-08 06:13
Ad I am using hithub desktop so when I merge them right, It automatically merges the files for me, in this case BP_Oxbaren merged automatically for me and just gave me the option to commit or abort, and after I click commit BP_Oxbaren is gone from unreal engine, and its turned into a pointer with the two pointer address. Should I be using git bash to do my push and pulls? :)

Thank you so much for your time and patience!

**Comment by chrisd8088** [comment] 2020-04-08 20:49
I'm not especially familiar with GitHub Desktop, but it sounds like you definitely want to choose "abort" when Desktop indicates there is a conflict during a merge or pull operation, unless you know enough to fix the problem right away.  That will ensure you don't break anything, and can then work to figure out how to resolve the conflict.  That's a good rule for working with Git regardless of your tooling, for that matter.

I would suggest reaching out to the GitHub Desktop support team, and in particular, looking at issue desktop/desktop#7166.  That sounds to me like it may describe what you have experienced.  There is a specific suggestion in https://github.com/desktop/desktop/issues/7166#issuecomment-578441575 to add a `binary` attribute to the lines in your `.gitattributes` file, as a workaround, so yours might be updated to look like:
```
*.uasset filter=lfs diff=lfs merge=lfs -text binary
*.umap filter=lfs diff=lfs merge=lfs -text binary
```

---

As for the problem where `git checkout` is failing with `command not found`, I can't explain that, but it feels like a problem with your shell environment somehow, such that it's trying to run a program named `=`.  You might want to try a different shell, or check your `PATH` environment variable settings.

**Comment by chrisd8088** [comment] 2020-04-14 16:07
As I think we've found the relevant other issues here and provided as much advice as we can, I'm going to close this issue.

**Closed by chrisd8088** 2020-04-14 16:07 UTC

**Comment by MartinLCoatsink** [comment] 2020-11-02 11:20
Still having this in git-lfs/2.11.0. 

Think some files got garbled because .gittattributes was set to "-text" instead of "-binary".

Is there a fix on the way?

**Comment by bk2204** [comment] 2020-11-02 16:21
> Still having this in git-lfs/2.11.0.

If you're seeing a problem, could you open a new issue with full details and reproduction steps?

> Think some files got garbled because .gittattributes was set to "-text" instead of "-binary".

`-text` indicates that the file is not text; `-binary` would turn off the binary attribute, which is probably not what you want here.

**Comment by MartinLCoatsink** [comment] 2020-11-06 11:37
> If you're seeing a problem, could you open a new issue with full details and reproduction steps?
There's an open issue [here](https://github.com/git-lfs/git-lfs/issues/3531). 

I originally intended to comment there, but mixed things up. Let's continue this conversation over there to keep things straight :)
