### ISSUE TITLE
Cloning repositary from local read-only directory

### ISSUE THREAD

**Issue by tsobolev** [git-lfs/git-lfs#5526] opened 2023-09-28 22:49 UTC
**Describe the bug**
Cloning repository from local read-only directory failed.

**To Reproduce**
git clone file:///kaggle/input/indic-wav2vec-accel-v1/indic-wav2vec-benagli-finetuned3/.git my_repo_dir_123

Cloning into 'my_repo_dir_123'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 41 (delta 10), reused 0 (delta 0)
Receiving objects: 100% (41/41), 5.77 KiB | 5.77 MiB/s, done.
Resolving deltas: 100% (10/10), done.
Downloading pytorch_model.bin (1.3 GB)
Error downloading object: pytorch_model.bin (01ecf34): Smudge error: Error downloading pytorch_model.bin (01ecf3456a56184da868d09e265a044b2ba160a475a0d83fbb4cd69bae90dd63): EOF

Errors logged to /kaggle/working/my_repo_dir_123/.git/lfs/logs/20230928T224300.572027939.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: pytorch_model.bin: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/

**Expected behavior**

**System environment**
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
diff.jupyternotebook.command=git-nbdiffdriver diff
merge.jupyternotebook.driver=git-nbmergedriver merge %O %A %B %L %P
merge.jupyternotebook.name=jupyter notebook merge driver
difftool.nbdime.cmd=git-nbdifftool diff "$LOCAL" "$REMOTE" "$BASE"
difftool.prompt=false
mergetool.nbdime.cmd=git-nbmergetool merge "$BASE" "$LOCAL" "$REMOTE" "$MERGED"
mergetool.prompt=false
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f

**Output of `git lfs env`**
git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5)
git version 2.25.1

Error: Failed to call git rev-parse --git-dir: exit status 128 
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_COMMIT=5b37fe29fefdef02f55a8db1fff9f9b63826f777
GIT_EXEC_PATH=/usr/lib/git-core
GIT_PAGER=cat
GIT_PYTHON_REFRESH=quiet
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**

22:33:19.407723 git.c:439               trace: built-in: git clone file:///kaggle/input/indic-wav2vec-accel-v1/indic-wav2vec-benagli-finetuned3/.git my_repo_dir_123
Cloning into 'my_repo_dir_123'...
22:33:19.410939 run-command.c:663       trace: run_command: unset GIT_DIR; 'git-upload-pack '\''/kaggle/input/indic-wav2vec-accel-v1/indic-wav2vec-benagli-finetuned3/.git'\'''
22:33:19.414248 git.c:439               trace: built-in: git upload-pack /kaggle/input/indic-wav2vec-accel-v1/indic-wav2vec-benagli-finetuned3/.git
22:33:19.430684 run-command.c:663       trace: run_command: git pack-objects --revs --thin --stdout --progress --delta-base-offset
22:33:19.430916 run-command.c:663       trace: run_command: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 2460 on 326ab7d42961' --check-self-contained-and-connected
22:33:19.433099 git.c:439               trace: built-in: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 2460 on 326ab7d42961' --check-self-contained-and-connected
remote: 22:33:19.434745 git.c:439               trace: built-in: git pack-objects --revs --thin --stdout --progress --delta-base-offset
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 41 (delta 10), reused 0 (delta 0)
Receiving objects: 100% (41/41), 5.77 KiB | 5.77 MiB/s, done.
Resolving deltas: 100% (10/10), done.
22:33:19.581094 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs '--progress=Checking connectivity'
22:33:19.583361 git.c:439               trace: built-in: git rev-list --objects --stdin --not --all --quiet --alternate-refs '--progress=Checking connectivity'
22:33:19.587148 run-command.c:663       trace: run_command: 'git-lfs filter-process'
22:33:19.594271 trace git-lfs: exec: git 'version'
22:33:19.599976 trace git-lfs: exec: git 'config' '-l'
22:33:19.602662 trace git-lfs: Install hook: pre-push, force=false, path=/kaggle/working/my_repo_dir_123/.git/hooks/pre-push
22:33:19.602837 trace git-lfs: Install hook: post-checkout, force=false, path=/kaggle/working/my_repo_dir_123/.git/hooks/post-checkout
22:33:19.602899 trace git-lfs: Install hook: post-commit, force=false, path=/kaggle/working/my_repo_dir_123/.git/hooks/post-commit
22:33:19.602981 trace git-lfs: Install hook: post-merge, force=false, path=/kaggle/working/my_repo_dir_123/.git/hooks/post-merge
22:33:19.603059 trace git-lfs: Initialize filter-process
22:33:19.603350 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
22:33:19.606083 trace git-lfs: tq: running as batched queue, batch size of 100
22:33:19.606498 trace git-lfs: filepathfilter: accepting "pytorch_model.bin"
22:33:19.607034 trace git-lfs: tq: sending batch of size 1
22:33:19.607064 trace git-lfs: tq: starting transfer adapter "lfs-standalone-file"
22:33:19.623407 trace git-lfs: xfer[git-lfs]: error creating handler: failed to call git rev-parse --git-dir: exit status 128
22:33:19.624599 trace git-lfs: filepathfilter: accepting "pytorch_model.bin"
Downloading pytorch_model.bin (1.3 GB)
22:33:19.624767 trace git-lfs: tq: running as batched queue, batch size of 100
22:33:19.624821 trace git-lfs: tq: sending batch of size 1
22:33:19.624836 trace git-lfs: tq: starting transfer adapter "lfs-standalone-file"
22:33:19.644796 trace git-lfs: xfer[git-lfs]: error creating handler: failed to call git rev-parse --git-dir: exit status 128
Error downloading object: pytorch_model.bin (01ecf34): Smudge error: Error downloading pytorch_model.bin (01ecf3456a56184da868d09e265a044b2ba160a475a0d83fbb4cd69bae90dd63): EOF

Errors logged to /kaggle/working/my_repo_dir_123/.git/lfs/logs/20230928T223319.645716647.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: pytorch_model.bin: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by bk2204** [comment] 2023-09-29 13:34
Hey,

Is the directory from which you're cloning owned by another user?  If so, this is a duplicate of #5448.  If not, can you try a newer version of Git LFS?  We've implemented a large number of improvements to the file backend since v2.9.2, and it may very well be that we've fixed it, since I'm not able to reproduce this on the latest `main`.

**Comment by tsobolev** [comment] 2023-09-29 16:30
Hello,

With version 3.4.0, it is possible to clone a repository and then check out a specific commit:

```
git config --global --add safe.directory /kaggle/input/whisper-small-bn-accel-v1/whisper-small-bn-accelerate
git clone /kaggle/input/whisper-small-bn-accel-v1/whisper-small-bn-accelerate/.git my_repo
cd my_repo 
git checkout 123c8a44e8741113ad8492d1f732f92fc18ac3be
```

However, if I attempt to fetch only the necessary file:
 
```
GIT_LFS_SKIP_SMUDGE=1 git clone /kaggle/input/whisper-small-bn-accel-v1/whisper-small-bn-accelerate/.git my_repo
cd my_repo 
GIT_LFS_SKIP_SMUDGE=1 git checkout 123c8a44e8741113ad8492d1f732f92fc18ac3be
git lfs fetch pytorch_model.bin
```

Unfortunately, there is still no success:

```
fetch: Fetching reference HEAD
error initializing custom adapter "lfs-standalone-file" worker 0: [0] error creating handler: no valid file:// URLs found
error: failed to fetch some objects from 'file:///kaggle/input/whisper-small-bn-accel-v1/whisper-small-bn-accelerate/.git'
```

Could you please give me advice on how to fetch only the necessary file without copying the entire repository?

**Closed** 2023-09-29 19:47 UTC
