### ISSUE TITLE
git lfs migrate import failure when used with multiple include file paths

### ISSUE THREAD

**Issue by wilddeej** [git-lfs/git-lfs#4272] opened 2020-10-07 17:08 UTC
**Describe the bug**
git lfs migrate import --everything does not actually migrate all specified --include files.  This only seems to happen when --include files are file paths;  file _types_ are handled correctly, from all apparencies.

**To Reproduce**
1. git clone https://github.com/git-lfs/git-lfs.git
2. cd git-lfs
3. git lfs install
4. git lfs migrate import --everything --include=git/githistory/fixtures/identical-blobs.git/index,git/githistory/fixtures/identical-blobs.git/objects/94/f3610c08588440112ed977376f26a8fba169b0,git/githistory/fixtures/identical-blobs.git/objects/b6/2b45ed2b59cf32dd676ca47497e76a1dab9c7e,git/githistory/fixtures/linear-history-with-annotated-tags.git/index,git/githistory/fixtures/linear-history-with-annotated-tags.git/objects/05/797a38b05f910e6efe40dc1a5c0a046a9403e8,git/githistory/fixtures/linear-history-with-annotated-tags.git/objects/20/ecedad3e74a113695fe5f00ab003694e2e1e9c,git/githistory/fixtures/linear-history-with-annotated-tags.git/objects/22/8afe30855933151f7a88e70d9d88314fd2f191,git/githistory/fixtures/linear-history-with-annotated-tags.git/objects/2e/65efe2a145dda7ee51d1741299f848e5bf752e,git/githistory/fixtures/linear-history-with-annotated-tags.git/objects/34/10062ba67c5ed59b854387a8bc0ec012479368,git/githistory/fixtures/linear-history-with-annotated-tags.git/objects/3c/b3201d7942353fff5f45e03d114e8e7a061f87,git/githistory/fixtures/linear-history-with-annotated-tags.git/objects/4a/78e180c45f18489941174df19d538c26d5318b,git/githistory/fixtures/linear-history-with-annotated-tags.git/objects/52/a8963f48d54c7d352695a278ca4b025e130cb4,git/githistory/fixtures/linear-history-with-annotated-tags.git/objects/63/d8dbd40c23542e740659a7168a0ce3138ea748,git/githistory/fixtures/linear-history-with-annotated-tags.git/objects/6b/de0b381fa1a039396445e2ce5a28c0451fde15,git/githistory/fixtures/linear-history-with-annotated-tags.git/objects/91/b85be6928569390e937479509b80a1d0dccb0c,git/githistory/fixtures/linear-history-with-annotated-tags.git/objects/d9/41e4756add6b06f5bee766fcf669f55419f13f,git/githistory/fixtures/linear-history-with-tags.git/index,git/githistory/fixtures/linear-history-with-tags.git/objects/20/ecedad3e74a113695fe5f00ab003694e2e1e9c,git/githistory/fixtures/linear-history-with-tags.git/objects/22/8afe30855933151f7a88e70d9d88314fd2f191,git/githistory/fixtures/linear-history-with-tags.git/objects/2e/65efe2a145dda7ee51d1741299f848e5bf752e,git/githistory/fixtures/linear-history-with-tags.git/objects/34/10062ba67c5ed59b854387a8bc0ec012479368,git/githistory/fixtures/linear-history-with-tags.git/objects/3c/b3201d7942353fff5f45e03d114e8e7a061f87,git/githistory/fixtures/linear-history-with-tags.git/objects/52/a8963f48d54c7d352695a278ca4b025e130cb4,git/githistory/fixtures/linear-history-with-tags.git/objects/63/d8dbd40c23542e740659a7168a0ce3138ea748,git/githistory/fixtures/linear-history-with-tags.git/objects/91/b85be6928569390e937479509b80a1d0dccb0c,git/githistory/fixtures/linear-history-with-tags.git/objects/d9/41e4756add6b06f5bee766fcf669f55419f13f,git/githistory/fixtures/linear-history.git/index,git/githistory/fixtures/linear-history.git/objects/56/a6051ca2b02b04ef92d5150c9ef600403cb1de,git/githistory/fixtures/linear-history.git/objects/6e/07bd31cb70c4add2c973481ad4fa38b235ca69,git/githistory/fixtures/linear-history.git/objects/71/a488ec1804ee97ea651b094aa9181ca85aab0a,git/githistory/fixtures/linear-history.git/objects/c5/decfe1fcf39b8c489f4a0bf3b3823676339f80,git/githistory/fixtures/linear-history.git/objects/d8/263ee9860594d2806b0dfd1bfd17528b0ba2a4,git/githistory/fixtures/linear-history.git/objects/e4/40e5c842586965a7fb77deda2eca68612b1f53,git/githistory/fixtures/linear-history.git/objects/ef/eab7a9b61312fa56fc74eee1e0f5a714abfb70,git/githistory/fixtures/non-repeated-subtrees.git/index,git/githistory/fixtures/non-repeated-subtrees.git/objects/07/bd7fbfc41b7d36135bcffe7c465490f4aca32d,git/githistory/fixtures/non-repeated-subtrees.git/objects/12/7ececad475cde6da0048051d62121cabd23194,git/githistory/fixtures/non-repeated-subtrees.git/objects/19/acdd81ab0abc15c771fe005bf1c2825e4e6080,git/githistory/fixtures/non-repeated-subtrees.git/objects/37/f99c7f2706d317b3bf7ff13d574eef33d8788a,git/githistory/fixtures/non-repeated-subtrees.git/objects/3d/1baaaceec085c52e3e57a47a75b87b7615d0ef,git/githistory/fixtures/non-repeated-subtrees.git/objects/8d/14cbf983b3fad683171c9418998d9f68340823,git/githistory/fixtures/octopus-merge.git/index,git/githistory/fixtures/octopus-merge.git/objects/04/df07b08ca746b3167d0f1d1514e2f39a52c16c,git/githistory/fixtures/octopus-merge.git/objects/15/805fe2044dc1a0508853e93d1a230bd94636be,git/githistory/fixtures/octopus-merge.git/objects/25/1e6b3461a3b5adc6bab694d5ae1abc878edf85,git/githistory/fixtures/octopus-merge.git/objects/2e/65efe2a145dda7ee51d1741299f848e5bf752e,git/githistory/fixtures/octopus-merge.git/objects/2f/3a8ec99d5b459b41b6675e52758e397c5e3103,git/githistory/fixtures/octopus-merge.git/objects/5a/0581b158a81b8fc5d2169c2ac2ca7772ff13fd,git/githistory/fixtures/octopus-merge.git/objects/63/d8dbd40c23542e740659a7168a0ce3138ea748,git/githistory/fixtures/octopus-merge.git/objects/8b/e6d64cddab01f53381e9feafe50d95ca5e6629,git/githistory/fixtures/octopus-merge.git/objects/b6/fc4c620b67d95f953a5c1c1230aaab5db5a1b0,git/githistory/fixtures/octopus-merge.git/objects/e9/4edfabfb7605f7cb959b4ce8fb6652b509fe03,git/githistory/fixtures/packed-objects.git/index,git/githistory/fixtures/packed-objects.git/objects/pack/pack-ac516ce2d006668dc5e001e8dda0aa1c7198500f.idx,git/githistory/fixtures/packed-objects.git/objects/pack/pack-ac516ce2d006668dc5e001e8dda0aa1c7198500f.pack,git/githistory/fixtures/repeated-subtrees.git/index,git/githistory/fixtures/repeated-subtrees.git/objects/12/b98c239e8f933d213617a1b965333d478b2743,git/githistory/fixtures/repeated-subtrees.git/objects/2e/65efe2a145dda7ee51d1741299f848e5bf752e,git/githistory/fixtures/repeated-subtrees.git/objects/47/d4d71022adc7ec6a14250d23491e535ec228f4,git/githistory/fixtures/repeated-subtrees.git/objects/5e/497ceceb14ad3c43bac781ed5c804bc67e8f3b,git/githistory/fixtures/repeated-subtrees.git/objects/63/d8dbd40c23542e740659a7168a0ce3138ea748,git/githistory/fixtures/repeated-subtrees.git/objects/b9/621d5d84b3174de020ad2c869f43b2f61f337f,git/githistory/fixtures/repeated-subtrees.git/objects/bc/4d1181aca5a33673d7c5d4c209d09ce1cfabd7,vendor/golang.org/x/sys/windows/zerrors_windows.go
    Migration completes successfully after some time; no errors indicated
5. git status
    Output indicates a clean working tree, nothing to commit
6. grep git/githistory/fixtures/identical-blobs.git/index .gitattributes
    Output indicates the file is present in .gitattributes, implying it is under Git-LFS tracking
7. git lfs ls-files | grep git/githistory/fixtures/identical-blobs.git/index
    No output; file is not being tracked by Git-LFS
8. git show HEAD:git/githistory/fixtures/identical-blobs.git/index
    Output does NOT indicate a Git-LFS pointer file as expected/directed by the migrate arguments

Despite being directed to migrate/track the indicated file, it is not (really) being tracked by Git-LFS.  To make matters worse, the .gitattributes file includes an entry indicating the file *is* being tracked with Git-LFS, which ends up causing other strange behavior if/when the migrated repository is pushed and subsequently cloned (such as _working tree files constantly showing as modified_ - a condition specifically called out in the Git-LFS FAQ, and attributed to someone making a commit to a file being tracked by Git LFS but not having Git LFS properly set up on their system).

**Expected behavior**
All specified file paths tracked as Git-LFS files

**System environment**
Windows 10 (VM-based), git-bash window

**Output of `git lfs env`**
`git-lfs/2.11.0 (GitHub; windows amd64; go 1.14.2; git 48b28d97)
git version 2.28.0.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
`

**Additional context**
List of files determined by programmatically analyzing the working copy for binary files and those over 400Kb in size

**Comment by chrisd8088** [comment] 2020-10-08 07:34
Hey, I'm sorry to having trouble.  After experimenting a bit with the process you outline, and using `GIT_TRACE=1` on the `git lfs migrate import` commands, I think I see what's going on here.

The specific problem is that, as the `git lfs migrate import` command moves forwards through the Git history of the project (in this case, the `git-lfs/git-lfs` repo itself, but it could be any repository), it is trying to match against the very long list of specific file paths you're providing on the command line with the `--include` option, such as `git/githistory/fixtures/identical-blobs.git/index` and so forth.

But as it happens, it never encounters a Git blob object matching that "include" path.  How is that possible, given that one can see a file with that path [right now](https://github.com/git-lfs/git-lfs/blob/68a8f8a49d834c91c9e9d39bc53c6fc065122dbd/git/githistory/fixtures/identical-blobs.git/index) in the repository?  It's because the objects currently in that location were originally created in a different location, prior to this particular [commit](https://github.com/git-lfs/git-lfs/commit/6896413a1eb9d5124a367649889c6ee76b9c06c3).  And since the objects didn't change, they were just moved, no new Git blob objects were created for them in the Git history; they were just assigned to a new tree object.  So `git lfs migrate import` only encounters them once, when they were first added, and at that time when it resolves their paths it sees they don't match any of your include patterns; this is from the tracing output:
```
trace git-lfs: filepathfilter: rejecting "git/odb/fixtures/identical-blobs.git/index" via [git/githistory/fixtures/identical-blobs.git/index]
```

So the more general challenge here is that supplying a set of include patterns, both for one-time Git LFS migration and for ongoing work (say, by using `git lfs track` to help add new patterns to `.gitattributes`), is a bit of an art -- you want patterns which will match effectively even as you move things around in your repo over time.  A big whitelist of explicit file paths is going to be fragile; for instance, if a new file was added under `git/githistory/fixtures/identical-blobs.git/`, it wouldn't catch that, and it would also break if these files are moved again.

In this particular example case of the `git-lfs/git-lfs` repo itself, it might be worth trying something like `--include="**/fixtures/*.git/**"`.  Trying again with that, I get:
```
$ git lfs ls-files
f6f2b945f6 - git/githistory/fixtures/identical-blobs.git/HEAD
cae33efdb0 - git/githistory/fixtures/identical-blobs.git/config
c6e70c0dc2 - git/githistory/fixtures/identical-blobs.git/index
...
```

**Closed by chrisd8088** 2020-10-08 07:34 UTC

**Comment by wilddeej** [comment] 2020-10-08 15:03
Thank you for your detailed and insightful analysis, @chrisd8088!  I see how what you uncovered would be at the core of the issue I reported, and can agree that this indicates that there is not an issue with git-migrate...
Except that there is - if the file is not going to be tracked, it should also not list the file in .gitattributes, which causes the same problem behavior "downstream" that I mention.  For this reason, I think this Issue should be re-opened against the faulty addition of the file(s) to the .gitattributes file.

**Comment by chrisd8088** [comment] 2020-10-08 22:07
Thanks for following up -- I took an additional look at what is going on here, and it seems like I was able to reproduce some inconsistent behaviour for files which have been moved in the history of the repository, but only when what is actually "moved" is the tree object to which they belong.  Rather than re-open this issue, I think I'll add that test case to #4167 where we've been waiting for a reproducible example.  Thanks again for the followup!

**Comment by wilddeej** [comment] 2020-10-09 10:46
I guess I need to submit a new issue for the errant entries made in the .gitattributes files then, @chrisd8088.

**Comment by chrisd8088** [comment] 2020-10-09 20:13
I don't think so -- I think that's covered in my notes in https://github.com/git-lfs/git-lfs/issues/4167#issuecomment-705858346.  Those entries are correct, I would argue, and the bug is that the corresponding files which should match the `--include` paths aren't being migrated.  If they were migrated correctly, the `.gitattributes` entries would be fine.  We don't want to undo those entries; we want to fix the bug in the migration of files so they align with the `.gitattributes` entries.  Anyway, that's my take on it at the moment.
