### ISSUE TITLE
git-lfs does not check out new objects after rebase

### ISSUE THREAD

**Issue by ErikaEllison** [git-lfs/git-lfs#3743] opened 2019-07-29 18:00 UTC
git-lfs fails to checkout new lfs objects after rebasing commits in which lfs objects were added.
I have a simple-as-possible repro case here: https://github.com/ErikaEllison/git-lfs-rebase-repro

I've been able to reproduce this on MacOS and Linux:

git-lfs/2.8.0 (GitHub; darwin amd64; go 1.12.7)
git version 2.22.0

git-lfs/2.8.0 (GitHub; linux amd64; go 1.12.6)
git version 2.19.2

full `git lfs env`:
```
git-lfs/2.8.0 (GitHub; darwin amd64; go 1.12.7)
git version 2.22.0

Endpoint=https://github.com/ErikaEllison/git-lfs-rebase-repro.git/info/lfs (auth=basic)
LocalWorkingDir=/Users/erikaellison/code/git-lfs-rebase-repro
LocalGitDir=/Users/erikaellison/code/git-lfs-rebase-repro/.git
LocalGitStorageDir=/Users/erikaellison/code/git-lfs-rebase-repro/.git
LocalMediaDir=/Users/erikaellison/code/git-lfs-rebase-repro/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/erikaellison/code/git-lfs-rebase-repro/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/erikaellison/code/git-lfs-rebase-repro/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=/usr/local/Cellar/git/2.22.0/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment] 2019-07-29 18:23
Hey,

Thanks for writing in. I can definitely reproduce this issue. I believe this is because the default `git rebase` behavior is to use `git am`, which apparently doesn't run smudge or clean filters. I did test with `git rebase -m` and `git rebase -i`, and there things appear to work properly.

I'm going to flag this as an upstream issue, since it is, and try to raise it with the Git folks. There's been some discussion upstream about switching to make `-m` the default, since it's much faster and supports renames, so this may become a non-issue in the near future.

**Comment by bk2204** [comment] 2019-08-09 11:16
Just to update you on this, I've done some analysis on this issue, and the problem is not that we don't run filters, but that we cache the attributes for the life of the rebase, which means that later patches aren't affected by changes made to `.gitattributes` in earlier ones.

I've posted [a patch to the Git list](https://public-inbox.org/git/20190809100217.427178-1-sandals@crustytoothpaste.net/T/) which should fix this issue. It likely won't make it into Git 2.23, since we're in the middle of -rc versions now, but hopefully it will be in 2.24.

**Comment by bk2204** [comment] 2019-09-26 13:45
Hey, the patch here has been picked up and is now in the Git `master` branch, so I'm going to close this.  Things should work right in Git 2.24.  Thanks again for reporting.

**Closed by bk2204** 2019-09-26 13:45 UTC
Labels: git-core

**Comment by TTimo** [comment] 2019-10-15 19:53
Is it possible that this bug surfaces when doing operations other than a rebase? Just a regular pull or maybe branch merges?

I have a machine part of our CI pipeline that has taken to leave some files as LFS pointers, and one difference I can identify is that it has ` 2.23.0.windows.1` installed whereas other boxes that do not have a problem are on `2.21.0.windows.1`

**Comment by bk2204** [comment] 2019-10-15 20:01
I'm not aware of any case where it's known that this occurs, but before this issue was reported, we didn't know that it occurred during rebase, either, so anything's possible.  We'd love to hear in a new issue if you can reproduce this occurring.
