### ISSUE TITLE
Import with `--no-rewrite` option adds incorrect commit timestamp

### ISSUE THREAD

**Issue by gtsiolis** [git-lfs/git-lfs#3310] opened 2018-10-10 13:05 UTC
I've tried to use the import migration mode and this added in a new commit with the following date:

```shell
Date:   Thu Jan 1 00:00:00 1970 +0000 
```

The migration used is the following:

```shell
git lfs migrate import --no-rewrite -m'Commit message...' path/to/files/*.png
```
This can be replicated without the commit message, too.

**Comment by gtsiolis** [comment] 2018-10-11 07:32
@ttaylorr can you verify this? Maybe I'm missing something.

**Comment by bk2204** [comment] 2018-10-11 13:36
Yup, I can confirm this.  Let me see about fixing this.

**Comment by bk2204** [comment] 2018-10-11 13:46
Oh, dear.  This is bad.  We're writing commit entries without a timestamp at all.  `git fsck` is not amused.

**Comment by ttaylorr** [comment] 2018-10-11 16:53
> We're writing commit entries without a timestamp at all.  `git fsck`
> is not amused.

I can imagine so. This is almost certainly my fault, so I appreciate
your assigning this to yourself. I'll look forward to taking a look at
your fix.

**Comment by gtsiolis** [comment] 2018-10-11 17:03
Thanks for confirming this @bk2204! I've temporarily updated the timestamp using `--amend` after the migration (see https://gitlab.com/gitlab-org/gitlab-design/merge_requests/66#note_108087036).

**Comment by bk2204** [comment] 2018-10-11 18:48
Sounds good.  That's a good workaround for now.  I've got a fix that I'm testing and I should have a pull request in shortly.

**Comment by bk2204** [comment] 2018-10-11 18:49
One note, you may want to use `--reset-author` as well, since the author timestamp will be similarly malformed.

**Closed** 2018-10-11 20:40 UTC

**Comment by gtsiolis** [comment] 2018-10-12 10:38
Thanks @bk2204! I tried `git log --pretty=format:"%h %aI %cI"` to print the author and committer date in strict ISO 8601 format but they were identical. Probably `--amend` updates both timestamps simultaneously, unless you mean something else.

**Comment by bk2204** [comment] 2018-10-12 13:28
If you have two valid timestamps, then you're good.
