### ISSUE TITLE
Cannot push using git LFS.

### ISSUE THREAD

**Issue by dkalaxdk** [git-lfs/git-lfs#3337] opened 2018-10-22 07:03 UTC
I cannot push using git LFS, nor can i untrack any files from git LFS. I have tried my best to untrack/retrack the files. Having both uninstalled git and git-lfs.

I get the following error:

Uploading LFS objects: 100% (1/1), 138 MB | 0 B/s, done                         
Counting objects: 22, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (19/19), done.
Writing objects: 100% (22/22), 10.83 MiB | 1.20 MiB/s, done.
Total 22 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 1 local object.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: b40e5da57527943045df5918e5a9f1a0
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File map is 131.75 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/hooolius/p1_pakkelevering.git
 ! [remote rejected] dev -> dev (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/hooolius/p1_pakkelevering.git'

**Comment by bk2204** [comment] 2018-10-22 19:13
It looks like this is a duplicate of #3338, so I'm going to close this in favor of that one.

**Closed by bk2204** 2018-10-22 19:13 UTC
