### ISSUE TITLE
Uploading failed due to unsupported Content-Type header

### ISSUE THREAD

**Issue by jfcarp-bfg** [git-lfs/git-lfs#4160] opened 2020-06-13 01:28 UTC
**Describe the issue**
The basic gist is after a few days of attempting to migrate a specific repository to GitHub we kept getting the same error on a single LFS file. The error being:
```
Git LFS: (0 of 1 files, 962 skipped) 2.21 GB / 2.21 GB, 7.67 GB skipped
Client error: https://lfs.github.com/[redacted]/objects/4b975d54d850f433f807f5020cc2b5b904363b21dd7c3f9e9186ae69851d3a95/verify from HTTP 422
```

This file is a pdb file with size of 2.3 GB. After upgrading to git-lfs 2.11.0, I was fortunate enough to receive a much nicer error.
```
info: Uploading failed due to unsupported Content-Type header(s).
info: Consider disabling Content-Type detection with:
info:
info:   $ git config lfs.contenttype false
```

I tried running the command it recommended, as well as replacing false with 0 (per a separate issue), but resulted in the same error. 
`git config lfs.contenttype false`

I have tried about 5 different versions of lfs (all with the same git version). All resulting in either the first or second error posted. I am beginning to think it is some issue with this specific file, but thought I would file an issue in hopes someone can help me verify that it is this and not an lfs issue with the specific file type. The file does not seem to be corrupt and is used currently in builds.

Running `file` on the file results in:
`MSVC program database ver 7.00, 4096*578474 bytes`

Thank you in advance, any assistance is greatly appreciated. Please let me know if any other information is required. 

**System environment**
Tested utilizing Ubuntu 18.04 and git-lfs/2.3.4
Tested utilizing docker image ubuntu:18.04 with git-lfs versions 2.3.4, 2.4.1, 2.5.0, 2.10.0, 2.11.0

**Output of `git lfs env`**
```
$ git lfs env
git-lfs/2.10.0 (GitHub; linux amd64; go 1.13.4)
git version 2.17.1

Endpoint=https://github.com/[redacted].git/info/lfs (auth=none)
  SSH=git@github.com:[redacted].git
LocalWorkingDir=/opt/repro
LocalGitDir=/opt/repro/.git
LocalGitStorageDir=/opt/repro/.git
LocalMediaDir=/opt/repro/.git/lfs/objects
LocalReferenceDirs=
TempDir=/opt/repro/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/opt/repro/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
The file was accepted by gitlab with/without lfs (custom gitlab server, not SaaS).

Tested with two different large files over 2GB, an ubuntu iso (2.5GB) and a dd generated file of 2.4GB, both were successful. 

I tested taking the file in question and creating a brand new repo with nothing else in it, but this file. Resulting in the same errors as above. It was the typical new lfs repo commands, nothing special.
```
git init
git lfs install
git lfs track '*.pdb'
git add .gitattributes
git commit -m 'gitattributes'
git remote add origin [url]
git push --set-upstream origin master
```

**Comment by bk2204** [comment] 2020-06-15 13:46
Hey,

Can you run your push command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and post the result here (preferably as an attachment)?  Note that this contains authentication credentials that you'll want to strip out.

**Comment by jfcarp-bfg** [comment] 2020-06-15 15:54
Good Morning,

Thank you kindly for your response. 

The push was run with the above variables for:

version 2.3.4 on Ubuntu 18.04
[gitlfs-repro-issue-4160-v2.3.4.txt](https://github.com/git-lfs/git-lfs/files/4781408/gitlfs-repro-issue-4160-v2.3.4.txt)

version 2.11.0 on docker Ubuntu 18.04
[gitlfs-repro-issue-4160-v2.11.0.txt](https://github.com/git-lfs/git-lfs/files/4781409/gitlfs-repro-issue-4160-v2.11.0.txt)

I've redacted anything that looks like a token, so hopefully I got it all. The upload was initialized with ssh. It just seems to be this one file and always a response of 422 Unprocessable Entity. Thank you in advance.

**Comment by bk2204** [comment] 2020-06-15 17:12
Hey,

I don't think this is actually an unsupported Content-Type header, because I don't believe GitHub actually has problems with those headers.  So in this case, that error message is misleading, since we try to guess what the problem is but guess wrong here.  I believe this is actually a server-side problem, and so you'll probably want to reach out to GitHub Support about it.

I will provide one thought to help: it's possible that if you have attempted to upload an object with the same hash but different sizes, that can cause this problem to occur.  It's extremely unlikely that such an issue can occur in reality (and there are a bunch of cryptographers who will be interested if that's actually the case), but it could happen due to some bug in the tooling, a corrupted pointer file, or a truncated LFS object.

Having said that, if that's not the case for your repository, I'd reach out to GitHub Support, since they've probably seen this issue before and can help you out.

**Closed by bk2204** 2020-06-15 17:12 UTC
