### ISSUE TITLE
git-lfs lock fails on Windows if the process's working directory does not match file system case

### ISSUE THREAD

**Issue by mstrap** [git-lfs/git-lfs#3276] opened 2018-09-21 10:15 UTC
When invoking `git lfs lock` or `git lfs unlock` programatically and providing the process's working directory with wrong file system case, both commands will fail with unexpected errors. For example, when invoking Git-LFS from following Java snippet:

	public static void main(String[] args) throws Exception {
		ProcessBuilder builder = new ProcessBuilder();
		Map<String, String> env = builder.environment();
		String gitBin = "d:/temp/git64/bin";
		env.put("Path", gitBin + ";" + env.get("Path"));

		String repoRoot = "D:/temp/gitlab.lfs.clone";

		builder.directory(new File(repoRoot));
		builder.command(Arrays.asList(gitBin + "/git.exe", "lfs", "lock", "huge"));
		builder.redirectOutput(ProcessBuilder.Redirect.INHERIT);
		builder.redirectError(ProcessBuilder.Redirect.INHERIT);

		final Process process = builder.start();
		process.waitFor();
	}

this works fine and outputs:

    Locked huge

However, when using repoRoot with wrong case (small 'd'):

    String repoRoot = "d:/temp/gitlab.lfs.clone";

It will fail with:

    Lock failed: CreateFile d:\temp\gitlab.lfs.clone\D:\temp\gitlab.lfs.clone\huge: The filename, directory name or volume label syntax is incorrect.

Note that it doesn't matter whether using forward-slashes or back-slashes.

**Expected behavior**

`lock` and `unlock` should work regardless of the working directory path case.

**Notes**

`git lfs locks` works fine.

`git lfs status` works, but will report absolute paths in case of wrong path case.

Tested with git-lfs/2.5.1 (GitHub; windows amd64; go 1.10.3; git e1628484).

**Comment by bk2204** [comment] 2018-09-21 13:55
Thanks for reporting this.  It looks like we try to turn the relative path to an absolute path and then back again, which is what's causing this.  Let me see if there's an easy fix for this.

I may ping you about testing to make sure that the code works in your situation, since I'm not on Windows.

**Comment by bk2204** [comment] 2018-09-21 14:55
Okay, I have a branch called [windows-relpath](https://github.com/bk2204/git-lfs/tree/windows-relpath).  Can you test it and see if it works for your particular case?

**Comment by mstrap** [comment] 2018-09-21 17:14
I can confirm that both `lock` and `unlock` work fine now. Thanks for this extremely fast fix!

**Comment by bk2204** [comment] 2018-09-21 17:26
Great! I’ll submit it shortly.

**Closed** 2018-09-21 18:56 UTC

**Comment by Shilpah123** [comment] 2019-05-22 08:51
Hi,
The lock command - git lfs lock <filename> does not seem to work and returns the error: Lock failed: exit status 1. Can anyone help please?

**Comment by bk2204** [comment] 2019-05-22 16:25
Hey, @Shilpah123, could you open a new issue and run your command with `GIT_TRACE=1` and paste that output and the output of `git lfs env` into your issue? That will help us track down what the problem is.
