### ISSUE TITLE
Line endings in tracked files not changing on Windows

### ISSUE THREAD

**Issue by jdsterritt** [git-lfs/git-lfs#2119] opened 2017-03-31 02:40 UTC
Files being tracks by LFS don't have the proper line endings applied when cloning a repo to my Windows environment. All files tracked with LFS retain (LF) line endings.  All other files in the repo have the correct line endings (CLRF) according to the autoclrf setting.

**Comment by ttaylorr** [comment] 2017-03-31 16:11
Closing as a duplicate of: https://github.com/git-lfs/git-lfs/issues/824.

**Closed by ttaylorr** 2017-03-31 16:11 UTC
