### ISSUE TITLE
Retrieve files contents from remote - how?

### ISSUE THREAD

**Issue by Elhazinforever** [git-lfs/git-lfs#5685] opened 2024-03-17 06:47 UTC
### Discussed in https://github.com/git-lfs/git-lfs/discussions/5684

<div type='discussions-op-text'>

<sup>Originally posted by **lapinott** March 16, 2024</sup>
Hello,

I have pushed a library of mp3 music files to my server with git lfs.

Then I tested a git clone to the repo locally. I notice the cloned files are somehow placeholders (I know this is how git lfs works internally, i.e. not clone the full files data).

Example file data:

> version https://git-lfs.github.com/spec/v1
> oid sha256:2236d7b3ee263a52c639ff2162e162fc4968ca65fa68dd51f00d69788df19eae
> size 1411958

How do I get the full files data back from the remote ? Is there a special git lfs command for that ?

Thank you.</div>

**Comment by chrisd8088** [comment] 2024-03-17 17:09
I'm going to close this as it is a duplicate of an existing discussion and so does not appear to add any value.

Please stop opening spurious issues and making inappropriate comments on existing issues, or we will have to report you and suspend your access to the project.

**Closed by chrisd8088** 2024-03-17 17:09 UTC
