### ISSUE TITLE
Ubuntu install instructions in wiki are misleading

### ISSUE THREAD

**Issue by mcclure** [git-lfs/git-lfs#3761] opened 2019-08-08 22:12 UTC
I wanted to run git lfs on ubuntu. So I typed "git lfs ubuntu" into google. The top hit is this page
https://github.com/git-lfs/git-lfs/wiki/Installation
It has an Ubuntu section
https://github.com/git-lfs/git-lfs/wiki/Installation#Ubuntu
The Ubuntu section has multiple problems.

* It says, "Ubuntu 12 and similar Wheezy versions" need a PPA to use git lfs. Over the course of today I have tested with Ubuntu 14.04.6 LTS, 16.04.06 LTS and 18.04.3 LTS. Both 14.04.06 and 16.04.06 did not have git-lfs in apt-get without a PPA. 18.04.3 **could** install git-lfs without a PPA. 

    Saying that "Ubuntu 12 and similar" need a PPA implies Ubuntu 14 does **not** need a PPA. You should either remove this text or specify that 12, 14 and 16 need PPAs and 18 does not.

* The Ubuntu section has one bullet point, then sections headered i, ii and iii, then sections headered 1, 2, and 3. I do not understand what this is trying to convey. It looks like a markdown error.

* Although I'm confused by the formatting, I **think** this section is trying to communicate you can get git-lfs by **either** adding the correct PPA  **or** by using `script.deb.sh`. If this is not what you meant, it should be clearer. If it **is** what you meant, it becomes important that apparently the PPA does not have packages for Ubuntu 16! When I tested with 16.04.06 plus your PPA plus a `apt-get update`, installing git-lfs still gave me "Unable to locate package git-lfs". A [nice person on Twitter](https://twitter.com/LeifAndersen/status/1159562170004197381) looked and said "the ppa itself… doesn't seem to actually have a git-lfs package for 16.04" but I don't understand enough about PPAs to know how she came to that conclusion.

I cannot put in a pull request because I don't know what the correct text would be. But someone who knows more about this than me should probably fix this.

If this section had said nothing but "upgrade to Ubuntu 18" I could have saved a lot of time trying things that turned out not to work.

**Comment by bk2204** [comment] 2019-08-09 14:07
Hey,

Sorry for the confusion. The issue is roughly this: in order to use Git LFS, you need a suitably recent version of Git itself. The instructions for the PPA were to install a newer version of Git so that Git LFS would work, and then the instructions followed for how to install Git LFS.

I agree that this is confusing, and since all the versions of Debian and Ubuntu we support now have a suitably up-to-date Git, I've just removed the references to installing a new Git altogether. Can you look at the version I've put up now and see if it's easier to understand?

**Comment by mcclure** [comment] 2019-08-11 00:39
Definitely the new version is not confusing! However, I think it would best to also note that with Ubuntu 18 or Debian Whatever "apt-get install git-lfs" works out of the box and the .sh is only needed for older Ubuntus.

**Comment by bk2204** [comment] 2019-08-12 13:17
I've done that. We generally suggest people use the latest version, because we do a decent amount of bug fixing and improvements and people tend to find we've already fixed their problem, but I understand that for a lot of folks it's preferable to use distro packages.

Since it looks like the documentation is better than it was, I'm going to close this issue.

**Closed by bk2204** 2019-08-12 13:17 UTC
