### ISSUE TITLE
Bug with accented chars?

### ISSUE THREAD

**Issue by pascalrobert** [git-lfs/git-lfs#1381] opened 2016-07-18 12:53 UTC
Hi,

I converted a repo to use Git-lfs. Conversion went fine, pushed it to GitLab, but now, when I try to pull it:

```
Resolving deltas: 100% (4711/4711), done.
Checking connectivity... done.
Downloading Général/logos.sketch (216.00 KB)
Error downloading object: Général/logos.sketch (833f098c2c583f229d1582b1396075676d01f0711fcfffc74deb2d03df470729)

Errors logged to /Users/probert/Code/materiel-ttl/.git/lfs/objects/logs/20160718T083921.793149137.log
```

And in the log:

```
git-lfs/1.2.1 (GitHub; darwin amd64; go 1.6.2; git 79bedeb)
git version 2.5.4 (Apple Git-61)

$ git-lfs smudge -- Général/logos.sketch
Error downloading object: Général/logos.sketch (833f098c2c583f229d1582b1396075676d01f0711fcfffc74deb2d03df470729)

exit status 1
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
    /Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:566 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x992330, 0xc820278000, 0xe04330, 0xc8201600c0)
    /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:197 +0xf80
github.com/github/git-lfs/commands.logPanic(0xe04330, 0xc8201600c0, 0x0, 0x0)
    /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:161 +0x412
github.com/github/git-lfs/commands.handlePanic(0xe04330, 0xc8201600c0, 0x0, 0x0)
    /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:136 +0x4e
github.com/github/git-lfs/commands.LoggedError(0xe04330, 0xc8201600c0, 0x61bb40, 0x21, 0xc820159c98, 0x2, 0x2)
    /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:86 +0x82
github.com/github/git-lfs/commands.smudgeCommand(0x84b7a0, 0xc8200bb240, 0x1, 0x2)
    /Users/rick/go/src/github.com/github/git-lfs/commands/command_smudge.go:79 +0xdcd
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0x84b7a0, 0xc8200bb0a0, 0x2, 0x2, 0x0, 0x0)
    /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x3f4
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0x84c7e0, 0x0, 0x0)
    /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
    /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:101 +0x23
main.main()
    /Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x12e

ENV:
LocalWorkingDir=/Users/probert/Code/materiel-ttl
LocalGitDir=/Users/probert/Code/materiel-ttl/.git
LocalGitStorageDir=/Users/probert/Code/materiel-ttl/.git
LocalMediaDir=/Users/probert/Code/materiel-ttl/.git/lfs/objects
LocalReferenceDir=
TempDir=/Users/probert/Code/materiel-ttl/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
GIT_DIR=.git
GIT_WORK_TREE=.

```

**Comment by ttaylorr** [comment] 2016-07-18 20:17
Hi @pascalrobert. Did you run `git-lfs smudge --` directly, or `git lfs pull`?

**Comment by pascalrobert** [comment] 2016-07-18 20:39
I was doing a clone, so I guess it was a git lfs pull behind.

**Comment by ttaylorr** [comment] 2016-07-19 21:06
Huh, this is weird. This may be a GitLab issue, since I am unable to reproduce it on GitHub.com:

```
~/d/misc $ g clone git@github.com:ttaylorr/lfs-test.git
Cloning into 'lfs-test'...
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 10 (delta 2), reused 9 (delta 1), pack-reused 0
Receiving objects: 100% (10/10), done.
Resolving deltas: 100% (2/2), done.
Checking connectivity... done.
Downloading b.dat (5 B)
Downloading à.dat (7 B)
~/d/misc $ cat ./lfs-test/à.dat
foobar```

**Comment by pascalrobert** [comment] 2016-07-20 15:41
Are you on Linux or OS X ? Might be a problem of Unicode normalization? Our repo is in GitLab on Linux, while I work on OS X.

**Comment by ttaylorr** [comment] 2018-07-27 17:45
Fixed in https://github.com/git-lfs/git-lfs/pull/3093! :tad.

**Closed** 2018-07-27 17:45 UTC
Labels: bug
