### ISSUE TITLE
Git LFS Push Problems/UI confusion

### ISSUE THREAD

**Issue by TimMensch** [git-lfs/git-lfs#1009] opened 2016-02-16 21:54 UTC
I tried creating a new repo with on the order of 1000+ LFS files, and the add and commit each took an unreasonably long time (I understand this is the Windows "it takes too long" bug; a separate issue). But then when I finally tried a push, it came up with this curious output:

```
Git LFS: (40 of 1065 files) 38.28 MB / 365.41 MB                                                                    FATAL ERROR: Server unexpectedly closed network connection
Git LFS: (1211 of 1065 files) 304.08 MB / 365.41 MB
```

So Git LFS has a hard time counting? But worse, after that, though, it ended up with hundreds of errors like this:

```
Post https://api.github.com/lfs/TimMensch/Steel/objects/11b07bce719807b7dfbe60e8eeeb8d99141aec2156beb85d7eabb59fa19e2497/verify: EOF
Authorization error: https://github-cloud.s3.amazonaws.com/alambic/media/122566436/56/61/566182bc5f60adcf42a785d60940e94a5a59d5739f8403e03b6200aa120e2495?actor_id=530873
Check that you have proper access to the repository
Authorization error: https://github-cloud.s3.amazonaws.com/alambic/media/122566436/42/da/42daa0cede4013e9ef42ac909280d7b1ebb0f301b5f05c8c615049ccfdbde7b8?actor_id=530873
Check that you have proper access to the repository
Authorization error: https://github-cloud.s3.amazonaws.com/alambic/media/122566436/6a/11/6a11c54419c1247ff5946fbf31e03aa32c20f86d8727979d0060bbf41197247f?actor_id=530873
Check that you have proper access to the repository
...
```

Trying again seems to get more files each time, but it's painfully slow to push as well -- probably for reasons of upstream bandwidth, but the UI for this could be clearer. I'm looking at the latest attempt to finish the push and I see this:

```
$ git push --set-upstream origin master
Git LFS: (13 of 1065 files, 898 skipped) 14.44 MB / 365.41 MB, 310.98 MB skipped
```

So this is 13 of 1065 files, or is it really 13 of 167 files (1065-898)? Same for the size. 

This could be easily updated to be much clearer as to what's really going on; it could read "13 of 167 files uploaded (898 found on server)" if that's what it really means.

**Comment by technoweenie** [comment] 2016-02-16 22:01
Are you getting those auth errors on a large push? I'm wondering if you're hitting an s3 timeout issue then? That's more of an issue on github and not git-lfs, actually. I have some ideas on dealing with those auth token timeouts better for Git LFS v1.2.

> This could be easily updated to be much clearer as to what's really going on; it could read "13 of 167 files uploaded (898 found on server)" if that's what it really means.

Not a bad idea, except that the same progress code is used for uploads and downloads. The message should read something like "13 of 167 files downloaded (898 found locally)". The extra clarity is probably worth it, though.

**Comment by sander120786** [comment] 2016-02-16 22:06
123

**Comment by TimMensch** [comment] 2016-02-24 08:05
The auth errors are in fact on a large push. I could believe that an auth token was expiring. It took several attempts to get all files to push, but it eventually worked.

**Comment by dylanfries** [comment] 2016-04-11 17:30
I'm having the same issues pushing a 1.3 gb push of assets. Did you do anything specfic to get it to go through or just attempt again and again?

**Comment by technoweenie** [comment] 2016-04-11 17:57
The reason it's not working is the client pushes up 100 objects to the LFS server to get back URLs for all of them. If the url to upload the 100th file is used after the url expires, then you'll have to re-push. Your LFS server should not require you to re-upload an existing file, so it'll _eventually_ work. 

The reason this is an issue on GitHub is that S3 doesn't let us tweak the upload token expiry AFAIK. I haven't been able to find a workaround for this using [AWS Signature version 4](http://docs.aws.amazon.com/general/latest/gr/signature-version-4.html).

There are some client side tweaks I want to investigate though in [v1.3](https://github.com/github/git-lfs/pull/1127):

* When attempting to upload or download a file, check `expires_at`, and throw it back in the queue to hit the LFS API again.
* Tweak the LFS object queue so it doesn't upload 100 objects, depending on the size. Though it really depends how fast you can upload to the server.

**Comment by dylanfries** [comment] 2016-04-11 19:18
So it'll get as far as it can before timing out and then drop off? Then the next push will essentially pick up from where it left off? Thanks for the reply, LFS has almost seemed like it would be easy but I've been getting stuck on issues like this. Thanks!

**Comment by aidanhs** [comment] 2016-06-09 17:06
```
$ git push origin aphs-branch
[...]
Git LFS: (347 of 342 files) 180.41 MB / 168.28 MB
```
I had hope that the sizes were right even if the file count wasn't, but no :(

(and then I got these errors, but at least I could resume)
```
Post https://api.github.com/lfs/[...]/objects/f80add2fe65bc3e3d4a2782097c4cdcff6df901a80d11ff54e72d18837e832ff/verify: EOF
Post https://api.github.com/lfs/[...]/objects/f80add2fe65bc3e3d4a2782097c4cdcff6df901a80d11ff54e72d18837e832ff/verify: EOF
Post https://api.github.com/lfs/[...]/objects/875f06d7b52ba0a341103945a0f6996e7c38d37cb6ca1d60414b7ac08b3715d0/verify: EOF
Post https://api.github.com/lfs/[...]/objects/875f06d7b52ba0a341103945a0f6996e7c38d37cb6ca1d60414b7ac08b3715d0/verify: EOF
```

**Comment by ttaylorr** [comment] 2018-07-27 17:39
Hi @TimMensch, this issue was fixed in https://github.com/git-lfs/git-lfs/pull/1958, so I think that this issue can be closed for now.

If this isn't the case, please make sure that you are on the latest version of Git LFS (v2.5.0) at the time of writing, and let me know what the problem is. I would be more than happy to dive in deeper here, or in another issue.

Thanks!

**Closed by ttaylorr** 2018-07-27 17:39 UTC

**Comment by TimMensch** [comment] 2018-07-27 17:53
Thanks @ttaylorr! I haven't actually seen this bug for a long while, though I've been doing a lot of my cloning and pushing using SmartGit, and I don't know if they're using the same code for Git LFS support, so I can't say one way or the other about whether it was fixed in mainline Git LFS, but I'll choose to believe that it's fixed until I see it again. 😄
