### ISSUE TITLE
Some files remain modified in `git status` after `git checkout <branch>`

### ISSUE THREAD

**Issue by DigitalMachinist** [git-lfs/git-lfs#2874] opened 2018-02-19 20:01 UTC
As the title says, I have a git repo for a game project that I'm working on that uses git-lfs to handle binary files from Unity as well as images and 3D assets. When switch branches or sometimes when pulling, I'll end up with one or more file that list as modified when running `git status`.

I've already googled this a bunch and tried a few things but nothing has stuck for me.

Anyway here's as much info about my situation as I can muster. If anything else will be helpful in diagnosing the problem, let me know.

And lastly, thanks in advance for taking a look. This problem has become a major workflow distraction and I'm really in need of getting this resolved, so appreciate your time investigating!

===

My OS is Windows 10 Pro.

I'm confident that no one currently using the repo has not run `git lfs install`.

**How the problem typically presents:**
```
Jeff ~/Documents/__git/quench (master)
$ git checkout resolve_lfs_issues
Pointer file error: Unable to parse pointer at: "Assets/Media/Meshes/Lion/lioness.fbx"
Pointer file error: Unable to parse pointer at: "Assets/Media/Meshes/Lion/lioness@lioness_anim_attackA.fbx"
Pointer file error: Unable to parse pointer at: "Assets/Media/Meshes/Lion/lioness@lioness_anim_attackB.fbx"
Pointer file error: Unable to parse pointer at: "Assets/Media/Meshes/Lion/lioness@lioness_anim_death.fbx"
Pointer file error: Unable to parse pointer at: "Assets/Media/Meshes/Lion/lioness@lioness_anim_grazeA.fbx" Pointer file error: Unable to parse pointer at: "Assets/Media/Meshes/Lion/lioness@lioness_anim_grazeB.fbx" Pointer file error: Unable to parse pointer at: "Assets/Media/Meshes/Lion/lioness@lioness_anim_hurt.fbx"
Pointer file error: Unable to parse pointer at: "Assets/Media/Meshes/Lion/lioness@lioness_anim_idleA.fbx"
Pointer file error: Unable to parse pointer at: "Assets/Media/Meshes/Lion/lioness@lioness_anim_idleB.fbx"
Pointer file error: Unable to parse pointer at: "Assets/Media/Meshes/Lion/lioness@lioness_anim_ko.fbx"
Checking out files: 100% (34/34), done.
Switched to branch 'resolve_lfs_issues'
Your branch is up-to-date with 'origin/resolve_lfs_issues'.

Jeff ~/Documents/__git/quench (resolve_lfs_issues)
$ git status
On branch resolve_lfs_issues
Your branch is up-to-date with 'origin/resolve_lfs_issues'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   Assets/Media/Meshes/Lion/lioness@lioness_anim_ko.fbx
        modified:   Assets/Scenes/Tests/VignetteAssetTest/VignetteAssetTest/LightmapSnapshot.asset

no changes added to commit (use "git add" and/or "git commit -a")
```

The failed pointer lookups are fine from what I understand. There was a time when the repo wasn't using git-lfs, so our history contains binary copies of some of these files from long ago. This same problem can present on the computers of anyone on the team, so it's not just me.

**My `git lfs env` output:**
```
Jeff ~/Documents/__git/quench (resolve_lfs_issues)
$ git lfs env
git-lfs/1.5.5 (GitHub; windows amd64; go 1.7.4; git c2dcd6f5)
git version 2.7.0.windows.1

Endpoint=https://bitbucket.org/AxonInteractive/quench.git/info/lfs (auth=none)
  SSH=git@bitbucket.org:AxonInteractive/quench.git
LocalWorkingDir=C:\Users\Jeff\Documents\__git\quench
LocalGitDir=C:\Users\Jeff\Documents\__git\quench\.git
LocalGitStorageDir=C:\Users\Jeff\Documents\__git\quench\.git
LocalMediaDir=C:\Users\Jeff\Documents\__git\quench\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\Jeff\Documents\__git\quench\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**My user's `.gitconfig`:**
```
Jeff ~/Documents/__git/quench (resolve_lfs_issues)
$ tail ~/.gitconfig
        default = simple
[gc]
        autoDetach = false
[pull]
        rebase = true
[filter "lfs"]
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge -- %f
        process = git-lfs filter-process
        required = true
```

**My repo's `.gitattributes`:**
```
Jeff ~/Documents/__git/quench (resolve_lfs_issues)
$ cat .gitattributes
## Unity ##

*.sln merge=binary
*.csproj merge=binary
*.cs diff=csharp text
*.cginc text
*.shader text

*.mat merge=unityyamlmerge eol=lf
*.anim merge=unityyamlmerge eol=lf
*.unity merge=unityyamlmerge eol=lf
*.prefab merge=unityyamlmerge eol=lf
*.physicsMaterial2D merge=unityyamlmerge eol=lf
*.physicsMaterial merge=unityyamlmerge eol=lf
*.asset merge=unityyamlmerge eol=lf
*.meta merge=unityyamlmerge eol=lf
*.controller merge=unityyamlmerge eol=lf
*.cubemap merge=unityyamlmerge eol=lf


## git-lfs ##

# Quench
*.hxl filter=lfs diff=lfs merge=lfs -text
*.qmb filter=lfs diff=lfs merge=lfs -text
*.dev.xml filter=lfs diff=lfs merge=lfs -text

# Image
*.ai filter=lfs diff=lfs merge=lfs -text
*.gif filter=lfs diff=lfs merge=lfs -text
*.jpg filter=lfs diff=lfs merge=lfs -text
*.jpeg filter=lfs diff=lfs merge=lfs -text
*.png filter=lfs diff=lfs merge=lfs -text
*.psd filter=lfs diff=lfs merge=lfs -text
*.tga filter=lfs diff=lfs merge=lfs -text

# Audio
*.aif filter=lfs diff=lfs merge=lfs -text
*.mp3 filter=lfs diff=lfs merge=lfs -text
*.ogg filter=lfs diff=lfs merge=lfs -text
*.wav filter=lfs diff=lfs merge=lfs -text

# Fonts
*.otf filter=lfs diff=lfs merge=lfs -text
*.ttf filter=lfs diff=lfs merge=lfs -text

# Video
*.mov filter=lfs diff=lfs merge=lfs -text
*.mp4 filter=lfs diff=lfs merge=lfs -text

# 3D Object
*.blend filter=lfs diff=lfs merge=lfs -text
*.c4d filter=lfs diff=lfs merge=lfs -text
*.FBX filter=lfs diff=lfs merge=lfs -text
*.fbx filter=lfs diff=lfs merge=lfs -text
*.obj filter=lfs diff=lfs merge=lfs -text

# Lightmaps
*.exr filter=lfs diff=lfs merge=lfs -text

# Bundled Code
*.dll filter=lfs diff=lfs merge=lfs -text
*.unitypackage filter=lfs diff=lfs merge=lfs -text

# Documents
*.pdf filter=lfs diff=lfs merge=lfs -text

# Archives
*.zip filter=lfs diff=lfs merge=lfs -text

# Don't now what these filetypes even are...
*.a filter=lfs diff=lfs merge=lfs -text
*.rns filter=lfs diff=lfs merge=lfs -text
*.reason filter=lfs diff=lfs merge=lfs -text
*.lxo filter=lfs diff=lfs merge=lfs -text
```

**Comment by ttaylorr** [comment] 2018-02-21 06:00
Hi @DigitalMachinist, thanks for opening this issue and sorry that you're having trouble! Thanks for posting such a detailed overview of your environment.

From the looks of it, I think what's going on here is that a change to a file tracked with LFS was committed without the Git LFS clean filter being ran. What that means in practice usually is that someone didn't have Git LFS properly installed on their computer when they were interacting with this repository.

Since Git expects the file to contain an LFS pointer, and it instead (assuming the above is true) contains a large object, there is a diff. This can be confirmed by running `git lfs status`.

A way to fix this is by running `git lfs migrate import --everything --include="path/to/file"`, which will rewrite history and move the affected files into LFS, upon which there should be no diff after checking out.

Can you give that all a whirl and let me know how it goes? If that doesn't seem to fix it, please don't hesitate to ping me here, and I'd be more than happy to reopen this issue. Thanks!

**Closed by ttaylorr** 2018-02-21 06:00 UTC

**Comment by DigitalMachinist** [comment] 2018-02-22 03:26
I'll try running this and get back to you. Thanks for the advice!

**Comment by DigitalMachinist** [comment] 2018-03-03 20:31
I just wanted let you and anyone who searches this in the future know that this seems to have taken care of my problem and then some!

I needed to run `git lfs migrate import --everything --include="path/to/file"` for all of the file types that I want git-lfs to track in my `.gitattributes`, but as far as I can tell no one has encountered any issues after doing this. Of course, I had to have everyone using the repo reset their local `master` branch to the new one, but the benefits since doing this have been substantial.

As far as I'm aware, no one has run into issues with files remaining modified after checking out since making this fix. Some notable side-benefits are that I no longer encounter any `"Pointer file error: Unable to parse pointer at: ..."` errors when checking out branches because even files from before git-lfs started being used are tracked properly, and the total size of the repo has shrunk (1600mb --> 350mb) so I'm no longer skirting repo size issues on Bitbucket once I asked their support team to run a `git gc` for me.

Thanks for the tip. Very helpful!

**Comment by DigitalMachinist** [comment] 2018-03-18 16:50
Just following up on this... Everything was fine for a while but I'm encountering this issue again.

There haven't been any commits pushed from computers that I didn't personally set up git-lfs on, but all of the files that keep having problems come from one computer in particular (there's only a couple we work on anyway). I can't get you that computer's config right now because it just left for GDC, but I just wanted to provide an update.

Once I have a chance to investigate further I'll left you know if I can resolve this. If not, expect another dump of git configuration files...

**Comment by ttaylorr** [comment] 2018-03-19 21:32
Hi @DigitalMachinist, thanks for the update!

> but all of the files that keep having problems come from one computer in particular

My assumption is that this is a similar issue, and would be resolved by `git lfs install && git lfs checkout`.
