### ISSUE TITLE
all LFS files show up as modified after a clean clone

### ISSUE THREAD

**Issue by KoenT-X** [git-lfs/git-lfs#4113] opened 2020-04-28 16:47 UTC
**Describe the bug**

So I converted a git repository to support LFS using the recommended BFG tool (https://github.com/rtyley/bfg-repo-cleaner) and pushed it to Bitbucket, where I indeed see that the repo size is just 80 MB, and the LFS storage size is 2.6 GB, which is what I expected.

When I now clone the repository from there, everything ends up fine on my machine (non-LFS files and LFS files), but git status tells me that all my LFS files are "modified" (so does TortoisGit, which shows them in red).

I tried cloning with git clone and also with git lfs clone, but both give the same results.

When I revert the "modified" files, they then show up as unmodified, but they are actually the small pointer files, not the actual binary files...
When I delete the files, and then do "git lfs checkout" the actual binary files are back, but again showing up as "modified".

**Expected behavior**
I would expect to see what I now see (actual binary files for the LFS files, but without them showing up as "modified" in git.

**System environment**

This is on Windows 10 64-bit.
"git --version" shows "git version 2.26.2.windows.1"
I'm using the Windows command prompt for command line actions, and also using TortoiseGit 2.10.0.2, which shows for version information:
TortoiseGit 2.10.0.2 (C:\Program Files\TortoiseGit\bin)
git version 2.26.2.windows.1 (C:\Program Files\Git\bin; C:\Program Files\Git\mingw64\; C:\Program Files\Git\etc\gitconfig))
I have "autocrlf = true" in my global config, as usual when on Windows.

Edit: using the Git LFS client from here: https://github.com/git-lfs/git-lfs/releases/download/v2.10.0/git-lfs-windows-v2.10.0.exe

**Output of `git config -l`:**

```
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor="C:\\Program Files\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
credential.helper=manager
user.name=me*********
user.email=me@********.com
credential.helper=wincred
core.autocrlf=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=git@bitbucket.org:myteam/test.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
tgit.commitshowpatch=false
```

**Output of `git lfs env`:**

git-lfs/2.10.0 (GitHub; windows amd64; go 1.12.7; git a526ba6b)
git version 2.26.2.windows.1

```
Endpoint=https://bitbucket.org/myteam/test.git/info/lfs (auth=none)
  SSH=git@bitbucket.org:myteam/test.git
LocalWorkingDir=C:\Koen\Temp\test
LocalGitDir=C:\Koen\Temp\test\.git
LocalGitStorageDir=C:\Koen\Temp\test\.git
LocalMediaDir=C:\Koen\Temp\test\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Koen\Temp\test\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Koen\Temp\test\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_SSH=C:\Program Files\PuTTY\plink.exe
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Output of git lfs status**

```
On branch master
Objects to be pushed to origin/master:


Objects to be committed:

        Applications/BackupAmazon/bin/Testing/imgs/scan0137.tif (LFS: b06931b -> Git: b06931b)
        ... a lot more ...
        External/tinyXML/lib/Release/tinyxmlSTL.lib (LFS: e37bcb0 -> Git: e37bcb0)

Objects not staged for commit:

```

**Other info**

I have several .gitattributes files in the folder tree, which got added by the BFG tool (placed in folders where there were actually files that were converted to LFS files), and they all look like this:

`*.{lib,dll,tif,exe,msi} filter=lfs diff=lfs merge=lfs -text`

Is this a known bug?
Anything I can do to fix this (hopefully without pushing a new repository again to Bitbucket ;-))?
Thanks!

**Comment by ScatteredRay** [comment] 2020-04-29 02:47
I'm having the same issue... So if I do a `git reset --hard` then `git status` doesn't list any changed files, however they all revert to being pointers, then doing `git lfs checkout` get's me back into the problem I started with... I tried doing `git add --renormalize .` as mentioned int his other post https://github.com/git-lfs/git-lfs/issues/4090 but that didn't seem to stage any files.

**Comment by ScatteredRay** [comment] 2020-04-29 04:21
I've just cloned my repo to a linux box and I'm still reproducing the same issue.

**Comment by ScatteredRay** [comment] 2020-04-29 04:40
Ok, so I tried to normalize again (on the linux machine specifically.)

I ran
`git add --renormalize .`
then
`git commit -m "test"`

That did make a commit, and git status now doesn't show any modifications, however I think it committed the blob:

So picking one arbitrary LFS file (it's a txt file that just got caught up in the filters, but should demonstrate the problem)

```
> git ls-tree HEAD^ Engine/GameEngine/ThirdPartyShipping/yajl/CMakeLists.txt
100644 blob 4a488a2777a6e6958741e45872994eb10b883381    Engine/GameEngin/ThirdPartyShipping/yajl/CMakeLists.txt
```

```
> git cat-file -p 4a488a2777a6e6958741e45872994eb10b883381
version https://git-lfs.github.com/spec/v1
oid sha256:c6db544f29e2259baaf3ee9f95bc1df91d084556960cc69320b87466883081be
size 3583
```

which is the pointer I expect, but now doing that on the new head:

```
> git ls-tree HEAD Engine/GameEngine/ThirdPartyShipping/yajl/CMakeLists.txt
100644 blob 04d463cdcbb954134a9666cfe19cc451d5bc20f0    Engine/GameEngine/ThirdPartyShipping/yajl/CMakeLists.txt
```

```
> git cat-file -p 04d463cdcbb954134a9666cfe19cc451d5bc20f0
# Copyright 2010, Lloyd Hilaiel.
#
[.... Rest of that CMakeLists.txt]
```

So I'm suspecting now maybe something in my .gitattributes isn't right?

```
Engine/GameEngine/ThirdParty filter=lfs diff=lfs merge=lfs -text
Engine/GameEngine/ThirdPartyShipping filter=lfs diff=lfs merge=lfs -text
Engine/GameEngine/cg filter=lfs diff=lfs merge=lfs -text
*.a filter=lfs diff=lfs merge=lfs -text
*.lib filter=lfs diff=lfs merge=lfs -text
*.dylib filter=lfs diff=lfs merge=lfs -text
```

**Comment by ScatteredRay** [comment] 2020-04-29 04:52
Looking deeper, it looks like it might be related to my usage of paths. I'm having this problem with `Engine/GameEngine/ThirdPartyShipping/yajl/CMakeLists.txt` but `Engine/CompressionEngine/lib32/CompressionEngine.lib` does not seem to be having this same issue. reading the .gitattributes docs, it seems maybe this is due to my paths it says specifically:

>patterns that match a directory do not recursively match paths inside that directory (so using the trailing-slash path/ syntax is pointless in an attributes file; use path/** instead)

But the paths still got converted with git lfs migrate, perhaps this is a mismatch between how git lfs matches paths, and .gitattributes does?

**Comment by ScatteredRay** [comment] 2020-04-29 05:11
It looks like somehow running the `git lfs checkout` added the binary blobs to the stage, running `git restore --staged .` seemed to get most things in order.

Now, however I've discovered a new class of file under the path of `Engine/AndroidGame/ThirdPartyShipping/...` That is somehow checked in as an LFS object, but is not (and never has been) in .gitattributes Not sure how that happened.

**Comment by KoenT-X** [comment] 2020-04-29 08:46
Edit: I've also added the output of running "git lfs status" to the description.

**Comment by KoenT-X** [comment] 2020-04-29 08:54
In issue #4090 it says:
"The usual way to fix this, if it is what you're seeing, is to take a clean tree and run git add --renormalize .. You can then run git lfs status and it will show the affected files with an entry like (Git: b5bb9d8 -> LFS: b5bb9d8). If you then commit, everything will be back to normal and you shouldn't see any more modified files."

Just to clear: I don't have a clean tree (or so it appears) when I do a clone, so would "take a clean tree" mean I have to first do a "git reset --hard", or does that mean running some version of the "git clean" command (and if so, what exactly)? @bk2204

Thanks!

**Comment by KoenT-X** [comment] 2020-04-29 09:12
Edit: I've also added the .gitattributes file contents to the description.

**Comment by KoenT-X** [comment] 2020-04-29 09:16
If I do this on a freshly cloned repo (that shows the "modified" LFS files):
```
git reset --hard
git add --renormalize .
```
then all the LFS files don't show up as modified any longer, BUT all my text-based files (.cs, .js, .txt, etc... which were never part of any .gitattributes or LFS conversion file pattern) now show up as modified, which doesn't make any sense...

**Comment by bk2204** [comment] 2020-04-29 13:47
Hey,

This problem can occur for several reasons.  In this case, the braces don't produce a valid alternation like you expect in a `.gitattributes` file, so `*.{lib,dll,tif,exe,msi} filter=lfs diff=lfs merge=lfs -text` isn't valid.  You'd need to write it like this:

```
*.lib filter=lfs diff=lfs merge=lfs -text
*.dll filter=lfs diff=lfs merge=lfs -text
*.tif filter=lfs diff=lfs merge=lfs -text
*.exe filter=lfs diff=lfs merge=lfs -text
*.msi filter=lfs diff=lfs merge=lfs -text
```

Also, directories have no effect in `.gitattributes`, so if you want to match all files, you need to append a `/**` to that.  It's known that our pattern matching in that case is not exactly what Git produces, but we haven't yet fixed it.

Finally, a `git add --renormalize .` renormalizes all files through all filters and line ending conversions.  If you are using `core.autocrlf` because you're on WIndows but your files have been checked in with CRLF endings, it will normalize them, too.  In that case, you should turn off `core.autocrlf` for that repo if you don't want LF endings in the repository and CRLF in the tree.

**Comment by KoenT-X** [comment] 2020-04-29 15:09
Hi,
thank you for your reply.

About the pattern in .gitattributes: I didn't create these myself.
I used the following command with BFG:
```
java -jar bfg-1.13.0.jar --convert-to-git-lfs "*.{lib,dll,tif,exe,msi}" --no-blob-protection TestLFS
```
similar to an example I saw on their usage pages.
I guess using single quotes won't make a difference either?

Does that also mean I can't use this:
```
java -jar bfg-1.13.0.jar --convert-to-git-lfs "*.lib,*.dll,*.tif,*.exe,*.msi" --no-blob-protection TestLFS
```
or would that be fine?
If not, I guess I will need to run the conversion for each extension separately then...

About the "directories"thing:
It seems like BFG will add a .gitattributes file where it thinks it is needed (so it puts one wherever it finds an LFS file in a subfolder), so I don't think I need any patterns with that /** appended if I understand you correctly?

About the renormalize:
I converted this repository from a Mercurial repository, and it might indeed be that the code files where indeed checked in there as CRLF, and then the after the conversion to Git,git notices this (because of the AutoCRLF flag) during the renormalize. I actually want to have that flag on in Git, so I guess I will probably need to do the renormalize once when the rest is stable, right?

Thanks again for your help.

**Comment by ScatteredRay** [comment] 2020-04-29 17:05
@bk2204 So it appears in my case, the problem can be fixed by updating .gitattributes (and perhaps rewriting history for that, since it appears that worked correctly.)

You mentioned:
> . It's known that our pattern matching in that case is not exactly what Git produces, but we haven't yet fixed it.

Is there a bug associated that can be linked?

**Comment by ScatteredRay** [comment] 2020-04-29 17:07
@KoenT-X 
> It seems like BFG will add a .gitattributes file where it thinks it is needed (so it puts one wherever it finds an LFS file in a subfolder), so I don't think I need any patterns with that /** appended if I understand you correctly?

I don't think you are using directories in your patterns, so that's correct. I think the /** issue is more related to my specific problems.

**Comment by bk2204** [comment] 2020-04-29 18:00
> About the pattern in .gitattributes: I didn't create these myself.
> I used the following command with BFG:
> 
> ```
> java -jar bfg-1.13.0.jar --convert-to-git-lfs "*.{lib,dll,tif,exe,msi}" --no-blob-protection TestLFS
> ```

I honestly am not sure about how BFG does or doesn't work.  It's possible you could specify multiple `--convert-to-git-lfs` arguments, but I don't know for certain.  Whatever you do, you need to end up with a valid `.gitattributes` pattern in your file, which means that braces aren't considered special.

> About the "directories"thing:
> It seems like BFG will add a .gitattributes file where it thinks it is needed (so it puts one wherever it finds an LFS file in a subfolder), so I don't think I need any patterns with that /** appended if I understand you correctly?

That was a response to @ScatteredRay.  Sorry for the confusion.

> About the renormalize:
> I converted this repository from a Mercurial repository, and it might indeed be that the code files where indeed checked in there as CRLF, and then the after the conversion to Git,git notices this (because of the AutoCRLF flag) during the renormalize. I actually want to have that flag on in Git, so I guess I will probably need to do the renormalize once when the rest is stable, right?

If you want to have `core.autocrlf` enabled, then your renormalize has worked as expected, according to what you said earlier.  That means your repository will check out CRLF on Windows and LF on Unix, and the repository will store LF.  That's generally the preferred behavior.

If you plan to redo the history import with BFG, then yes, I'd wait for that to complete before redoing the normalization, unless BFG can do that itself as part of the process.

**Comment by bk2204** [comment] 2020-04-29 18:05
> @bk2204 So it appears in my case, the problem can be fixed by updating .gitattributes (and perhaps rewriting history for that, since it appears that worked correctly.)

Yes, that should work.  We accept directories and rewrite them internally to append `/**`, but Git does not, so it doesn't pass your files in that directory to Git LFS.

> > . It's known that our pattern matching in that case is not exactly what Git produces, but we haven't yet fixed it.
> 
> Is there a bug associated that can be linked?

#3968 is one aspect of this.  There isn't a specific issue tracking it, but we do plan to eventually overhaul the entire git-lfs/wildmatch library to match the Git testsuite and then update Git LFS with it.

**Comment by KoenT-X** [comment] 2020-04-30 08:35
Thanks you both!

Just a comment: I could actually reproduce the behavior I saw with a very small repository that only contains a single text file and a binary .exe file. If I do the LFS conversion with the BFG command I mentioned, I get the same issue. I then tried to do the conversion with this:
```
git lfs migrate import --everything --include="*.lib,*.dll,*.tif,*.exe,*.msi"
git push --mirror
```
and then I get a .gitattributes file that has a line for each of the wildcards, and I can see in Bitbucket that the repo size is very small and the LFS size is the size of that binary file. So that all looks good.

[I hope I'm correct that "git push --mirror" is the way to go to push an existing local repo completely (so all branches and tags) to an empty repo on Bitbucket. I first tried "git push --force" as I read somewhere else, but that failed with an error "fatal: The current branch master has no upstream branch.".]

I then tried this approach on the big 1 GB repository, and while the lfs migrate completed all fine, I didn't see the expected .git/objects folder shrink (it was still at 1 GB) with the .git/lfs folder at over 2 GB (which is as expected). So it's a bit strange that I did see the shrunk objects folder size after lfs migrate with the small repo, but not with the big (it should go down to around 89 MB).

I then tried to use the cleanup / garbage collection:
```
git reflog expire --expire-unreachable=now --all
git gc --prune=now
```
which gave:
```
Enumerating objects: 76530, done.
Counting objects: 100% (76530/76530), done.
Delta compression using up to 12 threads
Compressing objects: 100% (28641/28641), done.
Writing objects: 100% (76530/76530), done.
Total 76530 (delta 60777), reused 53620 (delta 47211), pack-reused 0
Removing duplicate objects: 100% (256/256), done.    
```
and then I got this:
.git/objects folder size = 254 MB (or similar)
.git/lfs fodler size = 2.39 GB (or similar)
so less for the .git/objects folder, but still no 89 MB I saw earlier with the BFG conversion.

When I pushed with "git push --mirror" to a newly created empty repo on Bitbucket, I actually ended up with no source files (repo size = 32.6 KB, as for an empty repo), but with 2.4 GB of LFS storage. I think that might have been related to network issues, as I got this output (after about 1.5 hours):

```
FATAL ERROR: Remote side unexpectedly closed network connection
Uploading LFS objects: 100% (599/599), 2.6 GB | 2.3 MB/s
...
```
It's strange though that it completed in the end...
I'm gonna retry the push now from an Amazon machine to make sure the connection is stable (on an ADSL line here working from home)...

But anyway: I guess the conclusion of my issue is that there are issues with BFG using these file patterns, which then leads to incorrect .gitattributes files, which causes the issues I mentioned (apart from the line endings, which probably stems from the combination of Hg to Git conversion and the AutoCRLF flag).

**Comment by bk2204** [comment] 2020-04-30 21:31
> Just a comment: I could actually reproduce the behavior I saw with a very small repository that only contains a single text file and a binary .exe file. If I do the LFS conversion with the BFG command I mentioned, I get the same issue. I then tried to do the conversion with this:
> 
> ```
> git lfs migrate import --everything --include="*.lib,*.dll,*.tif,*.exe,*.msi"
> git push --mirror
> ```
> 
> and then I get a .gitattributes file that has a line for each of the wildcards, and I can see in Bitbucket that the repo size is very small and the LFS size is the size of that binary file. So that all looks good.

Good.  I'm glad that got you where you needed to be.  Please do report that to the BFG folks, because while I'm not familiar with the tool, I'm sure they'll want to make things work the best they can and they of course can only do that if they know about the problem.
 
> [I hope I'm correct that "git push --mirror" is the way to go to push an existing local repo completely (so all branches and tags) to an empty repo on Bitbucket. I first tried "git push --force" as I read somewhere else, but that failed with an error "fatal: The current branch master has no upstream branch.".]

That's usually a fine way to replicate a repo.  The only exception would be if you had extra remote-tracking branches you didn't want to replicate, but it doesn't seem to me like you would.

> I then tried this approach on the big 1 GB repository, and while the lfs migrate completed all fine, I didn't see the expected .git/objects folder shrink (it was still at 1 GB) with the .git/lfs folder at over 2 GB (which is as expected). So it's a bit strange that I did see the shrunk objects folder size after lfs migrate with the small repo, but not with the big (it should go down to around 89 MB).

We do have #3238, which may be the cause of this, but we have no reproduction steps for that issue.  It may be that everything got converted properly but the two tools work differently and that explains the size as well.  Without a good testcase, we wouldn't be able to say, but 254 MB is a rather reasonable size for a repository.

**Comment by bk2204** [comment] 2020-08-14 17:51
Hey,

Since it seems like we've gotten the expected answers here, I'm going to close this.  If folks are still seeing this problem, please open a new issue, and we'll look into it.

**Closed by bk2204** 2020-08-14 17:51 UTC
