### ISSUE TITLE
git-lfs is not tracking specific files

### ISSUE THREAD

**Issue by kikakuka** [git-lfs/git-lfs#2218] opened 2017-05-15 10:14 UTC
Hi,

Specific files (~6 Gb size) are not tracked properly by git lfs track. I believe this is connected to a max memory limit which I cannot change.

Consider following scenario:

```
> mkdir test
> cd test
> git init
> git lfs install
> cp ../a.lib .
> cp ../b.lib .
> touch c.lib
> git lfs track a.lib
> git lfs track b.lib
> git add .
> git lfs status
Git LFS objects to be committed:

        a.lib (Git: c2ce73f)
        b.lib (LFS: 549bfc6)
        c.lib (Git: e3b0c44)

Git LFS objects not staged for commit:
```

a.lib (6.2 GB) is not added to tracked files while b.lib (~700MB) is.  a.lib is visible in .git/lfs/objects and has correct size:
```
> du .git/lfs/objects/10/e1/10e1824e4cb0a29a1a3ae3633ecb6bb4d1c5908216a3bee35949af1876b4b3a5 
6523028 .git/lfs/objects/10/e1/10e1824e4cb0a29a1a3ae3633ecb6bb4d1c5908216a3bee35949af1876b4b3a5
> du a.lib 
6523028 a.lib
```

After committing , the pointer file reads
```
> git cat-file -p :a.lib
version https://git-lfs.github.com/spec/v1
oid sha256:10e1824e4cb0a29a1a3ae3633ecb6bb4d1c5908216a3bee35949af1876b4b3a5
size 6653375901
```

However, the pointer seems to be invalid.
```
> rm a.lib
> git checkout -- a.lib
Pointer file error: Unable to parse pointer at: "a.lib"
```

In the following, it is not uploaded to my server using `git push`. Further experiments show that is can be uploaded using `git lfs push origin --object-id <o-id>`.  Even then, other people will only receive the pointer file while the smudge filter is not working on a.lib.

I don't know if its connected but: I noted that `git gc` returns an alloc error. It complains that the mem limit is reached. I tried the options to avoid git gc failing:
```
git config pack.threads 1
git config pack.deltaCacheSize 1
git config core.packedGitWindowSize 16m
git config core.packedGitLimit 128m
git config pack.windowMemory 512m
```
However, that also seems to have no effect on git-lfs.

See my git lfs env for details on the lfs version:
```
git-lfs/2.1.0 (GitHub; linux 386; go 1.8; git bd2c9987)
git version 2.8.4
...
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_TRACE=0
git config filter.lfs.process = ""
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by ttaylorr** [comment] 2017-05-15 16:36
Hi @kikakuka, thanks for opening this and sorry that you're having trouble. I noticed that while you are running the latest version of LFS, your `filter.lfs.process` setting is out of date. Can you run

```
$ git lfs install --force
$ git lfs env | grep filter
```

to upgrade the settings and then post the output of both commands here?

**Comment by kikakuka** [comment] 2017-05-15 16:49
```
bash-3.00$ git lfs install --force
Updated git hooks.
Git LFS initialized.
bash-3.00$ git lfs env | grep filter
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

Unfortunately, this doesn't help. After removing .git/lfs/object (to redo the whole process):
```
git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .gitattributes
        a.lib

nothing added to commit but untracked files present (use "git add" to track)
bash-3.00$ cat .gitattributes 
a.lib filter=lfs diff=lfs merge=lfs -text
bash-3.00$ git add a.lib 
git lfs status
bash-3.00$ git lfs status
On branch master

Git LFS objects to be committed:

        a.lib (Git: 5236ffe)

Git LFS objects not staged for commit:

```
I also tried to run `git config --unset filter.lfs.process` with no effect.

**Comment by ttaylorr** [comment] 2017-05-15 16:52
@kikakuka thanks. One more thing -- your Git version is also quite out of date. To run the `process` filter please upgrade to 2.11 or greater (2.13 is the latest at the time of writing) and try again.

**Comment by kikakuka** [comment] 2017-05-15 17:07
Sorry for the old git version. I am working in a closed system...

However, I managed to find git 2.12, still unfortunately to no effect.

```
bash-3.00$ git --version
git version 2.12.0
bash-3.00$ git reset
bash-3.00$ rm -rf .git/lfs/objects
bash-3.00$ cat .gitattributes 
a.lib filter=lfs diff=lfs merge=lfs -text
bash-3.00$ git add a.lib 
bash-3.00$ git lfs status
On branch master

Git LFS objects to be committed:

        a.lib (Git: 5236ffe)

Git LFS objects not staged for commit:
```

**Comment by kikakuka** [comment] 2017-05-15 17:34
I did a cross-check on windows. I tried to download a repository where I uploaded the respective large file using `git lfs push origin --object-id <o-id>`.

```
$ git checkout -f origin/master
fatal: Out of memory, realloc failed
Error downloading object: a.lib (3d0a6e6): Smudge error: Error reading from media file: write /dev/stdout: The pipe has been ended.: write /dev/stdout: The pipe has been ended.

Errors logged to ...
Use `git lfs logs last` to view the log.

$ git lfs logs last
git-lfs/2.1.0 (GitHub; windows amd64; go 1.8.1; git bd2c9987)
git version 2.13.0.windows.1

$ git-lfs.exe filter-process
Error downloading object: a.lib (3d0a6e6): Smudge error: Error reading from media file: write /dev/stdout: The pipe has been ended.: write /dev/stdout: The pipe has been ended.

%+v
Smudge error: Error reading from media file: write /dev/stdout: The pipe has been ended.: write /dev/stdout: The pipe has been ended.
ENV:
...
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.git
GIT_PREFIX=
```
At least, this time it tried to resolve the pointer. I don't know if it is connected though.

**Comment by ttaylorr** [comment] 2017-05-15 18:24
@larsxschneider do you know what's going on here?

**Comment by larsxschneider** [comment] 2017-05-15 19:48
@ttaylorr Not really...

@kikakuka I just tried to reproduce the issue on OSX (with a newer Git version) but I wasn't able to. Is it happening only with your specific repo or can you reproduce the issue with a artificial repo? What file system do you use? What Linux Kernel version? Can you try the following steps?

```
git --version
git lfs version
git init .
git lfs track '*.bin'
dd if=/dev/zero of=test.bin bs=4k count=2000000
git add .
git lfs status
```

I get the following output:
```
$ git --version
git version 2.13.0
$ git lfs version
git-lfs/2.1.0 (GitHub; darwin amd64; go 1.8.1)
$ git init .
Initialized empty Git repository in /Users/redacted/.git/
$ git lfs track '*.bin'
"*.bin" already supported
+ dd if=/dev/zero of=test.bin bs=4k count=2000000
2000000+0 records in
2000000+0 records out
8192000000 bytes transferred in 9.229291 secs (887608813 bytes/sec)
$ git add .
$ git lfs status

Git LFS objects to be committed:

    .gitattributes (Git: 35c9aa1)
    test.bin (LFS: 7c084a7)

Git LFS objects not staged for commit:

```

**Comment by kikakuka** [comment] 2017-05-15 21:00
@larsxschneider Thanks for the detailed reply.

* system info

```
$ df -T
-> Type : nfs
```

``` 
$ uname -r
3.0.101-84-default
```

* Output of the test commands:
```
$ git --version
git version 2.12.0                                                                                                                                     
$ git lfs version
git-lfs/2.1.0 (GitHub; linux 386; go 1.8; git bd2c9987)                                                                                                                                     
$ git init .
Initialized empty Git repository in /nfs/imu/proj/tec/tpgit/packages/source/gittest/.git/                                                                                                                                     
$ git lfs track '*.bin'
Tracking "*.bin"                                                                                                                                     
$ dd if=/dev/zero of=test.bin bs=4k count=2000000
2000000+0 records in
2000000+0 records out
8192000000 bytes (8.2 GB) copied, 75.7078 s, 108 MB/s                                                                                                                                     $ git add .
$ git lfs status
Git LFS objects to be committed:

        .gitattributes (Git: 35c9aa1)
        test.bin (Git: 2f8b417)

Git LFS objects not staged for commit:

```

I also emptied `~/.gitconfig`, reinstalled lfs and retried. The output stayed the same.

**Comment by larsxschneider** [comment] 2017-05-15 21:11
Oh, "nfs" might cause the trouble. What version of nfs and what mount options do you use? What file system is used on the nfs server?
Can you try the test case on a local disk on your Linux box?

**Comment by kikakuka** [comment] 2017-05-16 07:18
```
nfsstat -m | grep XXX
XXX from XXX:XXX
Flags: rw,nodev,relatime,vers=3,rsize=65536,wsize=65536,namlen=255,
hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=XXX,
mountvers=3,mountport=635,mountproto=udp,local_lock=none,addr=XXX
```

This is what I see right away. Local linux test will follow and server fs follows.

I nailed down the critical size to be  2^31 B. As far as I understand (i am no expert on fs's) this really looks like a file system issue considering that the total transfer block size should also be rsize*wsize ( minus 1 check bit per w?) = 2^31.

**Comment by larsxschneider** [comment] 2017-05-18 10:35
I am curious about the local linux test? Did you solve the problem?

**Comment by ttaylorr** [comment] 2018-04-12 19:06
I am going to close this for now since it looks like a filesystem issue that LFS can't do anything about. Please let me know if there is something we can do, and if so -- I'd be happy to re-open this issue in the future.

**Closed by ttaylorr** 2018-04-12 19:06 UTC
