### ISSUE TITLE
All files inside git repo show up as lfs pointers

### ISSUE THREAD

**Issue by GTP95** [git-lfs/git-lfs#5543] opened 2023-10-15 16:30 UTC
Greetings,

I added and committed inside a local repository a file that is over GitHub's limit, so when I tried to push the latest commits it failed. I then tried to setup `git-lfs` to track that single file (a binary), here are the relevant commands I ran straight from my Bash history:
```Bash
git lfs install
git lfs track participant-login-poc/crates/client/resources/pepcli
git add .gitattributes
git lfs migrate import
git status
git lfs migrate import
git push
```
The reason why I ran twice `git lfs migrate import`, is that the first time I interrupted it after it gave me a warning about losing uncommitted changes. So I first checked that there weren't important uncommitted changes before running it again. Curiously, The only uncommitted change (at least that I remeber of) was the binary file I intended to track, which was likely modified by `git-lfs`.
Now each file I try to open shows up as a `git-lfs` pointer, e.g.
```Bash
$ cat participant-login-poc/crates/client/src/main.rs 
version https://git-lfs.github.com/spec/v1
oid sha256:63ecc7d8cd62fef16d3d6c50463644fa81dd9d92506bc9ca7a8f4fdb58579d8a
size 14851
```
How can I go back having files showing up normally (as text files containing code) and have only ` participant-login-poc/crates/client/resources/pepcli` managed by `git-lfs`? This seems similar to issue #3508, but following the suggestions given there didn't help. Maybe the fact that I didn't commit after adding `.gitattributes` has something to do about this?
Thank you for helping me.

**System environment**
I'm running Archlinux.
```Bash
$ git config -l
user.name=[redacted]
user.email=[redacted]
init.defaultbranch=main
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=git@github.com:GTP95/thesis.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
branch.desktop_application.remote=origin
branch.desktop_application.merge=refs/heads/desktop_application
lfs.repositoryformatversion=0
```

**Output of `git lfs env`**
```Bash
$ git lfs env
git-lfs/3.4.0 (GitHub; linux amd64; go 1.21.3)
git version 2.42.0

Endpoint=https://github.com/GTP95/thesis.git/info/lfs (auth=none)
  SSH=git@github.com:GTP95/thesis.git
LocalWorkingDir=/home/giacomo/git/thesis
LocalGitDir=/home/giacomo/git/thesis/.git
LocalGitStorageDir=/home/giacomo/git/thesis/.git
LocalMediaDir=/home/giacomo/git/thesis/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/giacomo/git/thesis/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/giacomo/git/thesis/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by GTP95** [comment] 2023-10-17 10:36
I was able to revert it locally by running `git lfs migrate export --everything --include="*"`, so now I at least have a local copy I can work with. But what would be the correct way to have only a single specific file stored inside git lfs?

**Comment by chrisd8088** [comment] 2023-10-18 21:47
Hey, I'm sorry you're having trouble, and I'm glad you found a way to get back to a working state.  Also, thank you for the detailed reproduction notes!

Looking at your reproduction steps, I think the issue is just that you ran `git lfs migrate import` without any other parameters, which by default imports all file types.  The key paragraph in this regard in the manual [page](https://github.com/git-lfs/git-lfs/blob/7bf4ebbf4b080d82d5091dc12583283da58b31d5/docs/man/git-lfs-migrate.adoc) is:
> For the `info` and `import` modes, all file types are considered by default; while useful in the `info` mode, this is often not desirable when importing, so either filename patterns (pathspecs) or the `--fixup` option should normally be specified in that case. (At least one include pathspec is required for the `export` mode.) Pathspecs may be defined using the `--include` and `--exclude` options (`-I` and `-X` for short).

So instead of these steps:
```
$ git lfs track participant-login-poc/crates/client/resources/pepcli
$ git add .gitattributes
$ git lfs migrate import
```

you want just this command:
```
$ git lfs migrate import --include=participant-login-poc/crates/client/resources/pepcli
```

That should rewrite your Git history so that when the `participant-login-poc/crates/client/resources/pepcli` file first appears, so does a `.gitattributes` file which contains:
```
participant-login-poc/crates/client/resources/pepcli filter=lfs diff=lfs merge=lfs -text
```

You won't need to run `git lfs track` at all, because the `.gitattributes` entry it would create has been generated by `git lfs migrate import`.

I hope that helps!  I'm going to close this issue, but let us know if there's more help we can provide.

**Closed by chrisd8088** 2023-10-18 21:47 UTC
