### ISSUE TITLE
Git lfs upload issue

### ISSUE THREAD

**Issue by 0xac0** [git-lfs/git-lfs#5296] opened 2023-02-26 14:07 UTC
**Describe the issue**
I can't seem to upload my files to git, I've tried doing git lfs fetch --all, but i get 404 error as the files don't exist. If i am correct this is because one of my uploads failed. I'd appriciate if anyone can help

**System environment**
git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)
git version 2.39.0.windows.2

**Output of `git lfs env`**

Error message
Uploading LFS objects:   0% (0/25), 0 B | 0 B/s, done.
Git LFS upload failed:
  (missing) Assets/Music Tracks/JumpyGame.wav (66ba7463dc9d4937be722515698e97463c124f907b16f0b335eba3c08adff4df)
  (missing) Assets/Music Tracks/Stupid_Dancer.wav (975ff3c6d30a69bf40aab31af09328ee49b22e01e110ff8bedbdff8f8dde5700)
  (missing) Assets/Music Tracks/Potato.wav (b01c8fb277a9f4aafdd8fa4e142ce574a05e282f3f60a6866d54c44172c86250)
  (missing) Assets/Plugins/GitHub/Editor/x64/pthreadVC2.dll (0e6af724609ef6846982ef717013426c359c455fff324e906d8d55c8bb88d16e)
  (missing) Assets/Plugins/GitHub/Editor/x86/pthreadVC2.dll (bac4472990c1dc2f037019791bd18888e78a3ae86605f3aae86f812a4d7d4f60)
  (missing) Assets/Plugins/GitHub/Editor/GitHub.Logging.dll (e495cb21943c4ea67673c11db54e737d25fd2aa00ef1af37d1df7ccba026759b)
  (missing) Assets/Music Tracks/StreetLove.wav (65e96436cfdd4b649b88c575683ab80c6c17a03cd1aaaf675109360f3e25f2ae)
  (missing) Assets/Music Tracks/Tiny_Blocks.wav (e6858763e845b3231856bcb7e6d7e3a2dbeeb52be9922d611614f92daf0328bf)
  (missing) Assets/Music Tracks/SunnyDay.wav (70398fac32b88e9cafe6469a8ec84af33e07eaed751fad7dd709962f5336a577)
  (missing) Assets/Music Tracks/Zephyr.wav (84365b6437f663fd76d8e47af8e9af4d3a4226cdce482f2e12bc6c258bc98bef)
  (missing) Assets/Plugins/GitHub/Editor/GitHub.Api.45.dll (1f88b65d56d7542c171548019eb408ae2b9ff10aa54657d71eddc2499384f856)
  (missing) Assets/Plugins/GitHub/Editor/GitHub.Api.dll (0598ee39acaec9732f0a00bd20528f07855a5298c67f53957bc6ad258c42d815)
  (missing) Assets/Plugins/GitHub/Editor/x86/sfw_x86.dll (843682e312df272a4222e2ba85f4feebfb0195524f101ef9f636f56ae0e0af21)
  (missing) Assets/Plugins/GitHub/Editor/GitHub.UnityShim.dll (409891774be0755c72effe01a3f47157858ce19fe8cba7e68c913acf0671ed75)
  (missing) Assets/Music Tracks/InfiniteDoors.wav (17cac4b4f721ae7d3166d4c629d70ad775af1fef37bd4ec536f17b001ff97202)
  (missing) Assets/Plugins/GitHub/Editor/Mono.Posix.dll (bda42c2c2c6d83a5c840d5262bfb1ae0e24e3c1778c96d5ea1ff96a1bb244f70)
  (missing) Assets/Plugins/GitHub/Editor/x64/sfw_x64.dll (4f8d586e00ddbe3cfa0cd2446bdd416a65e6c12ef31e7f451af14867b880c0dc)
  (missing) Assets/Plugins/GitHub/Editor/big-logo@2x.png (e986d8a21f6f621e89885d0e4e28a9c6171e02f2c095fbeb075e22d9b0f40f74)
  (missing) Assets/Plugins/GitHub/Editor/sfw.net.dll (21feeaa73e42bf03e86525bc5e1b954f4b9a2f16eed58a87c69e576509231480)
  (missing) Assets/Plugins/GitHub/Editor/ReadOnlyCollectionsInterfaces.dll (64803681966f009feaab1f02278ac2a38683fc99e88b4247d54d0534f1429b55)
  (missing) Assets/Music Tracks/Chunky_Monkey.wav (15aff0d509c97f5503ab2f18d949994da02e322d78f0be515cc768dfdeeb5da4)
  (missing) Assets/Plugins/GitHub/Editor/System.Threading.dll (25a3ec89ffc468c53a44a90ae99c23e1bcff9e5901be74033b4ce794a3202395)
  (missing) Assets/Plugins/GitHub/Editor/GitHub.Unity.45.dll (4abacb70e20c2f22a43d9cff198f7709f6601f7e3ff4f0aeb6f0f3b9dd7d74ba)
  (missing) Assets/Plugins/GitHub/Editor/GitHub.Unity.dll (966ffe7a5f4de501e439b9441fd29d7ceba3b76970f105ed331a6b385674ab3d)
  (missing) Assets/Plugins/GitHub/Editor/AsyncBridge.Net35.dll (0f61d9c0550c3a1e36e6eaa9bebbc3b5ca701c4e960dc2a92746df792d392140)
hint: Your push was rejected due to missing or corrupt local objects.

**Comment by chrisd8088** [comment] 2023-02-26 21:49
Hey, I'm sorry you're having trouble.  As you noted, there are clearly some missing objects which are causing your push to fail.

I suppose the first question to ask is whether these are objects you have created locally in the branch you are trying to push, or if these are objects which should exist on the server but apparently do not.  You mention running `git lfs fetch` and getting 404s, so I assume the problem is that the objects are supposed to be stored in the repo already, but are not there?

If that's the case (i.e., that these are not objects you've created locally in your branch), you would have to work with the server operator and/or any other developers using the repository to try to track down the missing objects.  Sometimes another developer may have them on their local system and can push them to "fill in" anything that's missing on the server.

**Comment by bk2204** [comment] 2023-04-25 19:40
I think this should answer the question reported, so I'm going to close this, but if that's not correct, please let us know and we can reopen.

**Closed by bk2204** 2023-04-25 19:40 UTC
