### ISSUE TITLE
git-lfs aborts with "LFS: Git credentials for https://XXX not found." even for repositories without passwords

### ISSUE THREAD

**Issue by JonasT** [git-lfs/git-lfs#1485] opened 2016-08-25 21:40 UTC
When run non-interactively, git-lfs pull aborts with "LFS: Git credentials for https://XXX not found." even for repositories _without_ any password protection.
When run interactively, it will download files correctly but prompt you a thousand times needlessly for some password which can be "fixed" by hitting the return key like an insane person.

To reproduce the bug, do the following setup:

```
mkdir blah
cd blah
git init .
git lfs install --skip-smudge .
git remote add origin https://gitlab.wobble.ninja/JonasT/wobbly.git
git remote update
git pull origin master
```

Now run in that folder the following command non-interactively: `git lfs pull origin master`
The repository is public and not password protected in any way, so obviously it should work. However, the result is: "LFS: Git credentials for https://gitlab.wobble.ninja/JonasT/wobbly.git not found."

(Alternatively, run it interactively and see a useless password prompt madness.)

A workaround would be highly appreciated, because this is preventing me from doing an automated deployment.

---

Expected behavior:

Non-interactively: at least _try without a password once_ instead of giving up with no good reason.

Interactively: if I just hit enter throughout the first prompts and the download works, asking me a thousand times for absolutely nothing is a bit silly (although I guess that gets better when using a credentials cache)

**Comment by JonasT** [comment] 2016-08-25 21:43
"Funny" trivia:

I tried to reproduce this in bash instead of my custom non-interactive server script, but even with ``` </dev/null >/dev/null 2>&1``` or wrapping it with ``` python3 -c "import subprocess; import sys; result = subprocess.call(['git', 'lfs', 'pull', 'origin', 'master']); sys.exit (result) ``` will make git / git-lfs find and grab the terminal and spam me with password prompts. Which also seems like kinda bad (or at least weird!) and unexpected behavior to me - if I'm running it with another stdin, I'm certainly not expecting a prompt, but oh well..

**Comment by JonasT** [comment] 2016-08-25 22:02
For anyone coming across this problem, I just found a workaround:

Submitting just any random nonsense in the url as user pw fixes it, e.g. https://gitlfsisbuggy:whatcanyoudo@gitlab.wobble.ninja/JonasT/wobbly.git

**Comment by technoweenie** [comment] 2016-08-25 22:05
Did your repository change permissions? By default, Git LFS won't ask any credentials. If the LFS server sends back a 401, Git LFS assumes the repository needs creds and sets `lfs.<url>.access`. Your local git config should have something like:

```
lfs.https://gitlab.wobble.ninja/JonasT/wobbly.git/info/lfs.access=basic
```

You can clear that key with `git config --unset lfs.https://gitlab.wobble.ninja/JonasT/wobbly.git/info/lfs.access`.

If that doesn't help, can you post `GIT_TRACE=1` output?

**Comment by JonasT** [comment] 2016-08-25 22:07
I tested this on two machines with one of them being a docker environment with freshly installed git-lfs in the latest version, so it's not a client config issue. This can be reproduced easily with any fresh git-lfs install given the instructions above.

As for the server, it's just how gitlab LFS server configures and serves the repo per default. I can't really influence that, and I didn't change anything. (Changing git settings of a repo on a gitlab server is kinda difficult anyway)

**Comment by technoweenie** [comment] 2016-08-25 22:12
Ah, I meant your local repo git config, not your server's.

Can you post `GIT_TRACE=1 git pull origin master` output for a fresh run? This looks like https://github.com/github/git-lfs/issues/1330, which is due to a problem in gitlab's lfs server http responses. The `GIT_TRACE=1` output will show if that's happening here too.

**Comment by JonasT** [comment] 2016-08-25 22:19
```
jonas@cyberman:~$ mkdir blah
jonas@cyberman:~$ cd blah
jonas@cyberman:~/blah$ git init .
Initialized empty Git repository in /home/jonas/blah/.git/
jonas@cyberman:~/blah$ git lfs install .
Updated pre-push hook.
Git LFS initialized.
jonas@cyberman:~/blah$ git remote add origin https://gitlab.wobble.ninja/JonasT/wobbly.git
jonas@cyberman:~/blah$ git remote update
Fetching origin
remote: Counting objects: 1212, done.
remote: Compressing objects: 100% (456/456), done.
remote: Total 1212 (delta 682), reused 1154 (delta 646)
Receiving objects: 100% (1212/1212), 314.02 KiB | 0 bytes/s, done.
Resolving deltas: 100% (682/682), done.
From https://gitlab.wobble.ninja/JonasT/wobbly
 * [new branch]      master     -> origin/master
jonas@cyberman:~/blah$ GIT_TRACE=1 git pull origin master
00:17:12.017903 git.c:344               trace: built-in: git 'pull' 'origin' 'master'
00:17:12.018206 run-command.c:334       trace: run_command: 'fetch' '--update-head-ok' 'origin' 'master'
00:17:12.018625 exec_cmd.c:120          trace: exec: 'git' 'fetch' '--update-head-ok' 'origin' 'master'
00:17:12.021788 git.c:344               trace: built-in: git 'fetch' '--update-head-ok' 'origin' 'master'
00:17:12.022578 run-command.c:334       trace: run_command: 'git-remote-https' 'origin' 'https://gitlab.wobble.ninja/JonasT/wobbly.git'
00:17:12.333177 run-command.c:334       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet'
00:17:12.337942 run-command.c:334       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all'
00:17:12.338430 exec_cmd.c:120          trace: exec: 'git' 'rev-list' '--objects' '--stdin' '--not' '--all'
00:17:12.340762 git.c:344               trace: built-in: git 'rev-list' '--objects' '--stdin' '--not' '--all'
From https://gitlab.wobble.ninja/JonasT/wobbly
 * branch            master     -> FETCH_HEAD
00:17:12.347983 run-command.c:334       trace: run_command: 'gc' '--auto'
00:17:12.348993 exec_cmd.c:120          trace: exec: 'git' 'gc' '--auto'
00:17:12.352423 git.c:344               trace: built-in: git 'gc' '--auto'
00:17:12.358541 run-command.c:334       trace: run_command: 'git-lfs smudge -- '\''docs/font/Quicksand-Light.ttf'\'''
00:17:12.358985 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git-lfs smudge -- '\''docs/font/Quicksand-Light.ttf'\''' 'git-lfs smudge -- '\''docs/font/Quicksand-Light.ttf'\'''
trace git-lfs: run_command: 'git' config -l
Downloading docs/font/Quicksand-Light.ttf (20.51 KB)
trace git-lfs: api: batch 1 files
trace git-lfs: HTTP: POST https://gitlab.wobble.ninja/JonasT/wobbly.git/info/lfs/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: {"objects":[{"oid":"ca656c46214997aed06c43480958b8d2a3abeff8d684291f446c92a4ed1bf2a2","size":21004,"actions":{"download":{"href":"https://gitlab.wobble.ninja/JonasT/wobbly.git/gitlab-lfs/objects/ca656c46214997aed06c43480958b8d2a3abeff8d684291f446c92a4ed1bf2a2","header":{}}}}]}
trace git-lfs: HTTP: 
Username for 'https://gitlab.wobble.ninja': 
Password for 'https://gitlab.wobble.ninja': 
trace git-lfs: Filled credentials for https://gitlab.wobble.ninja/JonasT/wobbly.git
trace git-lfs: HTTP: GET https://gitlab.wobble.ninja/JonasT/wobbly.git/gitlab-lfs/objects/ca656c46214997aed06c43480958b8d2a3abeff8d684291f446c92a4ed1bf2a2
trace git-lfs: HTTP: 200
00:17:25.648262 run-command.c:334       trace: run_command: 'git-lfs smudge -- '\''docs/font/Quicksand-Regular.ttf'\'''
00:17:25.648711 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git-lfs smudge -- '\''docs/font/Quicksand-Regular.ttf'\''' 'git-lfs smudge -- '\''docs/font/Quicksand-Regular.ttf'\'''
trace git-lfs: run_command: 'git' config -l
Downloading docs/font/Quicksand-Regular.ttf (23.27 KB)
trace git-lfs: api: batch 1 files
trace git-lfs: HTTP: POST https://gitlab.wobble.ninja/JonasT/wobbly.git/info/lfs/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: {"objects":[{"oid":"966cff99d5ff075470fa18ded16479295e8398562d6e9dc77da8eb32f494b467","size":23824,"actions":{"download":{"href":"https://gitlab.wobble.ninja/JonasT/wobbly.git/gitlab-lfs/objects/966cff99d5ff075470fa18ded16479295e8398562d6e9dc77da8eb32f494b467","header":{}}}}]}
trace git-lfs: HTTP: 
Username for 'https://gitlab.wobble.ninja': 
Password for 'https://gitlab.wobble.ninja': 
trace git-lfs: Filled credentials for https://gitlab.wobble.ninja/JonasT/wobbly.git
trace git-lfs: HTTP: GET https://gitlab.wobble.ninja/JonasT/wobbly.git/gitlab-lfs/objects/966cff99d5ff075470fa18ded16479295e8398562d6e9dc77da8eb32f494b467
trace git-lfs: HTTP: 200
00:17:27.314841 run-command.c:334       trace: run_command: 'git-lfs smudge -- '\''misc/logo/jellyphoto_orig.jpg'\'''
00:17:27.315365 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git-lfs smudge -- '\''misc/logo/jellyphoto_orig.jpg'\''' 'git-lfs smudge -- '\''misc/logo/jellyphoto_orig.jpg'\'''
trace git-lfs: run_command: 'git' config -l
Downloading misc/logo/jellyphoto_orig.jpg (519.08 KB)
trace git-lfs: api: batch 1 files
trace git-lfs: HTTP: POST https://gitlab.wobble.ninja/JonasT/wobbly.git/info/lfs/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: {"objects":[{"oid":"4f919fdfa1df571236f1df518a4f152fcd36de5aaaa14e685d87bef6c3f43f62","size":531540,"actions":{"download":{"href":"https://gitlab.wobble.ninja/JonasT/wobbly.git/gitlab-lfs/objects/4f919fdfa1df571236f1df518a4f152fcd36de5aaaa14e685d87bef6c3f43f62","header":{}}}}]}
trace git-lfs: HTTP: 
Username for 'https://gitlab.wobble.ninja': 
Password for 'https://gitlab.wobble.ninja': 
trace git-lfs: Filled credentials for https://gitlab.wobble.ninja/JonasT/wobbly.git
trace git-lfs: HTTP: GET https://gitlab.wobble.ninja/JonasT/wobbly.git/gitlab-lfs/objects/4f919fdfa1df571236f1df518a4f152fcd36de5aaaa14e685d87bef6c3f43f62
trace git-lfs: HTTP: 200
00:17:29.059777 run-command.c:334       trace: run_command: 'git-lfs smudge -- '\''misc/logo/logo.ico'\'''
00:17:29.060281 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git-lfs smudge -- '\''misc/logo/logo.ico'\''' 'git-lfs smudge -- '\''misc/logo/logo.ico'\'''
trace git-lfs: run_command: 'git' config -l
Downloading misc/logo/logo.ico (455.33 KB)
trace git-lfs: api: batch 1 files
trace git-lfs: HTTP: POST https://gitlab.wobble.ninja/JonasT/wobbly.git/info/lfs/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: {"objects":[{"oid":"f2ada7da98eef080add3abc6449e796833eadc5e2632fbc4ebef48031cc04770","size":466256,"actions":{"download":{"href":"https://gitlab.wobble.ninja/JonasT/wobbly.git/gitlab-lfs/objects/f2ada7da98eef080add3abc6449e796833eadc5e2632fbc4ebef48031cc04770","header":{}}}}]}
trace git-lfs: HTTP: 
Username for 'https://gitlab.wobble.ninja': 
Password for 'https://gitlab.wobble.ninja': 
trace git-lfs: Filled credentials for https://gitlab.wobble.ninja/JonasT/wobbly.git
trace git-lfs: HTTP: GET https://gitlab.wobble.ninja/JonasT/wobbly.git/gitlab-lfs/objects/f2ada7da98eef080add3abc6449e796833eadc5e2632fbc4ebef48031cc04770
trace git-lfs: HTTP: 200
00:17:30.927700 run-command.c:334       trace: run_command: 'git-lfs smudge -- '\''misc/logo/logo.xcf'\'''
00:17:30.928206 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git-lfs smudge -- '\''misc/logo/logo.xcf'\''' 'git-lfs smudge -- '\''misc/logo/logo.xcf'\'''
trace git-lfs: run_command: 'git' config -l
Downloading misc/logo/logo.xcf (900.90 KB)
trace git-lfs: api: batch 1 files
trace git-lfs: HTTP: POST https://gitlab.wobble.ninja/JonasT/wobbly.git/info/lfs/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: {"objects":[{"oid":"a2a25b73f819fd095b5542347b24b6f14ac640a29d08a18c9fead3eed578061a","size":922521,"actions":{"download":{"href":"https://gitlab.wobble.ninja/JonasT/wobbly.git/gitlab-lfs/objects/a2a25b73f819fd095b5542347b24b6f14ac640a29d08a18c9fead3eed578061a","header":{}}}}]}
trace git-lfs: HTTP: 
Username for 'https://gitlab.wobble.ninja': 
Password for 'https://gitlab.wobble.ninja': 
trace git-lfs: Filled credentials for https://gitlab.wobble.ninja/JonasT/wobbly.git
trace git-lfs: HTTP: GET https://gitlab.wobble.ninja/JonasT/wobbly.git/gitlab-lfs/objects/a2a25b73f819fd095b5542347b24b6f14ac640a29d08a18c9fead3eed578061a
trace git-lfs: HTTP: 200
00:17:33.138429 run-command.c:334       trace: run_command: 'git-lfs smudge -- '\''misc/logo/logo_base.xcf'\'''
00:17:33.138893 run-command.c:193       trace: exec: '/bin/sh' '-c' 'git-lfs smudge -- '\''misc/logo/logo_base.xcf'\''' 'git-lfs smudge -- '\''misc/logo/logo_base.xcf'\'''
trace git-lfs: run_command: 'git' config -l
Downloading misc/logo/logo_base.xcf (2.26 MB)
trace git-lfs: api: batch 1 files
trace git-lfs: HTTP: POST https://gitlab.wobble.ninja/JonasT/wobbly.git/info/lfs/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: {"objects":[{"oid":"428f7126c56cd1248d6db883874d56deee1e9e8087fd7323eab992019833080c","size":2372595,"actions":{"download":{"href":"https://gitlab.wobble.ninja/JonasT/wobbly.git/gitlab-lfs/objects/428f7126c56cd1248d6db883874d56deee1e9e8087fd7323eab992019833080c","header":{}}}}]}
trace git-lfs: HTTP: 
Username for 'https://gitlab.wobble.ninja': 
Password for 'https://gitlab.wobble.ninja': 
trace git-lfs: Filled credentials for https://gitlab.wobble.ninja/JonasT/wobbly.git
trace git-lfs: HTTP: GET https://gitlab.wobble.ninja/JonasT/wobbly.git/gitlab-lfs/objects/428f7126c56cd1248d6db883874d56deee1e9e8087fd7323eab992019833080c
trace git-lfs: HTTP: 200
Checking out files: 100% (49/49), done.
jonas@cyberman:~/blah$
```

Each time you're seeing a user and password prompt, I simply just hit enter to continue.

**Comment by technoweenie** [comment] 2016-08-25 22:50
Ah, different issue. The server needs to be updated to return `authenticated: true` for objects that don't need authentication. /cc https://github.com/github/git-lfs/pull/1452

**Comment by JonasT** [comment] 2016-08-25 23:01
The merge request sounds like this was supposed to be backwards compatible. However, it does seem to break non-interactive lfs pulls?

**Comment by technoweenie** [comment] 2016-08-25 23:10
> unless this never worked properly before, of course

Er nope :/ 

I think the suggestion in https://github.com/github/git-lfs/issues/1330#issuecomment-228803900 could make the client smarter about asking multiple times in a single command, without requiring the changes to the server.

**Comment by sokhanget** [comment] 2016-11-08 20:30
https://github.com/github/git-lfs/issues/1330#issuecomment-228803900

**Comment by JonasT** [comment] 2017-02-08 11:55
gitlab has finally added support for the "Authenticated" property a few hours ago: https://gitlab.com/gitlab-org/gitlab-ce/issues/23360

So I suppose in about a month, this problem should finally be solved for all gitlab instances that are kept up-to-date and the hosting service gitlab.com.

I guess it only remains left to ask whetger bitbucket is doing this properly, but otherwise this issue will be pretty much solved for the future.

**Comment by technoweenie** [comment] 2017-02-08 14:22
Thanks for the update! Closing this, as there's nothing on the client to fix.

**Closed by technoweenie** 2017-02-08 14:22 UTC

**Comment by axonetric** [comment] 2017-12-23 21:25
For those experiencing this issue on Windows, I found the following command fixes it:

`git config --global credential.helper cache`

**Comment by Canadauni** [comment] 2018-01-04 19:06
In my case on Windows using gitbash I had to use:
`git config --global credential.helper wincred`

**Comment by shopglobal** [comment] 2018-03-02 18:41
Thank you @Canadauni 
For Windows, this is still confirmed solution.

**Comment by NikoBele1** [comment] 2018-06-07 11:57
Same for me with @Canadauni's line

**Comment by brianagina** [comment] 2019-01-03 13:01
Canadauni, you are a life saver!

**Comment by Castern** [comment] 2019-06-08 17:59
git config --global credential.helper cache

Worked for me. Thank You!
