### ISSUE TITLE
Detect and reject over-sized files

### ISSUE THREAD

**Issue by otri** [git-lfs/git-lfs#2853] opened 2018-02-02 00:55 UTC
In reference to issue 
https://github.com/git-lfs/git-lfs/issues/730

> That'd be nice, but that server side limit has nothing to do with the Git LFS client. We could add an API call every time a file is added, but that would add even more overhead to adding files. I'd be interested in PRs that solve this though.

I'd argue that this issue is core to Git LFS usage, because the repercussions are non-trivial for all users that encounter it.  A quick usability test of adding a file to any Git LFS repository with a reasonable file size limit causes a forced failure mode that a user must unwind.  Thereby getting into deep internals of how git and git-lfs functions.  Most clients do not handle this issue well and the error is not brought to the surface.

So Git LFS must handle this file size restriction through a formalized method.

At bare minimum there should be a way to:
- Determine the file size limits on an associated Git LFS server, and cache this locally (not an API check on every add)
- Warn of adding an over-size file to Git LFS at time of the addition, allow a "--force" option
- Formalize handling of adding a file to the Git LFS server that encounters a restriction, and report the specific file in question
- Allow easy removal of the offending file by path or hash identifier

**Comment by ttaylorr** [comment] 2018-02-06 03:21
Closing as a duplicate of: https://github.com/git-lfs/git-lfs/issues/730#issuecomment-362451432.

**Closed by ttaylorr** 2018-02-06 03:21 UTC
