### ISSUE TITLE
reverting files

### ISSUE THREAD

**Issue by ggrrll** [git-lfs/git-lfs#5463] opened 2023-08-10 13:06 UTC
my local repo (only local, I did not push nor committed changes) is getting messy
I installed LFS and tracked few files types, but now I want to recover the original files -- what should I do?

* isn't weird that files were reduced to pointers, even if I did not push anywhere ?

I have read related issues like https://github.com/git-lfs/git-lfs/issues/3463 but:

* `git lfs migrate export --include ` is not working (files are still pointers)
* also `git lfs untrack ...` does not modify anymore .gitattribute 

no idea 🤷‍♂️  what do do ...

here are  my `git config --global`
```
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
```

thanks

**Comment by chrisd8088** [comment] 2023-08-10 14:58
Hey, I'm sorry you're having trouble.  If you can provide a complete reproduction case, plus the output of `git lfs env` (minus any private information like authorization details), as requested in the issue template, that would be great.  Without that, I'm not sure we can provide much assistance.

One key question is whether you ran `git lfs migrate import`, because that will rewrite your Git history to convert files to Git LFS objects in your local history; it's independent of whether you have pushed any commits to a remote.

**Comment by ggrrll** [comment] 2023-08-10 16:16
thanks for your answer

FRC is impossible ,as we have many sensitive data files 

here is my `env` 

```
git-lfs/3.4.0 (GitHub; linux amd64; go 1.20.6)
git version 2.25.1

Endpoint=https://BOTTNEURO@dev.azure.com/BOTTNEURO/phase1/_git/phase1.git/info/lfs (auth=basic)
LocalWorkingDir=/disk1TB/outputs
LocalGitDir=/disk1TB/outputs/.git
LocalGitStorageDir=/disk1TB/outputs/.git
LocalMediaDir=/disk1TB/outputs/.git/lfs/objects
LocalReferenceDirs=
TempDir=/disk1TB/outputs/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/disk1TB/outputs/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by chrisd8088** [comment] 2023-08-10 16:21
I understand your Git data may be private.  What I meant by a reproduction case was a set of instructions which illustrate the problem with non-sensitive example data.  For instance:
```
$ git init test
$ cd test
$ echo foo >foo.bin
$ git add foo.bin
$ git commit -m foo
$ git lfs migrate import --include="*.bin"
$ ...
$ git lfs migrate export --include="*.bin"
$ ... <show problem here>
```

**Comment by ggrrll** [comment] 2023-08-10 16:29
I don't remember running `import` ... I just followed https://git-lfs.com/ , before commit 

after `git add .` the tracked files became pointers 
if you tell me that that can only happen if you run `migrate import` then, I might forget something (although weird that is not present on my bash history)

**Comment by chrisd8088** [comment] 2023-08-10 17:08
Hmm ... well, the normal behaviour is for `git add`, which runs the Git LFS `clean` filter, to convert any files matching the set of Git LFS patterns in `.gitattributes` into Git LFS objects.  So that is expected; normally this means that an object file is created under `.git/lfs/objects` with the contents of the file being added, and the Git index is updated with the Git LFS pointer.  The copy of the file in the working tree is generally not altered.
```
$ git init test
$ cd test
$ echo foo >foo.bin
$ git add foo.bin
$ git commit -m foo

$ git lfs track "*.bin"
$ git add .

$ git diff --cached
diff --git a/.gitattributes b/.gitattributes
new file mode 100644
index 0000000..4edd5ac
--- /dev/null
+++ b/.gitattributes
@@ -0,0 +1 @@
+*.bin filter=lfs diff=lfs merge=lfs -text
diff --git a/foo.bin b/foo.bin
index 257cc56..ad483a9 100644
--- a/foo.bin
+++ b/foo.bin
@@ -1 +1,3 @@
-foo
+version https://git-lfs.github.com/spec/v1
+oid sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
+size 4

$ cat foo.bin 
foo

$ cat .git/lfs/objects/b5/bb/b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c 
foo
```

So in that respect, it is expected that `git add` will start generating Git LFS objects.

If you run through that example, do you get the same results, with the working tree untouched but a new object in `.git/lfs/objects` and the pointer in the Git index (i.e., the staged pointer file shown output of `git diff --cached`)?

**Comment by ggrrll** [comment] 2023-08-11 08:52
> The copy of the file in the working tree is generally not altered.

yes, indeed, this is what happened during a separate test  I did 
https://github.com/git-lfs/git-lfs/discussions/5458#discussioncomment-6689993

**Comment by ggrrll** [comment] 2023-08-11 09:01
so, the question is still : why `export` does not work ...

**Comment by ggrrll** [comment] 2023-08-11 10:10
meanwhile, I did my self, with  a little script -- is that what `export` is suppose to do ? 
(`mv`, instead of `cp`)

```
#!/usr/bin/env bash 

for pointerfile in $(git lfs ls-files  | awk '{print $NF}' | grep -v opt-opt) ; do

	pointerfile="./$pointerfile"
	myshasum=$(grep -o 'sha256:[a-f0-9]*' "$pointerfile" | cut -d ':' -f 2)
	file_path=$(find /disk1TB/outputs/.git/lfs/ -name "$myshasum")
	cp "$file_path" "$pointerfile"
done
```

**Comment by ggrrll** [comment] 2023-08-11 10:48
something more weird:

I managed to recover basically 1/2 of the files , now present as pointers, while the rest is not even listed in `git ls-file`  ... where did they go?

**Comment by chrisd8088** [comment] 2023-08-11 16:21
> is that what `export` is suppose to do ?

I think the short answer here is no, that's not what it does.  I would suggest reading through the manual [page](https://github.com/git-lfs/git-lfs/blob/1820b646e05c24497652b3f9eaf91500dc1ee988/docs/man/git-lfs-migrate.adoc), of course, but one key point is that `git lfs migrate` is intended to be, in general, a one-time operation which rewrites your existing Git history.  That is, it replaces existing commits with new ones; you end up with a different repo with a different chain of commits.

So the `git lfs migrate export` command works by traversing all the commits you specify (the current branch, or all branches with `--everything`, or a specific branch) and rewriting commits.

It won't affect files in your working copy if you haven't committed anything.  It only operates on your commit history.  So it's not the same as the script you wrote, which just modifies things in your working tree.

To help more, we would really need a precise and complete list of all the instructions you've followed in order to provide more assistance, along with at least an example set of files, commits, etc., even if you can't provide the originals.  It's very difficult to speculate as to what's going on otherwise.

**Comment by ggrrll** [comment] 2023-08-14 07:49
there was many commands , but basically the first 3 steps of https://git-lfs.com/, until the commit (excluded)

as far as I can see, I don't think we can recover those files, which is ok, as they were not crucial and can be re-generated  (our code base is in another repo)

**Closed** 2023-08-14 07:51 UTC
