### ISSUE TITLE
git lfs migrate import command corrupted object tree

### ISSUE THREAD

**Issue by yhe13** [git-lfs/git-lfs#4796] opened 2021-12-22 20:24 UTC
**Describe the bug**
git lfs migrate import command corrupted object tree.
>Note: This happends 100% on one of our repo (see below log), but does not happen on other repos. it is repo specifc.

**To Reproduce**
1. clone the repo in bare mode
2. run **git fsck** on the cloned repo, no issue reported.
3. run **git lfs migrate import --include="*.zip"** (commits rewritten)
4. run **git fsck** again, see lots of tree error: 
**error in tree <SHA>: duplicateEntries: contains duplicate file entries**

```
ad_yhe13@JFS1SAPP0042 MINGW64 /c/Hoffer/temp
$ git clone ssh://xxxxxxxxxxxxxxxx/hadas_cmt_testprog.git --bare
Cloning into bare repository 'hadas_cmt_testprog.git'...
Welcome to Intel Hardened OS
remote: Enumerating objects: 90, done.
remote: Counting objects: 100% (90/90), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 6685 (delta 36), reused 36 (delta 13), pack-reused 6595
Receiving objects: 100% (6685/6685), 191.77 MiB | 11.97 MiB/s, done.
Resolving deltas: 100% (1791/1791), done.

ad_yhe13@JFS1SAPP0042 MINGW64 /c/Hoffer/temp
$ cd hadas_cmt_testprog.git

ad_yhe13@JFS1SAPP0042 MINGW64 /c/Hoffer/temp/hadas_cmt_testprog.git (BARE:dev)
$ git --version
git version 2.34.1.windows.1

ad_yhe13@JFS1SAPP0042 MINGW64 /c/Hoffer/temp/hadas_cmt_testprog.git (BARE:dev)
$  git lfs --version
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)

ad_yhe13@JFS1SAPP0042 MINGW64 /c/Hoffer/temp/hadas_cmt_testprog.git (BARE:dev)
$ git fsck
Checking object directories: 100% (256/256), done.
Checking objects: 100% (6685/6685), done.

ad_yhe13@JFS1SAPP0042 MINGW64 /c/Hoffer/temp/hadas_cmt_testprog.git (BARE:dev)
$ git lfs migrate import --include="*.zip"
migrate: Sorting commits: ..., done.
migrate: Rewriting commits: 100% (154/154), done.
  dev                           464abc64ce576af2bf413a5c3843e4c1a0c4b0fb -> ba1bc6aaec61e91c475cf41331ba90622ae37574
  night_run_13May               5ac524449024ec90de7d11e724370d7524a60953 -> 6219d4a0e56ece6fbcc05f9f34d8f96f5c5ff808
  qual_pre_lkg_analysis         e828ee65a423b91c8dbba35d6e6cfb3e715f089c -> 8e9ef79d0946718cd2976983ca571a9b031bcb67
  qual_pre_lkg_analysis_rev2    3a0b24bf3da6f6d89296b14fbb2cc22ce6a92c47 -> 8aaa32351899a970da17c49dbed01c3556ea9a64
  qual_pre_lkg_analysis_rev3    7ab449303b340c14614986a31e8efa3c0c498fb1 -> 7b83a19392167b110d2a5919bd694b92dc8446d1
migrate: Updating refs: ..., done.

ad_yhe13@JFS1SAPP0042 MINGW64 /c/Hoffer/temp/hadas_cmt_testprog.git (BARE:dev)
$ git fsck
error in tree 00eb9ef41ada7ba69d1fa3d109134a34360b013d: duplicateEntries: contains duplicate file entries
error in tree 0b484acb3b4aa1a7e954ca29c035a1e7f77957a8: duplicateEntries: contains duplicate file entries
error in tree 0ba2c3a6d1b877017de7efffa05cd4b428b69257: duplicateEntries: contains duplicate file entries
error in tree 0c922abddc3bb857bfc7441f99fcc78653f3870a: duplicateEntries: contains duplicate file entries
....
error in tree fea2c3d70d906954a9f7d1a03d3d2dd150b0444a: duplicateEntries: contains duplicate file entries
Checking object directories: 100% (256/256), done.
Checking objects: 100% (6685/6685), done.
```

**Expected behavior**
no tree error after lfs migrate import

**System environment**
Git-bash on windows, git + git lfs on ubuntu 20

**Output of `git lfs env`**
```
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
git version 2.34.1.windows.1

Endpoint=https://gitlab.devtools.intel.com/sbakish/hadas_cmt_testprog.git/info/lfs (auth=none)
  SSH=git@gitlab.devtools.intel.com:/sbakish/hadas_cmt_testprog.git
LocalWorkingDir=
LocalGitDir=C:\Hoffer\temp\hadas_cmt_testprog.git
LocalGitStorageDir=C:\Hoffer\temp\hadas_cmt_testprog.git
LocalMediaDir=C:\Hoffer\temp\hadas_cmt_testprog.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Hoffer\temp\hadas_cmt_testprog.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Hoffer\temp\hadas_cmt_testprog.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by chrisd8088** [comment] 2021-12-23 19:00
Hey, thanks for the report, and this does sound like unexpected behaviour.

Would you be able to try with an older Git LFS client to see if it reproduces the problem?  For instance, could you try with v3.0.1 and v2.13.3?

As well, if you can provide any kind of small test repository that demonstrates the issue, that would be fantastic.

**Comment by yhe13** [comment] 2021-12-23 23:20
I've found this issue in 2.13.1, and then tried on latest version, both has the same error. I don't know how to create a smaller/non-confidential one to reproduce this, since this only happens on that particular repo...

any other command/verbose flags or ways that we can help debug this?

**Comment by chrisd8088** [comment] 2021-12-25 00:03
Interesting ... well, that rules out one possibility, at least.  I guess I'll mark this as "mcve-required" for now until we can find a reproducible public test case.

You could certainly try with `GIT_TRACE=1` and the `--verbose` flag to see if there's anything that jumps out, particularly with regard to the tree and files in question.

**Comment by yhe13** [comment] 2021-12-30 21:43
Thank you. we'll try check the verbos logs and also see if we can find a shareable case.

**Comment by Ashsegov23** [comment] 2021-12-30 21:45
Thank you so much I’m new to this so I really don’t know much thank you again 🙏🏼 God bless

Ashley Segovia

**Comment by chrisd8088** [comment] 2022-01-17 21:14
Out of interest, what do `git cat-file -p 00eb9ef41ada7ba69d1fa3d109134a34360b013d` and similar command show you for the tree objects that `git fsck` reports as having duplicate entries?  Can you identify what the duplicates are?  Even better would be if you identify what they were before the migration!

**Comment by chrisd8088** [comment] 2022-01-18 19:42
Interesting -- it looks like the `.gitattributes` file is being duplicated and that's the issue.  What's intriguing is that they have different permissions modes:
```
100755 blob e72d32c601a7589c44e9c185c45fc6c52d572d40	.gitattributes
100644 blob 79d38783743b2073da8ed6f54b6043dfd7be80b3	.gitattributes
```

With that hint, I was able to duplicate this behaviour with a simple test case:
```
$ git init test
$ cd test
$ echo foo > foo.bin
$ echo bar > bar.bin
$ echo '*.txt text' > .gitattributes
$ chmod 755 .gitattributes
$ git add .gitattributes *.bin
$ git commit -m init
 3 files changed, 3 insertions(+)
 create mode 100755 .gitattributes
 create mode 100644 bar.bin
 create mode 100644 foo.bin

$ git lfs migrate import --include='*.bin'

$ git ls-tree HEAD
100755 blob 6bd63ffcba2be1a59649db6528ce9df6a4d358dd	.gitattributes
100644 blob 4d00de526e9ade5436fc5180cba4b75a446bc289	.gitattributes
100644 blob 01613474789de934ab15077e96fb168c6a14f694	bar.bin
100644 blob ad483a923bcf4e7ef83182817802d740ee4d2ec6	foo.bin
```

This is, I assume, due to the fact that the [import](https://github.com/git-lfs/git-lfs/blob/20181362c2eaf951a5afabc9414865462ba7cbf4/commands/command_migrate_import.go#L255) and [export](https://github.com/git-lfs/git-lfs/blob/20181362c2eaf951a5afabc9414865462ba7cbf4/commands/command_migrate_export.go#L97) code specifically create or modify a tree entry with a 644 mode.

So as a workaround, you could try changing the mode of all your `.gitattributes` files to 644 (throughout your history and in all branches, not just in the tips of the branches).  I confess I don't have a handy set of instructions to do this, but perhaps other @git-lfs/core folk have an idea on how to use `git filter-branch` or something like that.

As for a proper fix, I suppose we could look for `.gitattributes` files with other modes and at least print an error ... there are a number of cases to consider here, not just the need to do this in multiple sub-commands (import, export, and info) but also the range of potential permissions modes (everything _except_ 644, in fact) and even the chance that a repo already has more than two `.gitattributes` files with different modes in the same tree object.  Hmm.

**Comment by bk2204** [comment] 2022-01-18 19:54
I'll just point out that Git only allows 644 or 755 permissions, although of course somebody could have stuffed a symlink or tree into that location, in which case we should just die.  Otherwise, if the permissions are 755, we should just deal with it, even though that's clearly nonsensical (since nobody will be able to execute the file).

I think if you need to use `git filter-branch`, you can use `--index-filter` with `git update-index --chmod=-x .gitattributes`, although I haven't tested that.

**Comment by yhe13** [comment] 2022-01-20 19:52
Is it possible to fix it in the lfs code to proper handle this case?

**Comment by bk2204** [comment] 2022-01-20 20:48
We'll end up providing a fix for this case, yes.  I believe the fix will probably end up in our gitobj library instead of Git LFS proper, though.  We'll likely end up delaying 3.1 to try to get a fix in here, so hopefully we can have a fix out relatively soon.

**Comment by yhe13** [comment] 2022-01-21 18:00
Thanks for helping on the fix @bk2204 ! 
yea, it doesn't make any sense for .gitattributes to have the execution bit.

**Closed** 2022-01-25 17:27 UTC
