### ISSUE TITLE
Separate Git dir not working on Windows (cygwin)

### ISSUE THREAD

**Issue by brice-ruppen** [git-lfs/git-lfs#3667] opened 2019-05-27 13:53 UTC
On Windows, I cannot use LFS while using a different git directory than ./.git

Here is a normal test:
```
$ mkdir test-original

$ cd test-original/

$ git init .
Dépôt Git vide initialisé dans /mnt/c/Users/brice/test-original/.git/

$ echo Hello World > README.md

$ git add README.md

$ git commit -m "Initial commit"
[master (commit racine) b890ecf] Initial commit
 1 file changed, 1 insertion(+)
 create mode 100644 README.md

$ git lfs install --local
Updated git hooks.
Git LFS initialized.

$ git lfs fsck
Git LFS fsck OK
```

Here I use a separate git directory:
```
$ mkdir test-separate

$ cd test-separate/

$ git init . --separate-git-dir=.tig
Dépôt Git vide initialisé dans /mnt/c/Users/brice/test-separate/.tig/

$ echo Hello World > README.md

$ git add README.md

$ git commit -m "Initial commit"
[master (commit racine) 8d6571b] Initial commit
 1 file changed, 1 insertion(+)
 create mode 100644 README.md

$ git lfs install --local
Updated git hooks.
Git LFS initialized.

$ git lfs fsck
Error checking Git LFS files

Errors logged to C:\Users\brice\test-separate\.tig\lfs\logs\20190527T152128.5375028.log
Use `git lfs logs last` to view the log.

$ git lfs logs last
git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
git version 2.17.0

$ git lfs fsck
Error checking Git LFS files

missing object: 557db03de997c86a4a028e1ebd3a1ceb225be238

Current time in UTC:
2019-05-27 13:21:28

ENV:
LocalWorkingDir=C:\Users\brice\test-separate
LocalGitDir=C:\Users\brice\test-separate\.tig
LocalGitStorageDir=C:\Users\brice\test-separate\.tig
LocalMediaDir=C:\Users\brice\test-separate\.tig\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\brice\test-separate\.tig\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\brice\test-separate\.tig\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_LFS_PATH=C:\Program Files\Git LFS

Client IP addresses:
fe80::d02f:2c97:d1da:f040 10.0.75.1
fe80::e131:ef91:e5d8:778b 169.254.119.139
fe80::202d:a6b8:6e30:42cf 192.168.137.1
fe80::9cd8:c540:696a:98a1 192.168.100.1
fe80::5868:338b:d97c:4ba 192.168.50.1
fe80::e8d0:60fd:8b60:f6ac 10.253.75.147
fe80::c5f4:c349:9b63:b999 172.18.88.193

$ git ls-files -s
100644 557db03de997c86a4a028e1ebd3a1ceb225be238 0       README.md
```

It works fine in WSL so I guess there is no problem with Linux.
Any pointers on what could be wrong ?

**Comment by bk2204** [comment] 2019-05-28 14:26
Hey, thanks for writing in.

I'm a bit confused by your reproduction steps, since for me (testing on Windows), I can't even succeed with `git add` without explicitly specifying a `--git-dir=.tig` option. It also looks like maybe you're using the Git from WSL, but a Windows-based Git LFS, to access a Windows mount by the use of `/mnt/c`.

Is that accurate, and do you have anything in your environment that might differ from a standard Git Bash?

**Comment by brice-ruppen** [comment] 2019-05-28 15:35
Hello, thanks for the reply.
When using `git init . --separate-git-dir=.tig`, Git actually creates a .git file and a .tig folder.
```
$ cat .git
gitdir: /mnt/c/Users/brice/test-separate/.tig
```
So you should be able to use git without explicitely adding `--git-dir=.tig`.
But I'm definitely using the Git from Cygwin.
```
$ git version
git version 2.17.0

$ which git
/usr/bin/git

$ cygpath -w $(which git)
C:\Users\brice\AppData\Local\cygwin\bin\git.exe

$ ldd $(which git)
        ntdll.dll => /mnt/c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffc245d0000)
        KERNEL32.DLL => /mnt/c/WINDOWS/System32/KERNEL32.DLL (0x7ffc21e70000)
        KERNELBASE.dll => /mnt/c/WINDOWS/System32/KERNELBASE.dll (0x7ffc214b0000)
        cygwin1.dll => /usr/bin/cygwin1.dll (0x180040000)
        cygintl-8.dll => /usr/bin/cygintl-8.dll (0x3f33b0000)
        cygiconv-2.dll => /usr/bin/cygiconv-2.dll (0x3f5200000)
        cygpcre-1.dll => /usr/bin/cygpcre-1.dll (0x3f1f70000)
        cygz.dll => /usr/bin/cygz.dll (0x3f06d0000)
```
I've tried installing Git-Bash and setting my environment variables and it works no problem:
```
$ git lfs env
git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
git version 2.21.0.windows.1

LocalWorkingDir=C:\Users\brice\AppData\Local\Temp\test-separate
LocalGitDir=C:\Users\brice\AppData\Local\Temp\test-separate\.tig
LocalGitStorageDir=C:\Users\brice\AppData\Local\Temp\test-separate\.tig
LocalMediaDir=C:\Users\brice\AppData\Local\Temp\test-separate\.tig\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\brice\AppData\Local\Temp\test-separate\.tig\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\brice\AppData\Local\Temp\test-separate\.tig\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

I've update my version of git but the problem still persists in Cygwin.
```
$ git lfs env
git-lfs/2.7.2 (GitHub; windows amd64; go 1.12.2; git 08a08ae0)
git version 2.21.0

LocalWorkingDir=C:\Users\brice\test-separate
LocalGitDir=C:\Users\brice\test-separate\.tig
LocalGitStorageDir=C:\Users\brice\test-separate\.tig
LocalMediaDir=C:\Users\brice\test-separate\.tig\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\brice\test-separate\.tig\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\brice\test-separate\.tig\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=/usr/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

It might be a problem with Git itself, but with the way Git LFS acts, it's difficult to see what is happening.
To answer the last question, I changed /cygdrive to /mnt and my Cygwin home is the same as Windows.

**Comment by bk2204** [comment] 2019-05-28 16:09
Okay, for some reason, Git Bash wasn't creating the gitlink for me when I was using it.

I think I know what's going on here: we have a spot where we aren't canonicalizing paths for the Git common directory. I have a branch called `cygwin-canonicalize-path` on my remote. Could you try that branch and see if it works for you? You'll want do something like the following:

```console
$ go get github.com/git-lfs/git-lfs
$ cd "$GOPATH/src/github.com/git-lfs/git-lfs"
$ git remote add bk2204 https://github.com/bk2204/git-lfs.git
$ git fetch bk2204
$ git checkout -b cygwin-canonicalize-path bk2204/cygwin-canonicalize-path
$ make
```

**Comment by brice-ruppen** [comment] 2019-05-29 09:53
And it works, thank you.
```
$ git lfs fsck
Git LFS fsck OK

$ git lfs env
git-lfs/2.7.0 (GitHub; windows amd64; go 1.12.5; git 5e876bbd)
git version 2.21.0

LocalWorkingDir=C:\Users\brice\test-separate
LocalGitDir=C:\Users\brice\test-separate\.tig
LocalGitStorageDir=C:\Users\brice\test-separate\.tig
LocalMediaDir=C:\Users\brice\test-separate\.tig\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\brice\test-separate\.tig\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\brice\test-separate\.tig\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=/usr/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment] 2019-05-29 13:49
Great, glad it's working. I'll get that branch submitted as a pull request and I expect the changes will be in the next version.

**Closed** 2019-05-29 18:31 UTC
