### ISSUE TITLE
cannot fork to run subprocess 'git-lfs filter-process'

### ISSUE THREAD

**Issue by MarekPetr** [git-lfs/git-lfs#4087] opened 2020-03-30 16:54 UTC
**Bug description**
I am trying to run git-lfs on an android arm device. Commands on their own are printing the expected output, but there is this error on `git add`:
    `fatal: cannot run git-lfs filter-process: No such file or directory`
    `error: cannot fork to run subprocess 'git-lfs filter-process'`
    `fatal: file.txt: clean filter 'lfs' failed`

**To Reproduce**
You can reproduce the behavior this way:
1. Download LFS branch artifacts at https://gitlab.com/MarekPetr/LfGit/pipelines or clone from https://github.com/MarekPetr/LfGit and checkout the branch
2. Add your repository from internal storage / or Init/Clone from menu in the right upper corner
3. Track some pattern using LFS track in the right drawer
4. Create a file that matches the pattern from your file manager
5. Click "Add all to stage" again from the drawer and see the error

**Expected behavior**
I have expected it to add the file to stage and show the file on "LFS List Files" (lfs ls-files). I have tried to `git add` the file using Termux and it works. Termux is accessing the storage through symlink in its own chroot environment, but using the binaries built the same way. I have only set the privileges for the app, set chmod 700 for all executable files and run it using the ProcessBuilder. That was enough for git.

**System environment**
Any android 5+ arm32/64. Tested using Xiaomi arm64 android 9, Samsung arm32 android 7

**Output of `git lfs env`**
git-lfs/2.10.0 (GitHub; android arm; go 1.14.1)
    git version 2.26.0
    
    Endpoint=https://github.com/MarekPetr/test2.git/info/lfs (auth=none)
    LocalWorkingDir=/storage/emulated/0/LfGit/test2_lfs/test2
    LocalGitDir=/storage/emulated/0/LfGit/test2_lfs/test2/.git
    LocalGitStorageDir=/storage/emulated/0/LfGit/test2_lfs/test2/.git
    LocalMediaDir=/storage/emulated/0/LfGit/test2_lfs/test2/.git/lfs/objects
    LocalReferenceDirs=
    TempDir=/storage/emulated/0/LfGit/test2_lfs/test2/.git/lfs/tmp
    ConcurrentTransfers=8
    TusTransfers=false
    BasicTransfersOnly=false
    SkipDownloadErrors=false
    FetchRecentAlways=false
    FetchRecentRefsDays=7
    FetchRecentCommitsDays=0
    FetchRecentRefsIncludeRemotes=true
    PruneOffsetDays=3
    PruneVerifyRemoteAlways=false
    PruneRemoteName=origin
    LfsStorageDir=/storage/emulated/0/LfGit/test2_lfs/test2/.git/lfs
    AccessDownload=none
    AccessUpload=none
    DownloadTransfers=basic,lfs-standalone-file
    UploadTransfers=basic,lfs-standalone-file
    git config filter.lfs.process = "git-lfs filter-process"
    git config filter.lfs.smudge = "git-lfs smudge -- %f"
    git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
All binaries were built using docker provided by Termux-packages. Those includes Git and its dependencies and git-lfs. Git works out of the box.

**Comment by bk2204** [comment] 2020-03-30 17:38
Hey,

I suspect that your problem is related to either the `PATH` or to a problem with the shell.  When you invoke `git add` and the filter process gets invoked, that invocation happens using the shell.  This is different from when Git invokes its own subcommands, which are usually not done with the shell.  Is it possible that your shell is configured differently or `PATH` is configured differently when you're seeing this?

**Comment by MarekPetr** [comment] 2020-03-30 17:44
Thanks for a fast response! The issue could be that I am using the android's system shell which is a very stripped down version of a linux shell and it is missing some commands `git-lfs` uses.

**Comment by bk2204** [comment] 2020-03-30 18:23
Git LFS shouldn't need to invoke a shell itself in most cases (although SSH is a potential exception).  It's typically a statically linked binary (although that might differ on Android).  However, any POSIX shell should work, both for Git and Git LFS; we don't require anything of the shell beyond that.

**Comment by MarekPetr** [comment] 2020-03-30 18:36
The git-lfs binary is a dynamic binary, which I have built. And the shell android uses lacks many utilities POSIX shell provides. There is no readlink, grep, cat and many other. So if git-lfs relies on some of those, that could be the issue.

**Comment by bk2204** [comment] 2020-03-30 20:10
The `git-lfs` binary does not depend on any of those things; it's written entirely in Go.  Unless you're using something like `GIT_SSH_COMMAND` where we have to invoke the shell for compatibility with Git, we don't invoke the shell at all, so its lack of POSIX utility support shouldn't be an issue.

**Comment by MarekPetr** [comment] 2020-03-30 20:17
I am glad to hear that! :) Tommorow I will try running it through strace. Maybe that will give me some insight about what is going on there.

**Comment by MarekPetr** [comment] 2020-03-31 10:57
This is the output from strace on `git add`. I am not really sure how to interpret it though.
[strace_log.txt](https://github.com/git-lfs/git-lfs/files/4408546/strace_log.txt)

**Comment by bk2204** [comment] 2020-03-31 14:01
Hey,

I think you need to run `strace` with the `-f` flag so we can see what happens in the child process, since I think that's where the problem is.

**Comment by MarekPetr** [comment] 2020-03-31 16:05
Sure, this is the log from `strace -f`
[strace_f_log.txt](https://github.com/git-lfs/git-lfs/files/4410213/strace_f_log.txt)

**Comment by bk2204** [comment] 2020-03-31 16:25
This line:
```
[pid 21202] execve("/data/data/com.lfgit/files/usr/bin/sh", ["/data/data/com.lfgit/files/usr/b"..., "-c", "git-lfs filter-process", "git-lfs filter-process"], 0xe8a9d2d0 /* 17 vars */) = -1 ENOENT (No such file or directory)
```
indicates that your shell is missing and can't be executed.

**Comment by MarekPetr** [comment] 2020-03-31 16:32
Yes! I have created a symlink to android's native shell and it works! Thank you sooo much!

**Comment by bk2204** [comment] 2020-03-31 16:36
Great!  I'm going to close this issue since it seems to be working for you.

**Closed by bk2204** 2020-03-31 16:36 UTC
