### ISSUE TITLE
Allow parallel download?

### ISSUE THREAD

**Issue by kilianc** [git-lfs/git-lfs#1002] opened 2016-02-13 01:35 UTC
When you have many small images it takes forever :/

**Comment by larsxschneider** [comment] 2016-02-13 14:50
I assume you're referring to the `clone` operation? You can use [this](https://gist.github.com/larsxschneider/85652462dcb442cc9344) today or wait for https://github.com/github/git-lfs/pull/988.

**Comment by kilianc** [comment] 2016-02-13 16:17
I am referring to the ability to resolve files during checkout in parallel.
I have a design repo with ~400 files all on git lfs and the first checkout is incredibly slow even if I have 150MB down because it's all small files downloaded in series.

**Comment by sinbad** [comment] 2016-02-15 11:06
Yes, this is exactly the situation that is helped by Lars' suggestions above. Parallel download will happen in both these cases.

**Comment by kilianc** [comment] 2016-02-15 18:05
:dancers: !

**Comment by kilianc** [comment] 2016-02-15 18:09
@sinbad I don't understand, I can't find any indication that the PR and the temp fix are related to what I am proposing. We are talking about parallel download from the LFS server correct? If yes how do we handle the size of the pool ? Is there a default?

**Comment by larsxschneider** [comment] 2016-02-15 18:25
@kilianc use these configs: https://github.com/github/git-lfs/blob/4cca3f8e7d77c5b86cdfe34c2e6bba2126e3d5cd/docs/man/git-lfs-config.5.ronn#L25-L33

**Comment by sinbad** [comment] 2016-02-16 10:25
The default out of the box is to use the batch API and 3 concurrent downloads / uploads - the issue is that you're driving that via the git checkout process which can only ever perform one API request and one download at a time. The PR and the temp fix show you how to avoid using the smudge filter at checkout and instead download using `git lfs pull`, which uses the batch requests and default 3 parallel transfers.

**Comment by lcsthom** [comment] 2016-06-17 15:13
I'm currently using a script to unset the global configs to use git lfs pull from a real pull rebase. 

Here are the scripted commands:
- remove global configs
- reset hard on the current Head (not to be dirty)
- pull rebase
- git lfs pull
- re-apply git configs
- git reset mixed

The last reset is needed to make the filter understand that the pointers filees  have been replace with their content in git-lfs, otherwise, I get a dirty repo with staged files. But I can't get rid of the enormous amount of git lfs cleans sequentially launched in background. Is there a way to do it?

**Comment by zippo227** [comment] 2017-08-22 15:44
Is there a status update or tutorial on how to do this? Painfully slow with all my files being downloaded in series.

**Comment by larsxschneider** [comment] 2017-08-22 16:36
Try `git lfs clone <url>`. At least until #2511 gets merged ;-)

**Comment by zippo227** [comment] 2017-08-22 16:38
will that perform git clone just like normal, but with the addition that lfs will pull in parallel?

**Comment by larsxschneider** [comment] 2017-08-22 17:03
correct!

**Comment by ttaylorr** [comment] 2017-08-25 00:25
> Is there a status update or tutorial on how to do this? Painfully slow with all my files being downloaded in series.

@zippo227 great question, @larsxschneider provided a great solution for making sure that 'git clone' operations are quick. One other thing: if the checkout after a 'git pull' operation is slow, make sure that you are on the latest version of Git (and run `git lfs install --system`, to be safe). There is a speed improvement made in the protocol which Git uses to communicate with external filters (like LFS) when checking out files.

**Comment by yvele** [comment] 2017-11-10 10:14
@ttaylorr why exactly `-system` instead of global?

https://github.com/git-lfs/git-lfs/blob/0484c70cd4a7c6cf54c0e49787d2c5ed4cf94592/docs/man/git-lfs-install.1.ronn#L24-L42

**Comment by technoweenie** [comment] 2017-11-13 18:46
Global changes only affect your user account, while system changes affect _everything_ on that machine. Either should work fine in most cases.

**Comment by yvele** [comment] 2017-11-13 19:08
Thanks for the clarification @technoweenie 👍

**Comment by technoweenie** [comment] 2017-11-13 19:11
One clarification, if you're on a system with 1 person (such as a personal laptop), `--global` will not require admin access. I'd prefer it to `--system` in the vast majority of cases.

**Comment by dimitrieh** [comment] 2018-04-04 09:02
@larsxschneider I think this issue can be closed correct, as https://github.com/git-lfs/git-lfs/pull/988 is merged

**Comment by ttaylorr** [comment] 2018-04-05 04:40
> @larsxschneider I think this issue can be closed correct, as #988 is merged

This PR is a little stale, since you can now accomplish a similar performance improvement with `git clone` alone.

**Closed by ttaylorr** 2018-04-05 04:40 UTC
