### ISSUE TITLE
In repos which using 'repo sync' downloaded, all branches can not be recognized

### ISSUE THREAD

**Issue by liguanghua838** [git-lfs/git-lfs#5682] opened 2024-03-14 08:50 UTC
**Describe the bug**
As the 'repo sync' repos are using '.git' symbolic link,  it can not support 'git lfs migrate import --include-refs=<branch_name>'.
This may need a solution for better user experience. 

**To Reproduce**
1. 'repo init' one AOSP code line. 
2. 'repo sync' one repo 
3.  checkout one SHA1 to local branch such as test_migrate
4.  using 'git lfs migrate import --include-refs=refs/heads/test_migrate --above=10mb --include=* '
5. Error returned "Error in `git rev-list --reverse --topo-order --do-walk --stdin --`: exit status 128 fatal: bad revision 'refs/heads/test_migrate '"

**Expected behavior**
The git migrate command should be execute without any error returned

**System environment**
ubuntu 20.04

**Output of `git lfs env`**
git-lfs/3.4.1 (GitHub; linux amd64; go 1.21.1)
git version 2.44.0

**Comment by bk2204** [comment] 2024-03-14 13:16
Hey,

This appears to be a duplicate of #5246, which is marked `mcve-required`.  If you can comment _in that issue_ with minimal reproduction steps (i.e., a shell script) that I can run to reproduce the problem on my Ubuntu 23.10 system, then we can look into it.  I'd much rather not download all of AOSP, so the minimal part is important; ideally the script takes at most a few seconds to run.

I'm going to close this in favour of that issue.

**Closed by bk2204** 2024-03-14 13:16 UTC
