### ISSUE TITLE
git-lfs dedup trashes index cache and corrupts some files

### ISSUE THREAD

**Issue by swisspol** [git-lfs/git-lfs#4053] opened 2020-03-03 19:30 UTC
**Describe the bug**
`git lfs dedup` appears to have multiple serious issues (on macOS at least).

**To Reproduce**
Steps to reproduce the behavior (I don't know if these are the minimal steps are needed to repro, but these are the ones I used):
1. `GIT_LFS_SKIP_SMUDGE=1 git clone ...`
2. `git config lfs.fetchexclude "XboxOne,Switch,PS4`
3. `git lfs pull`
4. `git status` to verify repo is clean
5. `git lfs dedup`

`git lfs dedup` does its job and returns success:
```
Successfully finished.
  De-duplicated  size: 33421355898 bytes
                count: 8183
```

The first problem is if you run `git status` afterwards, instead of taking a couple seconds like before, it now takes a minute or so, clearly re-hashing everything on disk. I suspect Git LFS is replacing the inodes or not preserving the mod time of the files or something and it trashes the Git index cache.

The second problem, much worse, is that `git status` now reports some changes (a 100 or so in my case):
```
$ git status
Refresh index: 100% (203501/203501), done.
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Engine/Content/Localization/Category/Platforms/PS4/en/Category.archive
	modified:   Engine/Content/Localization/Category/Platforms/PS4/es/Category.archive
(...)
```
The above files were reported as successes in `git lfs dedup` output:
```
Success: Engine/Content/Localization/Category/Platforms/PS4/en/Category.archive (Size: 84)
Success: Engine/Content/Localization/Category/Platforms/PS4/es/Category.archive (Size: 84)
```

And these are interesting findings:
```
$ cat Engine/Content/Localization/Category/Platforms/PS4/en/Category.archive
??{
	"FormatVersion": 2,
	"Namespace": ""

$ git checkout Engine/Content/Localization/Category/Platforms/PS4/en/Category.archive
Updated 1 path from the index

$ cat Engine/Content/Localization/Category/Platforms/PS4/en/Category.archive
version https://git-lfs.github.com/spec/v1
oid sha256:f7b49c13640eee20f428404a82be1a44f70aa6e20a17f29ccc9dbe94f834c0b6
size 84
```
```
$ git status Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libcrypto.a
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libcrypto.a

no changes added to commit (use "git add" and/or "git commit -a")

$ ls -l Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libcrypto.a
-rw-r--r--  1 pierre-olivier.latour  staff  5221674 Mar  3 10:32 Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libcrypto.a

$ git checkout Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libcrypto.a
Updated 1 path from the index

$ ls -l Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libcrypto.a
-rw-r--r--  1 pierre-olivier.latour  staff  132 Mar  3 11:29 Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libcrypto.a

$ git status Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libcrypto.a
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Expected behavior**
None of the above happens!

**System environment**
macOS 10.14.6 with Git LFS installed with brew.

**Output of `git lfs env`**
```
git-lfs/2.10.0 (GitHub; darwin amd64; go 1.13.6)
git version 2.21.1 (Apple Git-122.3)

Endpoint=(REDACTED)
LocalWorkingDir=/Users/pierre-olivier.latour/Downloads/perforce_mirror
LocalGitDir=/Users/pierre-olivier.latour/Downloads/perforce_mirror/.git
LocalGitStorageDir=/Users/pierre-olivier.latour/Downloads/perforce_mirror/.git
LocalMediaDir=/Users/pierre-olivier.latour/Downloads/perforce_mirror/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/pierre-olivier.latour/Downloads/perforce_mirror/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/pierre-olivier.latour/Downloads/perforce_mirror/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
FetchExclude=XboxOne, Switch, PS4
GIT_EXEC_PATH=/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
n/a

**Comment by bk2204** [comment] 2020-03-03 22:00
Hey,

So it sounds like there are two things you're reporting here.

First, it is known that `git status` will re-read all of the files, because we do indeed replace their inodes.  There isn't a way for us to avoid this, since as you noted Git stores inode values in the index, and the mtime will be set to whatever the original file was.  This is just how the CloneFile implementations work under the hood.

Second, it looks like one of the files you're seeing modified is listed under `lfs.fetchexclude`.  Could you disable that option and see if things work correctly for you?  That would help us track down where the problem lies.

**Comment by chrisd8088** [comment] 2020-03-03 22:01
Hey, sorry to hear you're having trouble with this.  So far I haven't been able to reproduce your issue, which sounds like some kind of interaction between your `fetchexclude` Git LFS configuration and the `git lfs dedup` command, whereby you end up with pointer files and not object files.

**Comment by swisspol** [comment] 2020-03-03 22:27
I reset the repo to be clean, then commented out `FetchExclude` from `.git/config` and re-run `git lfs dedup`.

Running `git status` still shows some changes, but quite fewer. Outside of 1, they are all on paths that used to be excluded with `FetchExclude`.

Poking around one of these files, I have no idea why Git says they are different?
```
$ git status Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libssl.a
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libssl.a

no changes added to commit (use "git add" and/or "git commit -a")

$ md5 Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libssl.a
MD5 (Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libssl.a) = 84df5768e7921f96992df241a676c32d

$ ls -l Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libssl.a
-rw-r--r--  1 pierre-olivier.latour  staff  855104 Mar  3 10:32 Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libssl.a

$ git checkout Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libssl.a
Updated 1 path from the index

$ md5 Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libssl.a
MD5 (Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libssl.a) = 84df5768e7921f96992df241a676c32d

$ ls -l Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libssl.a
-rw-r--r--  1 pierre-olivier.latour  staff  855104 Mar  3 14:25 Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libssl.a

$ git status Engine/Source/ThirdParty/OpenSSL/1.0.2g/lib/PS4/release/libssl.a
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by swisspol** [comment] 2020-03-03 22:29
BTW does `git lfs dedup` (or the underlying file cloning mecanism) run automatically under any circumstances (e.g. when doing `git lfs pull`)?

**Comment by bk2204** [comment] 2020-03-09 16:30
What do `git diff` and `git lfs ls-files` show?  It's possible that your file is showing up as modified if it's not stored as an LFS file but it matches an LFS pattern.

And to answer your question, no, `git lfs dedup` is invoked only manually, never automatically.

**Comment by bk2204** [comment] 2020-08-14 17:56
Hey,

It doesn't look like there's been a response to this recently, so I'm going to close it.  If you can provide the additional information we've requested, let us know and we'll reopen.

**Closed by bk2204** 2020-08-14 17:56 UTC
