### ISSUE TITLE
Issues with releases hosted in packagecloud

### ISSUE THREAD

**Issue by jharrison-quantium** [git-lfs/git-lfs#4548] opened 2021-07-13 06:25 UTC
**Describe the issue**
Attempting to do a `apt-get update` on a system configured with the git-lfs packagecloud source results in 

```
W: The repository 'https://packagecloud.io/github/git-lfs/ubuntu xenial Release' does not have a Release file.
```

It would appear that packagecloud are no longer providing the git-lfs packages as attempts to access any git-lfs packagecloud URL reports failure

**System environment**
Ubuntu 16.04

**Additional context**
This worked up until very recently.

**Comment by josephch** [comment] 2021-07-13 06:46
Same error here 

Err:19 https://packagecloud.io/github/git-lfs/ubuntu xenial Release
  402  Payment Required

**Comment by MarkusTeufelberger** [comment] 2021-07-13 07:55
The point of having a repository is that "using the binary" is not necessary. Yes, it is a workaround, but not a solution.

It is really strange to get a 402 error. How does this server expect me to issue payments towards it anyways?!

**Comment by bk2204** [comment] 2021-07-13 11:14
Thanks for the report.  We're looking into it.

**Comment by rjc** [comment] 2021-07-13 12:49
I haven't seen this information elsewhere so, in case this gives you any clues, I thought I'd mention it here - attempting to access [`https://packagecloud.io/github/git-lfs`](https://packagecloud.io/github/git-lfs), which is the URL on your [releases](/git-lfs/git-lfs/releases) page, gives the below error message:

> The page you were looking for doesn't exist.
>
> You may have mistyped the address or the page may have moved.
>
> If you are the application owner check the logs for more information.

**Comment by bk2204** [comment] 2021-07-13 12:59
Hey,

I appreciate the information.  We know what the cause of the problem is (a billing problem), but I'm trying to track down the responsible party here to get it fixed.

**Comment by bk2204** [comment] 2021-07-13 14:30
This should be fixed now.  Thanks again for the report, and sorry for the inconvenience.

**Closed by bk2204** 2021-07-13 14:30 UTC

**Comment by buvinghausen** [comment] 2021-07-13 15:16
@MarkusTeufelberger the issue isn't you not paying packagecloud.io the issue is git-lfs not paying packagecloud.io which happened initially in November 2020.  It seems to be a recurring issue.

**Comment by jph-tec** [comment] 2022-11-24 14:49
I am having this issue again. Could you check it? Thanks!

**Comment by brauliomartinezlm** [comment] 2022-11-24 17:30
I'm seeing problems in our servers too. Tagging @bk2204 @MarkusTeufelberger for awareness

**Comment by jph-tec** [comment] 2022-11-25 08:15
I think it is already fixed. Could anyone confirm it?

**Comment by LazarDjokovic** [comment] 2022-11-25 09:31
It seems to be working now.

**Comment by chrisd8088** [comment] 2022-11-25 21:11
The problem yesterday with Packagecloud was reported in #5197 and has since been resolved.

In general, we ask people to open a new issue rather than comment on an old, closed one, so I'm going to lock conversations on this issue as it's no longer active or relevant.
